yarnpkg/berry

- packages/berry-core/sources/scriptUtils.ts
- packages/berry-shell/sources/index.ts
- packages/berry-shell/tests/shell.test.ts
The shell is fairly complex by essence, so I'm trying to move things around in an effort to simplify it.
Two notes:
- It should improve performances, as I'm removing closures and stream indirections.
- It should hopefully solve in the process a CI error triggered on Node 8. I'm not 100% sure unfortunately, as Node has relatively complicated pipe sequences.
> Reworks the pipe system to be simpler

- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/commands/remove.ts
- packages/plugin-essentials/sources/commands/up.ts
- packages/plugin-essentials/sources/index.ts
- packages/plugin-typescript/bin/@berry/plugin-typescript.js
- packages/plugin-typescript/sources/index.ts
This PR improves the hook system by renaming `afterNewWorkspaceDependency` into `afterWorkspaceDependencyAddition`, which allows creating two other related hooks:
- `afterNewWorkspaceDependencyAddition`
- `afterNewWorkspaceDependencyReplacement`
- `afterNewWorkspaceDependencyDeletion`
Note that these hooks cannot run during `yarn install`. This is because Yarn doesn't keep a project state (except for the build artifacts), and as such cannot distinguish the dependencies that have always been listed but never installed versus those that have just been added into a manifest.
> Improves hooks

- .gitignore
- packages/berry-builder/sources/build-bundle.js
- packages/berry-builder/sources/build-plugin.js
- packages/plugin-pack/bin/@berry/plugin-pack.js
- packages/plugin-typescript/bin/@berry/plugin-typescript.js
- scripts/plugin-pack.js
- scripts/plugin-typescript.js
- scripts/run-yarn.js
- scripts/update-local.sh
I moved files around in order to prevent conflicts between files, but unfortunately forgot that the nightly build of Yarn is directly fetched from the version stored on Github.
This diff will put back the Yarn build at its previous location, which should restore the broken feature. A followup diff will add a test to make sure someone else doesn't make the same mistake 🙂 
Fixes #19
> Fixes policies set-version

- packages/acceptance-tests/pkg-tests-specs/sources/features/enableNetwork.test.js
- packages/berry-core/sources/Configuration.ts
- packages/berry-core/sources/LightReport.ts
- packages/berry-core/sources/httpUtils.ts
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/commands/up.ts
- packages/plugin-essentials/sources/suggestUtils.ts
- packages/plugin-typescript/sources/index.ts
This settings is identical to the `--offline` flag in the v1. It is meant to prevent Yarn from accessing the network, which is handy in two cases:
- To avoid unwanted internet access on sensitive machines
- To skip unwanted internet access when working offline (like in transports)
> Implements enable-network

- packages/berry-core/sources/Project.ts
- packages/berry-core/sources/RunInstallPleaseResolver.ts
There was a problem in the way the virtual links were generated: the tree recursion was done one dependency after another, but before they had all been virtualized. It caused the recursions to not see that the parent package was still referencing entries that would later get virtualized, and in response to virtualize them themselves.
This diff adds a two-pass processing: first we virtualize all the dependencies of the current package, and only then we update the dependencies and recurse within them.
> Fixes sibling peer dependencies

- packages/plugin-essentials/sources/commands/why.ts
Adds support for `--peers`, which also follows peer dependencies when traversing the tree.
> Adds support for --peers to yarn why

- .pnp.js
- .yarnrc
- packages/acceptance-tests/berry.setup.js
- packages/acceptance-tests/pkg-tests-specs/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/commands/stage.test.js
- packages/plugin-pnp/package.json
- packages/plugin-pnp/sources/index.ts
- packages/plugin-stage/bin/@berry/plugin-stage.js
- packages/plugin-stage/package.json
- packages/plugin-stage/sources/commands/stage.ts
- packages/plugin-stage/sources/drivers/GitDriver.ts
- packages/plugin-stage/sources/drivers/MercurialDriver.ts
- packages/plugin-stage/sources/index.ts
- packages/plugin-stage/sources/stageUtils.ts
- scripts/plugin-base.js
- scripts/plugin-pack.js
- scripts/plugin-stage.js
- scripts/plugin-typescript.js
- scripts/update-local.sh
- yarn.lock
This plugin (not bundled by default) implements a new command called `yarn stage`. Its goal is to remove the mental overhead required to cherry-pick the Yarn files and put them into a single commit, away from the logic changes introduced in a feature. If `yarn stage` does its work correctly, you just have to run `yarn add ... && yarn stage` to register your changes in your history without accidentally merging them with your code updates.
Basic usage:
- `yarn stage --dry-run` will print the list of files that belong to Yarn that have changed in the local repository. This would typically be the `yarn.lock` file + any `package.json` file, but can be more than that (for example the cache folders, the `.yarnrc` files, the `.pnp.js` files, etc).
- `yarn stage` will add this list of files to the …
> Implements "yarn stage"

- packages/acceptance-tests/pkg-tests-specs/sources/workspace.test.js
- packages/plugin-pnp/sources/PnpLinker.ts
Since the workspaces are installed through soft links, and since we disable postinstall scripts on soft links (because we don't want to run the postinstall scripts for packages depended upon via `portal:`), the postinstall scripts never ran on workspaces.
This diff ensures that postinstall scripts are always allowed on workspaces.
> Runs the postinstall scripts on workspaces

- CHANGELOG.md
- packages/berry-core/sources/Configuration.ts
- packages/plugin-essentials/sources/commands/config.ts
This PR adds a new settings, `enableGlobalCache`, disabled by default, which instructs Yarn to use a global folder to keep its cache rather than the one defined in `cache-folder`.
Another option was to add variable support within the configuration values, but it felt too complex and slow for the purpose. Additionally, a separate flag provides semantic information that can be used with functions such as `yarn cache clean`.
> Adds support for enableGlobalCache

- .pnp.js
- package.json
- packages/berry-cli/package.json
- packages/berry-core/sources/Plugin.ts
- packages/berry-core/sources/index.ts
- packages/berry-core/sources/scriptUtils.ts
- packages/plugin-node-gyp/package.json
- packages/plugin-node-gyp/sources/index.ts
- packages/plugin-pnp/sources/index.ts
- yarn.lock
The `node-gyp` package is a bit magic in both Yarn and npm in that it is downloaded on-demand if the package requests it. It's a horrible thing to do because you have no way to guarantee which version of `node-gyp` will be used. Still, that's how the ecosystem currently works and there's some friction to change it so I'll have to live with it for now (https://github.com/lovell/sharp/pull/924).
This PR implements a plugin that causes `node-gyp` to be installed when called, unless overridden by an explicit dependency. There's one improvement over Yarn 1 and npm, though: you can enforce the version of `node-gyp` that gets used by using the new `node-gyp-magic-locator` settings:
```yaml
node-gyp-magic-locator: "node-gyp@3.8.0"
```
> Adds a node-gyp plugin

- packages/plugin-constraints/sources/Constraints.ts
Spotted while working on #53 that `workspace_version` doesn't allow for asking what version a workspace is at, it only allows querying what version any workspace is at
> Replace workspace_version/1 with workspace_version/2

- .pnp.js
- packages/berry-shell/package.json
- packages/berry-shell/sources/index.ts
- packages/berry-shell/sources/pipe.ts
- packages/berry-shell/tests/shell.test.ts
- scripts/azure-run-tests.yml
- yarn.lock
There was a timing issue in the way the piping was handled: we were closing the output streams too soon, and that was causing weird race conditions (in Jest it could lead to timeouts, tests reported finished before they actually did, or validation errors within the Node internals). This diff should fix the logic behind it by:
- Ensuring that the builtin commands always close their stdout/stderr after they're done writing, except if they're the right-most command (because then they might close the real stdout, which would throw an exception).
- Ensuring that the builtin commands always close their stdin after they're done reading, except if they're the left-most command (for a similar reason but this time with the real stdin).
> Fixes piping

- packages/berry-core/sources/Manifest.ts
- packages/plugin-constraints/sources/Constraints.ts
- packages/plugin-constraints/sources/tauModule.ts
- packages/plugin-constraints/sources/types/tau-prolog.d.ts
Implements the `workspace_field/3` predicate proposed in #31.
Timings for the current constraints file in the berry repo on a 2017 MacBook Pro with 2.9 GHz i7:
- Before: mean 1.910s, deviation 0.230
- After: mean 1.845s, deviation 0.203
This is the average of five timings. It doesn't look like there's any speed impact at all for constraints files that don't use any predicate exposed in the javascript tau module.
> Introduce workspace_field/3 predicate to expose workspace manifest information

- packages/berry-core/sources/Cache.ts
- packages/berry-fslib/sources/LazyFS.ts
- packages/berry-fslib/sources/index.ts
- packages/plugin-file/sources/FileFetcher.ts
- packages/plugin-file/sources/TarballFileFetcher.ts
- packages/plugin-github/sources/GithubFetcher.ts
- packages/plugin-http/sources/TarballHttpFetcher.ts
- packages/plugin-npm/sources/NpmFetcher.ts
This diff implements `LazyFS` - an fs layer that only instantiates its underlying target when one of its methods gets called. Since the fetch step doesn't actually uses the resulting fs (we only do this at link-time), it trims off a fair amount of time (from ~2.45s on the Yarn repo with a warm cache to ~1s).
> Implements a lazy cache

- packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/list.test.js
- packages/plugin-essentials/sources/commands/workspaces/list.ts
Bring v1 `yarn workspaces info` to v2 by using `yarn workspaces list -v --json`
Todo:
> Implement `--json` and `-v,--verbose` for `yarn workspaces`

- azure-pipelines.yml
This diff disables the CI build for Node 8 on Windows as it never passes - without even running the tests. It's not clear what happens, and I can't reproduce it locally. Tracked over at #78 - hopefully someone can come up with an idea 🙁
> Disables the CI w/ Node 8 on Windows

- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/source.test.js.snap
- packages/plugin-constraints/sources/Constraints.ts
This diff updates the constraint engine to use relative paths to the workspaces instead of absolute ones. Cleaner in general, it also allows to target any workspace from within the rules without having to rely on `workspace_ident` to get their path (particularly useful for the top-level, which is always `.`).
> Uses relative paths for constraints

- packages/berry-core/sources/Manifest.ts
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-pnp/sources/commands/unplug.ts
- packages/plugin-pnp/sources/index.ts
This diff reimplements the `yarn unplug` command that disappeared when moving from the v1 to the v2.
> Implements yarn unplug

- packages/gatsby/content/advanced/error-codes.md
- packages/plugin-npm/sources/NpmSemverResolver.ts
Some packages 1/ omit to list `node-gyp` in their dependency list, and 2/ list an `install` script that doesn't even include `node-gyp` (ex [node-pty-prebuilt](http://registry.yarnpkg.com/node-pty-prebuilt)). This breaks the current heuristic we have.
As a workaround, I've added `prebuilt-install` to the list of script patterns that automatically cause `node-gyp` to be added to the dependency list if it isn't already there. This behavior isn't great, but I'm afraid we don't have anything better to do at the moment ... 
I've also documented the problem of implicit `node-gyp` dependencies for future references.
> Adds prebuilt-install to the list of implicit node-gyp consumers

- packages/acceptance-tests/pkg-tests-specs/sources/commands/link.test.js
- packages/berry-core/sources/Manifest.ts
- packages/berry-parsers/sources/index.ts
- packages/berry-parsers/sources/resolution.ts
- packages/plugin-essentials/sources/commands/link.ts
Given the positive response to [my tweet](https://twitter.com/arcanis/status/1120993281251454976) I went ahead and implemented it.
This diff changes the syntax for `yarn link`. Instead of "remembering" the local packages by first requiring our users to run `yarn link` in their individual directories and then to run `yarn link <package-name>` again but this time in their target project, we now only ask them to specify the link destination in their target workspace.
Before:
```
$> cd ~/source
$> yarn link
$> cd ~/target
$> yarn link source
```
After:
```
$> cd ~/target
$> yarn link ~/source
```
This behavior is simpler since we don't have to maintain a global store for `yarn link` to work, easier from a workflow perspective since our users need to run less commands, less frustrating because …
> Changes yarn link syntax

- packages/berry-core/sources/structUtils.ts
The `devirtualize` functions had an issue when the target reference contained a `#` character. The regex was greedy and thus removed all characters up to the last `#` instead of the first one.
> Fixes package devirtualization

- packages/berry-pnpify/lib/index.js
- packages/berry-pnpify/sources/index.ts
Extra check is added, before any and each translation on paths happens whether the path is indeed inside PnP project or not. 
`realpathSync` is changed to forward path to underlying fs for the cases where it is not possible to determine result otherwise.
> Bugfix: Do not translate paths that are outside PnP projects

- packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
- packages/acceptance-tests/pkg-tests-fixtures/packages/@private__package-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/@private__package-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/private-package-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/private-package-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/auth.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/config.test.js.snap
- packages/berry-core/sources/Report.ts
- packages/berry-core/sources/httpUtils.ts
- packages/plugin-npm/sources/NpmFetcher.ts
- packages/plugin-npm/sources/NpmSemverResolver.ts
- packages/plugin-npm/sources/NpmTagResolver.ts
- packages/plugin-npm/sources/index.ts
- packages/plugin-npm/sources/npmHttpUtils.ts
Implements #10 
Tested against a SonaType Nexus 3 server containing both public and private packages at work, with `npmAlwaysAuth` set to true.
> Support fetching private packages

- packages/berry-builder/sources/build-bundle.js
I had a typo doing something like `yarn build:cli --plugin @berry/plugin-typoHere` and got into a state where I couldn't rebuild the cli without deleting `berry-cli/bundles`.
This will make webpack not output the bundle if an error exists.
> Fix webpack generating bundles with errors

- .pnp.js
- packages/berry-cli/package.json
- packages/plugin-npm-cli/package.json
- packages/plugin-npm-cli/sources/index.ts
- yarn.lock
This diff adds a new plugin (`plugin-npm-cli`) to contain all the npm-specific commands.
Ref #121
> Adds a new plugin for the npm cli commands

- CHANGELOG.md
- packages/berry-libzip/package.json
- packages/gatsby/src/pages/configuration/manifest.js
- packages/plugin-pack/sources/packUtils.ts
I think it happens often that you would want to use a different `main` entry for your local development than after the packages have been published to the Yarn registry (for example in this very repository we want the `main` fields to point towards our TypeScript sources in most cases, but towards the JS sources when they're downloaded from the registry). To this effect I implemented two special fields in the `package.json` that allow just that.
Also note that it's even more important in a workspace-oriented environment, because packages often require each other by their name (which often isn't the case with traditional setups).
> Implements publishConfig.main

- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/config.test.js.snap
- packages/berry-core/sources/Configuration.ts
- packages/berry-parsers/tests/syml.test.js
- packages/plugin-npm-cli/sources/commands/npm/publish.ts
- packages/plugin-npm/sources/NpmFetcher.ts
- packages/plugin-npm/sources/NpmSemverResolver.ts
- packages/plugin-npm/sources/NpmTagResolver.ts
- packages/plugin-npm/sources/index.ts
- packages/plugin-npm/sources/npmConfigUtils.ts
- packages/plugin-npm/sources/npmHttpUtils.ts
As discussed at https://github.com/yarnpkg/berry/pull/95#discussion_r278822902
I've verified the behaviour by running it against a repo at work and only using our internal SonaType Nexus 3 registry for our private packages.
TODO:
Finishes #10
> Allow plugin-npm to be configured per scope and registry

- packages/berry-pnpify/lib/index.js
- packages/berry-pnpify/lib/tsserver.js
- packages/berry-pnpify/sources/NodeModulesFS.ts
- packages/berry-pnpify/sources/NodePathResolver.ts
This should fix the problem with Webpack including the same package multiple times. The reason Webpack does this under pnpify is because it sees the same npm package in multiple places. To prevent this, we symlink all the PnP files on the emulated fs to their target locations.
> PnPify: Symlink all the PnP files to their realpath

- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-1.0.0/scripts/install.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-1.0.0/scripts/postinstall.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-1.0.0/scripts/preinstall.js
- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/install.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
- packages/berry-core/sources/Project.ts
- packages/berry-core/sources/Report.ts
- packages/berry-shell/sources/index.ts
- packages/berry-shell/sources/pipe.ts
- packages/plugin-essentials/sources/commands/install.ts
- yarn.lock
This diff adds a new option to `yarn install`: `--inline-builds` instructs Yarn to print the build output to the standard output instead of creating temporary files.
cc @deini who wanted to use the new `createStreamReporter` function.
> Implements --inline-builds

- packages/acceptance-tests/pkg-tests-specs/sources/commands/_entry.test.js
- packages/berry-builder/sources/build-bundle.js
- packages/berry-cli/package.json
- packages/plugin-essentials/sources/commands/_entry.ts
- packages/plugin-essentials/sources/commands/index.d.ts
- Adds support for `yarn -v` alongside `yarn --version`
- Injects version via a webpack defined global `BERRY_VERSION`
Fixes #164 
- Added snapshot tests for new `-v` and existing `--version`
It's difficult to mock the version via the temporary env due to the constant being injected ...
> Add shorthand version

- .pnp.js
- packages/berry-core/sources/Manifest.ts
- packages/berry-core/sources/Project.ts
- packages/berry-core/sources/WorkspaceResolver.ts
- packages/berry-core/sources/scriptUtils.ts
- packages/berry-core/sources/structUtils.ts
- packages/berry-core/sources/types.ts
- packages/berry-parsers/sources/syml.ts
- packages/berry-pnpify/package.json
- packages/plugin-exec/bin/@berry/plugin-exec.js
- packages/plugin-exec/sources/ExecResolver.ts
- packages/plugin-file/sources/FileResolver.ts
- packages/plugin-file/sources/TarballFileResolver.ts
- packages/plugin-github/sources/GithubResolver.ts
- packages/plugin-http/sources/TarballHttpResolver.ts
- packages/plugin-link/sources/LinkResolver.ts
- packages/plugin-link/sources/RawLinkResolver.ts
- packages/plugin-npm/sources/NpmSemverResolver.ts
- yarn.lock
Under the previous model, `getAccessiblePackageBinaries` had to open the zip archives in order to figure out which binaries were available for a given package. This had a significant cost, especially since we were doing it twice (which was a bug in itself I'll fix in another PR).
This PR encodes the binaries exported by each package within the lockfile itself. It makes it possible to statically deduce which which package "owns" a given binary.
**Before:**
```
$ time YARN_IGNORE_PATH=1 node ./packages/berry-cli/bin/berry.js run jest --version
2.83s user 1.84s system 138% cpu 3.376 total
$ time YARN_IGNORE_PATH=1 node ./packages/berry-cli/bin/berry.js bin
1.62s user 0.95s system 134% cpu 1.918 total
```
**After:**
```
$ time YARN_IGNORE_PATH=1 node ./packages/berry-cli/bundles/berry.js run …
```
> Encodes the package binaries within the lockfile

- .gitignore
- packages/berry-pnpify/lib/NodeModulesFS.d.ts
- packages/berry-pnpify/lib/NodePathResolver.d.ts
- packages/berry-pnpify/lib/bin.js
- packages/berry-pnpify/lib/index.js
- packages/berry-pnpify/lib/tsserver.js
- packages/berry-pnpify/sources/generateSdk.ts
VS Code complains that it cannot determine TypeScript version. This PR adds `tssdk/package.json` generation during `yarn pnpify --sdk` execution. The version of typescript used by `@berry/pnpify` is recorded into `package.json`. It might be not the best approach, but at least we will get rid of unpleasant warning and user confusion
> Add generation of tssdk/package.json to remove VS Code warning

- packages/plugin-github/package.json
- packages/plugin-github/sources/githubUtils.ts
- packages/plugin-github/tests/githubUtils.test.ts
Currently, I can't install a package I forked via git url. 
- `https://github.com/olingern/ink-select-input.git`
The github plugn's current regex pattern will not recognize this as a valid github url.
This PR fixes that.
> Update regex for github urls

- .gitignore
- scripts/tssdk/lib/tsserver.js
This diff removes the sdk from the gitignore, since we always want to have it available.
> Checks-in the sdk

- packages/plugin-npm/sources/NpmFetcher.ts
- packages/plugin-npm/sources/NpmSemverResolver.ts
- packages/plugin-npm/sources/NpmTagResolver.ts
- packages/plugin-npm/sources/npmHttpUtils.ts
The npm fetcher wasn't encoding the `/` character on scoped packages. This was working fine with the npm registry, but was breaking for others (such as TaoBao, cf #191).
This diff slightly refactors the url generation to be inside `npmHttpUtils` (so that we don't have to reimplement it in three different files).
Fixes #191
> Fixes fetcher url generation

- packages/acceptance-tests/pkg-tests-specs/sources/features/resolutions.test.js
- packages/berry-core/sources/structUtils.ts
- packages/plugin-file/sources/FileResolver.ts
- packages/plugin-link/sources/LinkResolver.ts
- packages/plugin-link/sources/RawLinkResolver.ts
When a portal is used in the `resolutions` field (for example because of the new implementation of `yarn link`) the descriptor is "bound" to the top-level: it means that if the portal is a relative path, it will always be resolved relative to the location of the top-level package (and this without having to use an absolute path, which would impair portability).
The problem was that we were preventing portals from being bound twice; so when they were injected into the overriden dependencies (through the action of the `resolutions` field) we caused the code to crash.
This diff makes it so that binding a descriptor that's already bound has no effect. We might want to ensure that the binding schema is the same (so those in this case that both current and tentative bindings only contain a …
> Fixes links/portals being used in the `resolutions` field

- packages/acceptance-tests/berry.setup.js
Running tests in Azure with OSX has been inconsistent with timeouts with the default jest timeout of 5 seconds. This PR bumps it to 10 as we do for windows.
Note: Let's keep an eye and see if 10 is enough.
> Bump jest timeout for osx

- packages/gatsby/src/components/layout.css
It seems like #152 introduced a small visual bug that only appears in production, not in dev:
I think it's related to the specificity of the rules (my guess is that the order of the rules is different versus prod and dev, hence why we only see this after being deployed), which should hopefully be fixed by an `!important` tag.
> Ignores prism specificity on the website

- packages/berry-pnpify/lib/bin.js
- packages/berry-pnpify/sources/generateSdk.ts
It was parsing an empty string instead of an empty object, which was causing `JSON.parse` to fail.
> Fixes --sdk when the VSCode configuration isnt there yet

- packages/gatsby/gatsby-config.js
- packages/gatsby/gatsby-node.js
Currently on the yarn v2 docs site for the `cli` and `advanced` sections, if you select one of the pages other than the default (`install` for cli, `architecture` for advanced), the header links will lose the `active` class. It is because the header links themselves link directly to `/cli/install` and `/advanced/architecture`. 
This PR makes these sections behave like the others. The header links now just go to `/cli` and `/advanced`, and a redirect is added to take `/cli` to `/cli/install` and from `/advanced` to `/advanced/architecture`
> gatsby: fix cli and advanced links active display

- packages/gatsby/src/components/navigation.js
- packages/gatsby/src/utils/useScroll.js
Currently, the [cli page](https://yarnpkg.github.io/berry/cli/install) resets its left navigation to the top on page refresh. 
This change attempts to fix that issue by storing scroll position in sessionStorage, with a key of `gatsby:navigation:<leftmost path name>`.
> Gatsby: Maintain navigation scroll position from page to page

- packages/berry-core/sources/YarnResolver.ts
It seems that workspaces don't have any `resolved` field in old-style lockfiles. Since we don't handle this case, we break when running `yarn` within a v1 project that used workspaces. This diff simply ignores such entries and let Yarn resolve them again (which isn't a problem for workspaces, as they're local to the project).
Example of a lockfile that now works:
https://github.com/mui-org/material-ui/blob/60071b8b6d4406af3c0a7a332ff86ca02cffa32d/yarn.lock
> Fixes old-style import w/ workspaces

- .pnp.js
- packages/berry-core/sources/Project.ts
- packages/berry-core/sources/Report.ts
- packages/berry-pnpify/package.json
- yarn.lock
This PR adds a better error message when a stack overflow occurs during the peers resolution step. This typically only occur in a single case: when a package that lists a peer dependency also somehow depends on itself (for example in this PR you can see I removed a dependency from `@berry/pnpify` - `@berry/pnpify` itself). When it happens we virtualize the package, but since the virtualization depends on its parent we need to revirtualize the child (even though it's the same package as its parent).
While we might be able to detect the one-level case (where A depends on A), it still wouldn't work for multi-level cases (where A depends on B which depends on A), so I decided to go with a simpler solution and just print the resolution stacktrace. In the case of `@berry/pnpify`, you clearly …
> Improves the display when stack overflows occur

- .pnp.js
- packages/plugin-pnp/sources/PnpLinker.ts
Since those warnings/infos don't provide value apart from the first instance we can discard them 🙂
> Stops printing the same build warning multiple times

- packages/gatsby/src/components/navigation.js
- packages/gatsby/src/utils/useScroll.js
Fixes website generation by calling window once the component has mounted.
Changes the sessionStorage key to account for the build's `prefix-paths` option, from `gatsby:navigation:berry` to `berry:navigation:<top level menu item>`.
Doc build was tested [here](https://github.com/andrewl33/berry/tree/test-documentation-generation), using `yarn build` and `yarn serve`, the latter modified to `gatsby serve --prefix-paths`.
> Gatsby fix website generation

- .pnp.js
- README.md
- packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/__snapshots__/foreach.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/foreach.test.js
- packages/berry-core/sources/scriptUtils.ts
- packages/plugin-workspace-tools/bin/@berry/plugin-workspace-tools.js
- packages/plugin-workspace-tools/package.json
- packages/plugin-workspace-tools/sources/commands/foreach.ts
- yarn.lock
This PR fixes endless loop in foreach cmd which happens when lifecycle script name is the same as cmd name being run by `workspaces foreach run`
> Fix endless loop in foreach cmd

- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/config.test.js.snap
- packages/berry-core/sources/Manifest.ts
- packages/plugin-npm-cli/sources/commands/npm/publish.ts
- packages/plugin-npm-cli/sources/index.ts
- packages/plugin-npm/sources/npmHttpUtils.ts
This adds support for `publishConfig.registry` in the manifest to set the publish registry for a single workspace, but it also introduces the `npmPublishRegistry` configuration variable that allows setting the publish registry for an entire project.
The way yarn finds the registry to which to push:
- `publishConfig.registry` in the workspace's manifest
- `npmPublishRegistry` configuration option
- the regular registry as configured
Relevance: 
- `publishConfig.registry` is supported in npm and yarn
- self-hosted Nexus npm registries are setup like so: a registry for your packages and a "group" that groups that registry with a mirror of the public registry. You set the group as registry in the yarn config, but you must publish to the other registry
- Lerna supports setting a …
> Support overriding registry via publishConfig or configuration

- packages/acceptance-tests/pkg-tests-specs/sources/protocols/links.test.js
- packages/plugin-pnp/sources/PnpLinker.ts
This diff allows folders that don't even contain a manifest to still be used with the `link:` protocol (contrary to `portal:`, the `link:` protocol doesn't care about the content of the link destination).
There's still a problem in the design somewhere in that it (probably?) shouldn't be up to the linker to extract the metadata from the packages. It might not matter outside of `link:` though, so for now I'll sleep on it, but I'll keep it in mind in case we see another reason why it would make sense.
Also added some tests for the `link:` protocol in general.
> Prevents crashes when link: points to a folder without package.json

- packages/berry-parsers/sources/grammars/shell.d.ts
- packages/berry-parsers/sources/grammars/shell.js
- packages/berry-parsers/sources/grammars/shell.pegjs
- packages/berry-parsers/sources/index.ts
- packages/berry-shell/sources/index.ts
- packages/berry-shell/tests/shell.test.ts
This PR implements the syntax and base logic for shell redirections. The way it works is pretty simple: during the interpolation pass, the engine converts `foo > bar` into `setredirects ">" 1 bar -- foo`. This command is then executed as-is.
The `setredirects` command is a new builtin that can be implemented by the `@berry/shell` consumers. We'll provide a default implementation that uses the filesystem, but the idea is that it will make it possible to use `@berry/shell` for other purposes than executing shell commands, and in a secure way (for example you could imagine a game shell).
I also added support for [multios](http://zsh.sourceforge.net/Doc/Release/Redirection.html#index-multios) (from zsh), as that sounds a super useful feature I wasn't aware of until recently:
```
cat foo > bar …
```
> Implements shell redirections

- packages/berry-core/sources/Configuration.ts
- packages/berry-core/sources/execUtils.ts
- packages/plugin-npm/sources/NpmFetcher.ts
- packages/plugin-npm/sources/npmHttpUtils.ts
- packages/plugin-npm/tests/npmHttpUtils.test.js
The url concatenation was incorrect: it was completely stripping the path from the registry.
This diff takes a simpler approach which should work in both cases we were interested in.
I've also implemented a few tests that should cover the problems we encountered. They're interesting in that they're actually unit tests, rather than the integration tests we typically use. I think it makes sense in the context of testing the `npmHttpUtils` module, which is well-contained.
Fixes #238
> Fixes invalid url concatenation

- packages/berry-parsers/sources/syml.ts
Fixes #235.
The regexp detecting v1 yarnrc files only looks for linefeeds, this PR simply adds support for CRLF as well.
> FIX: Support CRLF in legacy regexp

- packages/berry-pnpify/lib/bin.js
- packages/berry-pnpify/lib/index.js
- packages/berry-pnpify/sources/NodePathResolver.ts
- packages/berry-pnpify/tests/NodePathResolver.test.ts
Some tools (for example `babel-loader`) use "dot folders" (`n_m/.cache`) to store cached data. Such paths were resolved into `null` since `.cache` wasn't a valid dependency.
This diff adds a bailout when the first character for the package name is a dot.
> Adds support for dotfolders in node_modules

- packages/plugin-essentials/sources/commands/install.ts
Fixes #251 - clipanion sets the value to `undefined` when the option isn't set (to contrast with `--no-cache-folder` which would set it to `null`).
> Fixes yarn install

- packages/berry-cli/sources/cli.ts
- packages/berry-core/sources/scriptUtils.ts
Various tools look at the binaries adjacent to the `process.execPath` (`node`) binary before even considering running files from the `$PATH`. This is an horrible practice, and in our case it is detrimental to the quality of the product because it causes the `yarn-path` settings to be lost (it always execute the global Yarn rather than [the one we set in the PATH](https://github.com/yarnpkg/berry/blob/master/packages/berry-core/sources/scriptUtils.ts#L40-L41), and since we set [`YARN_IGNORE_PATH`](https://github.com/yarnpkg/berry/blob/master/packages/berry-cli/sources/cli.ts#L27) the nested global instances never reexecute the local ones).
This diff "fixes" that by disabling `YARN_IGNORE_PATH` as soon as we can (we theoretically only need it as a "message" to send to the underlying …
> Makes ignorePath temporary

- packages/berry-pnpify/lib/bin.js
- packages/berry-pnpify/webpack.config.pkg.js
The shebang was missing in the pnpify binary, so it couldn't be used with Yarn 1.x (2.x was fine because we now [enforce running the binaries through Node](https://github.com/yarnpkg/berry/blob/7865c70d28a56af79ac3ebd734eff64f0c258dcc/packages/berry-core/sources/scriptUtils.ts#L145)).
Fixes #258
> Adds the proper shebang for the pnpify bin

- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-to-deeply-fail-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-to-deeply-fail-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-to-deeply-fail-1.0.0/scripts/install.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-to-deeply-fail-1.0.0/scripts/postinstall.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-to-deeply-fail-1.0.0/scripts/preinstall.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-to-fail-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-to-fail-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-to-fail-1.0.0/scripts/install.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-to-fail-1.0.0/scripts/postinstall.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-to-fail-1.0.0/scripts/preinstall.js
- packages/acceptance-tests/pkg-tests-specs/sources/script.test.js
- packages/berry-core/sources/Manifest.ts
- packages/berry-core/sources/Project.ts
- packages/gatsby/src/components/syntax.js
- packages/gatsby/src/pages/configuration/manifest.js
Optional dependencies are regular dependencies that don't cause the install to abort should they fail (the idea being that those packages have fallbacks they can rely on).
This diff implements this.
**Note:** I wouldn't recommend to use optional dependencies in the context of "a package only required in some specific cases whose may build may fail under some systems". Such use cases might be better solved by having a peer dependency and letting the user add the dependency themselves if they need the features that require them. It avoids downloading packages for nothing and doesn't cause all build errors to be swallowed.
**Note bis:** My particular use case is `less`, which puts a bunch of its packages inside optional dependencies, [even those that don't have build …
> Implements optional dependencies

- packages/berry-core/sources/YarnResolver.ts
I noticed that migrated lockfiles didn't use the `npm:` qualified in the lockfile. I'd like to discourage that (at least in the lockfile), so I made a small patch to ensure that the protocol was properly added. It works because:
- ★ The `YarnResolver` is setup, finds an entry for `foo@^1.0.0`, but registers it as `foo@npm:^1.0.0`
- We resolve our top-level workspace, and find a reference to `foo@^1.0.0`
- ★ It goes through `SemverResolver`, which converts it into `foo@npm:^1.0.0` and reinject it
- It goes through `YarnResolver`, which finds the internal `foo@npm:^1.0.0` entry and resolves it
The two steps marked ★ are what changed. Before, the entry persisted in the `YarnResolver` store was untransformed (`foo@^1.0.0`). Since `YarnResolver` is prepended to the set of regular resolvers, we …
> Uses the proper protocol when importing legacy lockfiles

- .pnp.js
- packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
- packages/berry-pnp/sources/generateSerializedState.ts
- packages/berry-pnp/sources/types.ts
- packages/plugin-pnp/sources/PnpLinker.ts
The current linker wasn't forwarding to the PnP API which peer dependencies weren't met (by opposition to not existing at all). This diff adds this capability, and a test to prevent regressions.
Fixes #265
> Throws the right error when a peer dependency is missing

- packages/berry-core/sources/Project.ts
The current code doesn't catch syntax errors, which cascade back to the top of the execution with pretty unhelpful messages. This diff ensures that even those errors get caught and logged.
> Catch all build errors, even syntax errors

- packages/berry-core/sources/VirtualFetcher.ts
Virtual links were created as `dir` on Windows even where they were pointing towards files, which was breaking installs. We didn't notice it before because:
- Our repository happens to contain the right type of symlinks (probably created before the regression), and the case didn't happen organically.
- For some reason Azure didn't catch the error, but running the tests locally did. Since I always run the tests on Azure only when working on Windows, I didn't notice it before.
A followup would be to refactor `NodeFS.symlinkPromise` to stop using this trailing-slash heuristic, and instead use the `type` parameter (I think we would just have to move this trailing-slash thing in the few places that actually need it, such as the `RawLinkFetcher`).
> Fixes the virtual link type

- .pnp.js
- packages/berry-core/package.json
- packages/berry-core/sources/Cache.ts
- packages/berry-fslib/sources/FakeFS.ts
- yarn.lock
Our cache was already designed to be accessed concurrently (much easier now that we have a single file per package), but the package we were using (`lockfile`) wasn't working very well in our case, so I swapped it to use our own implementation. After a quick try, it seems to work with four different processes installing the same project into the same cache.
Followup: avoid writing the cache files N times (we can just bailout after the siblings have finished generating their version of the file, if the checksum matches what we would expect).
Note: we can't make a regression test at the moment, because Azure runs with a single core.
> Concurrent cache

- packages/berry-core/sources/scriptUtils.ts
The user agent string is used by various tools to figure out under which package manager they're currently running. Even though the environment key is a bit unfortunate since we're no npm, there's no reason to break (especially given the precedence that are `npm_execpath` and co).
> Sets the user agent when calling a script

- packages/berry-core/sources/Configuration.ts
- packages/berry-core/sources/Plugin.ts
- packages/berry-core/sources/scriptUtils.ts
This diff implements a new hook called `wrapScriptExecution` that gets invoked when a script would get executed. It wraps the actual executor, meaning that the following use cases can now be implemented from within plugins:
- Use a different shell than the default one (for example if you want to leverage features only available in your native shell instead of the portable one).
- Log metrics regarding which scripts are run and how much time they take to execute (useful for frontend infrastructure teams that wish to get a better understanding of how product teams use the platform).
- Security measures (you can simply prevent a script from being executed based on the heuristic of your choice, for example the package name, author, ...).
> Implements a hook for scripts being run

- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/run.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/run.test.js
- packages/berry-cli/sources/cli.ts
- packages/plugin-essentials/sources/commands/run.ts
- packages/plugin-workspace-tools/sources/commands/foreach.ts
> I'm a Yarn user who's just starting on a repository, and I'd like to have a better idea of the main scripts of the project.
closes https://github.com/yarnpkg/berry/issues/284
When a user runs `yarn run` command without any parameters, he / she will get the list of the available scripts in the project. 
I did manual testing including regression tests - calling `yarn run` with some parameters or skipping `run` keyword and calling the commands like `yarn test:unit` 👍 
Thanks you  🙇 🙇
> `yarn run` with no parameters prints the list of available commands

- .pnp.js
- packages/plugin-pnp/package.json
- packages/plugin-pnp/sources/PnpLinker.ts
- yarn.lock
This diff changes the error message printed in the case described by https://github.com/yarnpkg/berry/issues/29#issuecomment-510854112. We now print the folder that contains the root of the project, which should help our users figure out what's wrong.
> Improves the message sent when we cant find the current package

- packages/plugin-essentials/sources/commands/plugin/dl.ts
The description for the two `plugin dl` and `plugin list` commands looks the same which might cause some confusion. I updated the command description for `plugin dl` to reflect what it actually does.
This is how `yarn --help` looks prior to this PR:
```
pack                 bundle local packages for publishing
plugin dl           list the active plugins
plugin list         list the active plugins
remove             remove dependencies from the project
```
> Updates descriptive text for plugin dl command

- packages/gatsby/src/components/header.js
I have noticed on production website that my search bar PR introduced the problem that Home top menu link stays active on doc pages. This PR fixes the problem - the Home menu link will be active on home page, during package search and while showing package details, on all doc pages it will be inactive.
> Fix double home menu link activation

- packages/gatsby/content/features/plugnplay.md
Quick fix to add a call to action for editing the caveat documentation, and update the list.
> Keep the caveats up-to-date

- packages/gatsby/content/advanced/lexicon.md
- packages/gatsby/content/features/workspaces.md
- packages/gatsby/src/components/header.js
- packages/gatsby/src/components/navigation.js
There was a problem on the website where the last navigation entry was often hidden from the view, even when scrolling as much as possible (this was caused by the top banner not being taken into account in the positioning of the navigation). This diff fixes the measures.
> Navigation fix

- packages/gatsby/content/advanced/plugin-tutorial.md
**WIP**
Current code snippet for the hello world command is incorrect in syntax, and probably with how it works so needs to update it.
This is currently WIP as we need to make another change to the 2nd example and also update guidelines on how to use deps in plugins.
> Update plugin tutorial on how to use commands

- packages/gatsby/src/pages/configuration/manifest.js
Fixes https://yarnpkg.github.io/berry/configuration/manifest#publishConfig: 
- not displaying the correct field name of `registry`
- `access` using an invalid placeholder
- `main` anchor linking to `publishConfig.access`.
[Fixed section](https://deploy-preview-331--keen-leavitt-98f35d.netlify.com/configuration/manifest#publishConfig)
> docs: Fix publishConfig fields

- packages/gatsby/content/advanced/plugin-tutorial.md
Updated the advanced plugin docs to include a complete and working example of using a Command-type plugin and its myriad of options such as:
- Command Usage such as with `yarn hello --help`
- Command listing in `yarn --help`
> Update plugin tutorial to include required elements

- packages/berry-core/sources/httpUtils.ts
Followup to #329
This diff changes the logic that removes the `Authorization` header on redirects to instead only do this if the hostname changed. We maybe should find a way to update the mock server to add an endpoint with such a logic, although that would make it harder to use Verdaccio in the future 🤔
Can you confirm it works for your use case, @Js-Brecht?
> Only removes the authorization header when switching hostnames

- packages/gatsby/src/components/syntax.js
For API documentation it's useful to be able to copy method/variable names. This is currently not possible for properties that have an anchor since the name is part of the anchor. This PR moves the name outside of the anchor while retaining hit size of the anchor.
Before:
After:
> docs: Improve anchor links UX for JSON docs

- .gitignore
- .vscode/pnpify/eslint/lib/api.js
- .vscode/pnpify/eslint/package.json
- .vscode/pnpify/typescript/lib/tsserver.js
- .vscode/pnpify/typescript/package.json
This diff ensures that the `.vscode` directory is properly checked into the repository (which is important because it contains the VSCode glue required for typecheck + linting).
It previously wasn't, because `.vscode` was ignored - and even though we had an override rules, they don't have any effect when the parent directory is ignored. Per the docs:
>  It is not possible to re-include a file if a parent directory of that file is excluded.
> Fixes the gitignore definitions

- .pnp.js
- packages/acceptance-tests/pkg-tests-specs/sources/protocols/npm.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/protocols/semver.test.js
- packages/plugin-npm/sources/NpmFetcher.ts
- packages/plugin-npm/sources/NpmSemverResolver.ts
This diff fixes #340 by ensuring that the version ranges are properly cleaned before querying the remote registry.
> Fixes support for v-prefixed semver ranges

- packages/berry-core/sources/scriptUtils.ts
Some images (alpine) don't have Bash installed. Since we're not using any Bash-specific feature, we can downgrade the shebang to only request `/bin/sh`.
Fixes #345
> Uses sh instead of bash for the proxy scripts

- .github/workflows/integration-workflow.yml
This diff adds support for Node 12 in our integration test pipeline.
> Enables tests for Node 12

- packages/berry-fslib/sources/index.ts
- packages/gatsby/content/getting-started/usage.md
- packages/plugin-essentials/sources/commands/entries/help.ts
- packages/plugin-essentials/sources/commands/set/version.ts
- packages/plugin-essentials/sources/commands/set/version/sources.ts
- packages/plugin-essentials/sources/index.ts
This command implements a new command:
```
yarn set version from sources
```
When run, this command will clone the Yarn repository into a temporary directory and build it there. The resulting will then be copied in the local project. This workflow makes it possible to quickly benefit from our fixes without having to wait for us to formally rebuild the artifacts.
> Implements "yarn set version from sources"

- packages/berry-core/sources/StreamReport.ts
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/commands/install.ts
This PR implements `--json` for both `install` and `add` (`remove` will come later if needed, as its use case is smaller than the two others).
In order to do this, the `StreamReport` class now has the ability to transparently transform all the messages it receives into NDJSON (without requiring to use `reportJson` to duplicate every message). This flag is meant to be disabled for commands that output "true" JSON data, such as `yarn config`.
> Implements --json for install & add

- packages/gatsby/content/features/plugnplay.md
Husky is supported starting from 4.0.0-1+.
> Updates the PnP compatibility list

- packages/berry-core/package.json
- packages/berry-fslib/package.json
- packages/berry-fslib/sources/FakeFS.ts
- packages/berry-fslib/sources/NodeFS.ts
- packages/berry-fslib/sources/ProxiedFS.ts
- packages/berry-fslib/sources/ZipFS.ts
- packages/berry-fslib/sources/ZipOpenFS.ts
- packages/berry-fslib/sources/index.ts
- packages/berry-fslib/sources/path.ts
- packages/berry-pnp/package.json
- packages/berry-pnpify/sources/NodeModulesFS.ts
- packages/berry-pnpify/sources/NodePathResolver.ts
- The fslib didn't account for some families of functions (`appendFile`, `readFile`, `writeFile`) being allowed to consume file descriptors.
- It also didn't implement `appendFile` at all.
I've added a new type, `FSPath<T>`, which encompasses `T | number`. This type is then used as input for the specific functions referenced above. Since most fake fs layers are abstracted under the `ProxiedFS` abstract, most of them don't have to deal with this as the fds will just be forwarded untransformed.
Of note: TypeScript doesn't prevent a subclass from implementing a subset of an abstract method, meaning that it'll not report it if a subclass of `FakeFS<T>` uses `T` as parameter for the relevant functions rather than `FSPath<T>`. …
> Improves fslib

- packages/berry-cli/package.json
- packages/berry-cli/sources/cli.ts
Yarn was running in an infinite loop when the `--cwd` option was pointing to the `/tmp` folder on OSX, which is a symlink to `/private/tmp`. I'm not 100% sure why it was doing that as we were doing a `chdir` to `/tmp`, not `/private/tmp`, so I'd have expected `process.cwd()` to return the same path, but it's not what happens (reproduced in the Node repl).
We'll now compare the realpath'd cwds rather than the virtual ones. This isn't a big deal anyway as this will only affect the few commands that use `--cwd`.
berry-cli
**Have you run `yarn version [major|minor|patch] --deferred` in those packages?**
> Prevents infinite loops with --cwd

- .github/workflows/integration-workflow.yml
- .github/workflows/package-workflow.yml
- .github/workflows/release-workflow.yml
- .pnp.js
- packages/berry-cli/package.json
- packages/berry-fslib/package.json
- packages/berry-libzip/package.json
- packages/berry-parsers/package.json
- packages/berry-pnp/package.json
- packages/berry-pnpify/package.json
- packages/plugin-constraints/sources/commands/constraints/query.ts
- packages/plugin-git/package.json
- packages/plugin-version/sources/commands/version/apply.ts
- scripts/actions/build-deb/build-deb.sh
- scripts/release.sh
- yarn.lock
Warning: hard to test, I'll probably have to commit to master for a few hours after that
We currently only build the CLI JS bundle when doing a release. No plugin, no deb, no packages.
The `release.sh` script will now build all the artifacts, and I've tried to plug the deb builder wrote by @Daniel15 into the release workflow. I'm not 100% certain of the syntax tho, so it's likely I'll have to make multiple releases to get it right!
> Improves the release process

- .github/workflows/e2e-jest-workflow.yml
> Add e2e test for jest

- packages/berry-cli/bin/berry.js
`yarn policies set-version v2` creates a file with the content `false` since https://github.com/yarnpkg/berry/raw/master/packages/berry-cli/bin/berry.js returns 404. Issue was caused by #395
Create a symlink from the old cli file to the current location
If any then the v1 cli should get a patch. Though this approach has the benefit that it is immediate and backports the fix.
- ~[ ] Yes~
> fix: yarn v1 downloading empty cli

- .github/workflows/e2e-mocha-workflow.yml
> Add e2e test for mocha

- packages/plugin-essentials/package.json
- packages/plugin-essentials/sources/commands/run.ts
- packages/yarnpkg-cli/package.json
Cf the comment - some tools use `yarn run --silent <something>` to make sure that Yarn won't pollute the output with its wrapper text. We don't do this anymore, but it's easier for them if they don't have to feature-detect it.
The `--silent` flag doesn't cause `yarn run` to crash (note that it *needs* to be between the `run` and the script / binary name - I have to double check because it seems to work even otherwise, but that would be a bug).
The flag is hidden because I don't want people to think it's useful when it doesn't actually do anything (we could document that, but just hiding it is simpler and maybe more effective).
plugin-essentials, yarnpkg-cli
**Have you …
> Adds support for (noop) run --silent

- packages/gatsby/gatsby-config.js
- packages/gatsby/src/pages/configuration/manifest.js
- packages/gatsby/src/pages/configuration/yarnrc.js
- packages/gatsby/src/templates/article.js
**What's the problem this PR 
E.g. https://yarnpkg.github.io/berry/features/offline-cache has no title when landing or `Home` when navigating from homepage.
Populate title by using `SEO` where necessary
- deploy docs
- ~[ ] Yes~
> fix(docs): Missing page titles

- packages/acceptance-tests/pkg-tests-specs/sources/commands/version/apply.test.js
- packages/plugin-version/package.json
- packages/plugin-version/sources/commands/version/apply.ts
- packages/yarnpkg-cli/package.json
Running `yarn version apply --all` in the berry workspace failed. While adding the malformed version string allows to find the rogue manifest via grep it would help to name the responsible workspace.
Prefix the usage error with the pretty locator of the workspace to help future debugging and fixed the version in `@berry/plugin-git`
* `@berry/cli`
* `@berry/plugin-version`
> feat(version): Add failed workspace name where apply fails

- packages/acceptance-tests/pkg-tests-specs/sources/features/resolutions.test.js
- packages/plugin-file/package.json
- packages/plugin-file/sources/FileResolver.ts
- packages/plugin-file/sources/TarballFileResolver.ts
- packages/yarnpkg-cli/package.json
Using `file:` within the `resolutions` field causes it to be bound to the top-level workspace (so that relative paths get resolved from the right location), but it causes problems when we later try to use that bound locator as a dependency of another one (because Yarn currently prevents rebinding on `file:`).
Does the same thing as #194, but for `file:` entries. Basically, if we try to rebind something that's already bound, we just ignore the bind call.
yarnpkg-cli
> Fixes using tarballs w/ the resolution field

- .pnp.js
- .vscode/pnpify/typescript/package.json
- package.json
- packages/plugin-essentials/sources/commands/workspaces/list.ts
- packages/plugin-exec/package.json
- packages/plugin-github/package.json
- packages/plugin-stage/package.json
- packages/plugin-stage/sources/commands/stage.ts
- packages/plugin-typescript/package.json
- packages/plugin-version/package.json
- packages/plugin-workspace-tools/package.json
- packages/vscode-zipfs/package.json
- packages/yarnpkg-builder/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-core/package.json
- packages/yarnpkg-fslib/package.json
- packages/yarnpkg-json-proxy/package.json
- packages/yarnpkg-libzip/package.json
- packages/yarnpkg-parsers/package.json
- packages/yarnpkg-pnp/package.json
- packages/yarnpkg-pnp/sources/generateSerializedState.ts
- packages/yarnpkg-pnpify/package.json
- packages/yarnpkg-shell/package.json
- yarn.lock
No actual issue but it IDE support is really laggy. Might make sense to leverage [incremental builds](https://devblogs.microsoft.com/typescript/announcing-typescript-3-4-rc/). First we need to fix breaking type changes though.
Bump typescript
None unless typescript changed how it emits code. Will go through release notes.
- ~[ ] Yes~
> build(deps): Bump typescript to 3.5.3

- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/install.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
- packages/yarnpkg-builder/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-core/package.json
- packages/yarnpkg-core/sources/Manifest.ts
- packages/yarnpkg-core/sources/Project.ts
- packages/yarnpkg-core/sources/Report.ts
As requested in https://github.com/yarnpkg/berry/pull/403#pullrequestreview-280066376. Picked an error that seemed the most "complex" for testing. Kind of too lazy to write test for every single validation warning :smile: 
Any errors encountered while loading manifests are currently supressed.
Persist those in the `Manifest` class and display warnings for all workspaces during install
* `@yarnpkg/builder`
* `@yarnpkg/cli`
* `@yarnpkg/core`
> feat(install): Display validation issues if any

- .github/workflows/e2e-husky-workflow.yml
> Add e2e test for husky

- .pnp.js
- packages/acceptance-tests/pkg-tests-specs/sources/features/unsafeHttpWhitelist.test.js
- packages/acceptance-tests/yarn.setup.js
- packages/gatsby/src/pages/configuration/yarnrc.js
- packages/yarnpkg-builder/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-core/package.json
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/sources/httpUtils.ts
- packages/yarnpkg-parsers/sources/resolution.ts
- yarn.lock
Although it's harder to exploit now than it was in the v1 (because we ignore by default what the registry tells us, and instead rely on the path convention), there is a potential attack vector where an attacker would surreptitiously insert an http url for a scoped package within the lockfile. This would cause Yarn to send the authentication token in clear, leading to all sorts of problem (remote code execution, session hijacking).
Yarn will now by default refuse to make any query to an http url. This behaviour can be overruled on a by-hostname basis thanks to the new `unsafeHttpWhitelist` field, which accepts a list of glob patterns. If a domain matches the rules listed there, http is allowed.
**Which packages would need a …
> Implements unsafeHttpWhitelist

- packages/acceptance-tests/pkg-tests-specs/sources/commands/add.test.js
- packages/plugin-essentials/package.json
- packages/plugin-essentials/sources/commands/add.ts
- packages/yarnpkg-cli/package.json
Problem is described in #361.
In short: say `lodash` is already installed as a regular dependency, typing `yarn add lodash --dev` duplicates the dependency entry in both `dependencies` and `devDependencies` within `package.json`.
As per https://github.com/yarnpkg/berry/issues/361#issuecomment-522326046:
1. Implement new flag `--prefer-dev`.
1. Switch installation target if package is already installed.
1. Throw `UsageError` if explicit flag causes a conflict.
In addition to that, clean up redundant dependency entries from `package.json`.
> Handle duplicate dependencies by `yarn add`

- packages/plugin-essentials/package.json
- packages/plugin-essentials/sources/commands/set/version/sources.ts
- packages/yarnpkg-cli/package.json
1. `yarn set version from sources` is slow
2. created file name contains too much yarn (should there exist such a thing as too much yarn? ;))
1. clone/fetch only latest commit
2. remove duplicate `yarn` prefix
> feat(set version): Miscellaneous changes

- packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
- packages/acceptance-tests/pkg-tests-specs/sources/dragon.test.js
- packages/yarnpkg-builder/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-core/package.json
- packages/yarnpkg-core/sources/Project.ts
When a workspace was depending on a package with a peer dependency (such as `react-dom`) through both `devDependencies` and `peerDependencies`, it wasn't virtualised in the context of the top-level workspace (because the code was incorrectly assuming that it got obtained through a peer dependency, which would require a single instantiation).
We now pass a flag during the virtualisation which indicates whether the package is a dependency of a top-level workspace. Since they are the only one to be in this situation (peer dependencies override regular dependencies since it doesn't make sense to list them both), a simple flag should be fine.
> Fixes virtual package generation

- packages/plugin-version/sources/commands/version/check.tsx
Since we get the file list from multiple sources, it sometimes happens that we get the same file multiple times. That breaks React, which expects unique keys.
We simply ensure unicity by converting back-and-forth with a `Set`.
> Prevents the same file from appearing twice in the list

- packages/acceptance-tests/pkg-tests-specs/sources/protocols/workspace.test.js
- packages/yarnpkg-builder/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-core/package.json
- packages/yarnpkg-core/sources/Workspace.ts
>  Our current recommendation is to use workspace:*, which will almost always do what you expect.
I expected it to match prerelease versions in the worktree. I'm a bit concerned with overloading semver `*` to work differently in different protocol contexts. I'd be fine with using relative paths but those are marked as experimental.
The use case is dogfeeding a component library to the docs of that library (both living in a monorepo). I never want yarn to look into the registry but strictly in the monorepo. So far I either have to adjust version ranges or use experimental features.
Add a special case for `workspace:*` that accepts every version. [npm semver `*` does not match …
> feat(resolve): Accept any workspace version in workspace:*

- packages/plugin-npm-cli/package.json
- packages/plugin-npm-cli/sources/commands/npm/publish.ts
- packages/plugin-npm/package.json
- packages/plugin-npm/sources/npmHttpUtils.ts
- packages/yarnpkg-cli/package.json
When publishing a scoped package to a registry, we were sending a GET requested to the registry to determine whether the version there already existed (when using `--tolerate-republish`). The problem is that we were doing this by passing the publish registry but not the ident, so our request was unauthenticated (and the GitHub Package Registry currently requires auth).
I could have solved that by using `npmAlwaysAuth`, but since the package was scoped the request should have been scoped anyway.
I relaxed the rules in the `RegistryOptions` so that a registry may now be defined when an ident is explicitly provided (I didn't find the rational why I didn't implement it this way, although I suspect this was before we had …
> Fixes publishing scoped packages to third-party registries

- packages/yarnpkg-builder/package.json
- packages/yarnpkg-builder/sources/boot-dev.js
- packages/yarnpkg-builder/sources/boot.js
The current script didn't have a shebang. This isn't a problem for the v2 since all scripts are run via Node by default, but the v1 used a regular `execFile` call which requires a shebang.
Adds a shebang to the file.
> Adds a shebang to yarnpkg/builder

- packages/yarnpkg-builder/package.json
```
Required package: @babel/plugin-syntax-class-properties (via "@babel/plugin-syntax-class-properties")
Required by: @yarnpkg/builder
```
```
Required package: @babel/plugin-syntax-decorators (via "@babel/plugin-syntax-decorators")
Required by: @yarnpkg/builder
```
Move dev dependencies to consumer dependencies.
Aside: This should probably be a rule that should be considered in #438 i.e. add a rule that given a list of files collects all import sources and checks if they are declared in a given manifest. In other words: Check that packages are not accidentally added in `devDependencies`.
> fix(builder): List undeclared dependencies

- .github/workflows/e2e-webpack-workflow.yml
- README.md
> Add webpack e2e tests

- packages/yarnpkg-pnpify/package.json
- packages/yarnpkg-pnpify/sources/generateSdk.ts
Pnpify SDK generation errors out if eslint is not installed #448 
Typescript and eslint existence checked first before attempt to generate sdk for each of them
> Check eslint and typescript existence before generating sdk

- packages/plugin-version/package.json
- packages/plugin-version/sources/commands/version/apply.ts
- packages/yarnpkg-cli/package.json
Running `yarn install` is required after running `yarn version apply`, as the lockfile hasn't been updated yet to reflect the changes (only the project manifests have been). This isn't ideal from a user experience point of view.
A real install will now be run after running `yarn version apply`, and the changes will only be made if the install passed. This ensures that if you commit the result after `yarn version apply` returns, you'll be in a good state with regard to `yarn install --immutable`.
> Runs a real install after yarn version apply

- packages/yarnpkg-builder/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-core/package.json
- packages/yarnpkg-core/sources/Project.ts
The message printed when cleaning unused archives doesn't highlight the file being removed.
The file name is now properly highlighted.
> Uses magenta when logging the file path

- scripts/setup-ts-execution.js
`@babel/register` stores its cache everywhere across berry monorepo, by creating many `node_modules/.cache/babel-register` dirs. 
This PR places `@babel/register` cache into os temporary dir. The implementation is not as clear as I would like, but it does the job I believe. The code inside @babel/register to pick the cache file name for the reference:
https://github.com/babel/babel/blob/master/packages/babel-register/src/cache.js#L8-L14
> Place @babel/register cache into tmp dir

- HISTORY.md
The project history is a bit fuzzy at the moment - who works on it, who used to, who to contact for context on some design decisions? Looking at the PRs helsp a bit, the teams as well (although they aren't up-to-date and probably could use a refreshing), but I think it's a good idea to keep track of it in a versioned document.
I've wrote this document based on what I know about the project (since I joined it, so ~feb 2017). Maybe @bestander, @cpojer, or @sebmck, could help fill the blank before this date if it doesn't match what they remember.
> Describes a bit the project history

- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/commands/bin.ts
- packages/plugin-essentials/sources/commands/cache/clean.ts
- packages/plugin-essentials/sources/commands/config.ts
- packages/plugin-essentials/sources/commands/install.ts
- packages/plugin-essentials/sources/commands/link.ts
- packages/plugin-essentials/sources/commands/node.ts
- packages/plugin-essentials/sources/commands/plugin/import.ts
- packages/plugin-essentials/sources/commands/plugin/list.ts
- packages/plugin-essentials/sources/commands/plugin/runtime.ts
- packages/plugin-essentials/sources/commands/remove.ts
- packages/plugin-essentials/sources/commands/run.ts
- packages/plugin-essentials/sources/commands/set/resolution.ts
- packages/plugin-essentials/sources/commands/set/version.ts
- packages/plugin-essentials/sources/commands/set/version/sources.ts
- packages/plugin-essentials/sources/commands/up.ts
- packages/plugin-essentials/sources/commands/why.ts
Closes #478 
Replace `yarn` in examples with `$0`
For some reason this already works even though a new version of clipanion hasn't been published yet. 🤷‍♂
> Remove binary name from examples

- packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
- packages/plugin-git/package.json
- packages/plugin-git/sources/constants.ts
- packages/plugin-pack/package.json
- packages/plugin-pack/sources/packUtils.ts
- packages/yarnpkg-cli/package.json
Listing `lib` into the `files` field didn't include the children of `lib` (you needed to put `lib/**/*`). This was mildly annoying for migration purposes (mostly annoying to find out), so I fixed it.
The previous pattern was blacklisting all files by default when a `files` entry was set. I've changed it to instead only blacklist the root entries (so once you override the rule with another one that allows a specific directory you don't need to whitelist the files, since they won't match the `/*` anymore). All tests seem to pass.
> Whitelists the full folder when packing

- packages/gatsby/src/pages/index.js
- packages/plugin-workspace-tools/bin/@yarnpkg/plugin-workspace-tools.js
- packages/plugin-workspace-tools/package.json
- packages/plugin-workspace-tools/sources/commands/foreach.ts
- packages/plugin-workspace-tools/sources/commands/workspace.ts
- packages/yarnpkg-cli/package.json
I thought it might make sense to let people know that they need to add `@yarnpkg/plugin-workspace-tools` to plugins.
Added the info to the commands.
I didn't find the workspace **list** command though.
Removed an unused import from gatsby index.js
> Add info to workspace command

- packages/yarnpkg-builder/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-cli/sources/main.ts
- packages/yarnpkg-core/package.json
- packages/yarnpkg-core/sources/execUtils.ts
The current code wasn't detecting properly when the stream sent to `stderr` was `stdout`.
- We don't alias `stderr` to `stdout` anymore (this isn't our role)
- We now check that the stream has a `fd` rather than just comparing it to a single stream instance
> Fixes pipevp fd detection

- .github/workflows/e2e-next-workflow.yml
Newer versions of Next.js support No-Config PnP support.
Removed the custom Next.js configuration step from the GitHub Workflow.
> Next.js Supports No-Config PnP

- packages/plugin-essentials/package.json
- packages/plugin-essentials/sources/commands/set/version/sources.ts
- packages/yarnpkg-cli/package.json
It's currently difficult to try out a PR outside of Yarn itself.
This diff adds a new `--pr` option to `yarn set version from sources`, which will try (best effort) to merge a pull request before building the CLI.
Some notes:
- It cannot be used at the moment to test changes on the non-CLI packages (such as PnPify)
- It's a best effort basis, so in case merge conflicts happen you're on your own for now
- Various misc changes are dropped before the merge (such as package.json or the various checked-in binaries), as they could generate potentially large conflicts with little value.
> Improves set version from sources

- packages/yarnpkg-pnpify/package.json
- packages/yarnpkg-pnpify/sources/NodeModulesFS.ts
- packages/yarnpkg-pnpify/sources/NodePathResolver.ts
- packages/yarnpkg-pnpify/tests/NodePathResolver.test.ts
There's an error which occurs when the top-level package refers to itself via its own name. In this case, PnPify was incorrectly reporting the `node_modules/<top level name>` as being a real folder.
My diff adds a basic capability to PnPify to return explicit folder symlinks. When this specific pattern is found (a package depending on itself), we now return a "proper" symlink.
Note that this doesn't solve the more general case of the `link:` and `portal:` protocols (I think? since they would trigger the same codepath), but those might be solvable through the work in progress at #500 and #470.
> Fixes top-level self-references in PnPify

- packages/acceptance-tests/pkg-tests-specs/sources/commands/version/check.test.js
- packages/plugin-version/package.json
- packages/plugin-version/sources/commands/version/check.tsx
- packages/yarnpkg-cli/package.json
Acts as a failing test case for `yarn version check` not considering reverted changes.
Didn't fix it yet. Just want to clarify semantics first. Workaround exists anyway since you can just change the nonce but is this really what we want?
> fix(version check): Don't consider reverted changes

- packages/plugin-essentials/package.json
- packages/plugin-essentials/sources/commands/install.ts
- packages/yarnpkg-cli/package.json
I made a typo in #490 by adding support for `ignore-engine` instead of `ignore-engines` (as was the case in the v1). It causes Next deployments to crash.
Fixed the typo. Since nothing should use that anyway, it's acceptable.
> Fixes typo in ignore-engines

- .github/workflows/integration-workflow.yml
It seems that the default shell changed and Windows is now using Powershell out of the box. It's problematic for our integration tests, since they are meant to run on both Windows and Posix.
I've explicitly set `bash` as the shell to use everywhere (cf [documentation](https://help.github.com/en/github/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions#using-a-specific-shell)).
> Forces bash on GitHub Actions

- packages/plugin-init/package.json
- packages/plugin-init/sources/commands/init.ts
- packages/yarnpkg-cli/package.json
Some bash scripts use the `-y,--yes` option from Yarn v1. Even though we're streamlining the syntax with the `--interactive` flag we can support `--yes` for now (and formally deprecate it later).
The `--yes` option won't generate an error (but won't have any effect since we don't ask questions by default).
> Exposes --yes for yarn init

- packages/yarnpkg-builder/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-core/package.json
- packages/yarnpkg-core/sources/Project.ts
During resolution there is no throttling of requests for metadata. A medium size
project (react native v61 boilerplate) can have more than 385 simultaneous
open connections to the npm registry. While registry.npmjs.org
and registry.yarnpkg.com can handle this load, a private registry such as
Nexus may not. 
...
This limits the concurrent requests to something manageable
for private registries. It leverages the same tool to limit parallel fetches
of tarballs in the fetchEverything method
...
> limit parallel requests to registry during resolution

- packages/acceptance-tests/pkg-tests-specs/sources/dragon.test.js
- packages/yarnpkg-builder/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-core/package.json
- packages/yarnpkg-core/sources/Project.ts
- packages/yarnpkg-core/sources/structUtils.ts
We create copies of packages when they have peer dependencies, and update their immediate parents to instead reference the copy.
Since parents have been copied themselves if there's a possibility they would resolve to different versions (because it only happens when they have peer dependencies themselves) the patch operation is safe. There's one catch though: workspaces aren't traversed this way in our implementation, so they aren't copied, and the dependency replacements may end up being mirrored in the other unrelated instances of the same package.
We now clone the original workspace dependencies before starting the traversal. This way, even if they are overwritten, further accesses will still be able to retrieve the base …
> Fixes a bug in how peer dependencies are propagated to workspaces

- plugins.yml
```
➤ YN0001: YAMLException: duplicated mapping key at line 23, column -324:
"@yarnpkg/plugin-workspace-tools":
^
```
Fix the typo.
> Fix duplicated plugin name

- .github/workflows/e2e-next-workflow.yml
This upgrades the workflow's Next.js version to the latest canary, which should stop it from failing.
This canary includes the fix landed in https://github.com/zeit/next.js/pull/9453.
> Fix Next.js E2E Workflow

- packages/plugin-exec/README.md
`mkdirSync` and `writeFileSync` are functions exported by `fs` node package not `child_process`.
Just change `child_process` to `fs` in readme.
> Update readme of @yarnpkg/plugin-exec

- packages/yarnpkg-pnpify/package.json
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
- packages/yarnpkg-pnpify/sources/hoist.ts
- packages/yarnpkg-pnpify/tests/hoist.test.ts
The problem is that hoister were forgetting original deps after hoisting out dependencies. Fixes: #607
We maintain original peer dependencies and dependencies and run require promise and peer dep promise rule checks on them, not on hoisted dependencies.
> Fix hoisting by maintaining and checking original deps in pnpify

- packages/yarnpkg-core/sources/Manifest.ts
- packages/yarnpkg-core/tests/Manifest.test.ts
Fixes https://github.com/yarnpkg/berry/issues/619
Remove BOM character prior to `JSON.parse`
> Strip byte order mark characters before parsing JSON

- packages/gatsby/content/features/plugnplay.md
WebStorm 2019.3 (and other JetBrains IDEs) adds native [support for Yarn PnP](https://blog.jetbrains.com/webstorm/2019/11/webstorm-2019-3/#tools).
> Add WebStorm as compatible tool

- .pnp.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/fallback-peer-deps-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/fallback-peer-deps-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/basic.test.js
- packages/yarnpkg-core/sources/Project.ts
Fixes #626 
> I found the issue - we're currently iterating over each package to find out their linkers, then we iterate a second time to inject the packages into the linkers. When I say "each package" it's not entirely true: we don't actually do this for packages that are "virtual package templates", since they usually don't need to be linked.
>
> The problem occurs when such a regular package template somehow depends on a virtual package template: since the virtual package template didn't get traversed in step 1, we haven't assigned it a linker, hence the failed assertion.
> 
> Package templates should never be valid package dependencies, but they currently are in one particular case: when a package lists the same name as both a dependency and a …
> Fixes assertion

- packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
- packages/acceptance-tests/pkg-tests-fixtures/packages/@private__unconventional-tarball-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/@private__unconventional-tarball-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/private-unconventional-tarball-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/private-unconventional-tarball-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/auth.test.js
- packages/plugin-npm/sources/NpmHttpFetcher.ts
- packages/plugin-npm/sources/npmHttpUtils.ts
Fixes https://github.com/yarnpkg/berry/issues/601
- Use `npmHttpUtils.get` in `NpmHttpFetcher`
- Add support for absolute paths in `npmHttpUtils.get`
> Fix missing credentials when fetching tarballs

- .github/workflows/e2e-cra-workflow.yml
The current E2E CRA test uses the `--typescript` flag, which is deprecated in favor of `--template typescript`.
Use the new `--template typescript` invocation
> Use CRA's new --template parameter in E2E test

- packages/plugin-init/sources/commands/init.ts
- packages/yarnpkg-core/sources/Manifest.ts
This PR fixes #624 
To summarize the issue, when running `yarn init` in a new project, the unused fields are all listed with the value `undefined`. This is because in `Manifest.ts` `exportTo` method, fields in the `data` object are being set as `undefined` if not used.
Here is an example:
```bash
> yarn init
{
name: 'example-project',
bin: undefined,
dependencies: undefined,
optionalDependencies: undefined,
devDependencies: undefined,
peerDependencies: undefined,
dependenciesMeta: undefined,
peerDependenciesMeta: undefined,
resolutions: undefined,
files: undefined
}
```
Now in the `Manifest.ts` `exportTo` function, instead of setting unused fields as `undefined` they get deleted from the `data` object. The new output looks …
> Fix yarn init printing undefined values

- .github/workflows/e2e-vue-cli-workflow.yml
- README.md
The Vue folks have nicely merged the fixes needed for PnP to be happy, and together with #603 we should be able to cover Vue-CLI with our E2E tests.
Added an E2E test 🎉
> Adds the Vue-CLI E2E workflow

- .github/workflows/e2e-angular-workflow.yml
- packages/plugin-patch/sources/tools/apply.ts
The current heuristic for located patched hunks within a file diverges significantly from the original, and that makes applying a patch to different versions of a same dependency pretty difficult.
In particular, the patch generated from TypeScript 3.7 can only be applied with a 500+ offset on TypeScript 3.6, and 800+ offset on TypeScript 3.5.
The heuristic is now much closer from the original one in that we no longer look in a fixed amount of lines around the hunk, and instead locate it wherever it is in the file then use that to constraint futur patches to a smaller subset of the file.
> Improves the patch heuristic

- .pnp.js
- packages/plugin-compat/gen-typescript-patch.sh
- packages/plugin-compat/package.json
- packages/plugin-compat/sources/patches/typescript-1.ts
- packages/plugin-constraints/package.json
- packages/plugin-dlx/package.json
- packages/plugin-essentials/package.json
- packages/plugin-init/package.json
- packages/plugin-interactive-tools/package.json
- packages/plugin-npm-cli/package.json
- packages/plugin-pack/package.json
- packages/plugin-patch/package.json
- packages/plugin-pnp/package.json
- packages/plugin-stage/package.json
- packages/plugin-typescript/package.json
- packages/plugin-version/package.json
- packages/plugin-version/sources/commands/version/check.tsx
- packages/plugin-workspace-tools/package.json
- packages/yarnpkg-check/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-core/package.json
- yarn.lock
It seems that `__spreadArray` wasn't available on older TS releases, so while the patch can be applied it doesn't actually work.
I now use `[].concat(A, B)` instead of `[...A, ...B]`.
> Fixes TS patch for older TS versions

- packages/gatsby/src/components/details/ReadMore.js
Images in readme were too big
images now can not be wider than the size of the container, like in v1
> fix(details): prevent images from overflowing in readmes

- packages/gatsby/content/features/plugnplay.md
> Fix typo in pnp docs

- packages/yarnpkg-core/sources/scriptUtils.ts
The install step of husky `>= 4.0.0-beta.4` fails on windows because `INIT_CWD` starts with `/`.
Since husky doesn't use an exit code, the install step passes, ref https://github.com/typicode/husky/pull/633
Normalize `INIT_CWD` using `npath.fromPortablePath`.
> fix: normalize INIT_CWD

- packages/plugin-interactive-tools/bin/@yarnpkg/plugin-interactive-tools.js
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
The plugin is @yarnpkg/plugin-interactive-tools instead of @yarnpkg/plugin-interactive
Documentation problem to use upgrade-interactive command
...
> [fix][doc] Fix doc for interactive plugin

- packages/gatsby/gatsby-config.js
it isn't used by the site, so its preloading isn't necessary as far as I can tell.
Removed Baumans from the font configuration
> remove Baumans font

- docs/404.html
- docs/index.html
- packages/gatsby/src/components/layout.css
- packages/gatsby/src/components/syntax.js
If the custom fonts would fail for some reason, or if someone blocks them, right now there are no fallbacks, meaning that a serif font would be displayed
Adding sans-serif to all instances of Open Sans, monospace to PT Mono
> add fallback font families

- .github/workflows/e2e-rollup-workflow.yml
Add e2e tests for `rollup` (#368)
Please tell me what other plugins/examples should I add :)
> Add e2e tests for rollup

- .yarn/versions/927303f6.yml
- packages/gatsby/content/advanced/editor-sdks.md
- packages/gatsby/content/advanced/pnpify.md
- packages/yarnpkg-pnpify/sources/generateSdk.ts
Since TS now has native support for PnP through our patch approach, we don't need PnPify to run it anymore.
Removed PnPify from the TS SDK.
> Removes PnPify from the TS SDK

- .yarn/versions/d9fa2c10.yml
- packages/plugin-dlx/sources/commands/dlx.ts
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/commands/install.ts
- packages/plugin-essentials/sources/commands/link.ts
- packages/plugin-essentials/sources/commands/remove.ts
- packages/plugin-essentials/sources/commands/runIndex.ts
- packages/plugin-essentials/sources/commands/set/resolution.ts
- packages/plugin-essentials/sources/commands/set/version/sources.ts
- packages/plugin-essentials/sources/commands/up.ts
- packages/plugin-essentials/sources/commands/why.ts
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
- packages/plugin-npm-cli/sources/commands/npm/publish.ts
- packages/plugin-pack/sources/commands/pack.ts
- packages/plugin-patch/sources/commands/patch.ts
- packages/plugin-patch/sources/commands/patchCommit.ts
- packages/plugin-pnp/sources/commands/unplug.ts
- packages/plugin-version/sources/commands/version.ts
- packages/plugin-version/sources/commands/version/apply.ts
- packages/plugin-version/sources/commands/version/check.tsx
- packages/plugin-workspace-tools/sources/commands/foreach.ts
- packages/plugin-workspace-tools/sources/commands/workspace.ts
- packages/yarnpkg-cli/sources/tools/WorkspaceRequiredError.ts
- packages/yarnpkg-cli/sources/tools/openWorkspace.ts
```
This command can only be run from within a workspace of your project
```
The error meant that there was a lockfile somewhere within the ancestors that prevented Yarn from correctly detecting the project root, but that was fairly difficult to understand.
The error now includes detailed information:
```
This command can only be run from within a workspace of your project (foo is not a workspace of /home/arcanis/package.json)
```
> Improves an error message

- .yarn/versions/042aef38.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/plugin/import.test.js
- packages/gatsby/content/advanced/plugin-tutorial.md
- packages/gatsby/content/advanced/questions-and-answers.md
- packages/gatsby/content/features/plugins.md
- packages/plugin-essentials/sources/commands/plugin/import.ts
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-parsers/sources/syml.ts
- plugins.yml
- scripts/plugin-hello-world.js
Running `yarn plugin import` required to know the full name of the plugin, which wasn't very easy (especially considering that all of our plugins have the same prefix anyway).
Plugins had to expose a `default` key, which wasn't obvious either.
The `yarn plugin import` command now automatically expands the plugin name if required, so running something like `yarn plugin import version` will now work.
The plugin loader now uses the `default` key if present, but also fallback to the whole object if the key isn't there (kind of like what the interop Babel helper does).
> Tweaks the plugin pipeline

- .yarn/versions/c60c2dbe.yml
- packages/plugin-pnp/sources/PnpLinker.ts
People ignore warnings, so the presence of the `node_modules` makes them thing that something is wrong in Yarn when the resolution goes there.
The lingering `node_modules` will now be removed when running `yarn install`.
> Removes the node_modules by default

- .vscode/pnpify/eslint/lib/api.js
- .vscode/pnpify/typescript/lib/tsserver.js
- .vscode/pnpify/typescript/package.json
- .yarn/versions/f79ad2fd.yml
- packages/yarnpkg-pnpify/sources/generateSdk.ts
Prettier is a common extension that wasn't covered by the SDK.
- Added a shim for `prettier` (plus the relevant configuration)
- Updated the shim template to use `createRequire` instead of the `paths` option, which seems more fickle (I'm not entirely sure why, but it didn't work with Prettier despite working for TS and ESLint).
> Adds prettier to the PnPify SDK

- .pnp.js
- .yarn/versions/8e9fccb2.yml
- packages/plugin-init/package.json
- packages/plugin-init/sources/commands/init.ts
- yarn.lock
Running `yarn init` used to leave a weird empty `dependenciesMeta` field because the proxy wasn't forwarding the `delete`.
Removed the proxy altogether. It doesn't matter since there can be no original manifest anyway.
> Stops using json proxy

- .yarn/versions/12db9b67.yml
- packages/yarnpkg-core/sources/Plugin.ts
- packages/yarnpkg-core/sources/Project.ts
Changing Node version wasn't causing the dependencies to be rebuilt.
A global cache key is now determined and may be used to trigger a fresh rebuild. By default this cache key includes the Node version, plugins can add others as needed (this should be fairly rare as I would prefer people to use regular dependencies to mark their ... dependencies).
> Rebuild packages when switching between Node versions

- .yarn/versions/03fb926a.yml
- packages/plugin-constraints/sources/tauModule.ts
- packages/plugin-essentials/sources/commands/workspaces/list.ts
- packages/plugin-essentials/sources/suggestUtils.ts
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
- packages/plugin-pack/sources/index.ts
- packages/plugin-version/sources/versionUtils.ts
- packages/plugin-workspace-tools/sources/commands/foreach.ts
- packages/yarnpkg-core/sources/Project.ts
- packages/yarnpkg-core/sources/WorkspaceResolver.ts
- packages/yarnpkg-core/sources/structUtils.ts
Back when I started Yarn 2 I felt like maybe it could be interesting to have multiple workspaces with different versions. In retrospect it felt a very bad idea, and I always planned to remove this before tagging the stable release.
Removed `findWorkspacesByDescriptor` since it can only have one result at most.
> Prevents workspaces from listing duplicates

- .yarn/versions/e251a5e7.yml
- packages/plugin-npm-cli/sources/commands/npm/publish.ts
The code was referencing `body.response` instead of `response.body`, which caused `yarn npm publish` to fail to print the error messages.
Fixed the typo.
> Fixes error handling when publishing

- packages/acceptance-tests/pkg-tests-specs/sources/features/localMirror.test.js
We didn't test that the cache wasn't poisoning the mirror. Since it's a recurrent concern with the 1.x branch I want to make sure we're not affected by this.
Added tests 🙂
> Adds a test for the local mirror

- .yarn/versions/f2edabde.yml
- packages/plugin-essentials/sources/commands/workspace.ts
- packages/plugin-essentials/sources/index.ts
- packages/plugin-workspace-tools/sources/index.ts
Using `yarn workspace` is very handy to work in another project than the current one. At the moment it requires installing the `workspace-tools` plugin which, although technically correct, is a bit annoying. From what I've seen, it'll most likely be the main command from our plugins that people will miss.
Given how small and useful it is we can just move it to the essentials plugin.
> Moves `yarn workspace` to the essentials

- .yarn/versions/07dba47d.yml
- packages/plugin-essentials/sources/commands/plugin/import.ts
I intended to make the following possible:
```
yarn plugin import workspace-tools
yarn plugin import plugin-workspace-tools
yarn plugin import @yarnpkg/plugin-workspace-tools
```
But the regex was boggus, causing #722.
Fixes #722
Fixed the regex.
> Fixes the `yarn plugin import` regex

- packages/gatsby/content/advanced/contributing.md
- packages/gatsby/content/advanced/lifecycle-scripts.md
- packages/gatsby/content/advanced/migration.md
- packages/gatsby/content/getting-started/install.md
- packages/gatsby/content/getting-started/usage.md
Some things were missing or outdated in the documentation.
> Upgrades the migration guide

- package.json
- scripts/compile.js
- tsconfig.json
Switch to the typescript compiler instead of babel to output `.d.ts` files next to the `.js` files.
Use a custom compile script instead of `tsc` to allow for a single `tsconfig.json` file for the entire berry project.
Fixes #707 
I still need to make some changes to the commands, because typescript is now complaining about the `usage` properties, but I wanted feedback on the setup before starting on that.
```
$ yarn packages/plugin-essentials prepack
sources/commands/add.ts(44,10): error TS2742: The inferred type of 'usage' cannot be named without a reference to '../../../../.yarn/cache/clipanion-npm-2.1.5-aef0ebbd62-1.zip/node_modules/clipanion/lib/advanced'. This is likely not portable. A type annotation is necessary.
sources/commands/bin.ts(14,10): error TS2742: The inferred type of …
```
> Switch to typescript for compilation to generate .d.ts files

- packages/gatsby/src/components/hit/index.js
v1 | v2
---|---
Make position absolute, like in v1 site
> fix(www): position links correctly in search

- packages/gatsby/src/components/search/SearchBox.js
Package names often are slight misspellings from real words, and thus the behaviour of the spelling getting changed is very frustrating!
avoid autocomplete, -correct, -capitalize & spell check. Also avoids a length of > 512 characters from being submitted (will throw an Algolia error)
This is the default behaviour of React InstantSearch (and thus Yarn v1)  too
> fix(www): avoid autocorrect etc.

- packages/gatsby/content/features/plugnplay.md
According to @merceyz, the table was out of the date. From the Discord conversation:
Apparently @typescript-eslint has been fully compatible since 2.12.
The last commit that sets the peer dependencies is the following: https://github.com/typescript-eslint/typescript-eslint/commit/348d2f6b207acb9e18721cba53f0aa85908fa777
The tag 2.12 is the first one whose diff with master doesn't display the commit: https://github.com/typescript-eslint/typescript-eslint/compare/v2.12.0...master
**UPDATE:** More good info from @merceyz:
I've added a commit to also update TypeScript's status.
> Update compatibility status on Typescript-Eslint

- packages/gatsby/content/advanced/sherlock.md
Let's pretend I read this statement and got confused how to expect on promises in #754 :laughing: 
`await` the `expect` statement
> docs(sherlock): await expect statements if they aren't returned

- packages/gatsby/content/advanced/migration.md
The link to "packageExtensions" does not go anywhere.
I added the correct path.
> Add URL for packageExtensions link

- packages/gatsby/content/advanced/editor-sdks.md
Updates the documentation of editor-sdks. Adds some additional information about what tools are currently supported, a note about needing to rerun the command after instaling certain dependencies, and a workaround for the go to definition issue.
Updated the documentation text.
Feel free to request changes if something should be reworded.
> docs: update editor-sdks

- packages/yarnpkg-shell/README.md
Just a minor typo in the yarnpkg-shell README.
Javascript → JavaScript
> docs: fix typo in yarnpkg-shell README

- .yarn/versions/31d91f93.yml
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
Fixes: #751
When workspaces were added (they really are not) the progress indicator was not notified.
Now the progress indicator is notified both for workspaces and normal packages.
> Fix bug - adding workspaces has not been reported

- packages/gatsby/src/components/details/Contributors.js
before|after
---|---
Added left padding: 0, and list-style-type: none
> chore(www): hide bullet points on contributor list

- .yarn/versions/51b29e0f.yml
- packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
- packages/plugin-pnp/sources/PnpLinker.ts
Similar to 1.x which was removing this directory until recently, 2.x was removing the whole node_modules regardless of what was stored inside. Since that's usually the place where caches are stored (for example in `babel-loader`), it was causing cold cache more often than needed.
Only non-dot-folders will be removed (or the whole folder if there is no dot folder). Added tests to prevent regressions.
> Keep the cache (n_m/.cache) between runs

- .vscode/pnpify/eslint/bin/eslint.js
- .vscode/pnpify/eslint/lib/api.js
- .vscode/pnpify/typescript/bin/tsc
- .vscode/pnpify/typescript/bin/tsserver
- .vscode/pnpify/typescript/lib/tsc.js
- .vscode/pnpify/typescript/lib/tsserver.js
- .yarn/versions/a8210a0e.yml
- packages/yarnpkg-pnpify/sources/generateSdk.ts
Setting the `NODE_OPTIONS` environment value has adverse effects on ... npm, which VSCode is using when putting the mouse over a dependency name in a `package.json`. I haven't investigated why although I'd be curious to know what might cause a problem.
Since we don't actually seem to need `NODE_OPTIONS` (tested without it locally) it's now disabled by default in the SDK.
> Skips setting node_option when useless

- .yarn/versions/b434333c.yml
- packages/acceptance-tests/pkg-tests-specs/sources/auth.test.js
- packages/plugin-npm/sources/index.ts
- packages/plugin-npm/sources/npmConfigUtils.ts
- packages/yarnpkg-core/sources/Configuration.ts
We were normalizing `npmRegistryServer` when reading from config, which caused mismatch for `npmRegistries` keys ending with trailing `/`
Added a `normalizeKeys` fn and normalize `npmRegistries` keys.
Related: https://github.com/yarnpkg/berry/issues/760
> normalize npm registries with trailing slash

- packages/gatsby/static/_redirects
`/lang/` shouldn't be user-facing, and actually breaks some URLs.
References #1031 (-ish)
> Remove /lang/ from redirect URLs

- .yarn/versions/b851b003.yml
- packages/plugin-compat/sources/extensions.ts
Can't use `@pm2/agent` because it doesn't declare `debug` as a dependency
Closes https://github.com/yarnpkg/berry/issues/795
Added `debug` as a dependency of `@pm2/agent` in `plugin-compat`'s extensions
> feat(compat): add @pm2/agent to extensions

- packages/gatsby/src/components/seo.js
- packages/gatsby/src/pages/configuration/manifest.js
- packages/gatsby/src/pages/configuration/yarnrc.js
- packages/gatsby/src/pages/index.js
- packages/gatsby/src/pages/package.js
The SEO for the website is inconsistent and contains default values from Gatsby.
Define a constant to be reused in all pages.
> Reuse seo keywords in all pages

- README.md
The link for plugin-stage was pointing to plugin-pack.
Changed the URL to what it should be.
> docs: fix link to plugin-stage

- packages/gatsby/src/components/header.js
...
Remove the css properly `height` and reduce `line-height` and wrap the white spaces only on mobile (this might depend of future text)
There are other issues in the home page, but this one looks ugly on mobile.
> Fix news container overlap the logo on mobile

- .pnp.js
- .yarn/versions/6e68a2ec.yml
- packages/plugin-pnp/package.json
- packages/plugin-pnp/sources/index.ts
- yarn.lock
Fixes #716.
@arcanis I followed your suggestion. Let me know if that's the appropriate location to throw this error. 
Thanks!
> throw error if using node <12 and the path to .pnp.js includes spaces

- .github/workflows/e2e-gatsby-workflow.yml
- .github/workflows/e2e-rollup-workflow.yml
Related to #368 and #689. Test against development build (yarn start) for `gatsby` app. Which includes some development only loaders like `eslint-loader`.
Since https://github.com/gatsbyjs/gatsby/pull/20629 has landed and released, it should fix the test now.
There are still some plugins that are not supported yet, one would be https://github.com/gatsbyjs/gatsby/pull/20638. We'll make another PR to make the test more comprehensive after upstream fixes the issue.
I also fix a bug in rollup e2e test where I accidentally use the wrong command 😞.
> Add development server e2e for gatsby

- .yarn/versions/1e97f110.yml
- packages/yarnpkg-fslib/sources/ZipFS.ts
- packages/yarnpkg-fslib/tests/ZipFS.test.ts
`zipFs.readFileSync("/a symlink")` returns the symlink target instead of the file content targeted by the symlink.
`zip_name_locate` uses paths without leading slash. Remote the slash. Also, fix the `statImpl` to return `S_IFLNK`.
> Fix symlink handling in ZipFS

- .yarn/versions/f7939de5.yml
- packages/yarnpkg-core/sources/httpUtils.ts
The `got@10` upgrade changed how the `hostname` property worked, and that caused one of our checks to be disabled. As a result, the authentication information were forwarded even when switching from an hostname to another. This caused problems on the GitHub Package Registry, which throws 400 when receiving multiple authentication tokens.
Fixes #846 
Fixed the condition to check the new name for the `hostname` property.
> Fixes authentication when redirected

- packages/gatsby/src/components/header.js
- packages/gatsby/src/components/layout-content-nav.js
- packages/gatsby/src/components/markdown.js
- packages/gatsby/src/components/navigation.js
- packages/gatsby/src/components/syml.js
- reduce the size of menu item
- takes less space
- width: 300px -> 260px
- padding: 1.5em -> 1em
- more readable
- [use fewer borders](https://twitter.com/steveschoger/status/897849211110273024)
- unify marker of top nav and of side menu
- add hover behavior
- [avoid using text justify](https://designforhackers.com/blog/justify-text-html-css/)
Before | After
-|-
- reduce padding of document: 2em -> 1em (only on mobile)
- fix z-index issue with main navigation
- make sub navigation scrollable instead of taking a lot of place on the page
(the padding are set to cut the text and so to highlight that this div is scrollable)
- add shadow on main nav
- use `x` in menu toggle when is open
- center and use a gray color for the content on the menu toggle
- avoid cutting title in their middle …
> Improve navigation of website (specially on mobile)

- packages/plugin-patch/LICENSE
Given that this package copies and modifies a portion of patch-package's source, the copyright should be maintained in accordance with the MIT license.
Added a sublicense conforming to the MIT license of patch-package.
---
The sublicense here can be modified however you'd like as granted by the original  license. I just put something together that I hoped was simple enough for the purpose. 
I appreciate all the work y'all have put in, especially given some of challenges around the PnP conversations. Despite the challenges, I think we should always try to do our best at providing attribution when we're benefiting from the work of others.
> Perserve copyright notice for patch-package source

- .eslintrc.json
- .pnp.js
- .yarn/versions/325ffac3.yml
- packages/plugin-pnp/sources/PnpLinker.ts
- packages/yarnpkg-fslib/sources/FakeFS.ts
- packages/yarnpkg-fslib/sources/NoFS.ts
- packages/yarnpkg-fslib/sources/NodeFS.ts
- packages/yarnpkg-fslib/sources/ProxiedFS.ts
- packages/yarnpkg-fslib/sources/VirtualFS.ts
- packages/yarnpkg-fslib/sources/ZipFS.ts
- packages/yarnpkg-fslib/sources/ZipOpenFS.ts
- packages/yarnpkg-fslib/sources/index.ts
- packages/yarnpkg-pnp/sources/generateSerializedState.ts
- packages/yarnpkg-pnpify/sources/NodeModulesFS.ts
When using packages with native files (files that wont be used by node directly) they have to be manually unplugged. This is an annoyance for one project but more of a hurdle if package authors have to provide a "and remember to unplug [...]" step. Then there are packages [silently ignoring access failure ](https://github.com/sindresorhus/term-size/blob/9ee61b4972e3f23047ddaca2aa569e7c91f6396f/index.js#L29-L36) causing issues to go unnoticed.
Fixes https://github.com/yarnpkg/berry/issues/663
Automatically unplug packages if they contain files with an extension matching a predefined set. This set might not match all use-cases but should take care of most of them.
Running on the yarn repo it unplugs three packages because of …
> feat: unplug packages with native files

- .yarn/versions/8d1e5cf5.yml
- packages/plugin-essentials/sources/commands/add.ts
This PR adds `yarn add --optional` to Berry and closes #837.
I added the `-O,--optional` flag to Berry.
It currenly has 4 uses:
* `yarn add --optional <package>` adds `<package>` to the `optionalDependencies` field, if it isn't already present in `package.json`
* `yarn add --optional <package>` moves `<package>` from the `dependencies` field to the `optionalDependencies` field, if it is already present in `package.json`
* `yarn add --optional --peer <package>` adds `<package>` as an optional peer dependency (
```json
"peerDependencies": {
"<package>": "<version>"
},
"peerDependenciesMeta": {
"<package>": {
"optional": true
}
}
```
) if it isn't already present in `package.json`
* `yarn add --optional --peer <package>` …
> feat(plugin-essentials): yarn add --optional

- packages/gatsby/content/advanced/migration.md
Maybe this line
```
yarn policies set-version berry
```
could be added to the migration guide? 🤔 
I mean it's in getting started, yet could make things even easier 😁
...
...
> docs: fix typo in migration.md

- packages/gatsby/content/getting-started/install.md
The provided script is incorrect as there is no `policies` command
Docs provide an incorrect command for setting policies
I refactored the command to be the one that worked for me on my local
> docs: corrected policy script

- packages/plugin-node-modules/README.md
I believe this should be `.yarnrc.yml` rather than `.yarnrc`. Ref #244.
> Update n_m linker doc

- .yarn/versions/f0f68ba3.yml
- packages/plugin-essentials/sources/commands/remove.ts
Running `yarn remove <package>` leaves behind:
```json
"peerDependenciesMeta": {
"<package>": {
"optional": true
}
}
```
I made `yarn remove <package>` also delete `<package>` from `peerDependenciesMeta`.
> feat(plugin-essentials): make `yarn remove` remove package(s) from peerDependenciesMeta 

- packages/gatsby/content/advanced/questions-and-answers.md
- packages/gatsby/gatsby-plugin-clipanion-cli/gatsby-node.js
In general, people are lazy to it's better to have the TL;DR at the beginning and then the full explanations
Put examples first:
Before | After
-|-
Reorder (gitignored then as you want then kept files) + put TL;DR first
Before | After
-|-
> Improve documentation's flow

- packages/gatsby/src/components/header.js
- packages/gatsby/src/components/search/SearchBox.js
- packages/gatsby/src/pages/index.js
Before | After
-|-
Continuation of this PR: https://github.com/yarnpkg/berry/pull/842
- Text center
- Increase padding top
Before | After
-|-
- Reduce font size (avoid making the page scrollable because the text is too big)
- Text center
- Increase margin bottom
Before | After
-|-
- reduce icon size
- reduce padding on section
- reduce margin bottom on h3
- flex center
Before | After
-|-
> Improve homepage on mobile

- .github/ISSUE_TEMPLATE/bug-report.md
- CHANGELOG.md
- CONTRIBUTING.md
- README.md
- docs/404.html
- docs/index.html
- packages/gatsby/content/advanced/contributing.md
- packages/gatsby/content/advanced/migration.md
- packages/gatsby/content/advanced/questions-and-answers.md
- packages/gatsby/src/components/header.js
- packages/gatsby/static/_redirects
- packages/plugin-compat/README.md
- packages/plugin-constraints/README.md
- packages/plugin-constraints/bin/@yarnpkg/plugin-constraints.js
- packages/plugin-constraints/sources/commands/constraints.ts
- packages/plugin-dlx/README.md
- packages/plugin-interactive-tools/README.md
- packages/plugin-node-modules/README.md
- packages/plugin-npm-cli/README.md
- packages/plugin-pack/README.md
- packages/plugin-pnp/README.md
- packages/plugin-stage/README.md
- packages/plugin-version/README.md
- packages/plugin-workspace-tools/README.md
- packages/yarnpkg-doctor/README.md
- packages/yarnpkg-pnpify/sources/cli.ts
Replaces `legacy.yarnpkg.com` to `classic.yarnpkg.com` as per the discussion in #766:
> The Yarn Classic documentation will be moved once again to be hosted at classic.yarnpkg.com
Replaces `next.yarnpkg.com` with `yarnpkg.com` now that the v2 site is the default one.
References #766
> Update site domains

- packages/gatsby/content/features/zero-installs.md
This improves some of the grammar in the “zero installs” feature doc. I tripped over the phrase “the lower amount of code possible” when reading through this after checking out the Yarn 2 release notes, so thought I’d reword it and fix some other minor grammar issues nearby. :)
> Docs: Fix grammar in zero installs feature doc

- packages/gatsby/src/components/details/Copyable.js
> fix(www): consistent spacing with Copyable container

- .eslintignore
- .yarn/versions/395d6de1.yml
- packages/yarnpkg-parsers/sources/grammars/shell.d.ts
- packages/yarnpkg-parsers/sources/grammars/shell.js
- packages/yarnpkg-parsers/sources/grammars/shell.pegjs
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/sources/pipe.ts
- packages/yarnpkg-shell/tests/shell.test.ts
The shell implementations hit a few edge cases:
- Redirects weren't parsed when they covered a subprocess (`(...) > foo`) (fixes #752)
- The `FOO=''` syntax didn't parse (`FOO=` or `FOO=""` did) (fixes #797)
- The subprocess interpolation was closing the final argument early (fixes #865)
> Various shell fixes

- .yarn/versions/fbe88b92.yml
- packages/yarnpkg-doctor/sources/cli.ts
`@yarnpkg/doctor` reports usage of `node_modules/.cache` as a warning.
Use a negative lookahead in the regex to not match `node_modules/.cache` and `node_modules\\.cache`
> fix(doctor): don't warn on node_modules/.cache usage

- .pnp.js
- .yarn/versions/0aca03e0.yml
- packages/yarnpkg-libzip/package.json
- yarn.lock
`@yarnpkg/libzip` depends on `@types/emscripten` but doesn't list it.
Fixes https://github.com/yarnpkg/berry/issues/746
Added `@types/emscripten` as a dependency.
> fix(libzip): add missing @types/emscripten

- .yarn/versions/863be327.yml
- packages/plugin-pnp/sources/PnpLinker.ts
Yarn isn't unplugging packages with `jar` files. When I implemented https://github.com/yarnpkg/berry/pull/853 I forgot to list `.jar` files, even though I had a note about including them.
ref https://github.com/yarnpkg/berry/issues/847
Added `.jar` to the `FORCED_UNPLUG_FILETYPES` set
> fix(pnp): unplug packages with jar files

- .yarn/versions/c808a1ce.yml
- packages/yarnpkg-fslib/sources/ZipFS.ts
The constructor for ZipFS says that the options are optional, but they're actually required.
Marked the options as required.
> fix(fslib): mark options for zipfs as required

- packages/gatsby/content/advanced/migration.md
Not sure of the wording desired here but this confused me a bit when I migrated until I came across #821. I'm confident other people will be left confused as well. Wrote this based on what I read in the aforementioned issue.
A lack of documentation regarding the removal of the `yarn global` command.
Wrote a note in the migration guide with a reference to the issue where I learned more about it.
> Document the removal of `yarn global`

- .yarn/versions/2a95873b.yml
- packages/yarnpkg-core/sources/StreamReport.ts
This PR is related to #816.
I've implemented the request of @arcanis. He advised me to keep the latest 5 fetch (`YN0013`) logs and use escaping characters while doing it.
I basically saved `YN0013` logs by keeping the latest 5 logs in the `forgettableLines` array.
Then, if it has more than 5 logs, the most aged one is dequeued and I started clearing the console up to 5 lines. And printing them back from the array with remaining lines.
If sequence is interrupted with another type of log, we reset the `forgettableLines` array.
Also, I kept them internally (private) and put the number 5 in a class-wide private variable, so it can be changed easily.
> StreamReport :: Limit fetch logs (YN0013) up to 5

- .github/workflows/e2e-vue-cli-workflow.yml
Vue CLI 4.2 has been released with built-in berry support, so no need for an extra plugin.
> Update Vue CLI E2E workflow, reflecting changes in Vue CLI 4.2

- README.md
- packages/gatsby/content/features/protocols.md
- packages/gatsby/src/components/details/Markdown.js
- packages/gatsby/src/components/details/index.js
- packages/plugin-essentials/sources/commands/set/version.ts
- packages/plugin-git/sources/gitUtils.ts
- packages/plugin-github/sources/githubUtils.ts
- packages/plugin-interactive-tools/bin/@yarnpkg/plugin-interactive-tools.js
- packages/plugin-version/bin/@yarnpkg/plugin-version.js
- scripts/actions/make-commit/entrypoint.sh
Just addressing a pet peeve of mine. Note that this only makes changes to documentation, strings, etc. The code is full of function names like `isGithubUrl`, `parseGithubUrl`, etc: trying to update all of those is probably not worth the trouble.
> GitHub has a capital H, GitLab has a capital L

- .yarn/versions/e948f224.yml
- packages/yarnpkg-core/sources/Configuration.ts
It's currently impossible to write a new plugin that includes package extensions.
Th hook in plugin-compat works only because of how async functions work: they're triggered synchronously so the code in the hook itself still runs when needed. If anything were to change there to make it really async, the plugin would be broken too.
Await the `registerPackageExtension` hook
> Await completion of registerPackageExtension hook

- .yarn/versions/e4b5e209.yml
- packages/yarnpkg-doctor/fixtures/pre-post-scripts/package.json
- packages/yarnpkg-doctor/sources/cli.ts
The `pre` / `post` scripts auto-run logic has been removed from 2.x (this is intentional; there are little reason for them to exist as they provide a fringe convenience that can be easily implemented by the users in a more explicit and less confusing way).
Running `yarn dlx @yarnpkg/doctor .` will now report that the `pre` and `post` scripts are discouraged.
> Adds suggestion to the doctor

- .yarn/versions/ac63a01f.yml
- packages/yarnpkg-builder/sources/commands/build/bundle.ts
- packages/yarnpkg-cli/package.json
It's sometimes difficult to know what's the version currently in use, and how up-to-date it is compared to master - especially when using `yarn set version` (since all builds share the same version number).
The builder will now automatically add a git suffix unless the `--no-git-hash` option is set (only used for our internal releases):
```
2.0.0-rc.28.git.20200210.35e40e23
```
> Uses hashes when building the bundle

- .yarn/versions/deb6cd80.yml
- packages/plugin-essentials/sources/commands/plugin/import.ts
```
$ yarn plugin import https://github.com/bgotink/yarn-plugin-angular/raw/master/bin/%40yarnpkg/plugin-angular.js
➤ YN0001: ReferenceError: name is not defined
at i.StreamReport.start (/Users/bram/Workspaces/Private/iapetos/.yarn/releases/yarn-rc.js:58:32837)
➤ YN0000: Failed with errors in 0.14s
```
> Use correct variable as pluginUrl when importing a plugin from URL

- .yarn/versions/5e3ff569.yml
- packages/yarnpkg-doctor/sources/cli.ts
The doctor doesn't filter properly workspace files. In particular, it seems it was only able to run on the root workspace but not nested projects.
Fixes https://twitter.com/bitfalls/status/1227619834571169794
The filtering has been fixed so that each workspace can retrieve the files it contains.
> Fixes "yarn doctor" filtering

- .yarn/versions/507c11d0.yml
- packages/yarnpkg-pnpify/sources/hoist.ts
- packages/yarnpkg-pnpify/tests/hoist.test.ts
This is a hoisting optimization
Blacklist is maintained to skip rechecking nodes that certainly cannot be hoisted.
> [node-modules] Use blacklist to avoid rechecking nodes that certainly cannot be hoisted

- .yarn/versions/6b579d42.yml
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
On a big monorepo reading `package.json` files from inside zips takes considerable time (2 seconds on a Babel monorepo)
`package.json` files from installed locations are read instead (this brings down `yarn install` time on already installed Babel monorepo from 17.3 seconds to 15.3 seconds)
> [node-modules] Use unpacked package.json files to read build scripts

- .yarn/versions/d91964bd.yml
- packages/plugin-essentials/sources/commands/plugin/runtime.ts
This PR adds the `--json` flag to the `yarn plugin runtime` command.
I added the `--json` flag to the `yarn plugin runtime` command. It behaves exactly like the `--json` flag of other commands. The output is NDJSON.
> feat(plugin-essentials): yarn plugin runtime --json

- packages/gatsby/content/features/constraints.md
Replaces `gen_invalid_dependency` with `gen_enforced_dependency` in the constraints recipe that demonstrates how to enforce consistent dependency versions across workspaces.
I ran into trouble trying to use the original recipe, and it appears the `gen_invalid_dependency` rule was removed by https://github.com/yarnpkg/berry/pull/338.
I copied/merged what I found in Yarn's [constraints.pro](https://github.com/yarnpkg/berry/blob/6ffb3c478c2aac7c942aebbc0f01279f203744d1/constraints.pro) configuration.
> Remove `gen_invalid_dependency` constraints recipe

- packages/gatsby/src/pages/configuration/yarnrc.js
- `pnpEnableInlining` takes a boolean, not a string
- `pnpUnpluggedFolder` has a default of `./.yarn/unplugged`, not `./yarn/unplugged`
Updated the docs to be correct.
> docs: fix some minor yarnrc errors

- .yarn/versions/46f20c4f.yml
- packages/plugin-essentials/sources/commands/run.ts
- packages/yarnpkg-core/sources/scriptUtils.ts
It's currently quite annoying to run binaries with the `--inspect` mode, despite it being somewhat common. You need to know about `yarn node`, you need to know about `yarn bin <name>`, and you need to know how to make them interact with each other.
This diff simply adds options to `yarn run` that will be forwarded to Node. As for all `run` options, they have to be passed before the script name in order to be taken into account (ie `yarn run foo --inspect` will send the `--inspect` flag to `foo`).
More options could be supported, but I think those two are the main ones we need. The others can (should?) be sent through the `NODE_OPTIONS` environment variable.
> Adds --inspect and --inspect-brk to `yarn run`

- .yarn/versions/cffae1c3.yml
- packages/yarnpkg-core/sources/StreamReport.ts
There are sometimes lots and lots of logs when the cache changes.
This PR makes it so that those messages are covered by the new "forgettable logs" mechanism, so 5 messages will be printed at most.
> Makes cache removal forgettable

- .yarn/versions/768f0faa.yml
- packages/plugin-npm-cli/sources/commands/npm/publish.ts
Packages published on a verdaccio registry had the wrong tarball URL, making it impossible to download them.
I copied the logic used by lerna (https://github.com/evocateur/libnpmpublish/blob/latest/publish.js#L142).
I couldn't find any test for the `npm publish` command, but I'll check if this works with Babel.
> Generate a valid tarball url when publishing

- .github/workflows/e2e-cra-workflow.yml
- .yarn/versions/e24d46f3.yml
- packages/yarnpkg-core/sources/StreamReport.ts
CI systems can't benefit from forgettable lines, so the output can be at times very verbose.
On systems that support it (only GitHub Actions and Travis, I didn't find something similar for CircleCI), we now print the right fences to fold the sections.
> Folds output by default on CI

- packages/gatsby/content/getting-started/install.md
As of this writing, the official Debian/Ubuntu package of yarn is v1.21,
which does not support the suggested berry installation command:
$ yarn set version berry
error Command "set" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
This is described in issue #904.
This commit adds a v1.21-compatible variant (as suggested by @arcanis)
to the installation guide.
> Add install instructions for yarn v1.21

- README.md
This PR improves the README.
Follow up to https://github.com/yarnpkg/berry/pull/961.
* I replaced the version shields with a single version shield that points to `npm@berry`.
* I added `plugin-interactive-tools` to the `Contrib plugins` section.
> docs(readme): change version shields and add `plugin-interactive-tools` to contrib plugins

- .yarn/versions/65e318bd.yml
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
This PR adds support for common CI workflow, when user caches only some of `node_modules` roots, top-level `node_modules` root for example and "forgets" to cache them all (or it is difficult for the user to do so)
When we read previous install state, we now run fast check to see wether all the `node_modules` roots are present on the file system and if some of them do not - we account that the tree branch that starts from non-existent module root is not here and should be installed.
cc @nicolo-ribaudo
> [node_modules] Implement transparent handling of some node_modules roots non-existence

- .yarn/versions/93797c98.yml
- packages/plugin-patch/sources/tools/apply.ts
Fixes #935
Previously, `berry` compared lines (original vs patched) even when there wasn't any content in the old line. 
Due to TypeScript not assuming Array access as possibly undefined, the issue wasn't discovered by it.
```ts
const originalLine = fileLines[offset]; // <<== possibly undefined, but resolves to 'string' type
```
I've added a check for the existence of `originalLine` in the `evaluateHunk` function.
> fix: a patch hunk that only adds lines caused failure

- .github/workflows/e2e-angular-workflow.yml
- .github/workflows/e2e-next-workflow.yml
- packages/gatsby/content/advanced/lifecycle-scripts.md
- packages/gatsby/content/advanced/migration.md
The documentation didn't reference that pre/post user scripts aren't supported anymore.
Updated the lifecycle scripts page, added a note in the migration guide.
Also fixed the E2E tests for Angular.
Fixes #995
> Improves the documentation

- .yarn/versions/a9a6cf57.yml
- packages/yarnpkg-pnpify/sources/generateSdk.ts
The dynamic require was causing `typescript` to be resolved relative to the `pnpify` package (or the top-level when it was a direct dependency), thus failing when invoked through `yarn dlx`.
We now make the require call by going through the resolved location.
> Fixes the dynamic require in `--sdk`

- packages/gatsby/content/advanced/pnp-api.md
3 things in this PR:
- using `import` and `require` statements in the same snippet seemed confusing. Change to `require` only.
- Looks like the `ZipOpenFS` constructor must take an object with at least a `libzip` key in it.
- There was a typo in the var name passed to the `PosixFS` constructor
...
...
> Fix the "Accessing the files" instructions

- packages/yarnpkg-shell/README.md
The usage example in the readme of `@yarnpkg/shell` uses an outdated package name. This PR fixes that.
> Use correct package in example

- packages/gatsby/content/getting-started/install.md
> fix: remove typo in getting-started documentation

- .yarn/versions/af44e1ad.yml
- packages/yarnpkg-pnpify/sources/cli.ts
`yarn pnpify` fails with `Error: This tool can only be used with projects using Yarn Plug'n'Play` when `package.json` uses `{ "type": "module"}` and therefore `.pnp.cjs` is created instead of `.pnp.js`.
Added a check for presence of `.pnp.cjs` and if it exists, it is used instead.
> Add .pnp.cjs support to pnpify CLI

- .yarn/versions/0d62487b.yml
- packages/yarnpkg-pnpify/sources/generateSdk.ts
as seen in: https://github.com/vuejs/vetur/pull/1737
Some third-party services/extensions require the typescript library (as opposed to the CLI only)
This PR makes it available in the typescript pnpfied SDK.
This adds a one-liner to write a third file to the typescript patch folder, thus exposing the typescript module to the world
> add file for pnpfying typescript lib (Typescript SDK)

- .yarn/versions/01d5b008.yml
- packages/yarnpkg-pnpify/sources/generateSdk.ts
This is a follow up on #1028. Since the pnpified tools follow commonjs format, it is required to specify `{"type": "commonjs"}` for their `package.json`s.
Added `type: 'commonjs'` to the `generateStack.writeManifest` function.
> @yarnpkg/pnpify: Specify in pnpify-generated manifests type=commonjs

- .yarn/versions/a37ef1a7.yml
- packages/yarnpkg-core/sources/StreamReport.ts
The following diff makes us use terminal sequences more in line with the [GitLab documentation](https://docs.gitlab.com/ee/ci/pipelines.html#custom-collapsible-sections). Unfortunately, I couldn't make the GitLab example work, so I suspect something is broken in the GitLab display itself 🙁
This is what should be displayed (notice the sections are all collapsed by default), and I can expand them by clicking on them:
https://github.com/yarnpkg/berry/pull/1031/checks?check_run_id=482377632#step:5:0
**How to repro:**
```
npm install -g yarn
yarn init -2
yarn set version from sources --branch 1031
yarn add webpack
```
You should have collapsed logs (in particular the fetch step, but the others as well), but you instead have a very large output.
> Fixes collapsing

- .yarn/versions/ed3f5539.yml
- packages/yarnpkg-core/sources/Configuration.ts
Those environment variables are used by the install script, so we shouldn't throw when they are used.
...
> Ignores some env variables

- .yarnrc.yml
Having `enableGlobalCache: true` in a global `.yarnrc.yml` file "disables" zero-installs in the berry repo
Explicitly set `enableGlobalCache: false` to allow me to have it enabled globally and still be able to run yarn in the repo
> chore: explicitly set enableGlobalCache to false

- .yarn/versions/555de3ec.yml
- packages/yarnpkg-core/sources/Project.ts
The peer dependency deduping was comparing the package dependencies rather than the package resolutions. As a result, in the following case, `X` wouldn't have been deduplicated even if `Y@^1.0.0` and `X@^1.1.0` would happen to resolve to the same package:
```
. -> A -> X ~> Y
-> Y@^1.0.0
-> B -> X ~> Y
-> Y@^1.1.0
```
Ref: https://github.com/yarnpkg/berry/issues/1049
We now run the dependency check based on the resolved dependencies rather than their ranges.
> Deduplicates through resolutions

- .yarn/versions/94e1cb0e.yml
- packages/acceptance-tests/pkg-tests-specs/sources/auth.test.js
- packages/gatsby/src/pages/configuration/yarnrc.json
- packages/plugin-npm/sources/index.ts
- packages/plugin-npm/sources/npmConfigUtils.ts
- packages/plugin-npm/sources/npmHttpUtils.ts
Adds support for scoped auth settings, useful when using the same registry with different tokens (eg: github's package registry)
```yml
npmScopes:
my-company:
npmRegistryServer: "https://registry.yarnpkg.com"
npmAuthIdent: "username1:password1"
my-company2:
npmRegistryServer: "https://registry.yarnpkg.com"
npmAuthToken: "ffffffff-ffff-ffff-ffff-fffffffffff2"
```
Edit: Updated the description example, first one was incorrect.
Closes https://github.com/yarnpkg/berry/issues/1030
> Adds support for scoped auth settings

- packages/gatsby/src/components/details/Markdown.js
Images and links are displaying `"null"` titles
> website: fix null titles in images and links.

- .yarn/versions/1d201328.yml
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
- packages/yarnpkg-libui/sources/misc/renderForm.tsx
Just a simple type-level fix for type-safety
> chore: Fix type definition of renderForm utility

- .yarn/versions/575ebbc8.yml
- packages/acceptance-tests/pkg-tests-specs/sources/features/pnpLoose.test.js
- packages/plugin-node-modules/sources/PnpLooseLinker.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
The hoister removes the virtual paths from the `target` properties, so the subsequent `findPackageLocator` couldn't work (causing packages with peer dependencies to be "hoisted" as references to the top-level workspace).
Fixes #1076
We now parse the `locator` field.
> Fixes virtuals w/ loose mode

- .yarn/versions/31781f15.yml
- packages/plugin-patch/sources/patchUtils.ts
The recent changes to the `mktemp` API led to the folder being mistakenly removed.
Fixes #1089
Detaches the temporary folder used for the patch.
> Prevents the patch folders from being garbage collected

- .yarn/versions/4c470e8b.yml
- packages/plugin-essentials/sources/commands/node.ts
The TS autocomplete put an invalid file here. It works when building the bundle (hence why we didn't detect it), but not when working with the published package.
Fixes #1086
Fixes the import.
> Fixes import

- .yarn/versions/25a73b1a.yml
- packages/plugin-npm/sources/NpmTagResolver.ts
Tags like `foo-2` are valid npm tags.
Fixes #1075
n/a
> Improves the tag resolver

- .yarn/versions/7a109220.yml
- packages/plugin-essentials/sources/commands/install.ts
Wrong config name for `cacheFolder` in the `install` command docs
This is valid `yarn config get cacheFolder`
This is **not** valid `yarn config get cache-folder`
Update the doc accordingly and replace `cache-folder` with `cacheFolder`.
> Update the name for the cache folder config

- .yarn/versions/6a9100dd.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
- packages/plugin-pack/sources/packUtils.ts
The install state was stored in the `yarn pack` output.
We now always blacklist it.
> Prevents the install state file from being in the packfiles

- .yarn/versions/09c8bf16.yml
- packages/plugin-compat/sources/extensions.ts
Running a typecheck with Yarn 2 failed because of missing types.
- opened https://github.com/sindresorhus/got/pull/1125
- added missing types for `responselike` and `keyv`
> Add types for got

- packages/gatsby/src/pages/configuration/yarnrc.json
https://yarnpkg.com/configuration/yarnrc does not list `nodeLinker` as a possible config while https://yarnpkg.com/advanced/migration#if-required-install-the-node-modules-plugin references it
Add nodeLinker to the `.yarnrc.yml` documentation file
> 🔧add the nodeLinker yarnrc.yml config

- .yarn/versions/73788921.yml
- packages/acceptance-tests/pkg-tests-fixtures/packages/prefer-unplugged-false-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/prefer-unplugged-false-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/prefer-unplugged-true-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/prefer-unplugged-true-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
- packages/plugin-pnp/sources/AbstractPnpInstaller.ts
- packages/plugin-pnp/sources/PnpLinker.ts
- packages/yarnpkg-core/sources/Manifest.ts
A package with `preferUnplugged` will be able to instruct Yarn to either force-extract its content on the disk (useful when for example you need to ship executable binaries for a reason or another), or to force it to stay within its archive (useful when you want your package to contain ALL the sources, including shellscripts, but they aren't useful for runtime purposes).
> Implements preferUnplugged

- .yarn/versions/37861a83.yml
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
We have observed one case of a race condition in `node-modules` linker between `mkdirp` and `remove` operations, during persisting of packages into `node_modules`
The error message looks like:
```
Error: While persisting /D:/a/berry/berry/.yarn/cache/@emotion-hash-npm-0.7.1-cc52d429a7-2.zip/node_modules/@emotion/hash -> /D:/a/berry/berry/node_modules/@emotion/serialize/node_modules/@emotion/hash ENOENT: no such file or directory, mkdir 'D:\a\berry\berry\node_modules\@emotion\serialize\node_modules'
```
I have tweaked the order of operations, so that all `remove`'s were executed first and only after they had been finished all the other file operations were performed.
Another change in this PR is simplification of the code …
> [node-modules] Fixes race between `mkdirp` and `remove`

- .yarn/versions/02747fd6.yml
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
This PR fixes: #715
Linker now consults with location tree to find the owner locator of the given path.
> [node-modules] Add support for `yarn run` in build scripts

- .yarn/versions/6ad9369f.yml
- packages/yarnpkg-core/sources/semverUtils.ts
- packages/yarnpkg-core/tests/semverUtils.test.ts
The current implementation was reporting that `5.0.0-beta.13` wasn't matching `^5.0.0` (we're only talking about the "peer dependency warning" here). Since we've decided a long time ago that prerelease versions shouldn't be taken into account when checking peer dependencies, this led to incorrect warnings.
I reimplemented `satisfiesWithPrereleases` to drop all prereleases from the comparison. Also added unit tests to prevent regressions.
> Improves satisfiesWithPrereleases

- .yarn/versions/5d6d7ade.yml
- packages/yarnpkg-core/sources/execUtils.ts
We attach a SIGINT handler for each process we spawn so that the user pressing ^C doesn't immediately abort Yarn (we instead wait for the child processes to exit on their own when receiving the signal). The problem is that our current logic was very simple: we were just registering one handler per process. Node didn't like that and was printing out a warning.
This new logic uses a refcount to keep track of how many processes are currently running, so we should never trigger the warning threshold again.
> Fixes the Node emitter warning

- .yarn/versions/0b7c9f55.yml
- packages/plugin-essentials/sources/commands/set/version.ts
The previous implementation wasn't allowing us to easily switch from one 2.x build to another - we could only ever go to the latest builds.
The command now accepts arbitrary version number.
Because the GitHub API was too limited to retrieve the full list of available versions (we store them in tags, and GitHub only returns a very limited subset of tags), I've removed the ability to use ranges altogether. You can still use `latest` to get the latest 2.x release, though.
Last notable point: the releases will now use a filename mirroring the actual version (even when using `latest`).
> Updates `yarn set version`

- .yarn/versions/2f54f272.yml
- packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
- packages/acceptance-tests/pkg-tests-specs/sources/features/packageExtensions.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/features/pnpLoose.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/pnpapi.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/protocols/links.test.js
- packages/plugin-pnp/sources/AbstractPnpInstaller.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
The `packagePeers` field currently lists peer dependencies for workspaces even under the root context (ie when they're accessed by running a script within their own directory). This causes issues in the linkers that expect these informations to be accurate.
The workspaces won't store packagePeers infos when under the root context. Added tests.
> Fixes the packagePeers info for workspaces

- .yarn/versions/e0cb4c4c.yml
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
The linker created self-referencing symlink for top-level package, this has confused some build toolchains, for example Vue.
Reproduction steps on Windows:
```
npx @vue/cli create repro
cd repro && yarn set version v2
printf "console.log(undefined ?? 'false')" > src/main.js
printf "yarnPath: ".yarn/releases/yarn-berry.js"\nnodeLinker: 'node-modules'" > .yarnrc.yml
printf "module.exports = {\nconfigureWebpack: {\nresolve: {\nsymlinks: false\n},\n}\n}" > vue.config.js
yarn && yarn build
```
I have removed creation of self-references altogether during node_modules tree creation.
> [node-modules] Remove self-references from node_modules tree

- .yarn/versions/fdc7a7ef.yml
- packages/plugin-init/sources/commands/init.ts
It's annoying to have to edit the package.json just to add the same `packages/*` workspace declaration right after initialization.
Running `yarn init -w` will now generate a workspace-aware project (I've also added the `-l` flag as an alias for `-i latest`, so running `yarn init -2lw` will create a Yarn 2 workspace project using the latest official release).
> Makes yarn init able to initialize workspaces

- .pnp.js
- .yarnrc.yml
- packages/gatsby/package.json
- packages/gatsby/typedoc-plugin-yarn/index.js
- packages/gatsby/typedoc-plugin-yarn/package.json
- packages/gatsby/typedoc-plugin-yarn/plugin.js
- packages/gatsby/typedoc.json
- yarn.lock
Currently, TypeDoc elements that are exported in more than one file are duplicated (examples in [yarnpkg-cli](https://yarnpkg.com/api/modules/yarnpkg_cli.html), [yarnpkg-core](https://yarnpkg.com/api/modules/yarnpkg_core.html) etc.).
This is caused by having TypeDoc in `library` mode. In my original PR, I set it to `library` before adding `@strictsoftware/typedoc-plugin-monorepo`, since it seemed to produce the most useful output. After adding the plugin, I forgot to retest the other modes.
This PR changes the TypeDoc mode from `library` to `modules`. This causes TypeDoc to classify re-exports as references and to not duplicate elements. Unfortunately, they are currently dead references (probably caused by …
> docs(api): change typedoc mode to `modules`

- packages/gatsby/src/pages/configuration/manifest.json
- packages/gatsby/src/pages/configuration/yarnrc.json
Few fixes for the documentation:
- There is a missing space in the documentation:
- Adds `the default` qualifier for `strict` `pnpMode` value (it should be changed for `loose` once 2.1 is out as stated in https://yarnpkg.com/features/pnp#pnp-loose-mode).
> Small fixes in documentation

- packages/gatsby/content/getting-started/install.md
- packages/gatsby/content/getting-started/usage.md
See this issue for more info:
https://github.com/yarnpkg/berry/issues/1130
Updating yarn to Berry.
...
```yarn set version latest ```
This is because the latest is already berry.
...
Closes #1130
> Fix issue for updating yarn to berry.

- .pnp.js
- .yarn/versions/4d235eca.yml
- packages/gatsby/content/advanced/editor-sdks.md
- packages/plugin-compat/sources/extensions.ts
- packages/yarnpkg-pnpify/sources/generateSdk.ts
This PR adds SDK documentation for Emacs which utilizes the generated binary wrappers for VS Code and supplies a new wrapper for https://github.com/theia-ide/typescript-language-server, enabling LSP support within Emacs.
Additionally, this also sorts SDK wrappers by name.
> docs(sdk): Add Emacs documentation and emit a typescript-language-server wrapper for (Emacs') LSP support

- .yarn/versions/3b24285f.yml
- packages/plugin-compat/sources/extensions.ts
See https://github.com/prisma-labs/http-link-dataloader/pull/22
<br>
[`http-link-dataloader`](https://github.com/prisma-labs/http-link-dataloader) doesn't list its transitive peer dep `graphql`
Added it to `extensions.ts` of plugin-compat and created a PR
> plugin-compat: extension for http-link-dataloader

- .yarn/versions/45eb25fd.yml
- packages/acceptance-tests/pkg-tests-fixtures/packages/@scoped__create-test-app-1.0.0/bin.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/@scoped__create-test-app-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/@scoped__create-test-app-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/create-test-app-1.0.0/bin.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/create-test-app-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/create-test-app-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/commands/create.test.js
- packages/plugin-dlx/sources/commands/create.ts
- packages/plugin-dlx/sources/index.ts
`yarn create` was removed in Yarn v2 as the `yarn dlx` command got added. 
The problem is that many of the starter-kit projects still only list `yarn create`:
- React - [create-react-app](https://create-react-app.dev/docs/getting-started#yarn)
- Next - [create-next-app](https://nextjs.org/docs/getting-started#setup)
- Nuxt - [create-nuxt-app](https://nuxtjs.org/guide/installation#using-code-create-nuxt-app-code-)
- Electron Forge - [create-electron-app](https://www.electronforge.io/#the-basics)
This can cause confusion to people who don't happen to read the `CLI` page on our website, as there's no other place where this change is mentioned.
You can also consider it as a small Yarn-exclusive QoL change. 😄 
I added the `yarn …
> feat(dlx): `yarn create <starter-kit-package>` as an alias to `yarn dlx create-<starter-kit-package>`

- scripts/vscode-zip-test-procedure.sh
We want to add support for Zip archives to VSCode, but are currently blocked on https://github.com/microsoft/TypeScript/issues/36943. In order to unblock it, we need to prove them that we know what we're doing, so I've started writing an automated procedure to make sure we cover all the cases we can think off, and they can check it as well.
I'll open an issue to track it with more details.
> Adds a prototype procedure

- .yarn/versions/c0ece226.yml
- packages/gatsby/src/pages/configuration/yarnrc.json
- packages/yarnpkg-cli/sources/main.ts
- packages/yarnpkg-core/sources/Configuration.ts
There are 2 code paths here: https://github.com/yarnpkg/berry/blob/215455f2c303a14fcb10e5513bdbbf82b5320d3d/packages/yarnpkg-cli/sources/main.ts#L64
The `--cwd` option is only checked for on the `else` branch, so when [`run`](https://github.com/yarnpkg/berry/blob/215455f2c303a14fcb10e5513bdbbf82b5320d3d/packages/yarnpkg-cli/sources/main.ts#L94) is called after `--cwd` is encountered, there is a possibility that the `if` branch will execute with the `--cwd` option that was already encountered.
This causes commands to be executed in the wrong directory in some cases.
This PR closes #1056.
I made the `--cwd` flag and its argument get removed from `process.argv` when `--cwd` is encountered.
> fix(cli): fix --cwd

- .yarn/versions/06552549.yml
- packages/gatsby/gatsby-plugin-clipanion-cli/gatsby-node.js
- packages/plugin-essentials/sources/commands/entries/clipanion.ts
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
- packages/plugin-workspace-tools/sources/commands/foreach.ts
Currently, there's ~~no information~~ (Edit: Actually there is some, but only for `yarn workspaces foreach` and `yarn upgrade-interactive`, but it's a bit hidden down inside the `Details` section and it is not automatically generated) in the CLI documentation about which commands require the user to install a plugin.
I made the `yarn --clipanion=definitions` output also include the originating plugins of commands:
```ts
definitions.commands[].plugin: {
name: string;
isDefault: boolean;
}
```
Now there's information about required plugins displayed at the top of the command pages from the CLI section on the website.
> docs(cli): generate "plugin required" information for some cli commands

- .yarn/versions/6581a588.yml
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
The link: protocol support was broken in node-modules linker because linker didn't handle when the locator of the node changes.
Now linker checks whether locator of the node in the tree changes and delete the old node first and only after that adds new locator to the same location.
This PR also fixes another race condition - the linker started adding new modules and removing old modules simultaneously, now we really wait for old modules to be deleted first
Another fix is directory removal, now location tree-aware algorithm is used, this solves issues with proper cleanup after other package manager on new install
> [node-modules] Link: protocol support fix

- .yarn/versions/8f6f8510.yml
- packages/yarnpkg-core/sources/Configuration.ts
Running Yarn 2 within a environment created by a Yarn 1 lifecycle script causes an error to be generated.
We now ignore the `YARN_WRAP_OUTPUT` environment variable.
> Adds ignore for the YARN_WRAP_OUTPUT environment value

- .yarn/versions/8dc23b49.yml
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
Currently nm linker does not allow adding `link:` dependency to a missing folder, because it always tries to parse manifest file
Nm linker now distinguishes `link:` locators and neither tries to parse their manifest nor create bin symlinks if the manifest happen to exist with bin field. The only action linker does for `link:` dependencies is creating a symlink with no regard whether target folder exists or not.
> [node-modules] Adds support for creating link: to a missing folder

- .yarn/versions/1e9c3b66.yml
- packages/acceptance-tests/pkg-tests-specs/sources/protocols/execs.test.js
- packages/gatsby/content/features/protocols.md
- packages/plugin-exec/README.md
- packages/plugin-exec/sources/ExecFetcher.ts
- packages/plugin-exec/sources/ExecResolver.ts
- packages/plugin-exec/sources/execUtils.ts
- packages/plugin-exec/sources/index.ts
`plugin-exec` can be greatly improved.
TODO:
> feat(exec): improve `plugin-exec`

- .yarn/versions/f234e0b0.yml
- packages/yarnpkg-core/sources/Project.ts
- packages/yarnpkg-core/sources/httpUtils.ts
The fetch step can be speedup. Currently we are capping number of concurrently running fetchers. The problem with this approach is that we really want to cap network requests, but fetchers do more than that and directly capping fetchers suboptimal and produces download stalls.
I am not capping fetchers, but instead cap the network requests directly, this results in 15% speed increase on my laptop of the fetch step (relative to `dns-cache` branch which has limit of 8 concurrent fetcher instead of 5 in master now).
> Speedup fetch step by limiting concurrency on network requests only

- .yarn/versions/b30df372.yml
- packages/yarnpkg-core/sources/Project.ts
In my previous PR I have limited network concurrency for requests and removed concurrency limit from fetchers. This lead to a problem with running out of file descriptor
I have returned limit on fetcher concurrency, but made it higher than network concurrency, it is set to 32.
> Limits fetcher concurrency

- .yarn/versions/3744b7e3.yml
- packages/acceptance-tests/pkg-tests-specs/sources/features/compressionLevel.test.ts
- packages/gatsby/src/pages/configuration/yarnrc.json
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/sources/tgzUtils.ts
- packages/yarnpkg-fslib/sources/ZipFS.ts
Currently the compression level setting is present, but really ignored by berry.
Really enables compression level setting.
> Really enable compression level setting

- .yarn/versions/badae20d.yml
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/plugin-node-modules/README.md
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
This PR solves issue: #1184 
The linker does not attempt removing node_modules folders if it is going to recreate them soon.
> [node-modules] Avoids recreating nm folders and only clears them

- packages/gatsby/src/pages/configuration/yarnrc.json
The config options docs page handles the phrasing for boolean options quite inconsistently.
I tried to follow the pattern that was partially but not consistently
already in place:
* set the shown example to the default
* if the default depends, to the default on most dev machines
* use only 'If true' or 'If false' sentences
* if the sentence talks describes the default, mention '(the default)'
* if the default depends, mention what it depends on
> docs(config): boolean option consistency

- packages/gatsby/src/pages/configuration/yarnrc.json
Readers may think setting `cacheFolder` to something global that they come up with is a good idea, especially because of the note on sharing it between projects.
Mention that there is `enableGlobalCache` for this.
> docs(config): hint at using enableGlobalCache instead of cacheFolder

- .yarn/versions/4ebc8ee9.yml
- packages/plugin-version/sources/versionUtils.ts
- packages/yarnpkg-core/sources/Project.ts
This PR solves issue #1194
* Implement tryWorkspaceByFilePath followng the common try/get structure
* Use tryWorkspaceByFilePath in versioning plugin to account for out-of-workspace files
* Add note remarking fetchChangedFiles can include out-of-workspace files
> Implement tryWorkspaceByFilePath (#1194)

- .yarn/versions/b62cfa7b.yml
- packages/gatsby/src/pages/configuration/yarnrc.json
- packages/plugin-version/sources/index.ts
- packages/plugin-version/sources/versionUtils.ts
This PR implements issue #1195
* Add changesetBaseRef, allowing for comparing files against non-master refs
* Update yarnrc documentation accordingly
> Add changesetBaseRef configuration option for versioning (#1195)

- .yarn/versions/d27a1090.yml
- packages/plugin-compat/sources/index.ts
Currently plugin-compat is turned off for node_modules linker due to perf considerations. However this also mean that lockfile become installation strategy dependent.
Reenable plugin-compat for all the linkers, because using PnP mode on CI and node_modules locally seems as a valid and important use case and its worth small perf penalty.
> Reenable plugin-compat for all the linkers

- .yarn/versions/0243a6ad.yml
- packages/acceptance-tests/pkg-tests-specs/sources/script.test.js
- packages/yarnpkg-core/sources/scriptUtils.ts
Fixes issue: #1032 
All passed arguments in a path wrapper are now enclosed in double quotes
> Fixes `yarn run` on Windows when project path has spaces

- .yarn/versions/4fc8bdb2.yml
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
Some packages distribute their executable files without execution permission properly set and rely that execution permission on bin target should be set by package manager. The yarn 1 has set execution permission on bin targets, so for backward compatibility reasons we should set them too.
This PR adds the code to set executable permissions on bin targets and amends .bin integration test to check this new behaviour.
> [node-modules] Set execution permission on .bin targets

- .yarn/versions/1007e617.yml
- packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
- packages/plugin-pnp/sources/PnpLinker.ts
Pnp linker cleans up all node_modules folders except dot folders inside them. This leaves out `.bin` folders that are certainly not needed for pnp mode.
Added removal of `.bin` entries inside `node_modules` as well.
> Cleanup .bin folders from node_modules

- .yarn/versions/1ec30f83.yml
- packages/plugin-essentials/sources/suggestUtils.ts
The core returns suggestions even when the descriptor doesn't need them. This is problematic when running things like:
```
yarn up foo@1.2.3
```
Because if `foo` is a workspace, then the command will fail with:
```
➤ BR0027: bar@workspace:foo has multiple possible upgrade strategies; use -i to disambiguate manually
```
We won't offer suggestions unless the range is loose (ie `yarn add foo -i` will have suggestions, but `yarn add foo@1.2.3 -i` won't).
> Don't suggest the workspaces unless it matches the request

- .yarn/versions/88316f5e.yml
- packages/yarnpkg-core/sources/CorePlugin.ts
- packages/yarnpkg-core/sources/Manifest.ts
- packages/yarnpkg-core/sources/Plugin.ts
- packages/yarnpkg-core/sources/Project.ts
Currently, there's no warning for resolutions not declared at the project root.
I added a warning for resolutions not declared at the project root.
In the process, I improved the `Validation step`:
- There are 2 new core hooks:
- `validateProject` - called during the validation step
- `validateWorkspace` - called during the validation step by `validateWorkspace`
Both of them have `reportWarning` and `reportError` parameters
- The manifest validation is now done inside the core implementation of `validateWorkspace`, where contextual errors (the ones that require `project` or `workspace`) are also pushed. I also ~~made `Manifest.errors` a `readonly Array<Error>` instead of a `ReadonlyArray<Error>`, to reduce the number of `// …
> feat: improve validation step and add warning for resolutions not declared at the project root

- packages/gatsby/src/pages/configuration/manifest.json
- packages/gatsby/src/pages/configuration/yarnrc.json
Relative paths aren't resolved relative to the path of the project when used inside protocols inside the `packageExtensions` field. This can cause confusion. (#1127)
I added a note about it.
> docs: add note about relative paths

- .yarn/versions/12a4d236.yml
- packages/yarnpkg-core/sources/Project.ts
Running `project.restoreInstallState` doesn't populate the `dependencies` field of the `Workspace` instances of the resolved workspaces.
I extracted the code responsible for it from the `resolveEverything` method into a `refreshWorkspaceDependencies` private method that's called at the end of the `resolveEverything` and `restoreInstallState` methods.
>  fix: fix `Workspace.dependencies` fields not being populated when running `project.restoreInstallState`

- .yarn/versions/dcb027cb.yml
- packages/yarnpkg-core/sources/Project.ts
When we receive the duplicate workspace name error while upgrading from V1, it can be enormously beneficial to see where exactly are the conflicting duplicates
People don't understand the "Duplicate workspace name" error message
https://github.com/yarnpkg/berry/issues/843
When including the paths of the duplicate workspaces it becomes clear where the fault lies.
> Improve "duplicate workspace name" error

- .vscode/settings.json
- .yarn/versions/64c38a0f.yml
- packages/yarnpkg-pnpify/sources/generateSdk.ts
VSCode merged https://github.com/microsoft/vscode/pull/95566 which makes the editor ask users if they want to use the workspace version of typescript if `typescript.enablePromptUseWorkspaceTsdk` is set to true. `pnpify --sdk` should set it automatically
Updated `pnpify --sdk` to set `typescript.enablePromptUseWorkspaceTsdk` to true
> feat(pnpify): set typescript.enablePromptUseWorkspaceTsdk to true

- packages/gatsby/content/advanced/editor-sdks.md
Update sdk docs according to https://github.com/yarnpkg/berry/issues/1189
...
> update editor sdk docs

- .yarn/versions/4c989b5e.yml
- packages/plugin-npm-cli/sources/commands/npm/publish.ts
Since the ident wasn't passed to the `put` function from the publish command, it wasn't detecting the package scope and thus was ignoring the scope configuration.
We now pass the ident, so the scope configuration will be taken into account.
> Fixes publishing scoped package publish auth

- .yarn/versions/0ca53cd6.yml
- packages/plugin-essentials/sources/commands/set/version.ts
`yarn set version latest` doesn't work on Windows, because the Node process is invoked with a `PortablePath` instead of a `NativePath`.
Fixes #1248.
I replaced `temporaryPath` with `npath.fromPortablePath(temporaryPath)`.
> fix(essentials/set/version): convert PortablePath to NativePath

- .pnp.js
- .yarn/versions/f4164863.yml
- packages/yarnpkg-fslib/sources/path.ts
- packages/yarnpkg-fslib/tests/npath.test.ts
- yarn.lock
`fromPortablePath` doesn't currently support UNC paths.
I made `fromPortablePath` support UNC paths.
Fixes #1230.
Tests are included.
> feat(fslib): add support for UNC paths

- .yarn/versions/36d37cca.yml
- packages/yarnpkg-pnp/sources/loader/makeManager.ts
Projects with `type: "module"` in their package manifest can't load any of the pnpified VS Code plugins.
`findApiPathFor` now takes `.pnp.cjs` files into account.
> Check .pnp.cjs when looking for a PnP API

- .yarn/versions/ff3089cd.yml
- packages/plugin-npm/sources/NpmTagResolver.ts
- packages/yarnpkg-core/sources/ProtocolResolver.ts
- packages/yarnpkg-core/sources/index.ts
The tag regex in `@yarnpkg/plugin-npm` doesn't include dots, which can cause problems.
Also, the tag regex in the `ProtocolResolver` from `@yarnpkg/core` doesn't even include numbers or dashes and is case sensitive, so some tags aren't remapped correctly.
Fixes #1267.
I unified the tag regexes into a single one exported from `ProtocolResolver` and I made it also include dots.
> fix(plugin-npm): fix tag regex

- .yarn/versions/c5d29d8b.yml
- packages/plugin-constraints/sources/Constraints.ts
- packages/plugin-exec/sources/ExecFetcher.ts
- packages/plugin-file/sources/FileFetcher.ts
- packages/plugin-http/sources/TarballHttpFetcher.ts
- packages/plugin-npm/sources/NpmHttpFetcher.ts
Some common Prolog functions (notably 'member/2') aren't available.
I've added the `lists` module by default to the Prolog runtime. I didn't add others since they seem relatively forgettable except for this one.
> Adds the 'lists' module to the Prolog engine

- .github/workflows/integration-workflow.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
Things seem *a bit* broken on Node 14. (e.g. #1236)
~~I've just done a quick check locally (only including the files mentioned below) and:~~
~~- 12/18 tests fail for `script.test.js`~~
~~- 8/12 tests fail for `require.test.js`~~
~~- 3/62 tests fail for `pnp.test.js`~~
~~- 3/8 tests fail for `node-modules.test.ts`~~
Edit: Apparently that only happens locally to me, that's why I made the PR, to see if it reproduces on CI. It seems there's only one error with Node 14, and it's not one of the original ones I got. Sorry for the heart attack. 😄
For now, I made the tests also run on Node 14 on CI, so we can see everything that's failing more easily.
> ci: run tests on node 14

- .yarn/versions/5996c9ac.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/focus.test.js
- packages/plugin-essentials/sources/commands/workspaces/list.ts
- packages/plugin-workspace-tools/sources/commands/focus.ts
- packages/plugin-workspace-tools/sources/index.ts
- packages/yarnpkg-core/sources/Project.ts
Fix #489 
The `yarn workspaces focus` command will only install the dependencies for one single workspace (unless it depends on other workspaces).
If we ever implement something like `--production` I think we'll do it here. But I really don't see any point in it (whereas I can see some for focused workspaces when users don't use Zero Installs), so I didn't implement it.
> Implements "yarn workspaces focus"

- .yarn/versions/68d1c5d9.yml
- packages/plugin-git/sources/__snapshots__/gitUtils.test.js.snap
- packages/plugin-git/sources/gitUtils.ts
`normalizeRepoUrl` uses a different regex compared to the `gitPatterns` regex used in `isGitUrl`.  It is missing the 0-9 bit, which means that Urls that are correctly marked as git urls in `isGitUrl` fail when being processed by `lsRemote`
This fix fixes that so that an address that passes isGitRepo will also successfully be parsed by normalizeRepoUrl
This can be tested by doing:
```yarn add @openzeppelin/cli --dev```
This command installs Web3-js@1.2.2 which listed `"scrypt-shim": "github:web3-js/scrypt-shim",` as a dependency.  (Not in package.json or anywhere easy to find mind, that would be searchable and we wouldn't want that)
Add 0-9 to normalizeRepoUrl, installed openzeppellin.  Swore at computer a great deal.  One of those two actions may have done it, not …
> Fix normalizeRepoUrl

- packages/gatsby/gatsby-config.js
- packages/gatsby/gatsby-node.js
Current | New
-|-
- change urls in the main nav so that they match base endpoints
- use gatsby's `createRedirect` based on netlify's `_redirect` file
- profit
> [gatsby] highlight top nav

- .yarn/versions/cd3456dd.yml
- packages/plugin-exec/sources/ExecFetcher.ts
- packages/plugin-exec/sources/execUtils.ts
The path wasn't being resolved relative to the localPath, so the `exec:` protocol used by workspaces was causing the file from being loaded relative to the cwd - likely the project root.
We now properly resolve the path, similar to what we do in the FileFetcher.
> Fixes exec: protocol resolution

- .yarn/versions/8e604a7d.yml
- packages/plugin-essentials/sources/commands/set/version/sources.ts
- packages/yarnpkg-builder/sources/commands/build/bundle.ts
It's difficult to use the `--plugin` option from `set version from sources`, because the plugin paths are relative to the `sources/tools` directory - which doesn't really makes sense.
- `yarn build:cli --plugin <path>` will be relative to `yarnpkg-cli`
- `yarn set version from sources --plugin <path>` will be relative to the repository root
> Resolves plugins relative to the repo root

- packages/gatsby/src/components/header.js
When I hover over the banner that says,
"For the 1.x doc", I get a hyperlink, and so I clicked that
expecting to be taken to v1 documentation.
Unfortunately that part of the sentence is linked to the berry
repository. When I arrived there, I assumed that I just needed to switch
to a v1.x branch or tag, but no such things exist on that repository.
After bouncing around a bit more, the second time I clicked on the
correct portion of the banner and was taken to production documentation.
I removed the banner-wide hyperlink to this repository homepage and replaced it with one ~on the phrase "Yarn 2."~ for the classic docs. This way, ~people that want to get to that code can, but~ people just trying to get to the production …
> [gatsby] refine targets for header hyperlinks

- packages/gatsby/gatsby-plugin-algolia-docsearch/gatsby-ssr.js
The Algolia context is trashed when moving from a page to another.
We just keep watching the dom, so that if the node disappears we can restart docsearch.
A better fix would be to use `useEffect`, but that comes with its own problems (DocSearch only accept a selector, so we couldn't just pass it the element reference).
> Keeps track of the Algolia element

- packages/gatsby/content/advanced/migration.md
- packages/gatsby/content/features/plugnplay.md
- packages/gatsby/src/components/layout.css
Discussion in #749, and the lack of documentation (overview) of changed CLI commands.
Add a full comparison table between v1 CLI commands and v2.
> docs(gatsby): add CLI comparison table to migration

- packages/gatsby/content/advanced/sherlock.md
The link to the sherlock API reference is broken.
Use absolute URL.
> docs: fix broken link

- .yarn/versions/9f2b588d.yml
- packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-empty-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-scripted-empty-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/script.test.js
- packages/eslint-config/rules/best-practices.js
- packages/plugin-compat/sources/index.ts
- packages/plugin-essentials/sources/commands/install.ts
- packages/plugin-essentials/sources/commands/remove.ts
- packages/plugin-essentials/sources/commands/set/version.ts
- packages/plugin-essentials/sources/commands/up.ts
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
- packages/plugin-node-modules/sources/PnpLooseLinker.ts
- packages/plugin-npm/sources/npmHttpUtils.ts
- packages/plugin-version/sources/commands/version/check.tsx
- packages/plugin-workspace-tools/sources/commands/foreach.ts
- packages/yarnpkg-cli/sources/main.ts
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/sources/Project.ts
- packages/yarnpkg-core/sources/StreamReport.ts
- packages/yarnpkg-core/sources/scriptUtils.ts
- packages/yarnpkg-fslib/sources/ZipFS.ts
- packages/yarnpkg-libui/sources/hooks/useFocusRequest.ts
- packages/yarnpkg-libui/sources/hooks/useListInput.ts
- packages/yarnpkg-pnpify/sources/hoist.ts
- packages/yarnpkg-shell/sources/index.ts
- tsconfig.json
Empty scripts in `executePackageScript` were failing because the comparision didn't include only `undefined`, but it also included the empty string.
Fixes #1071.
I changed `if (!script) return;` to `if (typeof script === 'undefined') return;`.
I also added an integration test.
> fix(core): fix empty scripts

- .yarn/versions/89b461de.yml
- packages/plugin-patch/sources/commands/patch.ts
The patch candidates include virtual locators, and that can cause confusion since most people don't know that those are virtual locators (and probably not even what a virtual locator is). 
Also, there's not really a use for patching virtual locators.
I added code that filters out virtual locators from the patch candidates.
> fix(patch): discard virtual candidates when running the patch command

- README.md
The Angular status badge is pointing to a workflow that doesn't exist
Updated to point to the correct one
> chore: update angular status badge

- .yarn/versions/f239bb28.yml
- packages/plugin-git/sources/__snapshots__/gitUtils.test.js.snap
- packages/plugin-git/sources/gitUtils.test.js
- packages/plugin-git/sources/gitUtils.ts
GitHub `/tarball/` URLs aren't currently supported.
Fixes #885.
GitHub tarball URLs are now supported and normalized correctly.
I also added a new pattern to the tests and updated the snapshots.
Note: I also made the URLs that go through `splitRepoUrl` be normalized as it was required for this change.
>  feat(plugin-git): add support for github tarball urls

- .yarn/versions/d8dd0ce4.yml
- packages/acceptance-tests/pkg-tests-fixtures/index.js
- packages/plugin-github/sources/githubUtils.ts
- packages/plugin-github/tests/githubUtils.test.ts
(Unrelated: I'm still using my fork because I have to clean up a few branches before I change `origin`.)
New style GitHub urls weren't parsed correctly.
Fixes #1317.
Now the `protocol=` part of `protocol=abcdef` (the "treeish" part of the url) is discarded correctly.
>  fix(plugin-github): parse new style github urls 

- .yarn/versions/060585a4.yml
- packages/yarnpkg-builder/sources/cli.ts
- packages/yarnpkg-builder/sources/commands/build/bundle.ts
- packages/yarnpkg-builder/sources/commands/build/plugin.ts
- packages/yarnpkg-builder/sources/commands/version.ts
- packages/yarnpkg-core/sources/StreamReport.ts
`@yarnpkg/builder` wasn't showing any progress while building the bundle / plugins. This was a bit annoying, as it seemed like `yarn set version from sources` took forever to finish.
I used [`webpack.ProgressPlugin`](https://webpack.js.org/plugins/progress-plugin/) to get Webpack's progress in real-time and convert it to `StreamReport` progress.
Now the progress is shown alongside Webpack's status messages (a maximum of 5 at a time, I had to tweak `StreamReport` to make `forgettableMessages` configurable).
I also tweaked the other messages to make them use `configuration.format` where possible.
This is how the `builder build bundle` output looks now:
This is how the `builder build plugin` output looks now:
Note: Currently …
> feat(builder): improve builder output

- packages/gatsby/content/advanced/lexicon.md
- The docs make several references to 'build scripts'
- i'm stupid
...
Sheer hard work
...
> Adds Lexicon Entry for 'Build Scripts'

- .yarn/versions/997be237.yml
- packages/yarnpkg-core/sources/Project.ts
Yarn is leaking `xfs` temp folders created when running build scripts. Running `yarn rebuild` on master (526947260dae29475ff69561c2cdb45024bbed04) leaves 6 empty `xfs` temp folders.
Explicitly close the stream created by `getSubprocessStreams`[1] after we're done with it so it doesn't prevent `removePromise`[2] from deleting the folder.
1: https://github.com/yarnpkg/berry/blob/526947260dae29475ff69561c2cdb45024bbed04/packages/yarnpkg-core/sources/Configuration.ts#L1005
2: https://github.com/yarnpkg/berry/blob/5f0439a087b8463d97fb70c96dc6f983a91be512/packages/yarnpkg-fslib/sources/FakeFS.ts#L179-L191
> fix(core): avoid leaking xfs temp folders when running build scripts

- .yarn/versions/bc84528b.yml
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/tests/shell.test.ts
Follow-up to #1166.
I added **a lot** of tests for the glob support in the shell, covering all kinds of patterns.
Since all of them are passing, we can safely say that the basic glob support works perfectly.
Note: Ignore the fact that it looks as if my fictional cat generated those filenames by jumping on my keyboard. I couldn't get more creative than that 😄.
Another note: I plan to follow-up in the future with some shell dragon tests that will combine all of the shell features in some very weird, impossible-looking scenarios.
> test(shell): add tests for glob support

- .yarn/versions/a1a51544.yml
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-a-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-a-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-b-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-b-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-b-2.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-b-2.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-c-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-c-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-c-2.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-c-2.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-c-3.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-c-3.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-d-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-7-d-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/dragon.test.js
- packages/yarnpkg-pnpify/sources/hoist.ts
Fixes: #1311 
After hoisting we are stripping peerDependencies and other misc information needed for hoisting from tree nodes. During this process we maintained a list of processed tree nodes in form of a map `node locator` -> `resulting node with extra info stripped`. This was wrong, because node with the same locator could have been hoisted differently in different parts of the tree. I have changed the map to be `node with extra hoisting info` -> `resulting node with extra info stripped`, this way node impersonation should no longer happen.
> [node-modules] Fixes same locator node impersonation after hoisting

- .yarn/versions/4ab5ebe6.yml
- packages/plugin-essentials/sources/commands/exec.ts
- packages/plugin-essentials/sources/commands/node.ts
- packages/plugin-essentials/sources/index.ts
Yarn doesn't currently have a `yarn exec` command, which makes `yarn workspaces foreach` less powerful than it could be, as it can only run Yarn commands.
I added a hidden `yarn exec` command, which works exactly like `yarn node` (I even made `yarn node` an alias for `yarn exec node`), but it's generic.
This means that these are now possible:
- `yarn exec ls *.js`
- `yarn workspaces foreach exec ls *.js`
>  feat(plugin-essentials): add exec command 

- scripts/setup-ts-execution.js
Computers with on access file antivirus scans can suffer greatly from every extra disk access. Allowing developers to set the `BABEL_CACHE_PATH` themselves makes it possible to move the babel cache into a folder that's excluded by the AV scan.
Only set `BABEL_CACHE_PATH` if it's not present already.
Moving the `BABEL_CACHE_PATH` nearly halves the total run time of `yarn node -p process.versions.pnp` in this repository on my computer, from a mean of 12 seconds to 6-7 seconds.
Fun fact: folders called `Yarn` are excluded in our AV configuration because of the global yarn cache location.
Other ignored folder names include `.git`, so I have colleagues who moved their entire workspace into a folder called `.git`. I wish I was …
> Only set BABEL_CACHE_PATH if not present in environment

- packages/gatsby/content/advanced/questions-and-answers.md
Minor documentation error:
After running `yarn set version berry` and `yarn install`, the created file is `.yarn/install-state.gz`, not `.tgz`.
Source code confirms this: https://github.com/yarnpkg/berry/pull/998/files#diff-23dd4c2e823c25186f1107e88e962032R201
Changed `.tgz` to `.gz` in documentation.
> Fix documentation regarding .yarn/install-state.gz

- .yarn/versions/966dd5b5.yml
- packages/plugin-essentials/sources/commands/set/version.ts
Yarn doesn't work inside workspaces with `"type": "module"`. 
Fixes #985 
Switch the yarn releases from `.js` to `.cjs` file extension. This marks the file as always being CommonJS, regardless of the surrounding workspace's type.
The same change should be done in yarn v1, given that a lot of people will keep using v1 as global yarn for the foreseeable future.
**Future work?**
Right now we store the PnP file as `.pnp.js` for regular workspaces, and as `.pnp.cjs` for workspaces marked `type=module`. There are some downsides to this approach:
- This leads to quite a bit of if-checks in yarn itself (generation fo the pnp file, the NODE_OPTIONS environment variable and pnpify).
- If there are external tools that depend on the …
> Make yarn work inside a workspace with "type": "module"

- .yarn/versions/b9fa3f4c.yml
- packages/yarnpkg-core/sources/Configuration.ts
Install output shows build error log paths as PortablePaths
Update `format` to convert `PortablePath` to `NativePath` when the type is `FormatType.PATH`
> fix(core): format FormatType.PATH as NativePath

- .yarn/versions/8045181c.yml
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
- packages/yarnpkg-libui/sources/components/ItemOptions.tsx
- packages/yarnpkg-libui/sources/components/ScrollableItems.tsx
When testing the new version of Yarn (berry) I found out that the interactive tool `upgrade-interactive` has been redone in Ink, but a lot of the "niceness" of the old version was gone. Since I have some experience with Ink, I decided to make it a bit nicer and later maybe add some features if you guys think this is going in the right direction.
Things I did:
- Added an info section
- Added a prompt
- Added column names
- Tweaked some chars
- Tweaked some colors and font weights
- Tweaked some widths, heights, and spacings
Before:
After:
> Upgrade interactive tweaks

- .yarn/versions/8c154503.yml
- packages/plugin-workspace-tools/sources/commands/focus.ts
fixes #1364
`workspaces focus` can produce different virtual package references from a full `yarn install`. Before this commit after running `focus` those dependencies became unreachable because the install state on disk didn't match the new references.
See https://github.com/dannycoates/yarnbug to reproduce the bug.
By adding `persistInstallStateFile()` the install state saves the new references without affecting the other project files.
> fix(workspace-tools): focus command should persist install state

- packages/gatsby/content/advanced/editor-sdks.md
The existing instructions add an extra dependency to `@yarnpkg/pnpify` which is not necessary.
Update the instruction to use `yarn dlx` instead
> docs(editor-sdks): update instruction to use yarn dlx

- packages/gatsby/content/features/plugnplay.md
The format is broken in #1294. this commit fixes it.
Append `default )\n` to the broken line.
> docs(gatsby): Fix typo in compatibility table

- .yarn/versions/39204e65.yml
- packages/plugin-version/sources/commands/version/check.tsx
There were some emojis used in the `version check -i` command that were causing problems for some users.
I replaced them with Unicode characters for it to be consistent with the `upgrade-interactive` command.
Before:
After:
> Replace emojis with Unicode characters

- .yarn/versions/4db76971.yml
- packages/plugin-exec/sources/ExecFetcher.ts
Installing an `exec:` package that depends on something calling `node -e` in their postinstalls (such as corejs) doesn't work. This is because the global accessors aren't configurable, so when Node tries to set its own it fails.
- The bootstrap is now done using `--require` instead of `NODE_OPTIONS` so that it doesn't affect nested Node contexts.
- The accessors are now configurable to allow for the user to rebind them if needed.
> Fixes global overrides when used with -e

- .yarn/versions/75154479.yml
- packages/acceptance-tests/pkg-tests-specs/sources/script.test.js
- packages/yarnpkg-core/sources/scriptUtils.ts
Fixes #1373
Do what yarn 1 / yarn 2 with the node-modules linker already do: create the sh script on windows environments as well.
> Always create path wrapper executables without suffix

- packages/yarnpkg-libui/sources/components/ScrollableItems.tsx
I was building one of my Yarn 2 plugins (that exists as a branch of a fork of this), 
```
[tsl] ERROR in /berry/packages/yarnpkg-libui/sources/components/ScrollableItems.tsx(58,40)
TS1382: Unexpected token. Did you mean `{'>'}` or `&gt;`?
```
Caused by a small regression with https://github.com/yarnpkg/berry/pull/1323
```jsx
<Color cyan>▶</Color>
```
to
```jsx
<Color cyan bold>></Color> 
```
throws the linter.
Just replaced it with a `{'>'}`
> fix(yarnpkg-libui): Fixed linting error

- .yarn/versions/0cef90fb.yml
- packages/yarnpkg-pnpify/sources/NodeModulesFS.ts
Angular over PnPify test is failing now because Angular tries to create a file inside root node_modules dir. Because this dir is virtual in the case of pnpify this attempt fails
We are checking if `fs.open` has write flags and the parent directory is a virtual directory, and if both are true we persist parent directory to disk.
**Checklist**
> [pnpify] Persist virtual node_modules dir to disk on file write

- packages/gatsby/src/pages/package.js
Currently, all packages have same (default) title so it's hard to navigate among browsers tabs 
https://github.com/yarnpkg/berry/issues/803#issuecomment-629855668
Prepend page title with a package name
**Checklist**
> docs: add package name into title

- packages/gatsby/src/utils/useScroll.js
Currently, scroll restoration is broken. Try to jump between pages in CLI section.
https://yarnpkg.com/cli/set/version
Seems that URLs structure was changed and it broke scroll restoration. Now we use a common part of URL. 
**Checklist**
> docs: fix scroll restoration for menu

- .yarn/versions/a3c71b4a.yml
- packages/gatsby/src/pages/configuration/manifest.json
- packages/gatsby/src/pages/configuration/yarnrc.json
- packages/plugin-init/sources/commands/init.ts
- packages/plugin-init/sources/index.ts
Resolves #1374
Previously `yarn init` allowed setting `author`, `repository` and various other fields. Now it can only set a few basic options like name, workspaces, version etc.
Also, in monorepos it's common to have the same properties in all packages in the repo, and it's a bit awkward to copy and paste those fields when initializing a new package in that repo.
Added an `initFields` configuration option. All the properties specified will be added to the generated `package.json` - there are no constraints in order to support arbitrary additional keys added by libraries, e.g. `"jest"`, `"babel"`, ...
The implementation is pretty simple - it effectively treats `initFields` as the old package.json and loads it into the …
> feat: Allow specifying arbitrary fields to be added to package.json during `yarn init`

- .yarn/versions/afc5c335.yml
- packages/plugin-git/sources/gitUtils.ts
Follow-up to https://github.com/yarnpkg/berry/pull/1367#issuecomment-630027701
When installing git dependencies, the checksum is different depending on the users git settings.
Pass `-c core.autocrlf=false` to git clone
**Checklist**
> fix(git): disable core.autocrlf when cloning a repo

- .yarn/versions/59b13d62.yml
- packages/plugin-version/sources/commands/version/check.tsx
The keybindings for the `yarn version check -i` command aren't currently shown anywhere and "tab to move focus" isn't always intuitive (see https://github.com/yarnpkg/berry/pull/1387#issuecomment-632163204).
I made it so that the keybindings are now displayed, just like for the `yarn upgrade-interactive` command. Feel free to tweak the alignment / whatever else you feel needs improvements.
**Checklist**
>  feat(version-check-interactive): display keybindings 

- .yarn/versions/8c6a6df8.yml
- packages/yarnpkg-core/sources/httpUtils.ts
The resolution step is currently a bit slow and uses a decent amount of memory.
- Once the GET request finishes, replace the entry in the cache with the response body
- If the entry from the cache is a buffer, skip the await call.
**Results**
Average measurements over three runs with no lockfile
||Total dependencies|Time before* | Time after*| RAM before** | RAM after**|
|--|--|--|--|--|--|
|next@9.4.5-canary.3  | 784 | 1881ms | 811ms|425MB | 196MB|
|react-scripts@3.4.1|1408 |  3633ms | 1325ms |642MB | 237MB|
*Time: `Self Time` of the `get` function measured by the profiler in Chrome DevTools
**RAM: Private bytes as measured by my task manager, after using Chrome DevTools' `Collect garbage` function three times …
> perf(core): skip await if response has already resolved

- .yarn/versions/85e06261.yml
- packages/plugin-compat/sources/extensions.ts
Installing `jss-plugin-rule-value-function` doesn't work on Yarn 2 due to missing dependencies.
Add the missing dependencies to plugin-compat/…/extensions.ts which solves this problem in the short term. See https://github.com/cssinjs/jss/pull/1315..
**Checklist**
> feat(plugin-compat): add missing jss-plugin-rule-value-function dependency to extensions

- .yarn/versions/d5806516.yml
- packages/yarnpkg-core/sources/execUtils.ts
- packages/yarnpkg-shell/sources/index.ts
Some terminals set the `PWD` environment variable, some don't. On windows the value of the variable is different depending on where the command was run. Running `node -p process.env.PWD` directly in Git Bash returns `/c/berry`, while running it from Git Bash as an integrated terminal in VSCode returns `C:/berry`. Running `yarn node -p process.env.PWD` returns `/c/berry` in both scenarios. It would be nice to have some consistency here.
Set the `PWD` environment variable whenever a process is spawned
**Checklist**
> fix: normalize pwd environment variable behaviour

- .pnp.js
- .yarn/versions/0c32cf56.yml
- packages/acceptance-tests/pkg-tests-fixtures/packages/@types__no-deps-2.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/@types__no-deps-2.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/commands/remove.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/commands/up.test.ts
- packages/plugin-essentials/package.json
- packages/plugin-essentials/sources/commands/remove.ts
- packages/plugin-essentials/sources/commands/up.ts
- yarn.lock
`yarn remove` and `yarn up` don't currently support glob patterns, which makes removing / upgrading all dependencies containing a specific scope / word more difficult than it should be.
Closes #1418.
I implemented glob support to both `yarn remove` and `yarn up`, using `micromatch`, the library that we already use for everything glob related.
For `yarn remove`, we get the list of idents for a scope and we iterate over the matches, removing the descriptor corresponding to the matched ident. 
For `yarn up`, we get the list of idents for a scope and we iterate over the matches, setting the existing descriptor to the descriptor corresponding to the matched ident, and the descriptor used in the request to a new descriptor, …
> feat(plugin-essentials): add support for glob patterns to yarn remove and yarn up

- .yarn/versions/2edeb9ad.yml
- packages/yarnpkg-core/sources/execUtils.ts
- packages/yarnpkg-shell/sources/pipe.ts
The shell wasn't using a refcount for its ^C interception, causing leak warnings to be emitted.
We have two places where process are spawned: within the core, and within the shell. Since the shell doesn't depend on the core (that's intended), the logic needs to be duplicated between both.
**Checklist**
> Fixes event emitter leaks

- .yarn/versions/97d8f96d.yml
- packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
- packages/yarnpkg-pnp/sources/generatePnpScript.ts
`path` was used before being required, which caused `pnpEnableInlining` to completely break.
Closes #1073.
We now require `path` before using it. ¯\\_(ツ)_/¯
I also added tests.
**Checklist**
> fix(pnp): fix pnpEnableInlining

- .yarn/versions/634da13b.yml
- packages/plugin-git/sources/__snapshots__/gitUtils.test.js.snap
- packages/plugin-git/sources/gitUtils.test.js
- packages/plugin-git/sources/gitUtils.ts
We currently support the "`git+https?` is optional, `.git` is required" case, but not the "`git+https?` is required, `.git` is optional" case.
Fixes #1447.
I split the pattern into 2 patterns, one for each case.
**Checklist**
> fix(plugin-git): add support for `git+https?` without `.git` ending

- .yarn/versions/1105671a.yml
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
- packages/yarnpkg-pnpify/sources/hoist.ts
This PR further speeds up hoisting process, by doing hoisting to each root node exactly in one pass, without need for multiple passes.
We are decoupling graph nodes to convert them into tree nodes as we go and use these new nodes to check the peer dependency promises are satisfied, this is possible now, because we hoist as we go. Previously we hoisted as we go, but used original nodes and hence our peer deps were always not satisfied which lead to the need for multiple iterattions.
The speedup varies, but I've seen 2x speedup on big projects.
The PR also fixes the case when workspace dependency locators were not merged together and some of them were lost because of this in `buildNodeModulesTree`. Now they are merged …
> [node_modules] Performs hoisting to each root node in one pass only

- .yarn/versions/25204950.yml
- packages/plugin-essentials/sources/commands/set/version.ts
This PR adds back `yarn policies set-version` as an alias to `yarn set version`. It will be removed in the next major.
Closes https://github.com/yarnpkg/berry/issues/472.
Closes https://github.com/yarnpkg/berry/issues/350.
Closes #904.
With a keyboard.
**Checklist**
> feat(plugin-essentials): add policies set-version alias

- .yarn/versions/8cc061aa.yml
- packages/yarnpkg-core/sources/Workspace.ts
When specifying a globstar pattern for workspaces, the `node_modules` folders aren't ignored which causes `duplicate workspace name` errors.
Fixes https://github.com/yarnpkg/berry/issues/1297
Fixes https://github.com/yarnpkg/berry/issues/1191
Ignore `node_modules` and `.git` folders when searching for workspaces
**Checklist**
> fix(core): ignore node_modules and .git folders for workspaces

- .yarn/versions/03110f2a.yml
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/sources/StreamReport.ts
Some TTYs don't report column count (Nix?), and some others just have very small sizes. Both cases cause issues due to `String.prototype.repeat`.
The progressbars aren't enabled unless columns are reported and are wide enough.
**Checklist**
> Fixes rendering on small terminals

- .yarn/versions/be0136f1.yml
- packages/plugin-constraints/sources/commands/constraints.ts
`yarn constraint --fix` does not work and even if all the workspaces fulfils the declared constraints it still run the multi-pass process 10 times and then exit with code 1 
...
decouple error management from error reporting
...
**Checklist**
> fixes constraint fix

- .yarn/versions/fb20bd87.yml
- packages/yarnpkg-pnpify/sources/sdks/vscode.ts
We were changing `svelte.language-server.runtime` which isn't the correct option to be used. Now it is changing `svelte.language-server.ls-path` which should be added by this [PR](https://github.com/sveltejs/language-tools/pull/202)
Changed the string
**Checklist**
> Using proper svelte extension settings now

- .yarn/versions/604dd281.yml
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/commands/up.ts
`yarn {add,up} foo -i` always prompts the user if `foo` already exists inside another workspace, even if it has the same range as the latest resolved from the registry.
I made it so that the prompt is skipped if all (non-null) suggested descriptors returned by `suggestUtils` are identical.
**Checklist**
> fix(plugin-essentials): don't show prompt if suggestions are identical

- .pnp.js
- .yarn/versions/91b6d6ad.yml
- packages/plugin-init/package.json
- packages/plugin-init/sources/commands/init.ts
- packages/plugin-init/sources/index.ts
- yarn.lock
I created a new project yesterday and I still had to spend 5+ minutes copying files from another repository. We should do better, especially since some of those settings (like the gitignore) are required because of Yarn itself.
Running `yarn init` will now generate more files than usual. It will also:
- initialize the folder as a git repository, because in practice that's always what we want
- add a gitignore + gitattributes file
- add an editorconfig with the configuration that we use for the `.json` / `.yml` files that we generate (also `.js` as a bonus, but that can be easily overridden in the configuration)
If I had this PR yesterday, I'd still have had to:
- Copy the tsconfig
- Copy the rollup config
- Set the main + …
> Improves init

- .yarn/versions/a0de8eea.yml
- packages/plugin-exec/README.md
This PR updates the `plugin-exec` documentation for the monorepo package build example with a package extraction that works for both GNU- and BSD-based OS's.
> chore(plugin-exec): Fix docs for tar usage that works for GNU & BSD

- .yarn/versions/b65d59df.yml
- packages/plugin-essentials/sources/commands/up.ts
- packages/yarnpkg-core/sources/Project.ts
`yarn up foo@tag` doesn't re-resolve `tag` if it's already part of the lockfile.
Fixes #1419.
- I added a new `project.forgetResolution` method - accepts both descriptors and locators as arguments.
- I made it so that `yarn up` calls this method if the current descriptor matches the updated descriptor. This "unlocks" the dependency, causing it to be resolved again to the latest satisfying version.
This means that now:
- `yarn up foo@canary` updates `foo` to the latest version resolved for the `canary` tag
- `yarn up foo@3.x` updates `foo` to the latest version resolved for the `3.x` range
- `yarn up foo@github-repo/foo` updates `foo` to the version resolved from the latest commit
Note: I removed the `hasChanged` part of …
> fix: make yarn up resolve latest for tag

- .yarn/versions/d7511af5.yml
- packages/plugin-patch/sources/patchUtils.ts
Some options (`diff.mnemonicprefixes`) cause Git to support different prefixes in its patchfiles.
We now enforce the prefixes to ensure normalization.
**Checklist**
> Enforces the patch prefixes

- .yarn/versions/27adb827.yml
- packages/plugin-exec/sources/ExecFetcher.ts
- packages/plugin-file/sources/FileFetcher.ts
- packages/plugin-file/sources/TarballFileFetcher.ts
- packages/plugin-git/sources/GitFetcher.ts
- packages/plugin-github/sources/GithubFetcher.ts
- packages/plugin-http/sources/TarballHttpFetcher.ts
- packages/plugin-npm/sources/NpmHttpFetcher.ts
- packages/plugin-npm/sources/NpmSemverFetcher.ts
- packages/plugin-patch/sources/PatchFetcher.ts
- packages/yarnpkg-core/sources/Cache.ts
- packages/yarnpkg-core/sources/Fetcher.ts
- packages/yarnpkg-core/sources/Project.ts
Yarn computes cache file checksums during `Fetch step` and then computes the same cache file checksums during `Link step`.
On a `next.js` project this results in the following timings:
||before|after|
|--|--|--|
|yarn add leftpad| 16.47s | 13.44s|
I have added a `skipIntegrityCheck` option to `Fetcher` that can be used during Link step to not run integrity checks on the same files the second time. 
**Checklist**
> perf: Reduce `yarn add/yarn remove` time by validating cache file checksums only once

- .yarn/versions/df0edab2.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/config/get.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/features/projectDetection.test.js
- packages/plugin-essentials/sources/commands/config.ts
- packages/plugin-essentials/sources/commands/config/get.ts
- packages/plugin-essentials/sources/commands/config/set.ts
- packages/plugin-exec/sources/execUtils.ts
- packages/plugin-file/sources/FileFetcher.ts
- packages/plugin-file/sources/TarballFileFetcher.ts
- packages/plugin-link/sources/LinkFetcher.ts
- packages/plugin-link/sources/RawLinkFetcher.ts
- packages/plugin-patch/sources/patchUtils.ts
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/tests/Configuration.test.ts
- packages/yarnpkg-pnp/sources/loader/applyPatch.ts
Running `yarn config get` currently returns a portable path, which makes it difficult to work with when used in shellscripts.
I've leveraged the work @paul-soporan did on the secret support to turn it into an all-purpose settings transform function (and renamed `getRedacted` into `getSpecial` to highlight that the function supports more transforms).
**Checklist**
> Makes `yarn config get` return native paths

- .yarn/versions/30ccfadf.yml
- packages/yarnpkg-core/sources/Workspace.ts
Fixes: #1191 
I have fixed it by fixing the ignore pattern basically `ignore: ['node_modules']` should rather be `ignore: ['**/node_modules/**']` as per:
https://github.com/mrmlnc/fast-glob#how-to-exclude-directory-from-reading
**Checklist**
> Fixes ignore glob pattern for workspaces

- constraints.pro
The constraints.pro file contained typos: `WorkspaceCwd` vs `WorkspacedCwd`
Remove the `workspace(WorkspacedCwd)` predicate entirely, the `WorkspaceCwd` is already populated with workspace values, so this is a superfluous validation.
The fact that this kind of typo can happen without any warning or error is a strong motivator for #1276.
**Checklist**
> Remove typos from constraints file

- .yarn/sdks/typescript/lib/tsserver.js
- .yarn/versions/35658422.yml
- packages/yarnpkg-pnpify/sources/sdks/base.ts
The TypeScript SDK doesn't strip the zip prefix correctly on Windows causing import suggestions to not show where the thing comes from.
Fixes #1533
Remove the leading slash that was left in on Windows
**Checklist**
> fix(pnpify): remove leading slash on windows in removeZipPrefix

- .yarn/versions/7bfd08a0.yml
- packages/plugin-version/sources/versionUtils.ts
js-yaml implements the YAML spec and it has no undefined type:
- https://github.com/nodeca/js-yaml/issues/356#issuecomment-311614322
I.e.:
```
> require('js-yaml').safeLoad('')
undefined // if the file is empty
> require('js-yaml').safeLoad('releases:\n')
{ releases: null }
```
> fix(plugin-version): Correctly check void releases for all falsy values 

- .yarn/versions/297c088c.yml
- packages/plugin-essentials/sources/commands/install.ts
The `--cache-folder` flag is deprecated but not set as hidden.
Set the flag as hidden
**Checklist**
> fix(essentials): set cache-folder as a hidden flag

- .yarn/versions/e2437f32.yml
- packages/vscode-zipfs/sources/ZipFSProvider.ts
Because Zip archives are considered regular files by the `ZipFSProvider`, they can't be expanded in the built-in file navigation menu at the top.
This also has to be changed for the sidebar `TreeView` I'm currently implementing to work correctly.
I made it so that all files with the `.zip` extension are treated as folders.
Before:
After:
**Checklist**
> feat(vscode-zipfs): treat zip archives as folders

- .yarn/versions/1b1c979e.yml
- packages/plugin-patch/sources/tools/apply.ts
Patches where hunks are systematically applied with a negative fuzzy offset grow the `fixupOffset` which leads to an even bigger offset for the next hunk, and so on and so on. This quickly leads to exponential growth of `offset` and a corresponding exponential growth of the time it takes to apply the next hunk.
Closes #1559
Let a negative offset shrink the `fixupOffset`
**Checklist**
> Apply negative offset if fuzzy match lies before first guess

- .yarn/versions/021b6d44.yml
- packages/yarnpkg-doctor/sources/cli.ts
`@yarnpkg/doctor` can't resolve dependencies that require a fetcher to be configured.
Fixes #778.
I made it so that the `fetchOptions` are passed to the resolver.
**Checklist**
> fix(doctor): fix resolve errors with resolvers that need fetchers

- .yarn/versions/eafbb3d6.yml
- CHANGELOG.md
- packages/yarnpkg-core/sources/Configuration.ts
Imagine that I implement a new `foo` configuration setting in a PR. I then decide to set it locally in my home `.yarnrc.yml` file, so that it only affects me. (Think of stylistic options like `preferTruncatedLines`)
It works fine for projects that are on Yarn versions that support that configuration setting, but it breaks for all other projects with `Unrecognized or legacy configuration settings found`.
I made it so that the home configuration is always non-strict.
**Checklist**
> fix(core): make home configuration always non-strict

- .yarn/versions/3c2d2550.yml
- .yarnrc.yml
- CHANGELOG.md
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/commands/up.ts
`yarn {add,up}` weren't respecting the `preferInteractive` configuration option.
Fixes #1566.
I made it so that `yarn {add,up}` respects the `preferInteractive` configuration option. I'm not sure if we should also make this change for `yarn version check`, as it's very different from `yarn version check -i`. What do you think?
**Checklist**
> fix(plugin-essentials): make `yarn {add,up}` respect `preferInteractive`

- .yarn/versions/0f1c494c.yml
- CHANGELOG.md
- packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
- packages/plugin-pack/sources/index.ts
- packages/plugin-pack/sources/packUtils.ts
- packages/yarnpkg-core/sources/CorePlugin.ts
- packages/yarnpkg-core/sources/Manifest.ts
There were two different problems:
- First, the `main` and `module` fields weren't properly hydrated when reading the manifest files. This caused `yarn pack` to simply not see them, and thus not include them in the generated archive unless they were properly listed in the `files` field.
- Second, the `bin` field was completely omitted from the logic that ensures that `main`, `module`, and `bin` are all part of the generated archive. So again, it had to be explicitly listed.
The `main` and `module` field are now properly hydrated, and `bin` is now accounted for in `genPackList`. Also added a test to prevent regressions.
**Checklist**
> Fixes main files not being packed

- .yarn/versions/2a7ebc69.yml
- packages/yarnpkg-fslib/sources/algorithms/copyPromise.ts
We were calling `chmod` on symlinks before the symlink target had been created. This caused issues since the chmod was then applied to a non-existing file, and failed.
Tbh it's not perfect; we should instead call `lchmod`, but this function doesn't seem supported elsewhere than OSX, so I need to make a bit of research of figure out what's the best course of action.
I also refactored a bit copy so that more things can happen in parallel: the `prelayout` pass is sequential and is meant to prepare the filesystem hierarchy, while the `postlayout` pass tweaks the filesystem attributes of the layout and thus can be executed in parallel.
**Checklist**
> Improves copy performances

- .pnp.js
- .yarn/versions/b895eba7.yml
- CHANGELOG.md
- packages/acceptance-tests/pkg-tests-specs/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
- packages/gatsby/src/pages/configuration/manifest.json
- packages/plugin-pack/sources/packUtils.ts
- packages/yarnpkg-core/sources/Cache.ts
- packages/yarnpkg-core/sources/Manifest.ts
- yarn.lock
Yarn currently always ignore the +x flag when packing projects. This breaks projects that depend on internal executable binaries that aren't listed in the `bin` field (it's pretty rare, but there are valid use cases).
A new `publishConfig.executableFiles` field will let users define the paths that Yarn need to keep executable during packing.
Alternatives and why we didn't do it:
- We could have used the +x flag from the filesystem, but it means that archives packed on Windows would have had different checksum than the ones compiled on Posix. Since we want to make the "install from a git repository" workflow (which requires packing) as painless as possible, this isn't possible.
- We could have always set the +x flag on all …
> Implements `executableFiles`

- .vscode/settings.json
- .yarn/versions/88c6bc4f.yml
- packages/yarnpkg-pnpify/sources/generateSdk.ts
- packages/yarnpkg-pnpify/sources/sdks/vscode.ts
Yarn's vendor files are currently taken into account by VSCode's file search, which can be very dangerous in combination with search & replace (just ask the person that accidentally replaced all occurences of `--frozen-lockfile` with `--immutable`, which included the ones in Yarn's source code...).
I made it possible to specify default SDKs (without requiring any specific dependency to be installed). I made it include the `search.exclude` VSCode setting and I also moved the `arcanis.vscode-zipfs` extension recommandation from the TS VSCode SDK to the Default VSCode SDK.
**Checklist**
> feat(pnpify): add default sdks

- .yarn/versions/197dc69d.yml
- CHANGELOG.md
- packages/yarnpkg-core/sources/httpUtils.ts
When installing big packages like [`hermes-engine@0.4.1`](https://packagephobia.com/result?p=hermes-engine@0.4.1) on slow internet connection, yarn would timeout even if package was slowly downloading.
Fixes https://github.com/facebook/jest/issues/10267
I used the `timeout.socket` option from [got](https://github.com/sindresorhus/got#timeout) to only timeout if the socket does not receive data for more than `httpTimeout`.
**Checklist**
> Use socket timeout instead of got timeout

- .yarn/versions/2bc54b30.yml
- packages/plugin-init/sources/commands/init.ts
The `init` plugin requires the entire lodash library for one function
Only import the used function, takes the cli from 2.35MB back down to 2.28MB
**Checklist**
> perf(init): import used lodash method only

- .yarn/versions/4c8d8011.yml
- packages/yarnpkg-core/sources/Cache.ts
When loading a package from the mirror(global cache) Yarn opens the zip file using ZipFS just to immediately close it again.
Modify `loadPackageThroughMirror` to return the path to the zip archive as that is what `loadPackage` is after.
**Result**
Testing on https://github.com/microsoft/TypeScript-Website this reduces the time to fetch from a hot global cache to the local cache by ~4 seconds
**Checklist**
> perf(core): avoid opening zip file with ZipFS just to close it again

- .yarn/versions/765b9eaf.yml
- packages/yarnpkg-builder/sources/commands/build/bundle.ts
- packages/yarnpkg-builder/sources/tools/makeConfig.ts
`esprima` is only needed for parsing `!!js/function`, which isn't part of the `FAILSAFE_SCHEMA`.
Unfortunately, `js-yaml` declares it as a hard dependency and requires the entire module, which causes `webpack` to add `0.13 MB` of unused code to the bundle.
Fortunately, `js-yaml` wraps the require call inside a `try / catch` block, so we can just ignore it.
Reference: https://github.com/nodeca/js-yaml/blob/master/lib/js-yaml/type/js/function.js#L15
I've used `webpack.IgnorePlugin` to ignore `esprima`. This decreases the bundle size from `1.89 MB` to `1.76 MB` (`6.87831%` decrease).
**Checklist**
> chore: don't bundle esprima

- .github/workflows/e2e-parcel-workflow.yml
We recently disabled autoinstall for `parcel build`...
This doesn't test autoinstall anymore, but I'm not sure how running `parcel serve`, waiting for the build to finish & stopping Parcel could be achieved via a shell script.
> Fix Parcel E2E test

- .pnp.js
- .yarn/versions/ca56081b.yml
- packages/yarnpkg-core/package.json
- packages/yarnpkg-core/sources/tgzUtils.ts
- yarn.lock
The yarn bundle contains both `tar` (in `@yarnpkg/core`) and `tar-stream` (in `@yarnpkg/plugin-pack`), which both do the same thing.
Replace `tar` with `tar-stream`. This decreases the yarn bundle size by 66150 bytes (about 3.6%).
**Checklist**
> feature(core): replace tar with tar-stream

- .yarn/versions/d5a0f5d8.yml
- packages/acceptance-tests/pkg-tests-specs/sources/features/immutablePatterns.test.ts
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/sources/LightReport.ts
- packages/yarnpkg-core/sources/Project.ts
- packages/yarnpkg-core/sources/StreamReport.ts
- packages/yarnpkg-core/sources/hashUtils.ts
The checksum was returned under the form of the checksum object, not a hash, so it was always comparing different. Additionally, `globby` has a problem with `expandDirectories`: https://github.com/sindresorhus/globby/issues/147
I also fixed the reporting for LightStream, and the telemetry payload for package extensions (so that they include the change that's applied).
We now get the list of directories matching the pattern, then we manually add those to the pattern list, without using the `expandDirectories` option.
**Checklist**
> Fixes pattern checksum

- .yarn/versions/6f730f82.yml
- packages/plugin-dlx/sources/commands/dlx.ts
`yarn dlx` currently counts as a project in the telemetry which will inflate that metric a lot.
Disabled telemetry for everything `dlx` does, `dlx` itself still counts but anything it does and anything the project it creates does isn't counted.
**Checklist**
> fix(dlx): prevent dlx from counting as a project in the telemetry

- .yarn/versions/49e87d67.yml
- packages/vscode-zipfs/sources/ZipFSProvider.ts
The `vscode-zipfs` `ZipFSProvider` didn't support read after write, which caused VSCode to not be able to save any changes inside zip archives.
I disabled the cache (`useCache: false`), which causes `ZipOpenFS` to create a fresh `ZipFS` instance on every FS operation, which prevents `ZIP_ER_CHANGED`.
**Checklist**
> fix(vscode-zipfs): support read after write

- .yarn/versions/ea6c2aeb.yml
- packages/yarnpkg-core/sources/Cache.ts
We were creating the `ZipFS` instance inside the `LazyFS` returned by `fetchPackageFromCache` too early inside `VirtualFetcher.ensureVirtualLink`, because we were calling `sourceFetch.packageFs.getRealPath`, which caused the `baseFs` to be created from the `factory` function and querried using `getRealPath`.
This can be optimized by wrapping the `LazyFS` inside an `AliasFS` targetting the `cachePath`, which causes all `getRealPath` calls to return the `cachePath` directly without having to go through the `ZipFS`.
This reduces the execution time of all `VirtualFetcher.ensureVirtualLink` calls from `238.4 ms` to `15.7 ms` (`93.4144%` decrease) - tested inside the Berry repo (with a hot cache - not that it would matter, since …
> perf(core): wrap LazyFS inside AliasFS to speed up getRealPath calls

- .yarn/versions/ee084e32.yml
- packages/yarnpkg-core/sources/execUtils.ts
`execUtils` didn't properly handle error codes when the child exited with a signal. In this case `code` is null, which gets returned all the way to clipanion in the run/exec commands, and clipanion assumes `null` means A-OK.
```fish
$ yarn node -e 'process.kill(process.pid, 2)'
$ echo $status
0
```
- Ensure a non-zero exit code if `code == null`, as that means the child exited with a signal
- Exit with proper exit codes for the most common signals that might kill a process
```fish
$ yarn node -e 'process.kill(process.pid, 2)'
$ echo $status
130
```
**Checklist**
> feat(core): ensure child is marked as failed if it exited with signal

- .yarn/versions/756df4ca.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/npm/__snapshots__/login.test.js.snap
- packages/plugin-npm-cli/sources/commands/npm/login.ts
`yarn npm login --scope` doesn't save the login token under the specified scope, instead overwriting the existing login.
When `--scope` is specified save the login under the `npmScopes` config
**Checklist**
> fix(npm-cli): save login under specified scope

- .yarn/versions/b28d8e82.yml
- packages/gatsby/content/advanced/migration.md
- packages/plugin-workspace-tools/sources/commands/focus.ts
There is currently no way to replicate the behaviour of `yarn install --production` from V1, `yarn workspaces focus --production` gets close but requires that the root depend on all workspaces to truly replicate the behaviour
Added a `--all` flag to the focus command (`yarn workspaces focus`) to allow `yarn workspaces focus --all --production`
**Checklist**
> feat(workspace-tools): add --all flag to the focus command

- .yarn/versions/a26384d1.yml
- packages/plugin-workspace-tools/sources/commands/foreach.ts
Hitting `ctrl-c` doesn't stop `yarn workspaces foreach <stuff>`. It kills the currently running processes, but yarn starts the next batch, and the next, and the next etc.
Fixes #1622
Handle signal code 130, which signals SIGINT, by blocking all future commands from running.
`yarn workspaces foreach` will also exit with the SIGINT exit code, signaling to parent processes, if any, that yarn has exited due to a signal.
**Checklist**
> feat(plugin-workspace-tools): handle SIGINT in workspaces foreach

- .github/workflows/e2e-pnpify-workflow.yml
- .yarn/versions/8f408611.yml
- packages/acceptance-tests/pkg-tests-core/sources/utils/yarn.ts
- packages/acceptance-tests/pkg-tests-fixtures/packages/one-fixed-dep-2.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/one-fixed-dep-2.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/commands/unplug.test.ts
- packages/plugin-essentials/sources/commands/link.ts
- packages/plugin-pnp/sources/PnpLinker.ts
- packages/plugin-pnp/sources/commands/unplug.ts
- packages/plugin-pnp/sources/index.ts
- packages/plugin-pnp/sources/pnpUtils.ts
- packages/plugin-workspace-tools/sources/commands/foreach.ts
Various commands had different styles of `--all` flag.
This PR normalizes the syntax by using the two following flags:
- `-A,--all` will always target all the workspaces (but not their transitive dependencies)
- `-R,--recursive` will always target all the dependencies (but not all the workspaces)
The `-a` flag for `yarn workspaces foreach` is deprecated, but will only be removed in the next major.
**Checklist**
> Uniformizes the --all flag

- .yarn/versions/bb9021aa.yml
- packages/plugin-compat/sources/extensions.ts
The gatsby e2e test has been failing for weeks and https://github.com/vadimdemedes/ink-select-input/pull/26 has been open for 17 days now.
Added `react` as a peer dependency to `ink-select-input` in `plugin-compat`
**Checklist**
> fix(compat): add ink-select-input extension

- .yarn/versions/6c7ed101.yml
- packages/plugin-essentials/sources/commands/install.ts
Deploying a Node.js package with Yarn v2 (via `.yarnrc.yml`) to Google Cloud Function (GCF) fails with the following error:
```
ERROR: (gcloud.functions.deploy) OperationError: code=3, message=Build failed: Build error details not available.
```
Fixes https://github.com/yarnpkg/berry/issues/1646
Do not exit with an error when running `yarn install --non-interactive --frozen-lockfile` in GCF environment.
**Checklist**
> Fix Google Cloud Functions (GCF) deployment

- .yarn/versions/e5035e39.yml
- packages/acceptance-tests/pkg-tests-core/sources/utils/yarn.ts
- packages/acceptance-tests/pkg-tests-specs/sources/commands/npm/__snapshots__/logout.test.ts.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/npm/logout.test.ts
- packages/acceptance-tests/pkg-tests-specs/sources/commands/plugin/import.test.ts
- packages/acceptance-tests/pkg-tests-specs/sources/commands/plugin/remove.test.ts
- packages/plugin-dlx/sources/commands/dlx.ts
- packages/plugin-essentials/sources/commands/plugin/remove.ts
- packages/plugin-npm-cli/sources/commands/npm/login.ts
- packages/plugin-npm-cli/sources/commands/npm/logout.ts
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/sources/miscUtils.ts
- packages/yarnpkg-parsers/sources/syml.ts
- scripts/plugin-hello-universe.js
The configuration patch workflow was so-so, which was causing issues like #1663 (running `yarn logout` was leaving empty fields).
Various fixes:
- Empty objects won't be serialized anymore (instead of serializing to empty strings)
- Non-indexable fields will be ignored from updates (instead of crashing)
- Improved the typing by using `unknown` instead of `any`
- Uniformized `logout -s` to follow the same logic as `login -s`
- Added a warning when there are remaining auth tokens even after logout (it can happen if the user specified auth tokens in both registry and top-level, for example).
**Checklist**
> Refactors login/logout

- .yarn/versions/7a667563.yml
- packages/yarnpkg-core/sources/Project.ts
Calling `project.forgetResolution` with a `Descriptor` also deletes the resolved `Locator`, which can be part of multiple resolutions.
Fixes #1507.
I split the logic inside `project.forgetResolution` between Descriptors and Locators, and I've also added some extra deletions for Locators.
**Checklist**
> fix(core): fix project.forgetResolution

- .pnp.js
- .yarn/versions/f73bdd81.yml
- packages/plugin-compat/sources/extensions.ts
`promise-inflight` requires Bluebird, and then falls back to native Promise (https://git.io/JJP8d). However, Bluebird is not declared as peer dependencies. (https://github.com/iarna/promise-inflight/pull/4)
`promise-inflight` has 12M weekly downloads.
Added `promise-inflight` to compat extensions.
**Checklist**
> fix(compat): add `promise-inflight` to extensions

- .yarn/versions/ac9cfab7.yml
- packages/yarnpkg-core/sources/Project.ts
During `fetchEverything` Yarn fetches the same locators multiple times wasting resources. Though the mutex prevents a full fetch.
Make `fetchEverything` only fetch unique locators, which also fixes the summary when the cache is empty to show `No packages were cached - 1911 packages had to be fetched` instead of `532 packages were already cached, 1911 had to be fetched`
**Result**
When run locally this improves the gatsby benchmark `install-cache-and-lock`, where there are 532 duplicated locators, by ~500ms.
Before: https://github.com/yarnpkg/berry/actions/runs/200437582
After: https://github.com/yarnpkg/berry/actions/runs/200511894
**Checklist**
> fix(core): only fetch unique locators

- .yarn/versions/2136b86b.yml
- CHANGELOG.md
- packages/acceptance-tests/pkg-tests-specs/sources/script.test.js
- packages/plugin-npm/sources/NpmSemverResolver.ts
- packages/yarnpkg-core/sources/Project.ts
- A typo was causing incorrect build executions
- The changelog was missing a few items (it still does)
- The incorrect error message was printed when running Yarn from a non-workspace directory
- Yarn wasn't differentiating deprecated versions from non-deprecated ones
- Fixed the typo, added tests
- Print a more helpful error message when Yarn is used on something that isn't a workspace
- Deprecated versions won't be used if other versions satisfy the range
**Checklist**
> Fixes build execution

- .yarn/versions/88041e15.yml
- packages/yarnpkg-core/sources/Cache.ts
When running `fetchPackageFromCache` Yarn checks if the file already exists using `existsSync` instead of `existsPromise` blocking the event loop.
Changed `existsSync` to `existsPromise`, however this caused race conditions (which lead to https://github.com/yarnpkg/berry/pull/1684) so I moved the load logic into `loadPackageThroughMutex` to make sure any part of the fetch for a specific locator is mutexed.
**Result**
When testing the gatsby benchmark `install-cache-and-lock` locally this reduces the time spent in `fetchPackageFromCache` from 1001ms to 393ms
Before: https://github.com/yarnpkg/berry/actions/runs/200598797
After: https://github.com/yarnpkg/berry/actions/runs/200603660
**Checklist**
> perf(core): make check for cache entries async

- .yarn/versions/466290f7.yml
- packages/yarnpkg-cli/sources/main.ts
- packages/yarnpkg-fslib/sources/FakeFS.ts
- packages/yarnpkg-fslib/sources/index.ts
Yarn is cleaning up its temp folders in the `exit` event which forces us to use sync IO calls which has a performance impact.
Implemented `rmtempPromise` and call it right after the CLI is done and about to exit, where we can run async IO without problems.
**Result**
Time spent cleaning up temp folders after a install with a hot cache and lockfile (`install-cache-and-lock` in the benchmarks)
| | before | after |
|--|--|--|
| Nextjs benchmark | 326ms | 25ms |
| Gatsby benchmark | 654ms | 20ms |
| Typescript Website | 846ms | 44ms |
Benchmark workflow result:
Before: https://github.com/yarnpkg/berry/actions/runs/200276519
After: https://github.com/yarnpkg/berry/actions/runs/200408519
**Checklist**
> perf(cli): perform async temp cleanup

- .pnp.js
- .yarn/versions/88e02473.yml
- packages/plugin-essentials/package.json
- packages/plugin-essentials/sources/commands/install.ts
- yarn.lock
Travis CI is calling `yarn --frozen-lockfile` by default and that behaviour cannot be overriden (as far as I know).
When bumping from Yarn to Berry it make builds crash at start-up on Travis.
This [PR](https://github.com/dubzzz/fast-check/pull/867) shows that Travis can be detected by using the check `!!process.env.TRAVIS && !!process.env.CI`.
Associated Travis build can be seen here: https://travis-ci.com/github/dubzzz/fast-check/builds/179306747 (by the way you can see that this job automatically calls `yarn --frozen-lockfile`)
And uses the following Travis configuration file: https://github.com/dubzzz/fast-check/blob/fa7e754eb5e4c4e348e8813469dbd964a9d70610/.travis.yml
I changed the error into a warning for Travis CI as …
> Mark `--frozen-lockfile` as a warning in Travis CI

- .github/workflows/e2e-storybook-workflow.yml
- README.md
- packages/gatsby/content/features/plugnplay.md
**Description**
[Storybook](https://github.com/storybookjs/storybook) is a massively used tool in the frontend dev community and wasn't compatible with Berry (PnP mode) for now.  
As of Storybook 6.0, Berry will be supported out of the box for some frameworks (for instance React). 6.0 release will be out soon, in the next few weeks, so I created an e2e test workflow for it. I also added a badge for this workflow in `Current status > Tooling` section of the README.
Closes https://github.com/yarnpkg/berry/issues/592.
--
**Checklist**
> Add GH Actions workflow for Storybook

- .yarn/versions/92d834ce.yml
- packages/plugin-patch/sources/PatchFetcher.ts
Now that we've implemented support for read-after-write in `ZipFS` in #1675, there's no need for the extra `copiedPackage` `ZipFS` step inside the `PatchFetcher`. This is important, because we had to use `saveAndClose` to persist the copied package on disk, even when everything can actually be done in memory.
I've removed the extra `copiedPackage` and `saveAndClose` parts. This saves `11485.5 ms` of the fetch step when running `yarn install` on the `TypeScript-Website` repo with a cold cache. 
I really hope that the tests are passing, haven't checked yet 😄.
**Checklist**
> perf(plugin-patch): remove unneeded saveAndClose

- .yarn/versions/7baa37a5.yml
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/suggestUtils.ts
`extractDescriptorFromPath` was fetching temporary `archive` archives using the project cache, which caused it to get polluted.
I've made `extractDescriptorFromPath` use a temporary cache.
**Checklist**
> fix(plugin-essentials): use temporary cache in extractDescriptorFromPath

- .yarn/versions/c0d3bd74.yml
- packages/yarnpkg-doctor/fixtures/peer-met-by-parent/package.json
- packages/yarnpkg-doctor/sources/cli.ts
`@yarnpkg/doctor` reports a missing peer dependency even if the parent is that dependency
Skip if the workspace identHash matches the peerDependency
**Checklist**
> fix(doctor): handle peer dependency met by parent

- .yarn/versions/c03daef8.yml
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
- packages/yarnpkg-pnpify/sources/hoist.ts
This PR fixes #1706. The nm hoister currently looses information when package peer depends on the parent package.
The hoister code was prematurely removing self-references from the tree. Now we keep self-references throughout hoisting process and remove them only when we build node_modules tree.
**Checklist**
> [node-modules] Fixes hoisting when package peer depends on parent itself

- .yarn/versions/f516d6b5.yml
- CHANGELOG.md
- packages/yarnpkg-parsers/sources/grammars/shell.d.ts
- packages/yarnpkg-parsers/sources/grammars/shell.js
- packages/yarnpkg-parsers/sources/grammars/shell.pegjs
- packages/yarnpkg-parsers/tests/shell.test.ts
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/tests/shell.test.ts
Grouping curly braces (`{echo foo} > bar.txt` - https://www.gnu.org/software/bash/manual/html_node/Command-Grouping.html#Command-Grouping) weren't supported by the portable shell.
I've implemented them mostly with ZSH's behavior in mind. They execute in the context of the current shell.
I've also made it possible to end a command with a semicolon.
I've also added tests.
**Checklist**
> feat(shell): grouping curly braces

- .yarn/versions/6f867693.yml
- packages/yarnpkg-doctor/sources/cli.ts
`@yarnpkg/doctor` is checking gitignored files, while technically correct it produces a lot of redundant missing dependency reports as it's reported for both the source and the build output
Enable the gitignore option in globby
**Checklist**
> fix(doctor): respect gitignore

- .yarn/versions/49b86066.yml
- packages/acceptance-tests/pkg-tests-specs/sources/dragon.test.js
- packages/yarnpkg-core/sources/Project.ts
Virtual descriptors with different base idents that resolve to the same virtual package (aka aliases) were incorrectly deduped out of existence.
Fixes #1352.
I've made it so that the `identHash` is taken into account when computing the `dependencyHash`.
I've added a dragon test for this edge case, and all of the other dragon tests are passing.
**Checklist**
> fix(core): don't dedupe virtual descriptors with different base idents resolved to the same virtual package

- .yarn/versions/b5d51e6a.yml
- packages/plugin-essentials/sources/commands/plugin/import.ts
The changes made to `updateConfiguration` (which now replaces rather than extend) broke the `yarn plugin import` command. As a result, running it would cause all other settings to be dropped from the file.
Just spread the previous fields and update the plugins.
**Checklist**
> Fixes `plugin import`

- .yarn/versions/35625539.yml
- CHANGELOG.md
- packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
- packages/plugin-pnp/sources/PnpLinker.ts
Using both pnp and node_modules linker in a single monorepo is not possible now, because pnp linker tries to remove node_modules. Example monorepo structure with the problem:
```
<pnp_monorepo_root>/
packages/
pnp-package/
...
nm-package/
.yarnrc.yml
yarn.lock
.yarnrc.yml
yarn.lock
```
PnP linker will remove node_modules inside `nm-package`, even though `nm-package` is meant to be managed by node-modules linker
PnP linker will not remove lingering node_modules if the folder matches `pnpIgnorePattern`
**Checklist**
> feat(pnp) Skip lingering node_modules removal inside pnpIgnorePatterns matched folders

- .yarn/versions/3210e9f1.yml
- packages/plugin-essentials/sources/commands/install.ts
Fixes errors thrown by Yarn 2 in process of deployment Node.js apps on GAE.
Closes #1719
Do not exit with an error when running `yarn install --non-interactive --frozen-lockfile` in GAE environment.
**Checklist**
- [x ] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
- [x ] I have set the packages that need to be released for my changes to be effective.
- [x ] I have verified that all automated PR checks pass.
> Fix deployment on Google App Engine (GAE)

- .yarn/versions/7fc37e0a.yml
- packages/plugin-npm/sources/NpmSemverResolver.ts
`NpmSemverResolver.getSatisfying` doesn't use the cached semver range because https://github.com/yarnpkg/berry/pull/1558 was merged 2 minutes after the semver range cached was merged
Make `NpmSemverResolver.getSatisfying` use `semverUtils.validRange` which caches the result
**Checklist**
> perf(plugin-npm): use cached range in NpmSemverResolver.getSatisfying

- .yarn/versions/244cf6e3.yml
- packages/yarnpkg-core/sources/semverUtils.ts
- packages/yarnpkg-core/tests/semverUtils.test.ts
`semverUtils.satisfiesWithPrereleases` had a bug that caused false positives with exact prerelease ranges (`1.2.3-beta.1` satisfied `1.2.3-beta.2`).
I've added the `includePrerelease` flag to semver, which *apparently* fixes this issue. I'm going to be honest and say that I have no idea why and what is going on there, but everything seems to work, so... good enough I guess?... ¯\\\_(ツ)_/¯
I've also added more tests to make sure that this doesn't break anything else.
**Checklist**
> fix(core): fix semverUtils.satisfiesWithPrereleases with exact ranges

- .yarn/versions/0c6da0b1.yml
- packages/yarnpkg-core/sources/execUtils.ts
I'm using `execvp` in a plugin to execute something in `$PATH`, but want to make that dependency optional. I tried catching `ENOENT`, but noticed that spawn errors in `execvp` are not handled at all, instead causing an unhandled promise rejection message.
Spawn errors now reject the `execvp` promise (similar to `pipevp`).
**Checklist**
> fix(core): handle execvp error event

- .yarn/versions/f939c5fd.yml
- CHANGELOG.md
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/tests/shell.test.ts
The shell wasn't respecting the left associativity of list operators, which caused commands like `inexistent && echo yes || echo no` to break the chain and exit with code `127` instead of triggering the next triggerable command in the chain.
Fixes #1694.
I've refactored the `executeCommandLine` function and made it loop through the entire chain instead of breaking it too early.
**Checklist**
> fix(shell): respect left associativity for list operators

- .yarn/versions/48a6394e.yml
- packages/yarnpkg-core/sources/Plugin.ts
- packages/yarnpkg-core/sources/Project.ts
Currently, [my Nix plugin](https://github.com/stephank/yarn-plugin-nixify) is a separate command `yarn nixify` that generates some files, but ideally it would just keep these up-to-date almost like a lockfile. I want to use `afterAllInstalled` to keep these files up-to-date, but believe I should only do this sort of thing if `persistProject` is set. I currently can't get at that flag from within the hook, it seems.
I added a second parameter to `afterAllInstalled` with the `InstallOptions`.
~~I'm not sure if just a patch release of core is enough. Nothing inside Yarn itself uses the hook, but I'm not sure if other packages need a release for the release bundle to be updated, eventually.~~
I couldn't finish the test suite …
> feat(core): pass options to afterAllInstalled

- constraints.pro
`detail` is referenced as a command but does not exist on any direct google search nor documentation.
...
```diff
% This file is written in Prolog
% It contains rules that the project must respect.
- % In order to see them in action, run `yarn constraints detail`
```
...
**Checklist**
> removes nonexistent command reference

- .yarn/versions/2b28b2f0.yml
- packages/plugin-constraints/sources/commands/constraints.ts
- packages/yarnpkg-core/sources/Manifest.ts
`yarn constraints --fix` doesn't persist changes when modifying manifest fields that are parsed by `Manifest.load`
https://github.com/yarnpkg/berry/blob/9a1ec1ab8d670f5913a3b91fc51c3af3ac0e981a/packages/yarnpkg-core/sources/Manifest.ts#L41-L74
The reason for this is that the fixes are applied to `Manifest.raw` but `Manifest.exportTo` overwrites the raw data with the parsed data so the changes are lost.
Reload the manifest from `manifest.raw` before persisting.
**Checklist**
> fix(plugin-constraints): update manifest before persisting

- .yarn/versions/52a1a172.yml
- packages/yarnpkg-core/sources/TelemetryManager.ts
There's one telemetry-related codepath that isn't properly wrapped inside a try/catch and may cause commands to fail when the `.yarn` folder is read-only. Since telemetry isn't a critical component, it shouldn't affect the experience in any way.
Write the file access inside a try/catch and ignore any error within it.
Fixes #1780 1780
**Checklist**
> Prevents telemetry from crashing on low access perms

- .yarn/versions/082ad24b.yml
- packages/yarnpkg-libzip/sources/async.ts
The browser version of `getLibzipPromise` isn't returning anything
Add a missing return statement
**Checklist**
> fix(libzip): return libzip from getLibzipPromise in browser version

- .yarn/versions/52ee9b6e.yml
- packages/plugin-git/sources/__snapshots__/gitUtils.test.js.snap
- packages/plugin-git/sources/gitUtils.test.js
- packages/plugin-git/sources/gitUtils.ts
Fix resolving dependencies prefixed with git+ssh:// and colon after a hostname:
`git+ssh://git@github.com:yarnpkg/berry.git#v2.1.1`
Closes https://github.com/yarnpkg/berry/issues/1647
I remove `git+ssh://` prefix for dependencies prefixed with `git+ssh://` and only if they contain colon after a hostname
**Checklist**
> Fix resolving dependencies prefixed with git+ssh:// and colon after a hostname

- .yarn/versions/4654c182.yml
- package.json
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/tests/shell.test.ts
We support default variables, but only on the named variables codepath - not on positional variables (`$1` etc).
Added support for default variables to both codepaths.
**Checklist**
> Fixes the shell default variables

- .yarn/versions/2713be1e.yml
- packages/yarnpkg-pnpify/sources/hoist.ts
NM_DEBUG_LEVEL errorred out on unhoisted self-references
I check now if the package depends on itself and was not hoisted and do not try to output reason for this case, because it is obvious.
**Checklist**
> [node-modules] NM_DEBUG_LEVEL errorred out on unhoisted self-references

- .yarn/versions/399a3585.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
- packages/plugin-pack/sources/packUtils.ts
- packages/yarnpkg-core/sources/Manifest.ts
We didn't properly account for the `browser` field when it's a map.
Fixes #1794
Adds support for the map. The code is also more defensive now.
**Checklist**
> Fixes support for the browser field

- .yarn/versions/9df8808e.yml
- packages/plugin-npm/sources/npmHttpUtils.ts
This PR fixes 2 issues:
1) When reporting invalid authentication errors, the `as` part reported `as undefined` because the response wasn't JSON.
2) 403 Forbidden was treated as invalid authentication, even though the npm registry uses it for prohibited actions, such as publishing a package with a name too similar to an exisiting package.
This PR helps people experiencing #1641 see what the actual cause is. (I'll only close that issue once it's confirmed that the remaining problems aren't on our side).
1) The whoami response is now JSON.
2) 403 isn't treated as invalid authentication anymore, which will make Yarn show the actual error message.
**Checklist**
> fix: don't report 403 as invalid authentication

- packages/acceptance-tests/pkg-tests-specs/sources/features/mergeConflictResolution.test.js
```
● Features › Merge Conflict Resolution › it should properly fix merge conflicts when old is Yarn 1 and new is Yarn 2
Temporary fixture folder: /tmp/xfs-8b0b32e9
expect(received).rejects.toThrow(expected)
Expected pattern: /CONFLICT/
Received message: "Command failed: git merge yarn2··
===== stdout:·
```
<Localized message>
```·
===== stderr:·
```
```·
"
99 |           await execFile(`git`, [`merge`, `2.0.0`], {cwd: path});
100 | 
> 101 |           await expect(execFile(`git`, [`merge`, `yarn2`], {cwd: path})).rejects.toThrow(/CONFLICT/);
|                                                                                  ^
102 | 
103 |           let lockfile = await readFile(`${path}/yarn.lock`, `utf8`);
104 |           lockfile = …
```
> test: set LC_ALL=C in `git merge` calls

- .pnp.js
- .yarn/versions/0f798784.yml
- packages/yarnpkg-shell/package.json
- packages/yarnpkg-shell/sources/globUtils.ts
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/tests/shell.test.ts
- yarn.lock
Arguments containing glob patterns weren't correctly interpolated because we were resolving each glob segment individually, instead of resolving the entire interpolated argument.
This meant that `echo $DIR/*` didn't work (I mean, ~~it worked because `*` matched `$DIR` instead of matching its contents, but that was incorrect~~ Edit: Actually it didn't, because `onlyFiles` was set to true.).
I've fixed this by resolving the entire interpolated argument. Glob patterns can currently be interpolated with variables and arithmetics, ~~but not with subshells because of a bug in the parser that causes `)/*` to be considered a valid glob pattern (well, it is a valid glob pattern in general, but not inside the shell). I'm not sure how …
> fix(shell): fix glob support

- .yarn/sdks/typescript/lib/tsserver.js
- .yarn/versions/e1155f85.yml
- packages/yarnpkg-pnpify/sources/sdks/base.ts
The typescript SDK stopped working due to changes in VSCode 1.48, see https://github.com/microsoft/vscode/issues/105014 for more
Fixes https://github.com/yarnpkg/berry/issues/1758
Fixes https://github.com/yarnpkg/berry/issues/1791
Fixes https://github.com/microsoft/vscode/issues/105014
Prefix the scheme with a caret
**Checklist**
> fix(pnpify): prefix zip protocol with a caret for VSCode 1.48

- .yarn/versions/a3cd4d4e.yml
- packages/plugin-essentials/sources/commands/up.ts
`yarn up` has several differences from `yarn upgrade` in Yarn 1. (#246)
Added documentation regarding difference between `yarn upgrade` and `up`
**Checklist**
> docs(plugin-essentials): document difference between `yarn upgrade` and `up`

- .yarn/versions/7fafd176.yml
- CHANGELOG.md
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
I have noticed that bin symlinks are not removed starting from 2.2.0 (they were properly removed in previous Yarn 2 versions)
The nm linker had written bin state to the top level locator, the algorithm to determine top level locator was path based and because of that fragile. Now we take top level locator directly from project.topLevelWorkspace instead. I have added integration tests to prevent future regressions.
**Checklist**
> [node_modules] Fixes regression - bin symlinks were not removed starting from 2.2.0

- .yarn/versions/7e3f7bba.yml
- packages/yarnpkg-pnpify/sources/hoist.ts
Looks like I have seriously broken NM_DEBUG_LEVEL=2 in cyclic peer dep hoisting PR
I have updated the code in various places to account that nodes that have hoisting answer DEPENDS might eventually switch to NO and the reasons should be kept in this case.
**Checklist**
> [node_modules] Fix NM_DEBUG_LEVEL=2 after cyclic peer dep hoisting changes

- .yarn/versions/dfb7d015.yml
- packages/yarnpkg-cli/sources/main.ts
When a script spawns Yarn using either `run`, `yarn`, `yarnpkg`, or `node-gyp`, that Yarn instance will spawn itself again. While this doesn't use much resources when the CLI is built it really slows down running commands in this repo.
Noticed while working on #1808
If the entrypoint of the current node instance is `yarnPath` avoid unnecessarily spawning of subprocesses
**Checklist**
> fix(cli): avoid unnecessary spawn when run directly

- .pnp.js
- .yarn/versions/fdf77815.yml
- .yarnrc.yml
- packages/plugin-compat/sources/extensions.ts
- yarn.lock
There are still a lot of packages that don't declare their dependencies correctly, we do our best to fix them upstream but sometimes it takes a long time for them to get merged, making everyone using these dependencies struggle to use PnP.
Added all the open PRs I have for adding missing dependencies to the builtin `packageExtensions`.
PRs included in this update
https://github.com/casesandberg/reactcss/pull/153
https://github.com/casesandberg/react-color/pull/746 (merged and tagged but not released)
https://github.com/angeloocana/gatsby-plugin-i18n/pull/145
https://github.com/3rd-Eden/useragent/pull/159
https://github.com/apollographql/apollo-tooling/pull/2049
https://github.com/mbrn/material-table/pull/2374 …
> chore(plugin-compat): update the builtin packageExtensions

- .yarn/versions/402ce7a1.yml
- packages/yarnpkg-cli/sources/boot-cli-dev.js
- packages/yarnpkg-core/sources/Configuration.ts
Inside our own repository we dynamically load the plugins and generate a runtime plugin configuration based on the repo state (whereas in the bundles we simply bundle up everything with a specific require function). While plugins are correctly exported this way, we forgot to do it for the regular dynamic libraries (for example the Yarn core). While it's not a problem in general because each plugin lists its dependency on the core anyway, it matters when using `yarn link` with external projects that use external plugins, since `yarn link` will provide the local (incomplete) module configuration.
Simply exposes the dynamic libs through the runtime configuration.
**Checklist**
> Fixes bootstraping for modules

- .yarn/versions/445c40cd.yml
- CHANGELOG.md
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
- packages/yarnpkg-pnpify/sources/hoist.ts
We know that dependencies relying on node_modules install strategy often have wrong assumptions about resulting node_modules layout. Because the idea of nm linker is to be as frictionless as possible we can adjust the preference for the packages we hoist to increase the probability that broken assumptions will work. 
In order to increase this probability we make hoisting to prefer in the order below:
1. Packages having the most peer dependents (thus we increase the accessibility of the most nodes from the top level to maximum)
2. Packages having the most dependents (to reduce number of duplicates)
**Checklist**
> [node_modules] Forgiving hoisting preference

- .yarn/versions/9ed95b15.yml
- packages/yarnpkg-core/sources/formatUtils.ts
`PortablePath` isn't formated as `NativePath` on Windows.
Originally fixed in https://github.com/yarnpkg/berry/pull/1361 but reverted by https://github.com/yarnpkg/berry/pull/1757
Add a formatter for `PortablePath`s
**Checklist**
> fix(core): format PortablePath as NativePath

- packages/gatsby/content/advanced/contributing.md
The contributing docs link to a page on package version management that no longer exists. ([Old link](https://yarnpkg.com/advanced/managing-releases))
Repoint the link [here](https://yarnpkg.com/features/release-workflow).
**Checklist**
> docs(contributing): fix link to release workflow docs

- .yarn/versions/df735296.yml
- CHANGELOG.md
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
- packages/plugin-node-modules/sources/PnpLooseLinker.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
Peer dependencies in workspaces are ignored by nm linker now.
I have implemented peer deps inheritance for nm linker from the closest workspace up in directory hierarchy
**Checklist**
> [node_modules] Inherit peer dependencies based on directory hierarchy

- .yarn/versions/822401f0.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/unplug.test.ts
- packages/plugin-essentials/sources/commands/remove.ts
- packages/plugin-essentials/sources/commands/up.ts
- packages/plugin-pnp/sources/commands/unplug.ts
- packages/yarnpkg-core/sources/formatUtils.ts
`yarn unplug` without `-AR` failed to find packages with peer dependencies because we were skipping virtual packages when we weren't supposed to. More details can be found on Discord: https://discordapp.com/channels/226791405589233664/654372321225605128/757931201364230184.
I removed the virtual package check inside the `traverse` implementation. I've also added an integration test.
**Checklist**
> fix(plugin-pnp): fix yarn unplug with packages with peer deps

- .yarn/versions/2e501780.yml
- packages/plugin-pack/sources/packUtils.ts
- packages/yarnpkg-core/sources/Cache.ts
- yarn.lock
We're currently packing archives by setting their mtime via a "second" timestamp, instead of a "millisecond" one. As a result, the files within the archive are outside the supported range for zip archives.
Properly multiplies the seconds before instantiating them via the `Date` constructor.
Fixes #1882
**Checklist**
> Fixes time typo in packUtils

- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/constraints.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints.test.js
The integration test for the `yarn constraints` command used snapshot testing, and the snapshot was bogus, because we were testing `yarn constraints check` (a non-existent command) instead of `yarn constraints`, which caused the snapshot to always contain `Unknown Syntax Error: Extraneous positional argument (\\"check\\").`
Per the request of @merceyz, I've cherrypicked the commit that fixes the test from #1883 and I will drop it from that PR once my PRs in Clipanion are merged and we update Clipanion.
**Checklist**
> test(integration): fix constraints test

- .yarn/versions/13d07961.yml
- packages/plugin-stage/sources/commands/stage.ts
- packages/plugin-stage/sources/drivers/GitDriver.ts
- packages/plugin-stage/sources/drivers/MercurialDriver.ts
Staging was not actually implemented in `plugin-stage`. Only `--commit` worked. Also `--reset` did not work because it was only iterating over *unstaged* changes, and was finding none.
* Implemented `makeStage` as a separate method in the driver. Needed to drop the `-N` argument from git for staging.
* Refactored `filterChanges` to add a parameter for whether to return staged or unstaged changes.
* Update where `--reset` is handled in order to work on the list of stashed changes.
* Instead of printing nothing, `yarn stage` will now print what would've been the commit message, if it was ran with `yarn stage --commit`
**Checklist**
> fix(plugin-stage): stage and unstage correctly

- .yarn/versions/871aaa79.yml
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/tests/Configuration.test.ts
Closes #779
Map configurations are now merged. The `overwrite` option defines the order in which the merge happens, i.e. with `overwrite: true` the newly loaded config overrules any previous config, otherwise existing configuration is kept.
I've opted for only merging maps because merging maps makes sense.
For shape configuration types it doesn't really make sense. What would the expected result be when merging
```yaml
npmScopes:
foo:
npmAuthIdent: someIdent==
```
into
```yaml
npmScopes:
foo:
npmAuthToken: a-token
```
?
The object would have both ident and token, so how do we decide which one to take?
What if the configs were turned around?
We could add a function on the `ShapeSettingsDefinition` type to perform this merge, …
> feat(core): merge map configuration properties

- .yarn/versions/13ac9863.yml
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
We have noticed the regression in nm linker with scoped workspaces support
The regression was due to scope being lost on locator assignment, now it is properly retained. Integration test is added to avoid regressions in the future.
**Checklist**
> [node_modules] Fixes scoped workspace support regression

- .yarn/versions/79a85249.yml
- packages/yarnpkg-core/sources/Configuration.ts
The Configuration isn't formatting the source when it finds a invalid config, which means it always prints a colourless `PortablePath`/string.
Use `formatUtils.pretty` to format the source as a path
**Checklist**
> fix(core): format source as path on invalid configuration item

- .yarn/versions/e92383f8.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/config/set.test.js
- packages/plugin-essentials/sources/commands/config/get.ts
- packages/plugin-essentials/sources/commands/config/set.ts
Setting deep configuration values sometimes logged undefined:
```
$ yarn config set "npmScopes.angular.npmAlwaysAuth" false
➤ YN0000: Successfully set npmScopes.angular.npmAlwaysAuth to undefined
$ yarn config set "npmScopes['angular'].npmAlwaysAuth" false
➤ YN0000: Successfully set npmScopes['angular'].npmAlwaysAuth to false
```
Consume the `.` in the path. This changes the path from `.angular.npmAlwaysAuth` to `angular.npmAlwaysAuth`, which matches what lodash.get expects.
I also added tests for `yarn config set`, and changed config get/set so these respsect the `enableColors` configuration value, which I needed to write the tests in set.test.js.
**Checklist**
> fix(plugin-essentials): correctly log deep properties getting set

- .yarn/versions/848713c4.yml
- packages/yarnpkg-pnpify/sources/commands/SdkCommand.ts
- packages/yarnpkg-pnpify/sources/generateSdk.ts
- packages/yarnpkg-pnpify/sources/sdks/base.ts
Using `--compat prettier,eslint`, the user can have the PnPify filesystem virtualization enabled in an SDK wrapper. This will allow users to get around packages (like `prettier`) that heavily rely on a `node_modules` file system layout to auto-load their plugins.
Fixes #1903
The template used for the wrapper, already has an argument to have the PnPify virtualization enabled. So far it appeares unused.
In the SDK generation path, I accept the same argument to have this virtualization enabled if requested from upstream.
I accept a new argument `--compat eslint,prettier,whatever` and when a base SDK name matches any of the given arguments, it will have the `usePnpify` option enabled.
**Checklist**
> fix(pnpify): Load prettier with in-memory node_modules enabled

- .github/workflows/e2e-nm-babel-workflow.yml
- .yarn/versions/8e1db223.yml
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
NM linker didn't take into account defaults for workspace peerDependencies, this was a regression.
https://github.com/babel/babel/pull/12134#issuecomment-702715343
CC: @nicolo-ribaudo 
The linker respects the defaults now.
**Checklist**
> [node_modules] Take into account peer dependency defaults when inheriting workspace peer dependencies

- .yarn/versions/d8eb7046.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/info.test.ts
- packages/plugin-essentials/sources/commands/info.ts
Info is currently inconsistent with how we want Yarn commands to behave: direct dependencies by default, other workspaces with `-A,--all`, and transitive dependencies with `-R,--recursive`.
Fixed the behaviour to follow the logic I mentioned.
**Checklist**
> Only iterates the first level of info by default

- .yarn/versions/ce4b8b98.yml
- packages/plugin-pack/sources/commands/pack.ts
`yarn pack` is printing the output path as a `PortablePath`
Set the format type to `PATH` instead of a hardcoded colour
**Checklist**
> fix(plugin-pack): format output path as a path

- .yarn/versions/bf5f5ec4.yml
- packages/yarnpkg-parsers/sources/grammars/shell.d.ts
- packages/yarnpkg-parsers/sources/grammars/shell.js
- packages/yarnpkg-parsers/sources/grammars/shell.pegjs
- packages/yarnpkg-parsers/tests/shell.test.ts
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/sources/pipe.ts
- packages/yarnpkg-shell/tests/shell.test.ts
`@yarnpkg/shell` didn't support redirection to file descriptors (e.g. `echo foo >& 2`). 
Fixes a part of https://github.com/yarnpkg/berry/issues/1901. (The other one is redirection from file descriptors - e.g. `{echo foo && inexistent} 1> stdout.log 2> stderr.log`)
I implemented support for redirection to file descriptors (only `0`, `1`, and `2` are currently emulated, custom ones can't be used yet).
**Checklist**
> feat(shell): implement redirection to file descriptors

- .yarn/versions/12e0d625.yml
- packages/yarnpkg-core/sources/LegacyMigrationResolver.ts
The `LegacyMigrationResolver` didn't support some patterns:
- GitHub Package Registry URLs (such as `https://npm.pkg.github.com/download/@datadog/build-plugin/0.3.2/92bb5d31f0463b9c175da48fcdbc5a6743ba65d9b337383c4a2deae2ad7dd531`), because they are very different from regular registry URLs. They are the ones the original issue is about.
- Git URLs starting with `git://` but not containing `.git` (such as `git://github.com/nash-io/react-input-range#7895c98aaadb0f115557efd17330e10da8b785c7`) - https://github.com/yarnpkg/berry/issues/902#issuecomment-588579962
- npm registry URLs that have additional components in their path preceding the `/pkgname/-/pkgname-0.0.2.tgz` part (such as `https://nexusrepomgr.$CORPORATION.com/repository/npm-proxy/yn/-/yn- …
> fix(core): improve legacy migration resolver patterns

- .yarn/versions/6e8fed5d.yml
- packages/vscode-zipfs/sources/ZipFSProvider.ts
The devtools in VSCode logs an error from the vscode-zipfs extension due to it's usage of `new Buffer`
Replace the use of the deprecated constructor with `Buffer.from`
**Checklist**
> fix(vscode-zipfs): use buffer.from instead of the deprecated constructor

- .yarn/versions/89e3c543.yml
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/tests/shell.test.ts
`@yarnpkg/shell` didn't support the ":" (colon) builtin - https://stackoverflow.com/questions/3224878/what-is-the-purpose-of-the-colon-gnu-bash-builtin
Fixes yet another part of #1901.
I implemented support for the ":" (colon) builtin as an alias for `true`.
**Checklist**
> feat(shell): support : (colon) builtin

- packages/gatsby/content/advanced/contributing.md
Incorrect url on contributing docs page.
Change the url to the correct one.
**Checklist**
> fix(docs): incorrect contributing link

- .yarn/versions/b0e1ca97.yml
- packages/acceptance-tests/pkg-tests-specs/sources/https.test.js
- packages/gatsby/src/pages/configuration/yarnrc.json
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/sources/httpUtils.ts
Fixes https://github.com/yarnpkg/berry/issues/798#issuecomment-705155101
Enables overriding the `caFilePath` per hostname. Example:
```yml
networkSettings:
"github.com":
caFilePath: <path>
caFilePath: <path>
```
Also updated the documentation and added additional tests.
**Checklist**
> feat(core): per hostname CA file support

- packages/gatsby/content/features/protocols.md
The workspace protocol was missing from the protocols docs. 
Added a line about the workspace protocol, and linked to the relevant content
...
**Checklist**
> Add workspace protocol doc to the protocols page

- .yarn/versions/969ac776.yml
- packages/plugin-pnp/sources/PnpLinker.ts
The uninstalled project error from the PnP linker doesn't format the path causing it to print `PortablePath`s on Windows
Format the path
**Checklist**
> fix(plugin-pnp): format path in uninstalled project error

- .yarn/versions/1bf94456.yml
- packages/plugin-compat/sources/extensions.ts
Adding new entries to `plugin-compat database` with the PRs I sent upstream.
> chore(plugin-compat): add extensions for react-bootstrap-table2-paginator and react-draggable

- .yarn/versions/e687f905.yml
- packages/acceptance-tests/pkg-tests-core/sources/utils/makeTemporaryEnv.ts
- packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
- packages/acceptance-tests/pkg-tests-specs/sources/commands/npm/__snapshots__/whoami.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/npm/whoami.test.js
- packages/plugin-npm-cli/sources/commands/npm/whoami.ts
`yarn npm whoami --scope <name>` doesn't work because it doesn't pass the scope to `npmHttpUtils`
Pass the specified scope to `npmHttpUtils`
**Checklist**
> fix(plugin-npm-cli): pass ident to whoami when scope is specified

- .yarn/versions/7f2f414b.yml
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
NM linker sometimes misdetects self-reference, when the package in question has multiple locators merged together. See issue:
https://github.com/facebook/create-react-app/issues/9765
In this issue `react-dom/node_modules/react-dom` is created with exactly the same contents. NM linker creates it, because react-dom are hoisted from two places and merged together, since all the constraints are met, as a result the react-dom has two locators.
I have came up with a more reliable check
**Checklist**
> [node_modules] Simpler self-references check

- packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
- packages/acceptance-tests/pkg-tests-specs/sources/__snapshots__/pnp.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
When I opened https://github.com/yarnpkg/berry/pull/1851 I didn't add a test
Fixes https://github.com/yarnpkg/berry/pull/1851#issuecomment-701386323
Added a test
**Checklist**
> test(pnp): pnpapi isn't lost on virtual path portals

- .yarn/versions/11383282.yml
- packages/plugin-essentials/sources/commands/plugin/import.ts
When importing a plugin by its filepath Yarn prints back that it's reading it as a PortablePath
Set the format type to `PATH`
**Checklist**
> fix(plugin-essentials): format plugin path in import

- packages/gatsby/content/features/release-workflow.md
I ran into some an issue when using `yarn version check` in GitHub actions, and it made sense to add some notes to the documentation to describe my solution.
I wrote a couple of paragraphs of documentation.
**Checklist**
> Update docs on version package to discuss GitHub Actions idiosyncracies.

- packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
Partially addresses #2002
Part of continuous effort to get rid of non-inclusive terms like "whitelist" and "blacklist" implying that white = good and black = bad.
Simple test rename.
**Checklist**
> refactor(acceptance-tests): change test name to mention "pnpIgnorePatterns" instead of "blacklist"

- packages/gatsby/src/components/details/Header.js
- packages/gatsby/src/components/hit/index.js
The TypeScript support icon on the package details page on the website didn't link to the DT entry when TypeScript support is `definitely-typed`.
With a keyboard.
**Checklist**
> docs: add DT link when TypeScript support is "definitely-typed"

- .yarn/versions/eedf13e1.yml
- CHANGELOG.md
- packages/yarnpkg-core/sources/Report.ts
- packages/yarnpkg-core/sources/StreamReport.ts
We render progress bar on each change now.
Fixes https://github.com/yarnpkg/berry/issues/1815
The rendering will be skipped now if the reported progress has no changes in the number of okay bars rendered on the screen.
**Checklist**
> perf(core): Optimize progress bar rerenders

- .yarn/versions/d341da35.yml
- packages/yarnpkg-core/sources/Cache.ts
The `.gitignore` file we write to `.yarn/cache` doesn't ignore the flock files we create
Added `.flock` to the list of ignored files
**Checklist**
> fix(core): ignore flock files in cache

- .yarn/versions/d1e66fa1.yml
- CHANGELOG.md
- packages/yarnpkg-shell/sources/errors.ts
- packages/yarnpkg-shell/sources/globUtils.ts
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/tests/shell.test.ts
The shell didn't have any concept of recoverable errors, which meant that commands like `echo inexistentFolder/* || true` were throwing instead of printing to stderr and continuing on to the next command in the chain.
Fixes #1984.
I've created a new `ShellError` class with a `recoverable` property. When executing a command chain, we now check if a recoverable error is thrown and we don't crash in that case - we instead print the error message to stderr and set the exit code to 1, so that we can continue on to the next command in the chain. I've also made a few more errors recoverable (`Bad file descriptor`, `Unbound {variable, argument}`).
**Checklist**
> fix(shell): make some errors recoverable

- .yarn/versions/cd65a831.yml
- packages/yarnpkg-core/sources/scriptUtils.ts
When installing a git repo without a lockfile as a dependency on Windows when you have a `package.json` and/or a `yarn.lock` in the home folder, the project root detection thinks `C:\Users\<username>\AppData\Local\Temp\xfs-12345678` is an undeclared workspace of `C:\Users\<username>` and refuses to pack it.
Fixes https://github.com/yarnpkg/berry/issues/2017
Write a empty `yarn.lock` before telling Yarn to pack the external project
**Checklist**
> fix(core): make lockfile if it's missing in prepareExternalProject

- .yarn/versions/a09d2933.yml
- packages/yarnpkg-doctor/sources/cli.ts
Signed-off-by: Reece Dunham <me@rdil.rocks>
This fixes the doctor package warning about pre/post scripts with a script named `prettier`, typically used for [Prettier](https://prettier.io).  It isn't a pre/post command, so it shouldn't warn about it.  
Just added a bit of extra regex.
...
**Checklist**
> [doctor] Don't warn about scripts named "prettier"

- .yarn/versions/a1d64a58.yml
- packages/plugin-version/sources/commands/version.ts
Cleans up unnecessary await when setting the releases map object.
...
...
**Checklist**
> fix(plugin-version): remove unnecessary await when setting map object

- .yarn/versions/134869e9.yml
- packages/plugin-workspace-tools/sources/commands/foreach.ts
The docs for `yarn workspaces foreach` documents the `--private` flag which makes it seem like it's not enabled by default, but it is.
ref https://github.com/yarnpkg/berry/issues/2034#issuecomment-715295553 (cc @vecerek)
Document the flag as `--no-private` and update the description which makes it clear that it's enabled by default
**Checklist**
> docs(plugin-workspace-tools): change --private to --no-private

- .pnp.js
- packages/gatsby/package.json
- packages/gatsby/tsconfig.json
- packages/gatsby/typedoc.js
- yarn.lock
I've introduced a new `tsconfig.json` file for the website in https://github.com/yarnpkg/berry/pull/1785, which caused TypeDoc to use the wrong `tsconfig.json` file when looking up which files to include, which caused the gatsby workspace to be included instead of the other ones.
I've made this change a few days ago and intended to do it in another PR, but since I have to postpone that PR, I've decided to open this PR with the change.
Fixes #2038.
We now pass the path to the root tsconfig inside the TypeDoc configuration options.
**Checklist**
> fix(gatsby/typedoc): use root tsconfig.json

- .yarn/versions/33c02888.yml
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
- packages/yarnpkg-core/sources/scriptUtils.ts
When using the `node-modules` linker and depending on any incompatible package with binaries, it's impossible to run unrelated binaries and scripts
Fixes https://github.com/yarnpkg/berry/issues/1891
Ignore locators that aren't installed when asking for them in `getPackageAccessibleBinaries`
**Checklist**
> fix(node-modules): allow running binaries and scripts while depending on an incompatible package with binaries

- .pnp.js
- .yarn/versions/9b987adf.yml
- packages/plugin-interactive-tools/package.json
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
- packages/yarnpkg-libui/package.json
- packages/yarnpkg-libui/sources/components/Gem.tsx
- packages/yarnpkg-libui/sources/components/ItemOptions.tsx
- packages/yarnpkg-libui/sources/components/Pad.tsx
- yarn.lock
The current baseline indicators use a simple underscore character pad. This can be improved by using a underline style over spaces.
Expands on #1980, #2029 
Instead of underscore characters, use space characters styled with `chalk.underline`
**Checklist**
> use chalk to emit smooth baseline text

- .yarn/versions/613aace9.yml
- packages/vscode-zipfs/package.json
If all `zip` files were excluded via the `search.exclude` setting in `.vscode/settings.json`, the extension would never activate.
This meant that `Mount as Zip` wouldn't do anything.
Added new activation events. Credits @merceyz: https://discordapp.com/channels/226791405589233664/226793713722982400/770640828438937620
**Checklist**
> fix(zipfs): allow extension activation via menu commands

- .yarn/versions/c8af9c56.yml
- packages/yarnpkg-core/sources/Manifest.ts
Packages can be published using backslash in their fields which breaks on non-Windows systems.
Fixes https://github.com/yarnpkg/berry/issues/2054
Replace backslash with slash in fields that can contain relative filepaths
**Checklist**
> fix(core): normalize relative filepaths in Manifest

- .yarn/versions/fb2c8f98.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/install.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
- packages/plugin-essentials/sources/commands/dedupe.ts
- packages/plugin-essentials/sources/commands/install.ts
- packages/plugin-essentials/sources/dedupeUtils.ts
- packages/plugin-essentials/sources/index.ts
- packages/plugin-pnp/sources/AbstractPnpInstaller.ts
- packages/yarnpkg-core/sources/Project.ts
Some third-party tools need to run installs but don't care about actually building the native packages (notably, bots like renovate). We don't support this well at the moment (setting `enableScripts` to false leads to different unplugged packages) and, while it could be hacked via the Linker API, since we're considering moving the build infra back into the core, it would make sense to provide this capability from the CLI.
Closes #2062 
A `--skip-builds` option will skip the build step but the packages will still be assumed to be unplugged.
**Checklist**
> Implements --skip-builds

- .yarn/versions/556f99e6.yml
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/tests/Configuration.test.ts
Log filters are defined as array, but arrays aren't merged in the configuration.
Make it possible to define arrays in the configuration that should get concatenated instead of replaced when multiple values are passed.
This implementations makes the assumption that either
- elements in the array overrule earlier elements (e.g. the case for `logFilters`), or that
- the order of elements in the array doesn't matter.
**Checklist**
> feat(core): merge multiple logFilter configurations

- .yarn/versions/db8a6d56.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/focus.test.js
- packages/plugin-workspace-tools/sources/commands/focus.ts
- packages/yarnpkg-core/sources/Project.ts
~unspecified workspaces were not removed from the project during focus install. Unspecified workspaces were kept inside `node_modules` and so, was accessible by others.~
This PR fixes the `yarn workspaces focus <workspace>` command. `postinstall` scripts from unfocus workspaces were executed.
We clear scripts from unfocused workspaces manifests.
**Checklist**
> fix(plugin-workspace-tools): Remove scripts from workspaces during focus

- .yarn/versions/574496f6.yml
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/commands/install.ts
- packages/plugin-essentials/sources/commands/remove.ts
- packages/yarnpkg-core/sources/Project.ts
I've noticed that the `restoreInstallState` call before installs (due to #2093) causes the lockfile data to be ignored (the install state overwrites the data structures). It's not clear under which situations this could cause a problem (hence no test), but it wasn't intended.
I improved `restoreInstallState` to allow to explicitly restore parts of the install state (unfortunately you currently opt-out; I'd prefer that to be opt-in, but it would be too much of a breaking change). I've also cleaned the typings around the install state to avoid desyncs.
**Checklist**
> Fixes how the lockfile interacts with installs

- .yarn/versions/c0cc9126.yml
- packages/plugin-pnp/sources/jsInstallUtils.ts
We always print the `scripts are disabled` warning, even when the packages don't actually have scripts 😅
Early return when needed.
**Checklist**
> Removes extraneous script warnings

- .yarn/versions/5badbc1c.yml
- packages/yarnpkg-core/sources/Project.ts
#2100 accidentally removed a few guards made to provide better error messages.
Adds them back. Note that HTTP errors still don't have the right prefix, probably because of Got doing some [magic](https://github.com/sindresorhus/got/blob/49c16ee54fb19ea7aa77e24ac8c2b602f0aad265/source/core/index.ts#L1187). I'll address that later by trying out Axios instead of Got.
**Checklist**
> Restores the catch details

- scripts/actions/local-yarn-command/entrypoint.sh
Fixes variable name in https://github.com/yarnpkg/berry/commit/2eb28cf6d0377a7986f56cc4a9b0da30c98a8ae5.
Since GitHub now shows an error if these commands are run and disabled updating `NODE_OPTIONS` environment variable, I've opened a pull request.
Fixed variable name
**Checklist**
> chore: fix variable name

- .yarn/versions/1c2724e7.yml
- packages/vscode-zipfs/package.json
Specifically, metadata for the vscode extensions manager
on the vscode extension marketplace, the extension doesn't list repo or homepage -- the repo field has a ssh remote, and that isn't parsed by the extension marketplace, and the extension page inside vscode doesn't navigate to this repo when opening up "repository" from its ui.
...
added "homepage" in vscode-zipfs's package.json
...
**Checklist**
> doc(vscode-zipfs): add homepage for vscode-zipfs

- .pnp.js
- .yarn/versions/0285726d.yml
- packages/plugin-compat/sources/extensions.ts
This peer dependency was fixed in [`apollo-upload-client@14.0.0`](https://github.com/jaydenseric/apollo-upload-client/commit/336691cec6698661ab404649e4e8435750255803), but `apollo-server` is depending on an old version of `graphql-tools` which depends on `apollo-upload-client@^13.0.0` (PR: https://github.com/apollographql/apollo-server/pull/4682), which means that a lot of people will probably have the Yarn v2 incompatible version of `apollo-upload-client` installed. This will resolve the issue automatically until the `apollo-server` PR is merged.
Added `apollo-upload-client` to `plugin-compat` package extensions, only if it's below v14.
**Checklist**
> Add apollo-upload-client <14 to package extensions

- .yarn/versions/8aa8cfef.yml
- packages/plugin-interactive-tools/README.md
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
Currently when running yarn upgrade-interactive it lists all installed packages and lazily displays new packages. When working on a project that has many dependencies (>20) this can get out of hand easily where you're scrolling for a while until you've "found" the first package with a new available version.
Fixes #1673 
...
To keep it simple since this is the first time I've attempted to make changes to the codebase, this looks for the presence of the new `--new-only` flag for `upgrade-interactive`, and renders a different component to the usual flow. On mounting the new component, all of the dependencies are checked for available updates. Any that don't return any update options are removed from the list to be displayed.
...
**Checklist**
> feat(upgrade-interactive): Only show packages with upgrades available

- .yarn/versions/7be5f20d.yml
- packages/yarnpkg-core/sources/scriptUtils.ts
The binaries created in `initializePackageEnvironment` and `executePackageAccessibleBinary` are created in serial which, with enough binaries, can cause noticeable slowdowns.
Create the binaries in parallel
**Checklist**
> perf(core): setup binaries in parallel for executing scripts

- .pnp.js
- .yarn/sdks/typescript/lib/tsserver.js
- .yarn/sdks/typescript/package.json
- .yarn/versions/f81f5c56.yml
- packages/acceptance-tests/pkg-tests-specs/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/features/editorSdks.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/features/editorSdks.utility.ts
- packages/yarnpkg-pnpify/sources/sdks/base.ts
- yarn.lock
Opening a virtual file in VSCode is 100% a disappointment. First you have more risks that something will go wrong (since it's difficult for them to work perfectly with file watcher mechanisms), but even in the best case it still takes an extra tab and looses the state of the real file. In most cases you end up closing the file and looking for the real one.
The SDK won't return virtual paths anymore to VSCode. It's slightly incorrect in that ctrl+click will lead to a file that *may* have different resolutions than what the virtual file would have had, but that seems an acceptable tradeoff compared to the overall IDE usability (especially when using workspaces w/ peer dependencies).
**Checklist**
> Hides virtuals from VSCode

- package.json
I've noticed that the @yarnpkg/parsers package doesn't contain type
definitions in `lib/grammars`[1], though they are present in the source
code.
This is because of the `rsync` command doesn't copy them to the `lib`
directory in `build:compile` script.
[1] https://cdn.jsdelivr.net/npm/@yarnpkg/parsers@2.3.0/lib/grammars/
`rsync` filter rules state[2]:
> As the list of files/directories to transfer is built, rsync checks
> each name to be transferred against the list of include/exclude
> patterns in turn, and the first matching pattern is acted on: if it is
> an exclude pattern, then that file is skipped; if it is an include
> pattern then that filename is not skipped; if no matching pattern is
> found, then the filename is …
> fix: include *.d.ts in published packages

- .yarn/versions/f8c9a277.yml
- packages/plugin-pack/sources/packUtils.ts
If the list of files passed to `packUtils.genPackStream` is anything but a file or symlink it would await a promise that would never resolve and since there was nothing left in the event loop node would terminate.
Reject the promise if the entry isn't a file nor a symlink and make `packUtils.genPackList` not add them to the list in the first place
**Checklist**
> fix(plugin-pack): avoid packing non file entries

- .yarn/versions/4a102be3.yml
- packages/yarnpkg-core/sources/LegacyMigrationResolver.ts
Importing Taobao registry patterns from v1 lockfiles wasn't supported because the regexp didn't match.
Updated the regexp to match both `/-/` and `/download/`.
**Checklist**
> fix(core): support importing taobao v1 lockfile patterns

- .yarn/versions/636369e8.yml
- .yarn/versions/fa98e249.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
- packages/yarnpkg-core/sources/Manifest.ts
Fixes #2166 
Set `manifest.files` to an empty Set even if the files array is empty.  This allows packUtils to recognize that a value was set, even though it was empty.
**Checklist**
> Allow an empty files array in package.json

- .yarn/versions/1c88d26a.yml
- packages/yarnpkg-cli/sources/main.ts
Node 14.0 and 14.1 have a bug in their stream implementation causing empty requests, we should warn about it to prevent issues getting opened here.
Closes https://github.com/yarnpkg/berry/issues/2151
Throw when the node version is detected as 14.0 or 14.1
**Checklist**
> chore(cli): throw on broken node 14 releases

- .yarn/versions/80f81cb1.yml
- packages/yarnpkg-pnpify/sources/commands/SdkCommand.ts
- packages/yarnpkg-pnpify/sources/dynamicRequire.ts
- Forgot to turn this one path into native again, from portable. Didn't get caught since the function accepts arbitrary strings (due to accepting bare identifiers).
- If run without a pnpapi already setup pnpify would fail to read files
- Turn the path into a NativePath.
- Call the `pnpapi`s `setup` function
**Checklist**
> fix(pnpify): turn portable path into native and setup fs patch

- .yarn/versions/7baa6423.yml
- packages/yarnpkg-core/sources/LegacyMigrationResolver.ts
v1 lockfile patterns without the https? protocol weren't supported.
Fixes https://github.com/yarnpkg/berry/issues/902#issuecomment-732360991.
I've added support for v1 lockfile patterns without the https? protocol as they aren't ambigous. I also had to tweak the regexp to allow extra segments between `/-/` and the tarball name.
**Checklist**
> fix(core): support v1 lockfile patterns without https? protocol

- .yarn/versions/f6398afe.yml
- packages/yarnpkg-core/sources/Configuration.ts
User-provided package extensions were registered before plugin-provided package extensions, which meant that user-provided extensions weren't reported as redundant when already declared inside a plugin.
I've made it so that user-provided package extensions are registered after plugin-provided ones.
**Checklist**
> fix(core): register user provided extensions after plugin provided ones

- .pnp.js
- .yarn/versions/24923973.yml
- .yarnrc.yml
- packages/plugin-compat/sources/extensions.ts
- yarn.lock
I have some extensions to add to the compat plugin most of which have been released already but there are still things that depend on old versions so they're added anyways to ease PnP migration.
Added them
**Checklist**
> chore(compat): update extensions list

- .pnp.js
- .yarn/versions/c7c7f820.yml
- packages/gatsby/static/configuration/yarnrc.json
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/sources/httpUtils.ts
- packages/yarnpkg-core/sources/miscUtils.ts
It's only possible to set a proxy for all traffic or no traffic.
Fixes https://github.com/yarnpkg/berry/issues/1531
Fixes https://github.com/yarnpkg/berry/issues/1530
Closes https://github.com/yarnpkg/berry/pull/2104
Added support for setting `httpProxy` and `httpsProxy` in network settings
**Checklist**
> feat(core): add support for httpProxy and httpsProxy in networkSettings

- .yarn/versions/6e262e49.yml
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/tests/shell.test.ts
Redirecting output to `/dev/null` on Windows would cause the shell to crash which meant that installing Yarn v1 using Yarn v2 wasn't possible on Windows.
Send all redirects to `/dev/null` to a writable stream that does nothing with the data
**Checklist**
> fix(shell): handle redirecting to /dev/null

- .yarn/versions/5bb5e685.yml
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
- packages/yarnpkg-libui/sources/components/ItemOptions.tsx
- packages/yarnpkg-libui/sources/components/Pad.tsx
When we don't have a range match, but we do have a latest match, show it in the correct column.
fixes #2200
...
In order to ensure we always display three columns of upgrade choices, we always provide three options. However, those that shouldn't be displayed as selectable options have an empty string for the label value. When choosing which ItemOptions should be keyboard selectable, we filter out those that don't have labels. This ties up with the fact that no label means a user can't see it to select it.
<strike>
**What is still broken?** 
Selecting the latest version in an intuitive manner. Consider the options presented for an upgrade with latest, but no range match:
```
[ { value: null, label: '3.9.0' }, {value: null, label: '' }, { value: '4.0.0', label: …
```
> fix: Display of latest and range matches

- .yarn/versions/d66325dd.yml
- CHANGELOG.md
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
Aliased packages now include themselves during node_modules installs, thanks to @non25 for finding the bug.
I have fixed the condition to detect self-references, actually simplified it and added the check into existing unit test.
**Checklist**
> [node_modules] Prevents aliased packages to include themselves

- packages/gatsby/src/components/json.tsx
- packages/gatsby/src/components/syml.tsx
- packages/gatsby/src/components/syntax.tsx
The elements of array properties inside the Manifest configuration page on the website got a bit scared of the `logFilters` introduced in https://github.com/yarnpkg/berry/pull/1907 and started breaking free:
By trapping them back inside the arrays.
**Checklist**
> docs(website): fix json syntax on the manifest configuration page

- packages/gatsby/static/configuration/yarnrc.json
`don't handle too well large amount of requests.`
to
`don't handle large amounts of requests very well.`
> docs: minor grammar improvement in documentation

- .yarn/versions/b749aab5.yml
- packages/plugin-version/sources/commands/version/check.tsx
The `useReleases` hook wasn't making a clone of the source map, so when we returned without doing any change the returned array was still the source map - and since we were cleaning it before injecting the new changes, previous decisions were completely erased.
Fixes #2231 
We now keep a copy of the original releases, and we don't mutate the original one until the program exits.
**Checklist**
> Fixes running yarn version check -i without changes

- .yarn/versions/651a3475.yml
- packages/plugin-compat/sources/extensions.ts
CRA hasn't merged https://github.com/facebook/create-react-app/pull/9872 yet, causing our tests to fail for two months.
I've added a forced peer dependency on React to CRA; I couldn't update `react-refresh` since package extensions can no longer override dependencies, but that should be enough for our tests.
**Checklist**
> Adds an extension for CRA

- .pnp.js
- .yarn/versions/871588f8.yml
- packages/yarnpkg-core/sources/Configuration.ts
I was scanning through this code and noticed two small issues:
- scopes on `Ident` are not prefixed with `@`, so we effectively added implicit peer dependencies for `@types/types__foo` if a package had a peer dependency on `@types/foo`
- the `peerDependenciesMeta` property on `Manifest` uses stringified idents as key, not the `IdentHash`. As `IdentHash` values are strings, typescript sadly didn't help here.
Removed the `@` and passed correct key to `Map#has`
**Checklist**
> fix(core): don't add implicit @types peer dependency if not needed

- .yarn/versions/f5ab92bd.yml
- packages/yarnpkg-core/sources/miscUtils.ts
Cache busting didn't properly work, which leads to problems e.g. when trying to execute things after an installation.
I've got a plugin that updates manifests, runs an installation and then runs a command (`ng update <package that was updated> --migrateOnly --from <previous version>`).
If the package providing that command (`@angular/cli`) got updated, the command fails with
```
➤ YN0000: ┌ Running migrations
➤ YN0000: │ Migrating @angular/cli from 11.0.3 to 11.0.4
➤ YN0001: │ UsageError: Couldn't find @angular/cli@npm:11.0.4 in the currently installed PnP map - running an install might help
at S.findPackageLocation (/redacted/.yarn/releases/yarn-2.4.0.cjs:2:265399)
at P (/redacted/.yarn/releases/yarn-2.4.0.cjs:2:428606)
at U …
```
> fix(core): use non-webpack require for cache busting

- .yarn/versions/9f429226.yml
- packages/plugin-init/sources/commands/init.ts
The example for `yarn init -i` was missing a equals sign
Closes https://github.com/yarnpkg/berry/issues/2248
Add the missing equals sign
**Checklist**
> docs(plugin-init): add missing equals sign to -i example

- .yarn/versions/273ab9b6.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/fix.test.js
- packages/plugin-constraints/sources/commands/constraints.ts
The change introduced in #1775 to fix fixing the field constraints
broke fixing dependency constraints, by overriding the changes made
to the manifest before persisting.
Fixes #2242
Dependency constraints work on the Manifest, field constraints work on the raw JSON object. Sync the two after every execution of the constraints to ensure every iteration uses the correct values.
**Checklist**
> fix(constraints): make constraints --fix persist changes to manifest

- .yarn/versions/19147bf1.yml
- packages/yarnpkg-core/sources/miscUtils.ts
`DefaultStream._flush` doesn't call the callback if the stream isn't empty which, because [node 15 waits for it](https://github.com/nodejs/node/pull/34314), causes the event loop to become empty and the process exits early during `workspaces foreach` calls
Note that the tests catch this when they run under node 15 but I can't enable it because of https://github.com/yarnpkg/berry/issues/2232
Always call the callback.
**Checklist**
> fix(core): always call callback in DefaultStream._flush

- .yarn/versions/ee6dfd28.yml
- packages/yarnpkg-builder/sources/commands/build/bundle.ts
When building from sources the hash `@yarnpkg/builder` adds to the version can start with zero (`0`) which is not valid semver
Fixes the failing tests in https://github.com/yarnpkg/berry/pull/2261
Prefix the hash segment with `hash-`
**Checklist**
> fix(builder): ensure version segment does not start with zero

- .yarn/versions/e3ed0187.yml
- packages/yarnpkg-cli/sources/main.ts
`node v14.10.0` introduce a regression into `streams` which was fixed in https://github.com/nodejs/node/commit/0f94c6b4e4. This causes an issue for `yarn install` which uses `streams` for fetching packages.
A modification to the `semver` string used by `yarnpkg-cli` was sufficient to address this (thanks @merceyz).
**Checklist**
-  [x] I have read the [Contributing Guide](https://yarnpkg.com/advanced/contributing).
> chore(cli): throw on broken node v14.10.0

- .yarn/versions/6e86083a.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/fix.test.js
- packages/yarnpkg-core/sources/Manifest.ts
As mentioned by @merceyz  in https://github.com/yarnpkg/berry/pull/2245#issuecomment-748990256, #1775 introduced another bug because `Manifest#load` unconditionally adds to the `workspaceDefinitions` array which leads to duplicate entries in workspaces (and only in workspaces AFAICT) when constraints are fixed.
Reset existing manifest properties during `Manifest#load`.
**Checklist**
> fix(core): reset existing properties in Manifest#load

- packages/acceptance-tests/pkg-tests-specs/sources/commands/stage.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/commands/version/check.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/features/mergeConflictResolution.test.js
Running all integration tests in the yarn repo asks for a gpg signature ± 10 times if git is configured to sign commits.
Fixes part of #2275
Configure tests that run git commands to not use gpg signatures on commits.
**Checklist**
> fix(acceptance-tests): disable gpg signing of commits

- .yarn/versions/98504c20.yml
- CHANGELOG.md
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
- packages/plugin-pnp/sources/PnpLinker.ts
- packages/yarnpkg-core/sources/CorePlugin.ts
- packages/yarnpkg-core/sources/structUtils.ts
`structUtils.requirableIdent` has been deprecated for a while and work on V3 has started
Removed it
**Checklist**
> refactor(core)!: remove deprecated structUtils.requirableIdent

- .yarn/versions/b339a0bb.yml
- packages/plugin-npm/sources/NpmSemverResolver.ts
- packages/yarnpkg-core/sources/semverUtils.ts
Closes https://github.com/yarnpkg/berry/issues/2224
This PR solves an issue with getting a different instance of semver in plugin-npm and in the core.
Complete details can be found in the mentioned issue.
...
Instead of using SemVer class from the semver package directly in plugin-npm, I explored the class from the semverUtils and use it from there.
...
**Checklist**
> fix(plugin-npm) use semver from semver utils

- .yarn/versions/e21be562.yml
- CHANGELOG.md
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/sources/types.ts
`PackageExtension['description']` was deprecated because it is identical to its alternative, `formatUtils.json(packageExtension, formatUtils.Type.PACKAGE_EXTENSION)`.
Removed it for the 3.x release.
**Checklist**
> refactor(core): remove deprecated PackageExtension['description']

- .yarn/versions/765b39b3.yml
- CHANGELOG.md
- packages/yarnpkg-core/sources/httpUtils.ts
`httpUtils.Options['json']` was deprecated because it is identical to its alternative, `httpUtils.Options['jsonResponse']`.
Removed it for the 3.x release.
**Checklist**
> refactor(core): remove deprecated httpUtils.Options['json']

- .yarn/versions/78cfdc45.yml
- CHANGELOG.md
- packages/yarnpkg-pnpify/sources/generateSdk.ts
The `@yarnpkg/pnpify` behavior that removed the old SDK folder (`.vscode/pnpify`) was deprecated.
Removed it for the 3.x release.
**Checklist**
> refactor(pnpify): remove old sdk folder removal

- .yarn/versions/53e3eb6b.yml
- CHANGELOG.md
- packages/plugin-workspace-tools/sources/commands/foreach.ts
The `-a` flag of `yarn workspaces foreach` was deprecated because it is identical to its alternatives, `-A,--all`.
Removed it for the 3.x release.
**Checklist**
> refactor(plugin-workspace-tools): remove legacy -a flag

- packages/gatsby/content/features/plugnplay.md
First of all, thanks for Yarn and Berry - amazing to have this tooling :)
The outdated PR https://github.com/microsoft/vscode-vsce/pull/379 has been superseded by https://github.com/microsoft/vscode-vsce/pull/493.
Updated the details
**Checklist**
> docs: fix vscode-vsce PR details

- packages/gatsby/gatsby-config.js
Links to the playground are treated as gatsby pages
Fixes https://github.com/yarnpkg/berry/issues/1714
Exclude the playground link as suggested in https://github.com/yarnpkg/berry/issues/1714#issuecomment-678811450
**Checklist**
> docs: fix links to playground

- .github/workflows/e2e-webpack-workflow.yml
Thread-loader got updated and doesn't support sass-loader anymore (https://github.com/webpack-contrib/thread-loader/pull/102#issuecomment-753965581).
Now using less-loader. I also cleaned a bit the file by splitting it into proper steps.
**Checklist**
> Fixes the Webpack CI

- .yarn/versions/dacba3b2.yml
- packages/yarnpkg-pnpify/sources/sdkUtils.ts
When PnPify was generating the SDKs, comments in arrays it updated weren't preserved because we were using spread + sets, which erased the comment information from the `CommentArray` instance generated by `cjson`.
By using manual iteration. I can confirm that comments are properly preserved now.
**Checklist**
> fix(pnpify): preserve comments in arrays

- .yarn/versions/3b907f33.yml
- packages/plugin-node-modules/sources/PnpLooseLinker.ts
- packages/plugin-pnp/sources/PnpLinker.ts
Using the loose mode with the node-modules linker used to crash because the loose mode was being executed outside of the regular PnP execution context.
Refactored the logic so that the loose mode is only executed when `nodeLinker` is set to `pnp`.
**Checklist**
> Fixes using loose mode with nm linker enabled

- .yarn/versions/2b06d4a7.yml
- packages/yarnpkg-core/sources/Project.ts
The logfile for stack overflows is deleted when the CLI terminates
Detach the temp folder containing the logfile to prevent it getting cleared on exit
**Checklist**
> fix(core): preserve stack overflow logfile

- .yarn/versions/52395a7b.yml
- packages/plugin-patch/sources/commands/patchCommit.ts
- packages/plugin-patch/sources/patchUtils.ts
Running `yarn patch-commit /path/to/generated/dir` returned without output nor generates any file when an incompatible `git` was present in the system.
The `diffFolders` function runs `git` and disregarded the return status `code` and `stderr`, which means it resolved with an empty value of `stdout`.
The default `git` that's included with OS X does not support one of the arguments passed to it. Example:
```sh
❯ git diff --src-prefix=a/ --dst-prefix=b/ --ignore-cr-at-eol --full-index --no-index /private/.../xfs-adf9c270 /private/.../xfs-e4548122
fatal: invalid diff option/value: --ignore-cr-at-eol
```
Berry thinks an empty string is the result of the diff, prints it to stdout and incorrectly returns status 0.
Closes #2331 …
> fix(plugin-patch): diffFolders returned silently when 'git' failed

- .yarn/versions/69ddbe20.yml
- packages/plugin-npm/sources/NpmSemverResolver.ts
- packages/yarnpkg-core/sources/semverUtils.ts
yarn install throws error:
`Invalid version: xxxx@xxxxx`
Context:
migrating an existing project to yarn 2 with private registry. some packages were released with arbitrary versions. leading to the yarn2 complains `invalid version`. but i think it's pretty common issue even in npm public registry packages. so, worth fixing in `plugin-npm`
...
As per https://github.com/npm/node-semver/blob/093b40f8a7cb67946527b739fe8f8974c888e2a0/internal/re.js#L94 npm package version can be arbitrary, so version like `1.2.3-alpha.00`, `1.0.0alpha1` etc... breaks the current logic. Maybe better to create SemVer in loose mode.
...
**Checklist**
> fix(plugin-npm): npm semver loose mode

- .yarn/versions/630f0472.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/config/unset.test.js
- packages/plugin-essentials/sources/commands/config/get.ts
- packages/plugin-essentials/sources/commands/config/unset.ts
- packages/plugin-essentials/sources/index.ts
There is currently no way to unset a config from the CLI
Add a `config unset` command
**Checklist**
> feat(plugin-essentials): config unset

- .yarn/versions/a3e39eeb.yml
- packages/plugin-essentials/sources/commands/config/unset.ts
fix typo for `yarn config unset`
Fixes https://github.com/yarnpkg/berry/pull/2337#discussion_r552643024
**Checklist**
> docs(plugin-essentials): correct config unset examples

- .yarn/versions/d883a19b.yml
- packages/yarnpkg-core/sources/formatUtils.ts
Context, this TS bug: https://github.com/microsoft/TypeScript/issues/35329
As a result, plugin authors can't use `formatUtils.pretty`, because everything gets inferred as `never`.
We can't use `const enum` because Babel doesn't support them. This diff thus fallback to a kind of "manual" implementation of enums, which should have the same public behaviour as the current one.
**Checklist**
> Turns Type into a const enum

- .yarn/versions/20529f15.yml
- packages/yarnpkg-core/sources/LegacyMigrationResolver.ts
Add another pattern to the Legacy Migration tool to support jfrog private registries.
Closes #2354
Added a separate pattern to target jfrog rather than update the generic npm rule. Modelled after https://github.com/yarnpkg/berry/pull/2164
**Checklist**
> fix(core): support jfrog in v1 lockfile migration tool

- .yarn/versions/78bcf3fc.yml
- packages/yarnpkg-pnpify/sources/sdks/cocvim.ts
The generated `.vim/coc-settings.json` sets relative filepaths to `.yarn/...`. The path is relative to the `coc.nvim` workspace root.
The appearance of files such as `package.json` at multiple levels in a monorepo setup causes `coc.nvim` to sometimes resolve to the incorrect workspace root and so `.yarn/...` is a broken path.
I added an option in neoclide/coc.nvim#2807 to always try and resolve the root from ~~right-to-left~~ left-to-right through the path, rather than checking the current working directory first.
I then set this option in the `cocvim` sdk, specifically in the `tsserver` section, as this was the integration that was failing.
**Checklist**
> fix(pnpify): added additional option to cocvim sdk

- README.md
The README links to the npm page for `@yarnpkg/cli` which is only used in the context of developing plugins. It doesn't correctly gauge popularity of yarn and may be misleading.
Updated it to point to the github page instead.
**Checklist**
> docs: update misleading link to cli

- .github/workflows/e2e-cra-workflow.yml
- .github/workflows/e2e-eslint-workflow.yml
- .github/workflows/e2e-fsevents-workflow.yml
- .github/workflows/e2e-gatsby-workflow.yml
- .github/workflows/e2e-husky-workflow.yml
- .github/workflows/e2e-jest-workflow.yml
- .github/workflows/e2e-mocha-workflow.yml
- .github/workflows/e2e-next-workflow.yml
- .github/workflows/e2e-nm-angular-workflow.yml
- .github/workflows/e2e-nm-babel-workflow.yml
- .github/workflows/e2e-nm-berry-workflow.yml
- .github/workflows/e2e-nyc-workflow.yml
- .github/workflows/e2e-pnpify-workflow.yml
- .github/workflows/e2e-prettier-workflow.yml
- .github/workflows/e2e-rollup-workflow.yml
- .github/workflows/e2e-snowpack-workflow.yml
- .github/workflows/e2e-storybook-workflow.yml
- .github/workflows/e2e-typescript-workflow.yml
- .github/workflows/e2e-vue-cli-workflow.yml
- .github/workflows/e2e-webpack-workflow.yml
- .github/workflows/integration-workflow.yml
- .github/workflows/plugin-compat-workflow.yml
- .github/workflows/sherlock-workflow.yml
- .yarn/versions/20cff2cf.yml
- CHANGELOG.md
- packages/yarnpkg-cli/sources/main.ts
Node 10 will reach its end of life in april; it's probably fine to remove it now, otherwise we'll be blocked with it for at least another year, and we currently use `got` which has fairly strict "last Node" requirements (so it's likely we would be blocked from further upgrades).
Removed 10.x from the matrix.
**Checklist**
> Removes Node 10 from the matrix

- packages/gatsby/content/features/protocols.md
Typo: "workpace"
I carefully placed my cursor before "work" and "pace" and pressed "s" key on my keyboard. I then moved my cursor past the now-fixed word "workspace", and removed one space so that the table columns would still be neatly aligned. 🧐 
**Checklist**
> docs: fix typo in protocols table

- packages/gatsby/static/configuration/yarnrc.json
Currently the link points to a non-existing page.
https://yarnpkg.com/telemetry/ - 404
However, there is a page about Telemetry, just under a different URL:
https://yarnpkg.com/advanced/telemetry/ - 200
Fixed link to point to /advanced/telemetry instead of /telemetry.
**Checklist**
> docs: fix link to Telemetry documentation

- .yarn/versions/ad9f0dd6.yml
- packages/plugin-compat/sources/extensions.ts
TestCafe won’t run with Yarn 2, because of missing dependencies that aren’t explicitly listed.
https://github.com/DevExpress/testcafe-legacy-api/pull/51
https://github.com/DevExpress/testcafe/pull/5872
I added the packages required by `testcafe` and `testcafe-legacy-api` to the `plugin-compat` database.
PRs have also been submitted to the TestCafe project.
**Checklist**
> chore(compat): add testcafe extensions

- .yarn/versions/511adc40.yml
- packages/acceptance-tests/pkg-tests-specs/sources/features/localMirror.test.js
- packages/yarnpkg-core/sources/Cache.ts
When populating the cache and/or mirror we call `mkdir` to create the folder(s) before writing every entry which is unnecessary as the cache folder is created during the setup though the folder for the mirror isn't.
Create the folder for the mirror in `setup` and remove the `mkdir` call from `writeFileWithLock`.
**Result**
Copying from the mirror to the local cache
```
Before
➤ YN0000: ┌ Fetch step
➤ YN0013: │ No packages were cached - 6157 packages had to be fetched
➤ YN0000: └ Completed in 12s 716ms
After
➤ YN0000: ┌ Fetch step
➤ YN0013: │ No packages were cached - 6157 packages had to be fetched
➤ YN0000: └ Completed in 11s 563ms
```
**Checklist**
> perf(core): only call mkdir for the cache and mirror once

- .yarn/versions/1b783d48.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/fix.test.js
- packages/plugin-constraints/sources/commands/constraints.ts
https://github.com/yarnpkg/berry/pull/2245 introduced a bug that causes fields in the manifest to be removed and have their order changed when fixing dependencies
Export the manifest to an empty object then assign it back to `manifest.raw`
**Checklist**
> fix(constraints): preserve manifest when fixing dependencies

- .yarn/versions/0eabfd97.yml
- packages/plugin-init/sources/commands/init.ts
The `.editorconfig` generated by `yarn init` has an extra `.` in the glob patten leading it to match filenames of the form `*..yml` instead of `*.yml`.
Removed the extra `.`.
**Checklist**
> fix(plugin-init): update editorconfig to match yml correctly

- .yarn/versions/7c6e77ff.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/constraints.test.js.snap
- packages/plugin-constraints/sources/commands/constraints.ts
Using constraints to enforce that a field shouldn't exist prints a message with the expected value (`null`) instead of the current value
Print the current value
**Checklist**
> fix(constraints): print the current value on extraneous fields

- .yarn/versions/10571222.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/constraints.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints.test.js
- packages/gatsby/content/features/constraints.md
- packages/plugin-constraints/sources/Constraints.ts
- packages/plugin-constraints/sources/commands/constraints.ts
Using constraints to enforce that all workspaces depend on the same version of a dependency and that some workspace can't depend on a dependency reports them as conflicting instead of extraneous
If any of the expected ranges are null always treat it as extraneous
**Checklist**
> fix(constraints): always treat an expected null range as extraneous

- .yarn/versions/52b83537.yml
- packages/yarnpkg-fslib/sources/xfs.ts
- packages/yarnpkg-fslib/tests/xfs.test.ts
Fixes #2420
Return the real path, as is already the case in `mktempPromise`.
**Checklist**
> fix(fslib): return real path in mktempSync

- .yarn/versions/0f833eb2.yml
- packages/acceptance-tests/pkg-tests-specs/sources/script.test.js
- packages/gatsby/content/advanced/lifecycle-scripts.md
- packages/plugin-essentials/sources/commands/exec.ts
- packages/plugin-exec/sources/ExecFetcher.ts
- packages/yarnpkg-core/sources/scriptUtils.ts
The `$npm_package_name` and `$npm_package_version` variables weren't exposed in order to prevent the explosion of variables we would need to put in the environment, and avoid ambiguities when a package wouldn't list them and would accidentally "inherit" those from other scripts.
After more consideration, I think it's reasonable to add those two since every package will have them, so there's no ambiguity issue.
Fixes #1659
Added the relevant environment variables, plus documentation, plus test.
**Checklist**
> Adds npm_package_name

- .yarn/versions/73183f84.yml
- packages/plugin-essentials/sources/commands/up.ts
A last minute change broke `yarn up -R` due to improper CLI validation when the `-R` flag was set.
Fixed the validation.
**Checklist**
> Fixes yarn up -R

- .yarn/versions/21795af1.yml
- CHANGELOG.md
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
- packages/yarnpkg-pnpify/sources/hoist.ts
- packages/yarnpkg-pnpify/tests/hoist.test.ts
Fixes issue:
https://github.com/babel/babel/pull/12583#discussion_r553391274
The issue happens because the dependency graph was not fully hoisted, which resulted in an unlucky situation when the place was temporary occupied in a single workspace by conflicting versions of the same dependency.
The simplified example of a dependency graph requiring multiple hoisting passes is below:
```
. -> A -> D@X -> F@X -> E@X -> B@Y -> C@Z
-> C@X
-> C@Z
-> C@X      
-> B@X
-> C@Z
-> D@Y
-> E@Y
-> F@Y
```
We try to hoist everything we can to the `.` node first, we cannot hoist anything
Then we try to hoist everything we can to `A` (`C@Z` has a priority, because its more popular), we have
```
. -> A -> D@X -> C@X
-> F@X
-> E@X -> C@X
-> …
```
> [node-modules] Support reducing trees requiring multiple hoisting passes to a terminal result 

- scripts/bench-run.sh
The benchmark suite is running one of the old benchmarks which has its output overwritten by the next benchmark in the list meaning its data isn't used.
Removed the old benchmark
**Checklist**
> ci: avoid running old benchmark

- packages/gatsby/content/features/plugnplay.md
At the moment Pulumi is incompatible with yarn PnP.
Added an entry to the compatibility list.
**Checklist**
> Add Pulumi to incompatible PnP packages

- .github/workflows/e2e-vue-cli-workflow.yml
The Vue CLI E2E test [loves](https://github.com/yarnpkg/berry/runs/1867663657?check_suite_focus=true#step:5:51) [to](https://github.com/yarnpkg/berry/runs/1866168981?check_suite_focus=true#step:5:51) [randomly](https://github.com/yarnpkg/berry/runs/1811994939?check_suite_focus=true#step:5:51) [fail](https://github.com/yarnpkg/berry/runs/1799884287?check_suite_focus=true#step:5:51) because when the network connection isn't that good it prompts the user whether they want to use the taobao registry, even on CI.
Set useTaobaoRegistry to false.
**Checklist**
> ci: set useTaobaoRegistry to false in vue e2e test
