yarnpkg/berry

- .pnp.js
- .yarnrc
- packages/plugin-pack/bin/@berry/plugin-pack.js
- packages/plugin-pack/package.json
- packages/plugin-pack/sources/commands/pack.ts
- packages/plugin-pack/sources/index.ts
- yarn.lock
Creates a dummy plugin for `yarn pack` command incl. help
Ref: #6
> Dummy plugin for yarn pack 

- packages/berry-core/sources/Manifest.ts
Adds the `files` field in Manifest API.
ref: #6
> Provides files field of manifest

- packages/berry-core/sources/Configuration.ts
The current require system was faulty and caused factories to be returned instead of the actual Node builtins (so `require("fs")` was returning a function that, when called, returned the actual `fs` module).
This diff changes the system to take such factories into account.
> Fixes builtin access for dynamically loaded plugins

- packages/berry-fslib/sources/ZipFS.ts
> Fix sqlite3 install (#41) 

- packages/plugin-essentials/sources/commands/policies/set-version.ts
The `yarn policies set-version` command was broken and the error messages were relatively unhelpful. This diff fixes the problem it had (it was writing the wrong path), gives more infos when it breaks (such as whether a rc would have matched), and implement `--list` to be able to see which Yarn releases are available in the first place.
> Fixes set-version

- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/config.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/config.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/check.test.js
- packages/berry-core/sources/Configuration.ts
- packages/berry-parsers/sources/syml.ts
- packages/plugin-essentials/sources/commands/config.ts
> Add SettingsType.SECRET

- .pnp.js
- packages/acceptance-tests/berry.setup.js
- packages/acceptance-tests/package.json
- packages/acceptance-tests/pkg-tests-core/package.json
- packages/acceptance-tests/pkg-tests-core/sources/utils/exec.ts
- packages/acceptance-tests/pkg-tests-core/sources/utils/fs.ts
- packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
- packages/acceptance-tests/pkg-tests-fixtures/index.js
- packages/acceptance-tests/pkg-tests-fixtures/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/commands/config.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/query.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/source.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/environments.js
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/query.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/source.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/commands/stage.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/pnpapi-v1.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/protocols/portals.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/require.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/script.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/workspace.test.js
- packages/plugin-constraints/sources/Constraints.ts
- packages/plugin-constraints/sources/commands/constraints/query.ts
- packages/plugin-constraints/sources/index.ts
- tsconfig.json
- yarn.lock
- Implement `constraints query <query>` (#32)
- Replace `fs-extra` with `@berry/fslib` in pkg-tests-core (as mentioned in https://github.com/yarnpkg/berry/pull/81#issuecomment-485180019)
> Introduce constraints query command

- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/config.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/check.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/query.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/features/peerDependenciesMeta.test.js
- packages/berry-core/sources/StreamReport.ts
- packages/gatsby/content/advanced/error-codes.md
I got feedback that it was a bit confusing and I agree. The BR is for "Berry", but it doesn't necessarily makes sense (should we change them for the v3? etc). Let's use YN for "Yarn" 🙂
> Renames BRxxxx into YNxxxx

- packages/acceptance-tests/pkg-tests-specs/sources/commands/add.test.js
- packages/berry-core/sources/structUtils.ts
- packages/berry-fslib/sources/FakeFS.ts
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/suggestUtils.ts
This diff adds support for `yarn add /foo/bar` and co.
Fixes #79
> Add path support to `yarn add`

- .editorconfig
- .vscode/extensions.json
As discussed in https://github.com/yarnpkg/berry/pull/95#discussion_r278727208
> Add editorconfig and recommend the official VS Code extension

- packages/acceptance-tests/pkg-tests-specs/sources/workspace.test.js
Counterpart of https://github.com/yarnpkg/yarn/pull/7214, courtesy of @benjie
> Fixes typo in a test

- .eslintrc.json
- packages/berry-core/sources/Configuration.ts
- packages/berry-core/sources/Project.ts
- packages/berry-pnpify/sources/NodePathResolver.ts
- packages/berry-pnpify/sources/PnPApiLoader.ts
- packages/berry-pnpify/sources/index.ts
- packages/berry-shell/sources/index.ts
- packages/berry-ui/sources/KeySequence.ts
- packages/plugin-essentials/sources/suggestUtils.ts
- packages/vscode-zipfs/sources/ZipFSProvider.ts
Linter will now fail when not using the correct 2-spaces indent.
> Add indent rule to eslint

- scripts/azure-run-tests.yml
Trying out `--runInBand`.
Things to look for:
- OSX tests to pass
- Time it takes
> Run integration tests in band

- packages/acceptance-tests/berry.setup.js
This is creating a file when I run the tests 🤔 I think it was left unintentionally.
> Remove remaining debug code

- packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
- packages/acceptance-tests/pkg-tests-fixtures/packages/@scoped__package-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/@scoped__package-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/@types__no-deps-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/@types__no-deps-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/@types__scoped__package/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/@types__scoped__package/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/plugins/plugin-typescript.test.js
Added a few tests for `plugin-typescript`.
Added a couple of packages fixtures:
- `@scoped/package`
- `@types/scoped__package`
- `@types/no-deps`
Not sure if `@scoped/package` is a good name 🤔, also not sure if it's okay that I'm piggybacking from `no-deps` and adding a `@types` for it.
> Adds tests for plugin-typescript

- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/config.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/config.test.js
- packages/berry-cli/sources/cli.ts
- packages/berry-core/sources/Configuration.ts
- packages/berry-core/sources/LightReport.ts
- packages/berry-core/sources/Report.ts
- packages/berry-core/sources/StreamReport.ts
- packages/berry-core/sources/ThrowReport.ts
- packages/plugin-constraints/sources/commands/constraints/fix.ts
- packages/plugin-dlx/sources/commands/dlx.ts
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/commands/config.ts
- packages/plugin-essentials/sources/commands/up.ts
- packages/plugin-essentials/sources/suggestUtils.ts
- packages/plugin-pack/bin/@berry/plugin-pack.js
- packages/plugin-typescript/bin/@berry/plugin-typescript.js
- packages/plugin-typescript/sources/index.ts
When working on my sides I spotted various things that annoyed me so I fixed them 🙂
> Various fixes

- packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/config.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/config.test.js
- packages/berry-core/sources/Configuration.ts
- packages/berry-core/sources/folderUtils.ts
- packages/berry-core/sources/index.ts
Closes https://github.com/yarnpkg/berry/issues/80
TODO:
> Read config from home folder

- .pnp.js
- .vscode/settings.json
- packages/acceptance-tests/berry.setup.js
- packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
- packages/acceptance-tests/pkg-tests-specs/sources/plugins/__snapshots__/plugin-npm-cli.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/plugins/plugin-npm-cli.test.js
- packages/berry-core/sources/Configuration.ts
- packages/plugin-npm-cli/package.json
- packages/plugin-npm-cli/sources/commands/npm/login.ts
- packages/plugin-npm-cli/sources/commands/npm/publish.ts
- packages/plugin-npm-cli/sources/commands/npm/whoami.ts
- packages/plugin-npm-cli/sources/index.ts
- packages/plugin-npm/package.json
- packages/plugin-npm/sources/npmConfigUtils.ts
- packages/plugin-npm/sources/npmHttpUtils.ts
- yarn.lock
Adds `yarn npm login` command with optional `--registry`.
TODO:
@arcanis I'm having a little trouble figuring out how to test this without mocking `inquirer`. Not sure how to write to `stdin` on `run`.
> Adds npm login command

- packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
- packages/gatsby/content/features/workspaces.md
- packages/plugin-pack/sources/index.ts
> Replace workspace: with a version number at package time

- packages/acceptance-tests/pkg-tests-specs/sources/commands/stage.test.js
- packages/berry-core/sources/Manifest.ts
- packages/berry-core/sources/execUtils.ts
- packages/plugin-stage/sources/commands/stage.ts
- packages/plugin-stage/sources/drivers/GitDriver.ts
- packages/plugin-stage/sources/drivers/MercurialDriver.ts
- packages/plugin-stage/sources/stageUtils.ts
implemented https://github.com/yarnpkg/berry/issues/75
> improve `yarn stage -c` messages

- packages/berry-core/sources/Configuration.ts
The Docker image for Node exposes the Yarn version through `YARN_VERSION`. Due to the configuration injection mechanism, Berry refuses to execute properly.
This diff simply ignores `YARN_VERSION` when loading the configuration settings from the environment.
> Fixes Berry usage on Docker

- README.md
- ~Fixes issue @arcanis and I talked about [here](https://github.com/yarnpkg/berry/issues/172#issuecomment-493013348)~
- Adds small bit about running the CLI ( it wasn't immediately intuitive to me ) after building
> Special case version

- .pnp.js
- .yarn/virtual/@berry-pnpify-virtual-4360deae1e446a1bbda907566d928a7f59cf80b6b0f4cffd92c49c13d113c2d0
- .yarn/virtual/@berry-pnpify-virtual-5dc4321d4efc80e9fe6908fb4bef694ac4c7360a4ddbe90c61517bd499e08dc5
- .yarn/virtual/@berry-pnpify-virtual-b9837795e64e120904d27e33de49c0b8e803ec181240c7f81e821b522b4b72dd
- .yarn/virtual/@berry-pnpify-virtual-bf720cc4a1ad6062ba6c0264067362e8d4e5e40f707b399f7174246aa0c135f8
- .yarn/virtual/@berry-pnpify-virtual-c2ebc1d8d4ce2c3f1f78762fce3ac1e1162c11de01383a6923a5bf98c376510a
- .yarn/virtual/@berry-pnpify-virtual-e1f9f8205713ba840c1eaa64a4fef8d662dff69a9d66f67fb7f0bc614c6a728a
- .yarn/virtual/@berry-pnpify-virtual-e473704238ca9e94dd23c55c23a35f3d933b0f3951240c94324158f62f085b4c
- .yarn/virtual/@berry-pnpify-virtual-ebda344aac3d4e2c5e1a7f09ca03a20b768b09c34c877988dc4728f1bbd588bc
- .yarn/virtual/@berry-pnpify-virtual-f1013090d7ec7f639986726ebb5dd6b6c3f0c9f49aa47a31bbe0cb197b7602dd
- .yarn/virtual/webpack-cli-virtual-284f4b5ce6694349254ed825bdabf3b55398b499f6fb10aacdaa193082ca411b
- .yarn/virtual/webpack-cli-virtual-332c4a3832b63887cbeb53c6bb3e114d4da8cd504b70eb0d066f400a8a1e5681
- .yarn/virtual/webpack-cli-virtual-51eb8de7d87f65b18055f02cb8f185a0b12114b6ec956be4b0077d5c01b3fe3f
- .yarn/virtual/webpack-cli-virtual-6d6e70ccb43fe2b17827abd8e132be4b1f1e4c8a6c9a0bc30202324bf1897126
- .yarn/virtual/webpack-cli-virtual-72375aa9899c1c32636eb7fafa8262d15250c63fb959e0e204a3454d879a78f5
- .yarn/virtual/webpack-cli-virtual-7be583bd6843a9e1a7202e53cca8cb997e90448df28eadac87591961b81d89a0
- .yarn/virtual/webpack-cli-virtual-c8d3c4ca8d75fc9d888af5efe91636cf89f0b2072502f5c6e83c4fda25cb5e49
- .yarn/virtual/webpack-cli-virtual-dea240f039eb7b92318c0976c55261f159779727e1527afa6da9816124116650
- .yarn/virtual/webpack-cli-virtual-f2e7bfa0803b14aa4ac8b3756fd7839312d896e9c2a0ccfa5f0b7ebc31b49c46
- packages/berry-pnpify/package.json
- packages/berry-pnpify/sources/generateSdk.ts
- yarn.lock
Now generating proper version number.
> Fix pnpify sdk version number

- packages/gatsby/content/features/zero-installs.md
Hey, just added a few grammar + spelling fixes to make it sound a bit more natural. Hope that's ok.
> Some small grammar and spelling fixes

- .gitattributes
Before:
After:
<details>
<summary>A complete breakdown of the files by type</summary>
```
74.69%  TypeScript
24.26%  JavaScript
0.45%   Shell
0.22%   Prolog
0.14%   Dockerfile
0.11%   HCL
0.09%   C
0.04%   CSS
HCL:
.github/main.workflow
JavaScript:
babel.config.js
jest.config.js
packages/acceptance-tests/berry.setup.js
packages/acceptance-tests/jest.config.js
packages/acceptance-tests/pkg-tests-core/sources/index.js
packages/acceptance-tests/pkg-tests-fixtures/default-index.js
packages/acceptance-tests/pkg-tests-fixtures/index.js
packages/acceptance-tests/pkg-tests-fixtures/packages/@types__scoped__package/index.js
packages/acceptance-tests/pkg-tests-fixtures/packages/one-deep1-dep-bins/index.js
packages/acceptance-tests/pkg-tests-specs/sources/auth.test.js …
```
> Add gitattributes to make github ignore js files built using webpack

- .pnp.js
- packages/berry-pnpify/lib/bin.js
- packages/berry-pnpify/lib/index.js
- packages/berry-pnpify/package.json
- packages/berry-pnpify/sources/bin.ts
- yarn.lock
Fixes the problem described in https://github.com/yarnpkg/berry/issues/235#issuecomment-504472664
Tested locally, it worked (on Windows). No idea why it didn't get catch by our tests, though 🤔
> Uses cross-spawn w/ PnPify

- packages/berry-core/sources/Configuration.ts
- packages/berry-core/sources/Report.ts
- packages/gatsby/content/advanced/error-codes.md
- packages/gatsby/gatsby-config.js
- packages/plugin-essentials/sources/commands/install.ts
Trying to make Netlify finally pass. Unfortunately I don't see a way without hardcoding some logic to make it more tolerant on their platform only (they enforce the `--cache-folder` flag with no way to prevent it 🤨).
Ref https://github.com/netlify/build-image/issues/319
> Workarounds netlify

- packages/gatsby/content/advanced/pnp-api.md
This documentation explains what is the PnP API, and how to use it.
> Adds documentation for pnpapi

- packages/berry-core/sources/structUtils.ts
- packages/plugin-essentials/sources/commands/why.ts
> Reimplements yarn why

- packages/gatsby/content/advanced/plugin-tutorial.md
This diff adds some basic documentation to write plugins.
> Adds initial documentation for plugins

- packages/plugin-essentials/sources/commands/plugin/dl.ts
Small fix for text cleanup as I was going through the CLI
> Minor grammar change on CLI output

- packages/berry-core/sources/YarnResolver.ts
@arcanis Does this look like the fix for what you mentioned in https://github.com/yarnpkg/berry/pull/297? I didn't see any test coverage of this functionality.
> Add support for git+ssh.

- packages/gatsby/content/advanced/plugin-tutorial.md
I think the original statement meant to drive the user to make the change in `.yarnrc.yml` so I updated accordingly.
> docs(plugins): fix target config file for plugins

- packages/gatsby/content/advanced/contributing.md
- packages/gatsby/content/advanced/error-codes.md
- packages/gatsby/content/advanced/lexicon.md
- packages/gatsby/content/advanced/plugin-tutorial.md
- packages/gatsby/content/advanced/pnp-api.md
- packages/gatsby/content/features/zero-installs.md
- packages/gatsby/src/components/markdown.js
This diff explains better how to contribute to the repository.
> Improves the contributing guide

- packages/plugin-essentials/sources/commands/cache/clean.ts
- packages/plugin-essentials/sources/commands/config.ts
- packages/plugin-essentials/sources/commands/workspaces/list.ts
- packages/plugin-pack/sources/commands/pack.ts
closes #308
I have documented/updated the `--json` flag for all the commands that use it.
> [CLI/DOCS] document the --json flag

- packages/gatsby/content/features/zero-installs.md
1st change stating Yarn explicitly is what I assumed you were referring to, as otherwise it confused me in my first read of future releases of what would actually get things to break...
> Minor language updates

- packages/plugin-essentials/sources/commands/remove.ts
- packages/plugin-essentials/sources/commands/up.ts
This diff adds an error when `yarn up` and `yarn remove` are used with packages that are nowhere to be found in the project.
> Improve up/remove feedback

- README.md
- packages/gatsby/content/features/plugins.md
Updates docs to new syntax from #323
> Use new plugin syntax in docs

- .github/workflows/e2e-eslint-workflow.yml
#368 - Adding one basic test for ESLint
> Adds an E2E test for ESLint

- .github/workflows/e2e-prettier-workflow.yml
#368 - Basic E2E for Prettier
Just modified eslint e2e workflow.
> E2E test for Prettier

- CHANGELOG.md
Ref: https://github.com/yarnpkg/berry/pull/385#discussion_r317196956
> docs(changelog): Add note about nested readmes and yarn pack

- .github/workflows/e2e-eslint-workflow.yml
- .github/workflows/e2e-jest-workflow.yml
- .github/workflows/e2e-mocha-workflow.yml
- .github/workflows/e2e-prettier-workflow.yml
- .github/workflows/e2e-typescript-workflow.yml
Adds an E2E test to cover TypeScript (or rather, `tsc` itself).
> Adds a typescript workflow

- README.md
Add mocha to status table in README
> Add mocha to status table in README

- packages/acceptance-tests/pkg-tests-specs/sources/commands/version/check.test.js
- packages/plugin-version/package.json
- packages/plugin-version/sources/commands/version/check.tsx
- packages/yarnpkg-cli/package.json
The current heuristic had some issues when merging back master into it (the master changes were reported as coming from the local PR instead of being ignored).
Switching from `git diff` to `git log` to get the list of changes made the trick, as per https://stackoverflow.com/a/39699006/880703.
> Better local change heuristic

- packages/gatsby/content/features/plugnplay.md
There are just a few spelling and grammar errors I saw on the Plug'n'Play page.
I have a spellchecker 🤙
> Spelling & Grammar fixes

- .github/workflows/e2e-next-workflow.yml
Implements an E2E workflow for Next.js.
> Adds the Next workflow

- packages/yarnpkg-pnpify/package.json
- packages/yarnpkg-pnpify/sources/cli.ts
> Adds the shebang to pnpify

- packages/gatsby/content/advanced/pnp-api.md
The PnP API documentation was missing some important parts.
More documentation 🙂
> Improves the PnP documentation

- docs/README.md
It's not very intuitive to find the location of the actual docs files since they aren't in the docs/ folder
...
Added this README to docs/
...
> Add README to docs folder

- README.md
Grammar fix on readme.md file
...
...
> Grammar fix on readme.md file

- packages/gatsby/src/pages/configuration/manifest.js
- packages/gatsby/src/pages/configuration/yarnrc.js
Fix some typos in documentation
> documentation improvements

- README.md
Commands example after plugin-constraints link was outdated
...
> [doc] plugin command is yarn constraints [--fix]

- .github/workflows/e2e-nyc-workflow.yml
- README.md
> Adds an E2E test for NYC

- packages/plugin-compat/package.json
- packages/plugin-constraints/package.json
- packages/plugin-dlx/package.json
- packages/plugin-essentials/package.json
- packages/plugin-exec/package.json
- packages/plugin-file/package.json
- packages/plugin-git/package.json
- packages/plugin-github/package.json
- packages/plugin-http/package.json
- packages/plugin-init/package.json
- packages/plugin-interactive-tools/package.json
- packages/plugin-link/package.json
- packages/plugin-npm-cli/package.json
- packages/plugin-npm/package.json
- packages/plugin-pack/package.json
- packages/plugin-patch/package.json
- packages/plugin-pnp/package.json
- packages/plugin-stage/package.json
- packages/plugin-typescript/package.json
- packages/plugin-version/package.json
- packages/plugin-workspace-tools/package.json
- packages/yarnpkg-builder/package.json
- packages/yarnpkg-check/package.json
- packages/yarnpkg-cli/package.json
- packages/yarnpkg-core/package.json
- packages/yarnpkg-core/sources/LegacyMigrationResolver.ts
I left a typo that broke a particular Git pattern (that isn't tested because we don't have the infra to test Git repositories through ssh).
> Fixes typo

- packages/gatsby/src/components/header.js
- packages/gatsby/src/pages/index.js
`light` is not a valid value for font-weight.
`lighter` is, but since the existing design has an invalid value, it will show as `normal`, and thus is likely what you are expecting to see. Changing to `lighter` now would be a change in the design.
> remove font-weight: light

- packages/gatsby/src/components/search/SearchBox.js
100 is an exceptionally thin value, and is hard to read.
Removed the font-weight, so it uses the default one
> placeholder font-weight: 100 -> normal

- packages/gatsby/gatsby-config.js
- packages/gatsby/src/components/header.js
This PR is probably going to be controversial, and personal, but I feel like this font is not helping the legibility of the text, and doesn't really fit with the rest of the design (which is more toned-down, default). 
Remove the font from the Google fonts prefetching list, as well as from the CSS
> remove Abel font

- .yarn/versions/9e794d06.yml
- packages/yarnpkg-core/sources/Project.ts
The logs path was difficult to find.
Colors will make it obvious and more consistent with other places where we print paths within logs.
> Adds colors to the logs when a build fails

- packages/gatsby/gatsby-node.js
- packages/gatsby/src/components/util.js
- packages/gatsby/src/pages/package.js
I haven't tried to run this on my machine yet, so let's make sure we wait for the deploy preview before merging.
fixes #694
Strategy comes from: https://github.com/yarnpkg/website/blob/8f2614827ac325c212d8dfa823d82bda897c9df0/js/src/package.js#L12-L20
> Remove question mark from details URLs

- _redirects
- packages/gatsby/static/_redirects
Once the new website will take over, the old link won't work anymore.
Playing with the `_redirects` file from Netlify.
> Adds redirects

- .yarn/versions/94cec4a3.yml
- packages/plugin-essentials/sources/commands/bin.ts
- packages/plugin-essentials/sources/commands/plugin/list.ts
https://github.com/yarnpkg/berry/issues/565#issuecomment-577416111
More `--json` flags.
> Adds more JSON flags

- packages/gatsby/content/getting-started/install.md
Don't want people to think that these are gone forever.
> Add note about installation methods

- packages/gatsby/content/features/plugnplay.md
Some lack of clarity in the plug-n-play description
Made some enhancements to grammar and wording. I think that I can still do some more cleanup to make the page better.
> Enhancements to plug-n-play feature description

- .yarn/versions/888efd53.yml
- packages/plugin-essentials/sources/suggestUtils.ts
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
- The `latest` tags weren't fetched
- The colors were a bit hard to parse
- The semver ranges weren't properly matched
- Ranges that didn't change could sometimes cause exceptions
Fixes #789, fixes #790
> Fixes upgrade-interactive

- packages/gatsby/content/features/plugnplay.md
These changes are not obviously wrong so much as non-idiomatic.
By correcting the phrasing to be more idiomatic.
> docs: fix typos

- packages/gatsby/content/features/plugnplay.md
> docs: fix wording

- README.md
typo in README.md
...
typo in README.md
...
> docs: typo in README.md

- packages/gatsby/src/pages/index.js
I believe "makes" fits the sentence better than "make".
Slightly funky sentence grammar.
Changed "make" to "makes"
> docs: fix grammar

- .yarn/versions/1644cb2b.yml
- packages/plugin-compat/sources/extensions.ts
The debug PR still didn't get merged. The extensions for `any-observable` was incorrect.
> Improves extensions

- packages/gatsby/content/advanced/error-codes.md
Fixes a minor typo in the YN0014 error code docs
> fix small typo in YN0014 docs

- .yarn/versions/e9df1d4a.yml
- packages/plugin-essentials/sources/commands/run.ts
Many people wonder [where is the yarn global gone](https://www.youtube.com/watch?v=JImcvtJzIK8).
Added a message with some alternatives.
> Adds a warning about 'yarn global'

- packages/gatsby/src/components/details/Aside.js
- packages/gatsby/src/components/details/index.js
before: 
in v1 the sidebar is after the readme, and I feel like that made more sense
The "files" tab floats left, so the sidebar needs to float right to make sense.
> fix(www): responsive issues on detail view

- README.md
This PR improves the README.
I fixed and improved the plugins section, I added more links, a `Migration` section, a `Contributing` section, and I ran the README through Grammarly.
> docs(readme): improve readme

- .yarn/versions/62a3d9ba.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/foreach.test.js
- packages/plugin-workspace-tools/bin/@yarnpkg/plugin-workspace-tools.js
- packages/plugin-workspace-tools/sources/commands/foreach.ts
#977 
...
Compute a global exit code and return it at the end.
...
> Fix workspace foreach exit code

- packages/gatsby/content/advanced/questions-and-answers.md
> Improves documentation

- packages/gatsby/content/features/release-workflow.md
> Fix minor typos

- packages/gatsby/content/advanced/error-codes.md
Add explanation for package _consumers_ as well as package authors, as discussed in #1068.
> Expand documentation for YN0002

- .yarn/versions/af4c199e.yml
- packages/gatsby/src/pages/configuration/yarnrc.json
- packages/plugin-constraints/sources/Constraints.ts
- packages/plugin-constraints/sources/index.ts
This PR closes #1072.
I added a ~~`constraintsFilename`~~ (Edit: `constraintsPath`) configuration option inside `@yarnpkg/plugin-constraints`.
> feat(constraints): add constraintsPath configuration option

- .github/workflows/integration-workflow.yml
We pinned Node to 13 a long time ago due to segfaults which have been fixed since then.
n/a
> Unpins Node 13

- .yarn/versions/9a40cac4.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/__snapshots__/foreach.test.js.snap
- packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/foreach.test.js
- packages/plugin-workspace-tools/sources/commands/foreach.ts
https://github.com/yarnpkg/berry/issues/1066
...
per discussion in https://github.com/yarnpkg/berry/pull/1140, fix the documentation instead.
...
> fix workspace foreach documentation and test case

- .github/workflows/e2e-husky-workflow.yml
It seems that changes on the GitHub Actions environments caused the Husky test to start failing.
We now enforce Husky to run even when under CIs.
> Forces execution on CI

- .yarn/versions/21de7e9a.yml
- .yarn/versions/48b625e7.yml
- packages/plugin-git/sources/__snapshots__/gitUtils.test.js.snap
- packages/plugin-git/sources/gitUtils.test.js
- packages/plugin-git/sources/gitUtils.ts
Support for `ssh://git@github.com...`
> Support ssh protocol

- packages/gatsby/src/components/header.js
The search bar has a fixed width, which causes issues on some resolutions.
The search bar will now shrink if needed.
> Fixes search flexbox

- .yarn/versions/66dca93d.yml
- packages/yarnpkg-fslib/sources/index.ts
Additional type export to allow downstream usage of fslib
...
Added export
...
> Export SymlinkType From fslib

- packages/gatsby/content/advanced/pnpify.md
Add the following paragraph in pnpify
> [gatsby] cross reference --sdk in pnpify

- packages/gatsby/content/advanced/sherlock.md
> docs(sherlock): add a note about plugins

- .github/PULL_REQUEST_TEMPLATE.md
- README.md
- packages/gatsby/content/advanced/contributing.md
- packages/gatsby/content/advanced/sherlock.md
- packages/gatsby/content/features/offline-cache.md
- packages/gatsby/content/features/plugnplay.md
- packages/gatsby/content/features/release-workflow.md
- packages/gatsby/src/components/json.js
- packages/gatsby/src/components/syml.js
- packages/gatsby/src/components/syntax.js
- packages/gatsby/src/pages/configuration/yarnrc.json
Small documentation changes that don't deserve their own PRs.
I changed a few things in the documentation.
I also added a very basic checklist to the PR template, to help people remember doing their chores. We can add more things to it if we see people forget about them.
> docs: small changes

- .yarn/versions/988a66bb.yml
- packages/plugin-workspace-tools/sources/commands/foreach.ts
> docs: fix typo (tological -> topological)

- packages/gatsby/static/_redirects
Package page responses with 404.
Compare these pages:
https://yarnpkg.com/package/webpack
https://deploy-preview-1396--yarn2.netlify.app/package/webpack
Closes #803
...
Just added rewrite for netlify. Is it suitable for yarnpkg.com?
**Checklist**
> add rewrite for /package/*

- .github/workflows/e2e-parcel-workflow.yml
- .yarn/versions/bd0a5b02.yml
- README.md
- packages/gatsby/content/features/plugnplay.md
- packages/yarnpkg-cli/sources/boot-cli-dev.js
- packages/yarnpkg-core/sources/scriptUtils.ts
- scripts/e2e-setup-ci.sh
This PR adds a new E2E test for `parcel@2`, since they've finally got PnP support thanks to @arcanis 🎉.
I added an E2E test for Parcel, containing various cases. I haven't tested it yet, so don't expect it to work on the first try :P.
**Checklist**
> ci(e2e): add e2e test for parcel

- .yarn/versions/888cd2fe.yml
- packages/plugin-essentials/sources/commands/plugin/import.ts
- packages/plugin-essentials/sources/commands/plugin/import/sources.ts
- packages/plugin-essentials/sources/commands/set/version/sources.ts
- packages/plugin-essentials/sources/index.ts
- packages/yarnpkg-builder/sources/commands/build/plugin.ts
Follow-up to the unfortunate failure in #1375.
I implemented the suggestion @arcanis gave me in his first comment.
Closes #1013.
https://github.com/yarnpkg/berry/pull/1375#issuecomment-631377463
> feat: minified plugins and yarn plugin import from sources

- .github/workflows/e2e-parcel-workflow.yml
- .github/workflows/e2e-rollup-workflow.yml
- README.md
This PR addresses the feedback in https://github.com/yarnpkg/berry/pull/1399#issuecomment-633601570.
I improved the Parcel E2E test.
**Checklist**
> ci(e2e-parcel): improve parcel test

- .yarn/versions/02af6d8d.yml
- packages/plugin-essentials/sources/commands/run.ts
Resolves #1436 #1358 
...
Handle both boolean and string type for --inspect and --inspect-brk
...
**Checklist**
> support --inspect and --inspect-brk string variants

- .yarn/versions/dc0b5ca7.yml
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
- packages/yarnpkg-pnpify/sources/hoist.ts
- packages/yarnpkg-pnpify/tests/hoist.test.ts
This PR fixes issue: #1311 
Current algorithm in `master` does not take into account depth of the hoisted node and because of that it performs a lot of unnecessary work.
This implementation radically reduces memory consumption by hoisting shallowest nodes first. 
**Checklist**
> [node_modules] Hoisting memory efficiency improvement

- .yarn/versions/3d49b43f.yml
- packages/yarnpkg-pnpify/sources/generateSdk.ts
- packages/yarnpkg-pnpify/sources/sdks/base.ts
- packages/yarnpkg-pnpify/sources/sdks/vscode.ts
This PR adds `svelte-language-server` to the supported SDKs.
By adding `svelte-language-server` to the supported SDKs.
**Checklist**
> feat: add svelte-language-server to pnpify

- .yarn/versions/8c267dc1.yml
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-8-a-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-8-a-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-8-b-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-8-b-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-8-c-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-8-c-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-8-d-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/dragon-test-8-d-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/dragon.test.js
- packages/yarnpkg-core/sources/Project.ts
Fixes #1478 
Paraphrasing the test:
We want to deduplicate all the virtual instances as long as their effective dependencies are the same. However, in order to do that, we need to run the deduping recursively since deduping one package may lead to others being candidates for deduping.
Reproducing the edge case we ran into is a bit tricky and heavily connected to our own algorithm. We need the following tree:
```
. -> A -> B --> C
--> D
-> C
-> D --> C
-> B --> C
--> D
-> C
-> D --> C
```
In this situation, the Yarn resolution will first traverse and register A, B, C, D. B and D will both get virtual instances. Then the traversal will leave the A branch and iterate on the remaining
nodes in B, C, D. At this point B will still reference the …
> Fixes deduping edge case

- packages/gatsby/content/advanced/editor-sdks.md
Extend the project search from a buffer's `default-directory` variable.
Propose a new `:local` dependency provider to keep configurations local per
project.
> fix(gatsby): Update the Emacs docs for Editor SDKs

- .yarn/versions/e70c6838.yml
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts
- packages/yarnpkg-pnpify/sources/commands/SdkCommand.ts
- packages/yarnpkg-pnpify/sources/hoist.ts
- packages/yarnpkg-pnpify/tests/hoist.test.ts
This PR fixes issue #1065
I have made hoister and node_modules builder to be aware of aliases. 
**Checklist**
> [node-modules] Add aliases support

- .yarn/versions/2a51d1da.yml
- CHANGELOG.md
- packages/acceptance-tests/pkg-tests-fixtures/packages/has-bin-entries-1.0.0/bin-with-exit-code.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/has-bin-entries-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/has-bin-entries-2.0.0/bin-with-exit-code.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/has-bin-entries-2.0.0/package.json
- packages/acceptance-tests/pkg-tests-specs/sources/commands/dlx.test.js
- packages/plugin-dlx/sources/commands/dlx.ts
The exit code wasn't being forwarded in `dlx`. Fixes #1551 
Adds a return, adds tests
**Checklist**
> Fixes the dlx exit code

- .yarn/versions/eca0cf63.yml
- CHANGELOG.md
- packages/plugin-essentials/sources/commands/config/set.ts
It's a bit painful to have to manually locate and update the home configuration file.
I made `yarn config set` support a new `-H,--home` configuration flag that makes it update the home configuration instead of the project configuration.
**Checklist**
> feat(plugin-essentials): yarn config set --home

- .yarn/versions/1da78660.yml
- packages/acceptance-tests/pkg-tests-fixtures/packages/has-symlinks-1.0.0/index.js
- packages/acceptance-tests/pkg-tests-fixtures/packages/has-symlinks-1.0.0/package.json
- packages/acceptance-tests/pkg-tests-fixtures/packages/has-symlinks-1.0.0/symlink.js
- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
Copying symlinks inside packages were broken in nm linker
This PR fixes symlinks copying by correctly computing symlink target path
**Checklist**
> [node-modules] Fixes symlinks copying

- .yarn/versions/9e2ecc7e.yml
- packages/yarnpkg-cli/sources/tools/getPluginConfiguration.val.js
When creating the `pluginConfiguration` the name of the plugins are included as a JSON object causing webpack to create unnecessary modules
Inlined the names directly as strings, reducing the bundle size by 1304 bytes
<details>
<summary>Truncated diff</summary>
```diff
exports.getPluginConfiguration = () => ({
modules: new Map([
-    [__webpack_require__(314).name, __webpack_require__(315)],
-    [__webpack_require__(320).name, __webpack_require__(230)],
-    [__webpack_require__(321).name, __webpack_require__(204)],
-    [__webpack_require__(322).name, __webpack_require__(232)],
-    [__webpack_require__(323).name, __webpack_require__(12)],
-    [__webpack_require__(324).name, __webpack_require__(255)],
- …
```
> perf(cli): inline plugin names

- .github/workflows/benchmark-workflow.yml
- scripts/bench-run.sh
- scripts/benchmarks/next.json
- scripts/submit-bench-data.js
We don't really track our performances.
This workflow will periodically submit benchmark data to Datadog, which will be exposed in a soon public dashboard.
**Checklist**
> Adds benchmarks

- packages/plugin-patch/README.md
> docs: fix typo

- .yarn/versions/32a79ce7.yml
- packages/plugin-npm-cli/sources/commands/npm/publish.ts
This lifecycle is documented, but it seems has been forgotten in the code itself 😅
Fix #1715 
Just call the script before packing.
**Checklist**
> Implements prepublish

- .github/workflows/benchmark-workflow.yml
- scripts/bench-run.sh
We're currently not optimizing nm installs. While it's the simplest way to benchmark the nm linker, people using it (and caring about benchmarks) will presumably want to optimize it as much as possible as long as tradeoffs aren't too pronounced.
We now disable cache compression when using the nm linker, and disable the global cache.
**Checklist**
> Perf test settings

- packages/gatsby/content/features/protocols.md
We're currently missing a fair bit of documentation here.
...
**Checklist**
> Protocol documentation

- packages/gatsby/content/advanced/migration.md
We are talking about one of our multiple aims, but the word 'aim' was singular—not plural.
...
Pluralized 'aim' by adding an 's'
...
**Checklist**
> pluralize the word aim

- packages/gatsby/src/pages/configuration/yarnrc.json
It fixes a smaller typo in the yarnrc configuration docs.
Removed a single word.
**Checklist**
> Smaler typo in yarnrc docs

- packages/gatsby/content/features/plugnplay.md
Redundant column in the table
Remove it
**Checklist**
> plugnplay.md: Fix table

- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
The transitive dependencies hoisting test was failing. It was failing because it recreated specific conditions for an edge case. These conditions were directly related to hoisting preferences.
I have changed the test to not rely on hoisting preferences. This reduced the test significance, because it no longer recreates tricky case. But even in its current form it makes sense to have this sort of transitive dependencies hoisting test.
**Checklist**
> fix(tests) Fixes failing transitive dependencies hoisting test

- packages/gatsby/content/advanced/plugin-tutorial.md
Update the plugin tutorial docs with another example for writing a plugin
...
Not relevant
...
**Checklist**
> docs: enhancing tutorial with another example

- packages/gatsby/content/getting-started/install.md
yarn 2 felt like a new, dangerous thing that would have issues, so I decided to run both of these commands (please check the change for this PR now for context)
I am just trying to help the next person who decides to run both commands. If I'm reading this incorrectly, let me know, we should clarify that the user should run _both_ commands
> Clarify set version berry commands

- .github/workflows/e2e-webpack-workflow.yml
Release candidate versions of `webpack` and `webpack-cli` have been released.
Install `next`-tagged versions of `webpack` and `webpack-cli`.
**Checklist**
> test(e2e): test webpack 5

- .yarn/versions/1188a97a.yml
- packages/yarnpkg-builder/sources/tools/makeConfig.ts
We didn't submit the metrics to the correct endpoint.
I totally forgot that your org was in EU.
Use the correct endpoint to EU.
**Checklist**
> fix: use the EU endpoint

- packages/gatsby/content/features/offline-cache.md
A minor typo ('later' instead of 'latter')
...
Fixed the typo
...
**Checklist**
> docs: fix typo in offline-cache.md

- .yarn/versions/cbf96855.yml
- packages/plugin-essentials/sources/commands/config/set.ts
Document nested property access, as discussed in #1940
> docs: Document `yarn config` nested property access

- packages/gatsby/src/pages/package.js
Trying to make more space on the package details page.
Removing the "Package detail" banner/header
**Checklist**
> feat(website): remove Package detail banner

- packages/gatsby/content/getting-started/editor-sdks.md
- packages/gatsby/content/getting-started/migration.md
- packages/gatsby/content/getting-started/questions-and-answers.md
- packages/gatsby/content/getting-started/usage.md
- packages/gatsby/gatsby-config.js
- packages/gatsby/static/_redirects
Moved some pages from underneath `Advanced` to `Getting Started`. They're topics that beginners would be immediately interested about.
Added redirects from old pages to new ones, and moved them.
Also moved `Features` before `Configuration` in the top navigation bar.
**Checklist**
> docs: reorganize getting started

- .github/workflows/e2e-webpack-workflow.yml
Webpack 5 has been officially released.
Install latest versions of `webpack` and `webpack-cli`.
**Checklist**
> test(e2e): test latest webpack

- scripts/compile.js
There were some linter errors in the compile script. It doesn't seem to be covered by `test:lint`.
The change is trivial. I don't believe it requires additional clarification.
**Checklist**
> style(scripts): Resolve linter errors

- .yarn/versions/2fbe5b14.yml
- packages/plugin-workspace-tools/sources/commands/foreach.ts
Partially addresses #2002
Part of continuous effort to get rid of non-inclusive terms like "whitelist" and "blacklist" implying that white = good and black = bad.
Simple string editing.
**Checklist**
> refactor(plugin-workspace-tools): update description of --include and --exclude flags

- .yarn/versions/3f432303.yml
- packages/plugin-interactive-tools/sources/commands/search.tsx
- packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
- packages/plugin-version/sources/commands/version/check.tsx
- packages/yarnpkg-libui/sources/components/Gem.tsx
- packages/yarnpkg-libui/sources/components/ItemOptions.tsx
This implements the upgrade-baselines feature proposed in #1980 , building on top of the ink upgrade in #2011 
**Checklist**
> Add baseline indicators to upgrade-interactive entries

- .yarn/versions/ec9bf7b7.yml
- packages/plugin-node-modules/sources/NodeModulesLinker.ts
- packages/plugin-pnp/sources/index.ts
I forgot to update a few symbols in #2093.
Fixed the symbols.
**Checklist**
> Fixes exports

- .yarn/versions/c021ba88.yml
- packages/plugin-essentials/sources/commands/set/resolution.ts
Update the examples to what is now working.
Retionale: https://github.com/yarnpkg/berry/issues/1598#issuecomment-728308788
**Checklist**
> docs(set): update set resolution examples

- .yarn/versions/cd7f5a63.yml
- packages/yarnpkg-core/sources/structUtils.ts
- packages/yarnpkg-core/sources/types.ts
Adds some jsdoc comments
With my keyboard.
**Checklist**
> docs: add jsdoc comments

- .yarn/versions/01cbe594.yml
- packages/yarnpkg-core/sources/miscUtils.ts
- packages/yarnpkg-core/tests/Configuration.test.ts
Empty replacements didn't work in yarnrc files
By supporting empty replacements
**Checklist**
> fix(core): support empty replacements in environment variables

- packages/gatsby/content/getting-started/questions-and-answers.md
Fixed a small grammatical error in the documentation.
...
Changed "Why that?" to "Why's that?"
...
**Checklist**
> Fixed grammatical error

- packages/gatsby/content/advanced/rulebook.md
scripts link was pointing to localhost
...
Corrected link
...
**Checklist**
> docs(rulebook): corrected typo in link

- .yarn/versions/b8dfe5c3.yml
- packages/yarnpkg-core/sources/LegacyMigrationResolver.ts
Addresses https://github.com/yarnpkg/berry/pull/2164#discussion_r530257579.
Funny story: When I fixed https://github.com/yarnpkg/berry/issues/902#issuecomment-732360991, I thought that the URL referenced by the comment didn't have a protocol because one of the browser extensions I'm using decided to hide the protocol 😅 :
I only discovered that when seeing the review from @arcanis, but I postponed responding to that comment because I was working on something else at the time and I forgot to mark the PR as draft in the meantime and it got merged 1 day later.
I reverted the change that made the protocol optional.
**Checklist**
> revert: revert change that made legacy pattern protocol optional

- .pnp.js
- .yarn/versions/90e0f45e.yml
- packages/plugin-essentials/sources/commands/explain/peerRequirements.ts
`yarn explain peer-requirements` didn't have a description.
By adding a description.
**Checklist**
> docs: add description to yarn explain peer-requirements command

- .pnp.js
- .yarn/versions/c0f3617a.yml
- packages/plugin-essentials/sources/commands/explain/peerRequirements.ts
The output of `yarn explain peer-requirements` had some problems:
- "provides" was always shown even when it should've been "doesn't provide"
- the output was verbose because we also printed the reference of the root requester
Just like you would imagine.
**Checklist**
> fix: fix and refactor yarn explain peer-requirements output

- GOVERNANCE.md
The governance isn't transparent. I think we all have a fairly good idea what it is, but it can be worth putting it in words - especially if we're looking at accepting sponsorships in the future.
I started from the [Rome](https://github.com/rome/tools/blob/main/GOVERNANCE.md) governance model, since it presents many similarities with the situation here, and slightly adapted it.
cc @yarnpkg/berry
> Governance file

- .yarn/versions/02f785b3.yml
- CHANGELOG.md
- packages/acceptance-tests/pkg-tests-specs/sources/features/initFields.test.ts
- packages/plugin-init/sources/commands/init.ts
- packages/plugin-init/sources/index.ts
- packages/yarnpkg-core/sources/Configuration.ts
`initFields` had a few issues (you can see them by looking at the linked issue or at the tests I added).
Fixes #2230.
I fixed those issues and also removed the deprecated `initVersion` and `initLicense` fields.
**Checklist**
> fix: fix initFields issues

- packages/gatsby/content/features/constraints.md
> docs: use past tense of perplex

- .yarn/versions/7a7e17b7.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/focus.test.js
- packages/eslint-config/rules/style.js
- packages/plugin-npm/sources/npmHttpUtils.ts
- packages/plugin-patch/sources/commands/patchCommit.ts
- packages/plugin-patch/tests/diffFolders.test.ts
- packages/yarnpkg-core/sources/Manifest.ts
- packages/yarnpkg-core/sources/httpUtils.ts
- packages/yarnpkg-doctor/sources/cli.ts
- packages/yarnpkg-fslib/tests/ZipFS.test.ts
Comma spacing wasn't being enforced by the eslint config.
By enabling the comma-spacing ESLint rule.
**Checklist**
> style(eslint-config): enable comma-spacing

- .yarn/versions/f53d1835.yml
- packages/yarnpkg-core/sources/Plugin.ts
The core hooks were documented via regular comments rather than jsdoc comments.
...
**Checklist**
> style: use jsdoc

- .github/workflows/e2e-snowpack-workflow.yml
I added an e2e test for snowpack to catch issues like https://github.com/yarnpkg/berry/issues/2229 earlier.
I also validated locally that this new e2e test fails against 2.4.0, but passes against the current master.
> Add an e2e test for snowpack

- .yarn/versions/4bfc3e92.yml
- packages/yarnpkg-core/sources/RunInstallPleaseResolver.ts
The error message for a missing install isn't explicit about what the solution is
Fixes https://github.com/yarnpkg/berry/issues/2398
Rephrase the error message
**Checklist**
> chore(core): rephrase error message for missing install

- .yarnrc.yml
- README.md
- packages/gatsby/content/features/plugnplay.md
2 small changes that should be considered my review suggestions for https://github.com/yarnpkg/berry/pull/2362 (which I forgot to review before it was merged).
...
**Checklist**
> chore: uncomment changesetIgnorePatterns and add esbuild e2e workflow to readme

- .yarn/versions/6ae87912.yml
- packages/plugin-essentials/sources/commands/install.ts
> docs(essentials): fix immutablePatterns ref

- packages/gatsby/content/getting-started/migration.md
> Update migration.md - minor edit

- .yarn/versions/24da4497.yml
- packages/plugin-compat/sources/extensions.ts
Fix `@google-cloud/firestore` to play nice with PnP
https://github.com/googleapis/nodejs-firestore/pull/1425
Should be clear from the commit
**Checklist**
> chore(compat): add @google-cloud/firestore@<=4.9.3 extensions

- packages/gatsby/content/features/protocols.md
"compartiment" -> "compartmentalize" so the sentence makes sense.
...
...
**Checklist**
> Docs: Fix a typo.

- packages/yarnpkg-core/sources/Plugin.ts
fixed typo
`availabe` -> `available`
**Checklist**
> chore(core): fix typo in Plugin.ts

- .yarn/versions/3140b32c.yml
- packages/plugin-workspace-tools/README.md
This command was missing from the README and documentation at https://yarnpkg.com/api/modules/plugin_workspace_tools.html.
Added it.
**Checklist**
* Tests appear to be timing out? This is just a README.md change.
> Add `yarn workspaces focus` to workspace-tools doc

- .yarn/versions/85c27e01.yml
- packages/yarnpkg-builder/sources/commands/new/plugin.ts
seems there is a typo in the plugin builder template code
> fix(builder): correct template code

- packages/yarnpkg-pnp/sources/loader/applyPatch.ts
fixed typo
`occuring` -> `occurring`
**Checklist**
> chore(core): fix typo in applyPatch.ts

- .yarn/versions/18d406e2.yml
- packages/plugin-patch/sources/PatchFetcher.ts
Forgot to test after making a change (which kinda proves I should add more tests to this section!).
Skips the following save if the patch cannot be applied.
**Checklist**
> Fixes patch early return

- packages/gatsby/content/features/plugins.md
Plugin discovery is currently a bit difficult. We have improvements to do on this front, but for now a static list will be a good improvement.
**Checklist**
> Improves the plugin documentation

- packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
Before https://github.com/yarnpkg/berry/pull/2481 using `nmHoistingLimits: workspaces` with nested workspaces would still hoist the dependencies of the nested workspace
Added a test to ensure we don't regress
**Checklist**
> test(node-modules): hoisting limit for nested workspaces

- .yarn/versions/fb382e04.yml
- packages/plugin-version/sources/commands/version/apply.ts
typo
```
refering -> referring
```
**Checklist**
> docs(version): fix typo in apply details

- .yarn/versions/bb9f6051.yml
- packages/yarnpkg-core/sources/Workspace.ts
- packages/yarnpkg-core/tests/Project.test.ts
Closes #2725
Update the `manifest.raw` to be the value we just wrote to the file system.
**Checklist**
**Additional Comments**
Couldn't find any direct test coverage around the Workspace itself. Not sure the best way to test this, open to suggestions.
> fix(core): update `Manifest.raw` when persisting a Workspace

- packages/gatsby/content/advanced/error-codes.md
Missing error code docs.
**Checklist**
> docs: add error codes YN0062 and YN0063

- .yarn/versions/505395be.yml
- packages/yarnpkg-core/sources/StreamReport.ts
We write group markers on CI, but it causes the JSON output to break.
Fixes #2634
Don't print group markers when the CI mode is enabled.
**Checklist**
> Fix --json on CI

- packages/gatsby/content/advanced/plugin-tutorial.md
fix relative link so that it directs to the plugin section
...
update `#builder` to `#all-in-one-plugin-builder`
...
**Checklist**
> docs(plugin): fix plugin link

- .github/workflows/e2e-pnpify-workflow.yml
- .github/workflows/e2e-snowpack-workflow.yml
- .yarn/versions/0ccf9067.yml
- packages/plugin-compat/sources/extensions.ts
The Angular and Snowpack tests are failing due to missing dependencies in both.
Adding them to our builtin extension list as a workaround.
**Checklist**
> Adds new compat extensions

- .yarn/versions/7991e2d7.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
- packages/yarnpkg-core/sources/Cache.ts
> fix(core): throw if cache is missing when immutable

- packages/gatsby/content/features/plugnplay.md
- packages/gatsby/content/getting-started/recipes.md
This add a Recipes page to the docs. It should serve as a quick reference to have small snippets of code and instructions that come up often in support requests.
Added a markdown page.
**Checklist**
> docs: adds a Recipes page to the docs

- packages/acceptance-tests/pkg-tests-specs/sources/commands/remove.test.js
Fixed typo.
```
occurences -> occurrences
```
**Checklist**
> chore(core): fix typo in remove.test.js

- packages/gatsby/content/features/plugnplay.md
The incompatibility table (found [here](https://yarnpkg.com/features/pnp#incompatible)) does not include information for ReScript.
Added an entry to the table, referencing the issue tracking the feature in the ReScript repository.
**Checklist**
> docs: add entry to incompatibility table for ReScript

- .yarn/versions/de9aeaa4.yml
- packages/yarnpkg-parsers/sources/grammars/shell.d.ts
- packages/yarnpkg-parsers/sources/grammars/shell.js
- packages/yarnpkg-parsers/sources/grammars/shell.pegjs
- packages/yarnpkg-parsers/tests/shell.test.ts
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/tests/shell.test.ts
Background jobs aren't currently supported in the shell and users get a cryptic PegJS error (#1349).
Parse the `&` with the same precedence as `;` and throw a detailed error in the shell when encountered.
The error is only temporary, I'll replace it with a proper implementation in the shell when I have time (hopefully soon :tm:).
**Checklist**
> feat(shell): throw error on background jobs

- packages/gatsby/content/features/protocols.md
Small typo on the protocols page.
**Checklist**
> docs: fix typo on the protocols page

- packages/gatsby/content/features/plugins.md
Just docs, it was suggested by @arcanis 
...
/
...
**Checklist**
> docs: add the `conditions` plugin to the "Contrib plugins" list

- .yarn/sdks/typescript/lib/tsserver.js
- .yarn/versions/97037a6a.yml
- packages/yarnpkg-pnpify/sources/sdks/base.ts
Speling and grammar can be hard sometimes 😄 .
> chore(pnpify): fix typo in comment in tsserver SDK

- packages/acceptance-tests/pkg-tests-specs/sources/dragon.test.js
fixed typo.
`independant` -> `independent`
**Checklist**
> chore: fix typo in `dragon.test.js`

- .yarn/versions/df439046.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/unlink.test.js
- packages/plugin-essentials/sources/commands/unlink.ts
Addresses https://github.com/yarnpkg/berry/pull/2588#discussion_r638209031
Replaced leadingArgument with leadingArguments (Rest)
**Checklist**
> feat(plugin-essentials): support multiple patterns for unlink command

- packages/gatsby/content/advanced/error-codes.md
- #2688 accidentally duplicated a line: https://github.com/yarnpkg/berry/pull/2688/files#diff-9bda92e2668e464c75e1f8ddd457419f3aed650af366319acb9e780edf8dba3fR337
- small typo
- remove duplicated line
- `explicitely` -> `explicitly`
**Checklist**
> docs: remove duplicated line and fix typo

- .pnp.cjs
- packages/gatsby/gatsby-node.js
The monaco editor [tries to read `process.env.VSCODE_BROWSER_CODE_LOADING`](https://github.com/microsoft/vscode/blob/bfac07cd0e374c433c2c06d6999dabf9cf9d5d29/src/vs/base/common/platform.ts#L80), but `process.env` became `undefined` starting with c66ad15ec80f167673b56efa842c148a07d43a5a.
Fixes #3040.
Define `process.env` as an empty object.
**Checklist**
> fix(website): fix sherlock playground

- .yarn/versions/a42e7293.yml
- packages/plugin-essentials/sources/commands/set/version.ts
- packages/plugin-init/sources/commands/init.ts
We currently set the version inside the `packageManager` field, but I forgot to also set the package manager name.
**Checklist**
> Fixes the packageManager field

- packages/gatsby/content/features/plugnplay.md
Edit plugnplay.md for grammar and readability
Enhances Plug'n'Play documentation
Manual editing along with a bit of help from grammarly
> docs: improve Plug'n'Play documentation

- .yarn/versions/1fb334a0.yml
- packages/yarnpkg-doctor/sources/cli.ts
Fixes #2752 
...
Fixed a bad parameter when using `createSourceFile`
...
**Checklist**
> fix(doctor): fixes ArrayLiteralExpression error when running doctor with unmet peer dependency

- packages/gatsby/content/features/plugins.md
This is a really tiny PR, but after seeing you added yarn.build (thanks!) I would like to update the description to clarify what it does
A small update to clarify the description of yarn.build
**Checklist**
> docs: update to yarn.build description

- packages/gatsby/content/advanced/plugin-tutorial.md
I figured that the word "easier" was spelt as "easyer".
...
...
**Checklist**
> fixed a typographical error

- .github/workflows/integration-workflow.yml
- .yarn/versions/fd063983.yml
- packages/yarnpkg-parsers/package.json
- packages/yarnpkg-parsers/sources/grammars/resolution.js
- packages/yarnpkg-parsers/sources/grammars/syml.js
We didn't ensure that the parser grammar files are consistent with fresh builds.
Added a new step to the integration workflow.
**Checklist**
> ci: make sure that the grammar files are consistent with fresh builds

- .pnp.cjs
- .yarn/versions/0a60d7bd.yml
- packages/yarnpkg-pnpify/package.json
- packages/yarnpkg-sdks/package.json
- yarn.lock
Adds missing tslib dependency to sdks and pnpify. Fixes: #3139 
Added missing dependency
**Checklist**
> fix(sdks) Add missing tslib dependency to sdks and pnpify

- CHANGELOG.md
Adds a couple missing commands and fixes some typos.
...
**Checklist**
> docs: add a couple missing commands, and fix typos

- packages/gatsby/content/features/plugnplay.md
One code snippet under https://yarnpkg.com/features/pnp#initializing-pnp still refers to the old `.pnp.js` filename.
I replaced `.pnp.js` with `.pnp.cjs`
**Checklist**
> docs(plugnplay.md): update `.pnp.js` → `.pnp.cjs`

- packages/gatsby/src/components/layout.js
- packages/gatsby/static/opensearch.xml
https://yarnpkg.com doesn't have a OpenSearch config
**Checklist**
> docs: add OpenSearch config

- packages/gatsby/content/advanced/lexicon.md
- packages/gatsby/content/advanced/lifecycle-scripts.md
- packages/gatsby/content/getting-started/migration.md
Part of the docs are outdated or lacking some information
Ref https://github.com/yarnpkg/berry/discussions/3197
Ref https://github.com/yarnpkg/berry/issues/3188
**Checklist**
> docs: update some outdated information

- .yarn/versions/7c4f7995.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
- packages/acceptance-tests/pkg-tests-specs/sources/protocols/workspace.test.ts
- packages/gatsby/content/features/workspaces.md
- packages/plugin-pack/sources/index.ts
- packages/yarnpkg-core/sources/Workspace.ts
closes #2658 
accept new alias in `@yarnpkg/core` and resolve to correct version in `@yarnpkg/plugin-pack`
**Checklist**
> feat: add support for `workspace:~` and `workspace:^` aliases

- packages/gatsby/content/features/plugins.md
Adding documentation for contrib plugin
Docs Update
**Checklist**
> Adding az-cli-auth contrib plugin

- packages/gatsby/content/advanced/error-codes.md
> docs: update outdated docs for `YN0019`

- CHANGELOG.md
As per https://github.com/yarnpkg/berry/compare/@yarnpkg/cli/3.0.1...@yarnpkg/cli/3.0.2
Same same:
@yarnpkg/pnp: https://github.com/yarnpkg/berry/compare/@yarnpkg/pnp/3.0.1...@yarnpkg/pnp/3.0.2
@yarnpkg/plugin-pnp: https://github.com/yarnpkg/berry/compare/@yarnpkg/plugin-pnp/3.0.1...@yarnpkg/plugin-pnp/3.0.2
> docs(changelog): Add 3.0.2 changelog; fix 2 minor typos

- .yarn/versions/81c4f75b.yml
- packages/plugin-essentials/sources/commands/install.ts
Typo/grammar
Typed inline
**Checklist**
> Minor wording corrections on install documentation

- .yarn/versions/6ae35f0e.yml
- packages/plugin-essentials/sources/commands/install.ts
Fixes #3147.
@arcanis helpfully provided a reference to the relevant documentation, and I linked to it from where people will need it.
P.s. This also updates https://yarnpkg.com/cli/install since that is generated automatically from this.
**Checklist**
> Reference which lifecycle scripts are run

- packages/gatsby/content/getting-started/migration.md
Suggest migration path for `--verbose` to use `CI=true`
> docs: suggest `CI=true` alternative for `--verbose`

- packages/gatsby/playground-sandbox/pages/api/fetch-node-version.js
- packages/gatsby/playground-sandbox/pages/index.js
- packages/gatsby/src/components/playground/Playground.js
- packages/gatsby/src/components/playground/PlaygroundNodeVersion.js
- packages/gatsby/src/utils/playgroundUtils.js
This PR makes it easier to see the Node version inside the playground.
**Checklist**
> feat(playground): display node version

- packages/gatsby/content/getting-started/questions-and-answers.md
I've reordered the `.gitignore` so that it's easier to visually diff.
Alphabetized.
**Checklist**
> docs: reorder .gitignore

- .yarn/versions/46c38fa6.yml
- packages/yarnpkg-parsers/sources/grammars/shell.d.ts
- packages/yarnpkg-parsers/sources/grammars/shell.js
- packages/yarnpkg-parsers/sources/grammars/shell.pegjs
- packages/yarnpkg-parsers/sources/shell.ts
- packages/yarnpkg-shell/sources/index.ts
- packages/yarnpkg-shell/tests/shell.test.ts
Resolves #3451
- Added variable syntax to `yarnpkg-parsers/sources/grammars/shell.pegjs` to parse alternative expressions.
- Added logical logic to (`yarnpkg-parsers/sources/shell.ts`) to stringify the argument segment, which is an alternative expression.
- And interpolate alternative value if the variable is a number or a variable value is assigned. 
**Checklist**
- ~Help! in interactive version check, should I choose `minor` for `@yarnpkg/parsers` and `@yarnpkg/shell`, and `decline` for dependent workspaces?~ Resolved
> feat(shell): support ${FOO:+bar} expression

- .yarn/versions/ce41a8b6.yml
- CHANGELOG.md
- packages/yarnpkg-core/sources/Project.ts
- packages/yarnpkg-core/sources/Report.ts
- packages/yarnpkg-core/sources/StreamReport.ts
- The resolution step lacked a spinner / some kind of progress indicator.
- Because of a bug (introduced while improving the performance of the progress bar), the progress spinner didn't spin if the progress bar wasn't updated.
Fixes https://github.com/yarnpkg/berry/issues/861.
- Added a spinner with the name of the descriptor that's being resolved as the title. I also throttled it to 15 fps so that it doesn't affect performance too much. Perhaps we should throttle it even more?
- Made it spin again.
https://user-images.githubusercontent.com/32596136/139860669-a4b22218-1803-45ab-b4b2-aae13ffc03b1.mp4
**Checklist**
> feat: resolution step progress

- packages/gatsby/static/configuration/yarnrc.json
`preferTruncatedLines` wasn't documented.
Documented it inside the JSON schema.
**Checklist**
> docs: document preferTruncatedLines

- packages/gatsby/content/advanced/plugin-tutorial.mdx
`YARN_PLUGINS` wasn't documented.
Documented it.
**Checklist**
> docs: document `YARN_PLUGINS`

- .pnp.cjs
- .yarn/versions/09689a2a.yml
- packages/plugin-compat/sources/extensions.ts
Updates the extensions list to include
- https://github.com/GoogleChromeLabs/critters/pull/91
- https://github.com/terser/terser/commit/05b23eeb682d732484ad51b19bf528258fd5dc2a
- https://github.com/facebook/create-react-app/pull/11751
**Checklist**
> chore(compat): update extensions list

- packages/gatsby/src/components/details/Header.js
> fix(website): add spacing between version and ts icon

- packages/gatsby/static/configuration/yarnrc.json
`enableMessageNames` wasn't documented.
Documented it.
**Checklist**
> docs: document enableMessageNames

- .github/workflows/e2e-nm-angular-workflow.yml
- .github/workflows/e2e-pnp-angular-workflow.yml
Create new angular app in a single step, as most users would do.
Specify yarn as package manager
**Checklist**
> ci: specify yarn when creating Angular project

- packages/gatsby/playground-sandbox/package.json
- packages/gatsby/playground-sandbox/pages/api/clone-repo.js
- packages/gatsby/playground-sandbox/sandbox.config.json
- Updated the playground Node version to `16`
- Updated `@arcanis/sherlock` to `^2.0.3` so that it works with Node 16
- Replaced `rimraf.sync` with `fs.rmSync(..., {recursive: true, force: true})`
- Checked in the sandbox config (`sandbox.config.json`) into this repo too
I've already updated the sandbox and now I'm opening a PR here too so that the changes don't get out of sync. We should really find a way to automatically sync the changes. 
**Checklist**
> refactor(playground): tweaks

- packages/gatsby/content/features/plugins.md
Adding a yarn plugin to the list over yarn plugins
Updated markdown file with list over yarn plugins.
**Checklist**
> Adding project yarn-plugin-envinfo to the list over yarn plugins

- .yarn/versions/75b38d6e.yml
- packages/plugin-essentials/sources/commands/add.ts
- packages/yarnpkg-core/sources/Project.ts
Some parts of Yarn still cause errors that may be difficult to understand for new users. I'd like to make it easier to understand what happens, and in particular how to fix the issues.
- I tried to reword an existing error message to cover the "what if I want a nm project inside a pnp one" use case
- I added a better error message when using `yarn add` with urls / git repos without explicit names
**Checklist**
> Improves UX

- packages/gatsby/static/configuration/yarnrc.json
- `cloneConcurrency` wasn't documented.
- Some properties in the yarnrc schema weren't sorted.
- Documented it.
- Sorted them.
**Checklist**
> docs: document cloneConcurrency and sort some properties

- packages/gatsby/content/features/workspaces.md
> docs: grammar corrections

- packages/gatsby/content/advanced/contributing.md
Closes: https://github.com/yarnpkg/berry/issues/1830
Added comments from https://github.com/yarnpkg/berry/issues/1830#issuecomment-690429246 under Profiling section
**Checklist**
> docs: add profiling section in contributing guide

- packages/gatsby/content/features/plugins.md
Add `yarn-plugin-publishconfig` to Contrib plugins
**Checklist**
> docs: Add `yarn-plugin-publishconfig` to Contrib plugins

- packages/gatsby/content/features/plugins.md
> docs: add `yarn-plugin-http-proxy` contrib plugin

- packages/gatsby/src/components/header.js
The official link to support Ukraine became unavailable
I've updated the link to point to the different page of the same official website:
https://war.ukraine.ua/support-ukraine/
**Checklist**
> docs: Updates the link to support Ukraine

- .yarn/versions/bef0dfc3.yml
- packages/plugin-essentials/sources/commands/up.ts
> fix(essentials): correct typo in prompt

- .yarn/versions/e9e09213.yml
- packages/plugin-npm-cli/sources/commands/npm/audit.ts
Closes #4357
...
Return 1 on error, and 0 on no error.
...
**Checklist**
> Yarn npm audit json exitcode

- scripts/benchmarks/gatsby.json
- scripts/benchmarks/next.json
The benchmark dependencies are fairly old, and in some case refer to versions that no longer exist (deleted git repos).
Updated all dependencies to their newest ranges.
**Checklist**
> Updates benchmark dependencies

- packages/gatsby/content/features/plugins.md
Add `yarn-plugin-version-tools` to Contrib plugins
**Checklist**
> Add `yarn-plugin-version-tools` to Contrib plugins

- packages/acceptance-tests/babel.config.js
Fixes the integration tests not getting transpiled in https://github.com/yarnpkg/berry/pull/4419
**Checklist**
> test: add Babel config to integration tests

- packages/gatsby/content/features/plugnplay.md
Added 🐊`Putout` code transformer to list of native support.
Yarn PnP supported since [`v22.8`](https://github.com/coderaiser/putout/releases/tag/v22.8.0).
...
...
**Checklist**
-  [x] I will check that all automated PR checks pass before the PR gets reviewed.
> docs(pnp): add Putout to native support table

- packages/gatsby/static/configuration/manifest.json
- packages/gatsby/static/configuration/yarnrc.json
The manifest `libc` field wasn't documented on the website.
Added it to the schema.
**Checklist**
> docs: document libc in `manifest.json` schema

- packages/acceptance-tests/pkg-tests-specs/sources/features/cache.test.js
- packages/yarnpkg-fslib/tests/ZipFS.test.ts
We're missing tests for the changes in our forked `libzip`.
Add tests.
**Checklist**
> test: add tests for our changes to `libzip`

- packages/gatsby/content/features/release-workflow.md
Fix minor grammatical error.
Modified copy.
**Checklist**
> docs: fix small grammar error

- packages/yarnpkg-fslib/sources/index.ts
I made an error in the `export from` statement.
> fix: Fixes MountFS export

- .yarn/versions/5fb9cb98.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/list.test.js
- packages/plugin-essentials/sources/commands/workspaces/list.ts
Fixes #4700 
Adds the flag.
**Checklist**
> feat(essentials): Add `--no-private` flag to list command

- .pnp.cjs
- packages/yarnpkg-fslib/package.json
- packages/yarnpkg-fslib/sources/errors.ts
- packages/yarnpkg-libzip/sources/ZipFS.ts
I forgot to move `@yarnpkg/libzip` from the deps to the devDeps, so there's a dependency cycle that prevents publishing.
**Checklist**
> Removes dependency cycle

- .yarn/versions/9fb28ef8.yml
- packages/yarnpkg-nm/sources/index.ts
> feat(nm): export the hoist function

- .yarn/versions/2a2db5e7.yml
- packages/plugin-essentials/sources/commands/add.ts
- packages/plugin-essentials/sources/commands/dedupe.ts
- packages/plugin-essentials/sources/commands/install.ts
- packages/plugin-essentials/sources/commands/remove.ts
- packages/plugin-essentials/sources/commands/up.ts
Fix a typo in command usage docs.
...
Update `install.ts`. Don't know if I need update any other fixtures, let's see what CI tells me.
...
**Checklist**
> fix(essentials): fix a typo in the `--mode` flag documentation

- .yarn/versions/b8a9ea1f.yml
- packages/yarnpkg-extensions/sources/index.ts
Updates the extensions list to include
- https://github.com/thecodrr/fdir/pull/76
- https://github.com/thecodrr/fdir/pull/80
- https://github.com/leonardfactory/babel-plugin-transform-typescript-metadata/pull/61
- https://github.com/graphql-compose/graphql-compose/pull/398
**Checklist**
> chore(extensions): update list

- packages/gatsby/content/features/plugins.md
There is a typo in the docs.
Fixed the typo.
**Checklist**
> doc: Fix typo

- packages/gatsby/content/features/plugnplay.md
It works out of the box, no SDKs required.
fixed the docs
**Checklist**
> Update pnp docs for webstorm

- packages/plugin-essentials/sources/commands/set/version.ts
Fixing grammatical errors in version.ts
Modified the copy
**Checklist**
> fix: Fixes grammatical errors in version.ts

- packages/gatsby/static/configuration/yarnrc.json
Fixes typos and grammatical errors in `yarnrc.json` file
**Checklist**
> docs: Fix typos and errors in yarnrc.json file

- packages/gatsby/content/features/plugins.md
Adds a link to a new contrib plugin
N/A
**Checklist**
> Update plugins.md with yarn-plugin-env-vars

- packages/gatsby/content/getting-started/migration.md
As someone who has never used yarn before, I had to look this up.
Yarn upgrade howto should be tailored for users who know NOTHING about yarn (like me!) I had to go look up where the .yarnrc.yml file goes, so I proposed a minor doc change so the next person doesn't have to. 
...
I proposed a minor doc change so the next person doesn't have to go look up where to put .yarnrc.yml
...
**Checklist**
> docs: explain where the `.yarnrc.yml` should be placed in `migration.md`

- packages/acceptance-tests/pkg-tests-specs/sources/features/configuration.test.ts
> Fixes typecheck

- .github/workflows/integration-workflow.yml
Follow-up to https://github.com/yarnpkg/berry/pull/5573, which didn't remove the comment with the relevant issue (which isn't relevant anymore).
Removed the comment.
**Checklist**
> chore: remove outdated comment

- packages/docusaurus/src/pages/search.tsx
I added Doppler, but it's actually WorkOS which should be there.
> Fixes the sponsor link on the new website

- packages/docusaurus/docusaurus.config.js
- packages/docusaurus/src/lib/packageChecks.tsx
- packages/docusaurus/src/pages/index.module.css
- packages/docusaurus/src/pages/search.tsx
- packages/docusaurus/static/_redirects
- The search wasn't working
- Some mobile displays were a little broken on the home page
- Some package pages were broken
- The old `?q=` shortcuts were broken
> Website fixes

- packages/docusaurus/static/_redirects
- Adds redirections for a couple of common pages
Fixes #5695
Fixes #5693 
Fixes #5684
> Small fixes for the website

- packages/docusaurus/src/components/HomepageFeatures/index.tsx
Fixed typos on the front page of the website.
"Yarn may solve all your problems - but it'll give you the tools to solve the ones you find on your way." -> "Yarn may not solve all your problems - but it'll give you the tools to solve the ones you find on your way."
"Yarn will always be to the frontline" -> "Yarn will always be at the frontline"
> "Yarn may [+not] solve all your problems" and "will always be to[+at]"

- CHANGELOG.md
Very minor change, feel free to ignore my pedantry. 😅
> docs: change wording in changelog

- packages/docusaurus/docs/getting-started/migrating/steps.md
Correct grammar
...
...
**Checklist**
> docs: fix typo in migration guide

- .yarn/versions/64c67350.yml
- packages/plugin-pnp/sources/index.ts
Fixes: https://github.com/yarnpkg/berry/issues/5847
Add 'pnpm' option in nodeLinker config description
**Checklist**
> chore(plugin-pnp): add 'pnpm' option in nodeLinker config description

- README.md
Fixes #5869 
Updated the link in the README.md file to correct link
**Checklist**
> fix : Update link to difference between link and portal

- .yarn/versions/b9be4faf.yml
- packages/yarnpkg-core/sources/Project.ts
overriden -> overridden
...
**Checklist**
> chore(core): fix typo in Project.ts

- packages/docusaurus/blog/2023-08-20-bun.md
- packages/docusaurus/docs/advanced/03-pnp/pnp-spec.md
This pull request fixes typos in blogs. I kindly request the repository maintainers to review and merge it. Thanks! :heart: 
**Checklist**
> fix typos in blogs

- packages/docusaurus/docs/getting-started/migrating/benefits.md
This PR fixes some minor grammar issues in benefits.md (https://yarnpkg.com/migration/overview).
> Fix grammar in benefits.md

- .yarn/versions/21efce51.yml
- packages/plugin-essentials/sources/commands/set/version/sources.ts
Resolves #5670 
...
Use windows-native `move` command for win32` platform
...
**Checklist**
> fix(set version) - fix build workflow for windows

- .yarn/versions/226801d8.yml
- packages/acceptance-tests/pkg-tests-specs/sources/commands/version/apply.test.ts
- packages/plugin-version/sources/commands/version/apply.ts
`yarn version apply --all --dry-run` makes changes, https://github.com/yarnpkg/berry/issues/5717
Added an if-check
**Checklist**
> fix(version) stop --dry-run from changing anything

- .yarn/versions/10ef22f9.yml
- packages/yarnpkg-extensions/sources/index.ts
https://github.com/pzmosquito/eslint-import-resolver-vite/pull/22
**Checklist**
> fix(extensions): `eslint-import-resolver-vite@<2.0.1`

- README.md
At the moment the image to SysGears logo is broken, because the URL has changed to the `sysgears.com` domain from `cdn3.sysgears.com` subdomain. 
I have updated the URL to the logo to point at GitHub, so that Yarn weren't affected by external website changes. I also updated spelling of the SysGears name from Sysgears to SysGears, as the latter is more correct.
**Checklist**
> fix(docs): Fixes SysGears logo in the README and SysGears name spelling

- .yarn/versions/022ed111.yml
- packages/plugin-essentials/sources/commands/add.ts
Adds documentation on how to install a dependency from your local filesystem
...
added some docs
...
> docs(cli): add docs on installing local package

- packages/docusaurus/static/configuration/yarnrc.json
fixes a typo in the documentation below to more accurately describe the expected input for `npmAuditExcludePackages`.
https://yarnpkg.com/configuration/yarnrc#npmAuditIgnoreAdvisories
N/A
> doc: update npmAuditExcludePackages description

- packages/docusaurus/static/configuration/yarnrc.json
incorrect spelling of option
...
fix the spelling
...
> fix typo workerPoolMode

- .github/workflows/e2e-storybook-workflow.yml
related https://github.com/yarnpkg/berry/issues/6545
The job named "E2E Storybook" has failed.
...
I fixed the setup steps for Storybook to the latest version.
https://storybook.js.org/docs
...
> ci(e2e): fix E2E Storybook

- .github/workflows/e2e-parcel-workflow.yml
related: #6545 
...
I've fixed the syntax error for now.
...
> ci(e2e): fix syntax error in the Parcel workflow

- .yarn/versions/37c4f060.yml
- packages/yarnpkg-extensions/sources/index.ts
https://github.com/iamhosseindhv/notistack/issues/551
...
...
> fix(extensions): notistack@^3.0.0

- .yarn/versions/e7f5fdea.yml
- packages/plugin-pack/sources/commands/pack.ts
Hey! Small typo addressed, nothing fancy
...
> fix: typo in yarn pack

- .yarn/versions/624760b9.yml
- packages/yarnpkg-extensions/sources/index.ts
https://github.com/fastify/fastify-type-provider-typebox/issues/114
> fix(extensions): `@fastify/type-provider-typebox`

- .yarn/versions/9195f0b5.yml
- packages/acceptance-tests/pkg-tests-specs/sources/features/prunedNativeDeps.test.ts
- packages/plugin-essentials/sources/commands/explain/peerRequirements.ts
- packages/plugin-essentials/sources/commands/plugin/import.ts
- packages/yarnpkg-core/sources/Configuration.ts
- packages/yarnpkg-core/sources/index.ts
- packages/yarnpkg-core/sources/miscUtils.ts
- packages/yarnpkg-core/sources/nodeUtils.ts
- packages/yarnpkg-pnp/sources/loader/applyPatch.ts
Our tests weren't covering the default configuration, when `supportedArchitectures` wasn't set. This is fixed by adding new `YARN_CPU_OVERRIDE` and `YARN_OS_OVERRIDE` test variables.
> Tweaks tests
