.yarn/versions/8f07f907.yml
packages/plugin-npm/sources/NpmSemverResolver.ts

Just noticed in https://github.com/yarnpkg/berry/runs/1871469680#step:5:26 that duplicate package deprecation warnings were being reported because I used `reportWarning` instead of `reportWarningOnce` in #1401.
...
**Checklist**

fix: report package deprecation warnings once

---

.yarn/versions/a7b438c0.yml
packages/plugin-node-modules/sources/NodeModulesLinker.ts

The `node-modules` linker doesn't await its calls to `xfs.symlinkPromise` in `symlinkPromise`
`await` the two calls to `xfs.symlinkPromise`
**Checklist**

fix(node-modules): add missing await to symlinkPromise

---

.github/workflows/e2e-parcel-workflow.yml

We recently switched to only installing the JS-related Parcel plugins by default and autoinstalling the other plugins on demand once the corresponding file format/language is used (https://github.com/parcel-bundler/parcel/pull/5769)
Autoinstalling is disabled on CI by default.
@arcanis

Parcel E2E: update for autoinstalling Parcel config

---

.yarn/versions/6df90ada.yml
packages/plugin-git/sources/GitFetcher.ts
packages/plugin-github/sources/GithubFetcher.ts
packages/yarnpkg-core/sources/scriptUtils.ts

Yarn log output for external projects is confusing
Currently, when external projects (git/github projects) are listed in a project's package.json and those external projects use something other than Yarn v2, Yarn logs a message describing that the project will be built using the detected package manager without logging any references to which project it is referring to. Because there is no supplementary logs describing which projects it is affecting, it is very easy for users to misunderstand the warning and think that their whole repository is being built with the logged package manager. In addition, because there is no logs around which project it is referring to, if the user wanted to remedy this error they would have no way of knowing which …

Add explanatory logging when installing git-based dependency

---

.yarn/versions/d2fb9e75.yml
packages/acceptance-tests/pkg-tests-specs/sources/protocols/patch.test.js
packages/plugin-patch/sources/patchUtils.ts

In my project (which is using PnP and strict mode), I have `package-a` listed as a dependency, and `package-a` lists as a dependency `patch:package-b@1.0.0#./package-b.patch`.
When I attempt to do `yarn install` the top level, I get the error `ENOENT: no such file or directory, open './package-b.patch`.
I'm not super familiar with the yarn code, but it appears that the `patchFiles` function is ignoring the `prefixPath` property.
**Checklist**

fix(patch): make patchfile path relative to prefixPath

---

.yarn/versions/256bdd8e.yml
CHANGELOG.md
packages/yarnpkg-pnpify/sources/sdks/base.ts

Prettier SDK used to rely on in memory node_modules for prettier plugin autoload purposes. It was turned out, because I believed that this is the only way for prettier to load its plugins in a PnP environment. But there is an explicit way for this, which works with PnP out of the box.
I turned off in memory node_modules usage, instead explicit plugins configuration should be used in prettier's `plugins` config property:
https://github.com/prettier/prettier/issues/7073#issuecomment-711954542
**Checklist**

fix(pnpify) Turn off in memory node_modules for prettier SDK

---

.yarn/versions/08c52146.yml
packages/plugin-pack/sources/index.ts

We assume everywhere that "no version" means `0.0.0`, except here. It causes the dependency to be set to `null`, which is incorrect.
**Checklist**

Fixes `pack` when a workspace dependency has no version

---

.yarn/versions/cccd82b4.yml
packages/plugin-compat/README.md

I found that a handful of new cache packages were downloaded when moving from yarn v1 to v2 (although I had to compare the cache manually to find them, see https://github.com/yarnpkg/berry/issues/2465).  After some digging, I found that they were being added by plugin-compat, although it wasn't immediately obvious where the `fsevents-patch` files were coming from.  Eventually I realized that it was also from plugin-compat, although the readme didn't mention it.
I added `fsevents` to the readme, and updated some of the links that were broken.
I declined the version bump, not sure if that was the right thing for a readme update or not...
**Checklist**

Add fsevents to plugin-compat README

---

.yarn/versions/920e00bf.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/plugin-node-modules/sources/NodeModulesLinker.ts

The `node-modules` linker prints a `YN0006` warning when a workspace depends on a workspace with postinstall scripts
```diff
➤ YN0000: ┌ Link step
- ➤ YN0006: │ dep@workspace:dep lists build scripts, but is referenced through a soft link. Soft links don't support build scripts, so they'll be ignored.
➤ YN0007: │ dep@workspace:dep must be built because it never did before or the last one failed
➤ YN0000: └ Completed
```
Skip workspace dependencies when fetching build scripts
**Checklist**

fix(node-modules): avoid soft-link warning on workspace dependencies

---

.github/workflows/e2e-storybook-workflow.yml

The current latest release of storybook (6.1.18) has an undeclared dependency that we could have caught earlier
cc @gaetanmaisse 
Test the `next` version of storybook
**Checklist**

ci: test storybook@next

---

.yarn/versions/8cf7ae4d.yml
CHANGELOG.md
packages/yarnpkg-pnpify/sources/hoist.ts
packages/yarnpkg-pnpify/tests/hoist.test.ts

Currently when a dependency peer depends on its parent it is not get hoisted by nm linker
Fixes: #2500
I'm going to update check for this special case to allow hoisting.
**Checklist**

fix(node-modules) Allow hoisting child when it peer depends on its parent

---

.yarn/versions/fbda37a0.yml
packages/yarnpkg-core/sources/Project.ts
packages/yarnpkg-core/sources/scriptUtils.ts

When the core runs into a workspace that hasn't been resolved it isn't descriptive about which workspace it is nor how to fix it.
Make the error more descriptive
```diff
- Internal Error: Assertion failed: Expected workspace to have been resolved
+ Internal Error: Assertion failed: Expected workspace foo (/berry/packages/acceptance-tests/package.json) to have been resolved. Run "yarn install" to update the lockfile
```
**Checklist**

fix(core): make unresolved workspace error more descriptive

---

.yarn/versions/e4a42765.yml
packages/yarnpkg-core/sources/Cache.ts

When the core fetches from the offline mirror it copies the result back into it again which is redundant and increases the risk of corrupting it.
Helps with https://github.com/yarnpkg/berry/issues/2349 but doesn't fix it
Skip copying back to the mirror when we just fetched from it
**Results**
Testing with https://github.com/yarnpkg/berry/blob/ef6f09d5b333df040776c761349b0ad8c1e0c995/scripts/bench-run.sh#L70-L72
```diff
Testing install-cache-and-lock
Benchmark #1: yarn install
-    Time (mean ± σ):     11.326 s ±  0.142 s    [User: 14.781 s, System: 5.490 s]
-    Range (min … max):   11.197 s … 11.598 s    10 runs
+    Time (mean ± σ):     10.956 s ±  0.082 s    [User: 14.544 s, System: 4.898 s]
+    Range (min … max): …
```

perf(core): avoid copying back to mirror when fetching from it

---

.yarn/versions/138dfd75.yml
packages/yarnpkg-cli/sources/tools/backportClipanionCompatibility.ts

The clipanion backward compatibility layer had a problem when used with commands that had default values.
Instead of trying to replace the property and keep the same name, we add a new one prefixed by `__` and proxy values to the underlying property. Solution was proposed by @arcanis on Discord.
**Checklist**

fix(cli): clipanion compatibility layer when used with default values

---

.yarn/versions/c958a387.yml
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/StreamReport.ts

I can understand why some people would prefer to reclaim some of their terminal with by removing the message names from the output. I still think we should add them by default (otherwise they'd be completely pointless, since the people who would most need them would be unaware of their existence), but power users should have a way to skip them.
A new `enableMessageNames` setting now lets you remove the message names from the output. As any setting, it can be configured in the home `.yarnrc.yml` file, in a project-local one, or via the environment.
**Checklist**

Implements enableMessageNames

---

.yarn/versions/b3cffd46.yml
packages/plugin-npm/sources/NpmSemverResolver.ts
packages/plugin-npm/tests/NpmSemverResolver.test.ts

The `NpmSemverResolver` doesn't parse the references passed to it in `getSatisfying`
Fixes https://github.com/yarnpkg/berry/issues/2377
Fixes https://github.com/yarnpkg/berry/issues/2467 (probably, no repro so i'm not sure)
Parse the references instead of just stripping off the protocol before checking if they are valid semver
**Checklist**

fix(plugin-npm): parse reference in NpmSemverResolver.getSatisfying

---

.yarn/versions/6f9b2372.yml
packages/acceptance-tests/pkg-tests-specs/sources/script.test.js
packages/yarnpkg-core/sources/scriptUtils.ts

The cmd file written by `makePathWrapper` doesn't work with utf-8 characters on Windows
Fixes https://github.com/yarnpkg/berry/issues/2397
Add `@setlocal` to the script
**Checklist**

fix(core): add missing setlocal in the cmd file for Windows

---

.yarn/versions/5c15602e.yml
packages/gatsby/static/configuration/yarnrc.json
packages/plugin-essentials/sources/commands/install.ts
packages/plugin-essentials/sources/index.ts

This PR makes Yarn immutable by default on CI. One of the v3 roadmap items and something that was discussed previously in the v1 repo: https://github.com/yarnpkg/yarn/issues/5869.
...
**Checklist**

feat: make enableImmutableInstalls default to true on ci

---

scripts/e2e-setup-ci.sh

I accidentally broke the e2e tests because I didn't realize that they'd be affected by https://github.com/yarnpkg/berry/pull/2530.
Set  `enableImmutableInstalls` to false before the tests run.
**Checklist**

ci: fix e2e tests

---

scripts/bench-run.sh

Perf benchmarks are failing to run for v2
https://github.com/yarnpkg/berry/pull/2531 but for the benchmarks
**Checklist**

ci: fix performance benchmarks

---

.yarn/versions/7e34fb4a.yml
packages/yarnpkg-doctor/sources/cli.ts

Resolves #2521. 
Captured the report from `StreamReport.start()` and returned its exit code in the command's `execute` method.
**Checklist**

Fix doctor not emitting nonzero exit code on failure

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/versions/e9cc398c.yml
packages/yarnpkg-pnpify/sources/sdks/base.ts

TypeScript plugins doesn't work in VSCode when the global cache is enabled due to [TypeScript trying to resolve them using a path relative to itself](https://github.com/microsoft/TypeScript/blob/1b57a0395e0bff191581c9606aab92832001de62/src/server/project.ts#L2238) and [VSCode not wanting to turn on `allowLocalPluginLoads`](https://github.com/microsoft/vscode/issues/45856).
TypeScript resolves these paths depending on the Yarn config
```
node_modules:        /berry/node_modules
PnP /w global cache: /globalFolder/cache/typescript-patch-bd6352e847-7.zip/node_modules
PnP /w local cache:  /berry/.yarn/cache/typescript-patch-bd6352e847-35322004ca.zip/node_modules
```
The path for the global cache isn't controlled by anything so it goes to the native …

fix(pnpify): force enable allowLocalPluginLoads in the typescript sdk

---

.yarn/versions/7b489a47.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/__snapshots__/foreach.test.js.snap
packages/plugin-workspace-tools/sources/commands/foreach.ts

When using `yarn workspaces foreach`  it may be difficult to track when process start and exit, especially when a process exit with an error code. Currently the verbose flag don't log start of process, and log process exit only when process doesn't output something, but it can happen a process log something and fail with an exit code.
Change the behavior of the verbose flag to be more clear:
* always log when a process is started
* always log when a process exit, whatever it's exit code and whatever if the output is empty or not
**Checklist**

feat(plugin-workspace-tools): foreach log process start/exit events in verbose mode

---

.yarn/versions/62996569.yml
packages/yarnpkg-core/sources/LegacyMigrationResolver.ts

This PR did not really work: https://github.com/yarnpkg/berry/pull/2357, however since I had the cache populated, I never noticed until some other developers on my team attempted to migrate their codebases. The issue is that in migrating a legacy yarn v1 lockfile that contained a reference to jfrog (private registry), we'd receive HTTP 404s.
When migrating, bind the locator with the jfrog url in the archiveUrl param. This is what happens when doing a `yarn add <my-private-package>` anyway.
**Checklist**

Preserve URL when migrating private jfrog references

---

.yarn/versions/a278601e.yml
packages/plugin-git/sources/__snapshots__/gitUtils.test.js.snap
packages/plugin-git/sources/gitUtils.ts

The `git:` protocol hardcoded `master` instead of using the actual `HEAD`. This meant that it was impossible to install repos like https://github.com/arcanis/typanion without specifying the default branch name.
I've made the `git:` protocol use the actual `HEAD` pseudo-ref when no specific head is requested.
**Checklist**

feat(plugin-git): make git: protocol default to HEAD

---

.yarn/versions/a1a1cf29.yml
packages/plugin-pnp/sources/PnpLinker.ts

We were always re-requiring the PnP API anew, even inside tight loops.
Closes https://github.com/yarnpkg/berry/issues/2560
The PnP API is now cached. This should be fine, considering that users will just have to create a new linker (from the configuration class) to clear all such caches.
**Checklist**

Improves yarn run performances

---

.yarn/versions/0b00790b.yml
packages/plugin-node-modules/sources/NodeModulesLinker.ts

https://github.com/yarnpkg/berry/pull/2564 but for the node-modules linker
ref https://github.com/yarnpkg/berry/issues/2575
Cache the install state
**Results**
Running `hyperfine -w 5 'yarn jest --version'` on https://github.com/jest-community/eslint-plugin-jest (cc @SimenB)
```diff
Benchmark #1: yarn jest --version
-  Time (mean ± σ):      2.645 s ±  0.026 s    [User: 1.227 s, System: 0.288 s]
+  Time (mean ± σ):      2.347 s ±  0.020 s    [User: 930.2 ms, System: 235.9 ms]
-  Range (min … max):    2.624 s …  2.702 s    10 runs
+  Range (min … max):    2.320 s …  2.386 s    10 runs
```
(Ran on WSL2 over the network mounted C drive)
**Checklist**

perf(node-modules): cache install state

---

.yarn/versions/6e4ec8bf.yml
packages/yarnpkg-fslib/sources/FakeFS.ts

When `removePromise` encounters a folder it deletes its content one item at a time instead of all at once.
Ref https://github.com/yarnpkg/berry/issues/2575
Change the for loop to a `map` and `Promise.all`
**Result**
Running `hyperfine -w 5 'yarn lint-staged'` on https://github.com/jest-community/eslint-plugin-jest (cc @SimenB)
```diff
Benchmark #1: yarn lint-staged
-  Time (mean ± σ):      1.454 s ±  0.024 s    [User: 749.1 ms, System: 170.3 ms]
+  Time (mean ± σ):      1.458 s ±  0.041 s    [User: 732.1 ms, System: 199.7 ms]
-  Range (min … max):    1.420 s …  1.493 s    10 runs
+  Range (min … max):    1.396 s …  1.513 s    10 runs
```
Close to no difference in perfs but removing in parallel makes sense
**Checklist**

perf(fslib): run removePromise in parallel

---

.yarn/versions/509c08b4.yml
packages/acceptance-tests/pkg-tests-core/sources/utils/makeTemporaryEnv.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/install.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
packages/yarnpkg-core/sources/Project.ts

When workspace-a depends on workspace-b, where workspace-b has a build script and a peer dependency, the core will build workspace-b twice. Once for the original and once for the virtual version.
Check if the workspace locator is virtual and skip the build if it is.
**Checklist**

fix(core): skip building virtual workspaces

---

.yarn/versions/9c2796ec.yml
packages/plugin-essentials/sources/commands/dedupe.ts
packages/plugin-essentials/sources/commands/explain/peerRequirements.ts
packages/plugin-essentials/sources/commands/link.ts
packages/plugin-essentials/sources/commands/rebuild.ts
packages/plugin-essentials/sources/commands/set/resolution.ts
packages/plugin-essentials/sources/commands/up.ts
packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
packages/plugin-version/sources/commands/version/apply.ts
packages/plugin-workspace-tools/sources/commands/focus.ts
packages/yarnpkg-core/sources/Project.ts

When I moved the build state into the install state in https://github.com/yarnpkg/berry/pull/2574 commands that called `Project.install` but didn't call `Project.restoreInstallState` started causing all packages to rebuild
Call `Project.restoreInstallState`
**Checklist**

fix: restore build state to prevent rebuilds

---

packages/gatsby/content/features/plugnplay.md

See https://gohugo.io/hugo-pipes/babel/ - without resorting to the `node-modules` plugin, sadly, Hugo pipes cannot find dependencies such as babel. It looks like this has nothing to do with `$NODE_PATH`, it is simply incompatible with Yarn Berry. I've also filed an improvement proposal under gohugo: https://github.com/gohugoio/hugo/issues/8301
In case other people use Hugo in conjunction with Yarn Berry, without enabling the `node-modules` plugin, things go bad - provided you use a hugo pipe such as the babel preset. It expects mode packages to be in the classic dependency directory. 
I simply added hugo to the current incompatible list so other folks also know what's going on.

docs: Hugo 0.79+ extended does not work with PnP

---

.yarn/versions/ff187132.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
packages/yarnpkg-core/sources/Project.ts

If the build script `preinstall` fails `install` and `postinstall` is still run for a package and if those are successful the build is marked as successful even though it failed
Check if the script ran successfully and if it didn't, stop running scripts for that `Package`
**Checklist**

fix(core): don't run other build scripts for a `Package` when one failed

---

.yarn/versions/36558667.yml
packages/plugin-version/sources/commands/version/check.tsx
packages/plugin-version/sources/versionUtils.ts

The version plugin prints `PortablePath`s instead of `NativePath`s
Print `NativePath`s
**Checklist**

fix(version): print `NativePath`s instead of `PortablePath`s

---

.yarn/versions/e2ae2e88.yml
packages/yarnpkg-core/sources/TelemetryManager.ts

Datadog doesn't support sending multiple times the same tag with different values. As a result, the following payload:
```json
{
"versions": ["2.5.0", "2.4.0", "2.6.0"]
}
```
Is turned into `versions:2.5.0-2.4.0-2.6.0`. It makes it difficult to write queries like "how many people use the 2.4 line", since we now have to glob into the value. For instance here, we would have to write something like `versions:*-2.4.*`, but using wildcards as both prefix and suffix isn't supported by Datadog at the moment.
The telemetry manager will now submit one query for each metric (while still optimizing them to send multiple different metrics in the same batch). It means that the following:
```json
{
"versions": ["2.5.0", "2.4.0", …
```

Improves telemetry for better version support

---

.yarn/versions/41e6909c.yml
packages/esbuild-plugin-pnp/sources/index.ts

The esbuild pnp plugin throws if the path isn't under PnP instead of letting the next resolver run.
Return `undefined` on paths external to the pnpapi as documented here https://esbuild.github.io/plugins/#resolve-callbacks
> The callback can return without providing a path to pass on responsibility for path resolution to the next callback
**Checklist**

fix(esbuild): fallback to default resolver when path isn't under pnp

---

.yarn/versions/25c5db37.yml
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/tests/Configuration.test.ts

Boolean config settings containing env variables weren't being parsed correctly.
Fixes #2339.
In case a boolean config setting is a string, we now replace its env variables first.
**Checklist**

fix(core): parse boolean config settings containing env variables

---

.yarn/versions/5d046bd4.yml
packages/yarnpkg-core/sources/TelemetryManager.ts

The enumerators (ie properties submitted as the different number of elements rather than the elements themselves) were still stored in the telemetry file as their actual value. This wasn't a problem per-se (we never transmitted them), but it could be worrying for users to see them (it happened at least twice that someone thought we were accidentally sending them).
The file will now only contain their hash representation. It doesn't change anything functionally speaking, but now it's clearer that those values simply can't be leaked.
**Checklist**

Hash telemetry enumerators

---

packages/gatsby/src/components/markdown.js
packages/gatsby/src/components/toc/index.js
packages/gatsby/src/templates/article.js

This adds an `Edit this page on Github` link to markdown based documentation pages.
It should make it easy for people to contribute improvements, grammar fixes, etc, to the docs.
Added logic to parse out the absolute file path of an article and transform it to a github url that links to the specific page.
**Checklist**

docs: add edit on github link to doc pages

---

packages/gatsby/src/components/markdown.js
packages/gatsby/src/components/toc/index.js

fixes: 
Seems algolia parses the h1 as it is. This reorganizes the html so that the `h1` tag only contains the title, and moves the "Edit on GitHub" link outside of it
**Checklist**

docs: fix h1 css leaking into search results

---

.yarn/versions/cf75bb5b.yml
CHANGELOG.md
packages/plugin-essentials/sources/commands/plugin/import/sources.ts
packages/plugin-essentials/sources/commands/set/version/sources.ts

Each time the user runs `yarn set version from sources` they have to update the contrib plugins to that same commit, because otherwise things might break (e.g. plugin uses a function that doesn't exist anymore in the updated bundle).
`yarn set version from sources` will now update all existing contrib plugins automatically (can be toggled off by using the `--skip-plugins` flag). Currently, they are build sequentially because, this way, we can stream the output. When I get the time, I will open a followup PR that builds them in parallel while still somehow making the output look pretty.
**Checklist**

feat: make `yarn set version from sources` update contrib plugins

---

.yarn/versions/62828ed0.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/rcFiles.test.js
packages/yarnpkg-core/sources/Configuration.ts

When the users home directory is an ancestor of the current project directory the global config is parsed in strict mode which means having configs for newer versions of Yarn in the global config causes older versions to throw.
Mark the config in the home directory as non-strict so the location of it doesn't matter
**Checklist**

fix(core): always load home config in loose mode

---

.yarn/versions/11055917.yml
packages/yarnpkg-core/sources/Cache.ts

When a install is cancelled at just the right time the global cache gets corrupted while copying from the local cache to the global cache.
Fixes https://github.com/yarnpkg/berry/issues/2349
Create a second copy of the zip file entry and use a `move` to get the zip file into the global cache
**Checklist**

fix(core): use atomic writes for the global cache

---

.yarn/versions/b5ea4a20.yml
packages/plugin-version/sources/commands/version/apply.ts
packages/plugin-version/sources/commands/version/check.tsx
packages/plugin-version/sources/versionUtils.test.ts
packages/plugin-version/sources/versionUtils.ts
packages/plugin-workspace-tools/sources/commands/foreach.ts
packages/yarnpkg-core/sources/Workspace.ts

The current version workflow doesn't handle prereleases particularly well. It requires to know ahead of time whether a package will be released as prerelease or not, which doesn't match the reality (we often merge PRs, and only much later decide to cut a prerelease).
This PR removes the prerelease flag from the `yarn version check -i` command, and adds a new `--prerelease` flag to `yarn version apply`. Setting it has two effects:
- It prevents the version definitions from being discarded (since we need to recompute the new version from the latest stable at each new prerelease, we need to keep the list of changes since the latest stable).
- It adds a prerelease identifier at the end of the versions. The identifier is a …

Implements `yarn version apply --prerelease`

---

.yarn/versions/157b40e5.yml
packages/yarnpkg-core/sources/Project.ts
packages/yarnpkg-core/sources/StreamReport.ts

`preferAggregateCacheInfo` (defaults to true on CI) doesn't effect the cache cleanup causing a lot of info to be logged.
Respect `preferAggregateCacheInfo` in the cache cleanup and print a one line summary.
**Checklist**

feat(core): aggregate cache info for cache cleanup

---

.yarn/versions/2fd07169.yml
packages/plugin-init/sources/commands/init.ts

`yarn init` creates a `.gitattributes` by default to exclude `.yarn` from GitHub language statistics (`linguist`), but this is no longer necessary as [they are already ignored by linguist](https://github.com/github/linguist/blob/736df2bb2a78ccc23115cdeb33aef31156f3efac/lib/linguist/vendor.yml#L44-L49).
Remove related code.
**Checklist**

feat(plugin-init): stop creating unnecessary `.gitattributes`

---

.yarn/versions/12a089c0.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/focus.test.js
packages/plugin-workspace-tools/sources/commands/focus.ts

`yarn workspaces focus <somePackage>` was following workspace devDependencies and installing their dependencies, even when `--production` was turned on. This appears to be a bug.
...
When `--production` is passed, I only examine `dependencies`, not any dev deps.
**Checklist**

fix(workspace-tools): don't follow dev dependencies for `focus --production`

---

.yarn/versions/9179116a.yml
packages/acceptance-tests/pkg-tests-fixtures/packages/node-modules-path-1.0.0/bin.js
packages/acceptance-tests/pkg-tests-fixtures/packages/node-modules-path-1.0.0/package.json
packages/acceptance-tests/pkg-tests-fixtures/packages/node-modules-path-2.0.0/bin.js
packages/acceptance-tests/pkg-tests-fixtures/packages/node-modules-path-2.0.0/package.json
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/plugin-node-modules/sources/NodeModulesLinker.ts

`plugin-node-modules` picks the first bin it finds in any workspace instead of preferring the one in the current workspace
Closes #2666
Instead of picking the first match, we now look for the bin that is in the current workspace and fallback to the previous behavior.
**Checklist**

fix(node-modules): prefer binaries from calling workspace

---

packages/gatsby/content/advanced/error-codes.md

Fix a typo in the error docs.  It's `dependenciesMeta[].built` not `.build`.
#2705
**Checklist**

docs: fix typo for the YN0004 error code

---

packages/gatsby/static/configuration/yarnrc.json

`yarnUpgradePath` isn't a implemented setting but is documented as if it was
Fixes https://github.com/yarnpkg/berry/issues/1014
Remove the documentation for it
**Checklist**

docs: remove yarnUpgradePath

---

.yarn/versions/a4e08704.yml
packages/plugin-dlx/sources/commands/dlx.ts

Running `yarn dlx sb init` on a project with `enableGlobalCache: true` fails due to `Unable to locate pnpapi, the module '/foo/bar/baz' is controlled by multiple pnpapi instances` errors
Set `enableGlobalCache` to the opposite of the current value
**Checklist**

fix(dlx): set enableGlobalCache to the opposite of the current value

---

.pnp.cjs
.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/package.json
.yarn/versions/bb02f129.yml
package.json
packages/gatsby/package.json
packages/plugin-constraints/package.json
packages/plugin-exec/package.json
packages/plugin-interactive-tools/package.json
packages/plugin-stage/package.json
packages/plugin-typescript/package.json
packages/plugin-version/package.json
packages/plugin-workspace-tools/package.json
packages/vscode-zipfs/package.json
packages/yarnpkg-builder/package.json
packages/yarnpkg-cli/package.json
packages/yarnpkg-doctor/package.json
packages/yarnpkg-fslib/sources/NodeFS.ts
packages/yarnpkg-fslib/sources/ZipFS.ts
packages/yarnpkg-parsers/sources/grammars/shell.pegjs
packages/yarnpkg-pnp/package.json
packages/yarnpkg-pnp/sources/loader/internalTools.ts
packages/yarnpkg-pnpify/package.json
yarn.lock

Bumps TypeScript to 4.3 beta. Hopefully we'll catch bugs if there are any (my own editor made a mess by crashing the TS server repeatedly but I'm not sure why ... after enabling the logs the crashes stoped, and didn't come back when I removed them again 🤔).
n/a
**Checklist**

Bumps TypeScript

---

.yarn/versions/d4afcb16.yml
packages/plugin-dlx/sources/commands/dlx.ts

To run packages like `yeoman` you need to install the `yo` package and some kind of generator at the same time, doing this with `yarn dlx` is not possible as it only accepts one package
Fixes #2572 
Fixes #944
Allow specifying an array of packages, example:
```
yarn dlx -p generator-joplin -p yo yo joplin
```
`yo` isn't actually able to find the generators but they are installed so that's an upstream issue
**Checklist**

feat(dlx): allow specifying an array of packages

---

.yarn/versions/4a4e5597.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/immutablePatterns.test.ts
packages/yarnpkg-core/sources/Project.ts

Fixes #2699
`immutablePatterns` cannot cover `package.json`.
Create `before` hashes before persisting the project.
**Checklist**

fix(core): `--immutable` covers Project.persist

---

.github/workflows/e2e-vue-cli-workflow.yml
.yarn/versions/0ae1c66a.yml
packages/plugin-dlx/sources/commands/dlx.ts

Running `yarn dlx` on a package where the binary name doesn't match the package name requires explicitly listing it using `yarn dlx -p <package> <binary name>`, but this is only necessary if the package has multiple binaries.
Closes #2013
If there is only one binary available and the binary name wasn't explicitly provided use it instead of the package name
**Checklist**

fix(dlx): use binary name if package name doesn't match

---

.yarn/versions/51068c25.yml
packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts

`@yarnpkg/pnpify` is importing from `@yarnpkg/core/sources/structUtils` which doesn't exist when published
Fixes https://github.com/yarnpkg/berry/runs/2322171355#step:5:124
Use `structUtils` from `@yarnpkg/core` instead
**Checklist**

fix(pnpify): avoid importing from sources

---

.yarn/versions/41b9f38e.yml
packages/plugin-essentials/sources/commands/plugin/import.ts
packages/plugin-version/sources/commands/version/check.tsx

Plugins are currently downloaded straight from master. It has various drawbacks:
- Users still on the latest stable automatically get the rc plugins when running `yarn plugin import`.
- If we don't store the plugins in the repo until stable, then users using rc releases can't use plugins.
This PR changes from where official plugins will be downloaded. Instead of being from `master`, they'll now be downloaded from the `@yarnpkg/cli/<version>` tag, where `<version>` will be the version for the CLI running the command. This ensures that someone running `yarn plugin import` will always get the plugin version at the time of the release for their CLI.
I've also made it possible to import any specific version of the plugin, just …

Downloads the compatible plugin for the current Yarn version if possible

---

packages/gatsby/content/advanced/error-codes.md

`--frozen-lockfile` is deprecated.
**Checklist**

docs: change references to `--frozen-lockfile` to `--immutable`

---

packages/gatsby/content/advanced/plugin-tutorial.md

According to the source code, the signature is `setupScriptEnvironment(project: Project, env: {[key: string]: string}, makePathWrapper: (name: string, argv0: string, args: Array<string>) => Promise<void>`.
https://github.com/yarnpkg/berry/blob/dfda0204eef1503cc650fb5c77c4fdcedc37d769/packages/plugin-pnp/sources/index.ts#L25
So the example in the doc seems to be wrong (as it says that the 1st argument is the envs and not the project.

docs: fix plugin example for using hooks

---

.yarn/versions/85263fbb.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
packages/plugin-pnp/sources/jsInstallUtils.ts

Documentation states that you should get an info for any dependency
with `dependenciesMeta[].built: false` and `enableScripts: false`, but you currently get a warning.
Fixes #2705
Reorder "scripts disabled" reports
**Checklist**

fix(plugin-pnp): fix build script disabled logging

---

scripts/dist-scripts/yarn
scripts/dist-scripts/yarn.cmd
scripts/release/03-release-npm.sh

Volta would benefit from the shims being in the archive (https://github.com/volta-cli/volta/issues/651#issuecomment-818990073).
Note that those scripts are generally untested (which is why they were initially removed) and currently provided on a best effort basis, so YMMV.
Added the shims we already had to the archive. It won't affect the 2.4.1, since it has already been published, but will benefit starting from 3.0.0-rc.3.
**Checklist**

Adds the dist-scripts to the released packages

---

.yarn/versions/cb4fb96b.yml
packages/yarnpkg-core/sources/hashUtils.ts

`hashUtils.makeHash` calls `Hash.update` for every argument
Concat all string arguments in a row before calling update
**Results**
Testing on the repro provided in https://github.com/yarnpkg/berry/issues/973#issuecomment-589201567
```diff
- 712ms (29%)     resolvePeerDependenciesImpl
+ 525ms (23.07%)  resolvePeerDependenciesImpl
```
**Checklist**

perf(core): concat strings before computing hash

---

.yarn/versions/b3f26d64.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
packages/plugin-pnp/sources/PnpLinker.ts

When deleting the `.yarn/unplugged` folder (or any folder in it) Yarn will reinstall the package(s) but not run any build scripts for them.
Fixes https://github.com/yarnpkg/berry/issues/2452 (One of the reasons I implemented https://github.com/yarnpkg/berry/pull/2574)
If the `.ready` file is missing delete the locator from `Project.storedBuildState`.
**Checklist**

fix(plugin-pnp): delete stale build state when unplugged folder is missing

---

packages/gatsby/content/advanced/pnp-api.md

There was an incorrect link in [pnpapi docs](https://yarnpkg.com/advanced/pnpapi).
...
I removed the unnecessary hyphen(-).
...
**Checklist**

docs: Fix incorrect link in pnpapi docs

---

.yarn/versions/f01fa2ef.yml
packages/yarnpkg-fslib/sources/ZipOpenFS.ts
packages/yarnpkg-fslib/tests/ZipOpenFS.test.ts

`findZip` inside `ZipOpenFS` isn't as fast as it can be because we use a regexp to extract the archive part from paths.
By using an `indexOf`-based implementation that is 3.7x faster.
Profiled on the Storybook repo (lockfile only install):
- Before: `337.0 ms` (spent executing the regexp)
- After: `89.2 ms` (spent inside `getArchivePart`)
I haven't tested how much it improves PnP runtime's perf, but it would be interesting to see. :thinking:
**Checklist**

perf(ZipOpenFS): replace FILE_PARTS_REGEX with indexOf implementation

---

packages/yarnpkg-shell/README.md

Running the example for `@yarn-pkg/shell` as-is yields an `Unbound argument #1` error. The wrong example makes using arguments confusing until you try to pass more than one argument, especially considering the indices are different than the normal argument variables in a typical script.
No issue filed.
...
Updated the docs example to use `$0` instead of `$1`. This matches the usage in the [relevant test](https://github.com/yarnpkg/berry/blob/master/packages/yarnpkg-shell/tests/shell.test.ts#L397).
...
**Checklist**

docs(shell): fix example in readme

---

.yarn/versions/bdbb6a34.yml
packages/yarnpkg-core/sources/Project.ts

During an install Yarn serializes and compresses the install state twice when it hasn't changed, once before checking build scripts and once after everything is done, which with a large Project is expensive.
- Don't call `Project.persistInstallStateFile` unless a build actually needs to run
- Check if the serialized state is different from the previous one before compressing it
**Result**
Running `yarn install` in the Storybook repo (using PnP) when nothing has changed
```diff
- Done with warnings in 4s 748ms
+ Done with warnings in 3s 569ms
```
Gatsby benchmark
```diff
$ bash scripts/bench-run.sh yarn gatsby $(mktemp -d)
Benchmark #1: yarn add dummy-pkg@link:./dummy-pkg
-  Time (mean ± σ):      2.901 s ±  0.061 s    [User: …
```

perf(core): avoid persisting install state if it didn't change

---

.yarn/versions/4d8c2fcd.yml
packages/yarnpkg-shell/sources/index.ts
packages/yarnpkg-shell/tests/shell.test.ts

The shell wasn't throwing errors when redirecting to files in non-existent folders on Node 14.x (it works on all other versions).
Fixes #2818.
Explicitly reject the promise on write stream errors.
**Checklist**

fix(shell): throw error when redirecting to file in non-existent folder

---

packages/gatsby/content/getting-started/questions-and-answers.md

When the Yarn release and plugin bundles change, Git uses its standard line-by-line diff to show the changes.  This is probably not what you want, since those bundles are not really meant to be read by a human.
In my repo, I used ".gitattributes" to tell Git to treat them like binary files, which reduces the amount of garbage in the "git diff" output.  I thought this tip might be worth sharing on the official website.
...
...
**Checklist**

[website] Recommend using .gitattributes to treat release and plugin bundles as "binary"

---

.yarn/versions/0cbbb51e.yml
packages/yarnpkg-doctor/README.md
packages/yarnpkg-doctor/fixtures/bundle-dependencies/package.json
packages/yarnpkg-doctor/fixtures/bundled-dependencies/package.json
packages/yarnpkg-doctor/sources/cli.ts

I've just come across one of my old stashes - it makes the doctor warn when the `bundleDependencies` or `bundledDependencies` fields are used.
...
**Checklist**

feat(doctor): warn on bundleDependencies

---

.yarn/versions/45babb85.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/link.test.js
packages/plugin-essentials/sources/commands/link.ts

`yarn link` loads plugins from the target causing errors if the CLI versions mismatch
Skip loading plugins in the link target
**Checklist**

fix(essentials): skip loading external plugins when using `yarn link`

---

packages/gatsby/content/features/plugins.md

Adds a license plugin to the list of community plugins.
I found this plugin at [issue 1164](https://github.com/yarnpkg/berry/issues/1164#issuecomment-786720087). This plugin is especially useful for enforcing in CI that no direct or indirect dependencies with incompatible licenses are added to your project.
**Checklist**

Add license plugin to list of community plugins

---

.vim/coc-settings.json
.yarn/sdks/integrations.yml
.yarn/sdks/typescript/lib/tsserver.js
.yarn/versions/18b674ec.yml
packages/yarnpkg-pnpify/sources/sdks/base.ts

fixes https://github.com/neoclide/coc-tsserver/issues/244
https://twitter.com/KrComet/status/1370033304464855044
`gd`(Go to Definition) is not working for [coc-tsserver](https://github.com/neoclide/coc-tsserver) host.
...
I was looking for a way to search inside zip with vim, and it seems to possible with [vim-rzip](https://github.com/lbrayner/vim-rzip) plugin.
This patch makes it possible to resolve paths compatible with vim-rzip in the coc-nvim host.
https://github.com/lbrayner/vim-rzip is required for the user's vim config.
...

fix(pnpify): make go to definition work with coc.nvim

---

.yarn/versions/eeae7dcf.yml
packages/acceptance-tests/pkg-tests-specs/sources/protocols/patch.test.js
packages/plugin-patch/sources/tools/parse.ts

When adding a patch file with invalid content Yarn "applies" it successfully even though it didn't apply anything
Fixes https://github.com/yarnpkg/berry/issues/2553
Throw if no changes were found in the patch file
**Checklist**

fix(patch): throw on patch files without changes

---

.gitignore
.yarn/versions/c743d681.yml
packages/plugin-npm/sources/Hooks.ts
packages/plugin-npm/sources/index.ts
packages/plugin-npm/sources/npmConfigUtils.ts
packages/plugin-npm/sources/npmHttpUtils.ts

Adds a hook for adding authentication headers, intended to be used for OAuth style authentication flows.
Closes #2067
...
I used reduceHook inside getAuthenticationHeader to collect the potential values from the hook, then return the provided value if there is one instead of checking npmAuthToken or npmAuthIdent
...
**Checklist**

feat(npm): add hook for getting the authentication header

---

.yarn/versions/7a4b3cc0.yml
packages/vscode-zipfs/sources/TerminalLinkProvider.ts
packages/vscode-zipfs/sources/index.ts

In https://github.com/yarnpkg/berry/pull/1835 I forgot to add the disposable returned by `vscode.window.registerTerminalLinkProvider` to `context.subscriptions`
Added it
**Checklist**

fix(vscode-zipfs): add `TerminalLinkProvider` disposable to `context.subscriptions`

---

.yarn/versions/785fed9b.yml
packages/plugin-essentials/sources/commands/set/version.ts

- `yarn set version ...` downloads a bundle and runs `--version` on it from the cwd of the project, if the project contains a configuration the new bundle doesn't support it fails
- If the version returned by the new bundle is invalid Yarn doesn't include it in the error message making it rather vague
- Run the command in the temp directory
- Include the version in the error
**Checklist**

fix(essentials): `set version` - get version of bundle in a temp directory

---

.yarn/versions/62765bae.yml
packages/yarnpkg-fslib/sources/algorithms/watchFile/CustomStatWatcher.ts

This PR removes an outdated comment that I left when I first implemented the `CustomStatWatcher` that described the fact that bigint stats weren't supported.
...
**Checklist**

chore: remove outdated bigint comment

---

.yarn/versions/56bdc806.yml
packages/plugin-patch/sources/patchUtils.ts

`yarn patch-commit` (`patchUtils.diffFolders`) can end up with different output on different systems depending on their global config.
Guessing this is the issue in https://github.com/yarnpkg/berry/issues/2852 since whitespace changes isn't visible in their diff.
Ignore the global git config
**Checklist**

fix(patch): ignore global git config

---

.yarn/versions/939a73e5.yml
packages/yarnpkg-builder/README.md

Related to: #2872.
Fixes confusion relating to usage of the plugin builder, as the current version is for building Yarn 3 plugins, but this is not obvious. This is compounded by the fact that the [Yarn 2.0 docs recommend usage of the builder](https://yarnpkg.com/advanced/plugin-tutorial/#gatsby-focus-wrapper) without mentioning that you must use v2.x of the builder to make plugins compatible with Yarn 2.
Added a note to the builder readme explaining that the current version is for building Yarn 3 plugins, and recommending usage of `@yarnpkg/builder@^2` if the user wants to build plugins for 2.x.
**Checklist**

docs(builder): add note about v3.0 vs v2.0 plugins

---

.yarn/versions/54411559.yml
packages/plugin-patch/sources/commands/patch.ts

Running `yarn patch <package-name>` prints instructions to run `yarn patch-commit <absolute path>` when you're done editing the sources, this path is unquoted on Windows which means users need to manually quote it if they're using a terminal other than CMD and PowerShell.
Quote the path on Windows
**Checklist**

fix(patch): quote path in `yarn patch` output on Windows

---

.yarn/versions/f0d52d1c.yml
packages/yarnpkg-core/sources/hashUtils.ts

`fs.createReadStream` has to allocate a new Buffer for each read operation because it can't safely reuse the Buffer from the previous read.
Allocate a Buffer once in `hashUtils.checksumFile` and reuse it for each read operation on a file.
**Result**
Storybook repo
```diff
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 4288 packages were already cached
- ➤ YN0000: └ Completed in 1s 118ms
+ ➤ YN0000: └ Completed in 0s 863ms
```
Gatsby benchmark
```diff
bash scripts/bench-run.sh yarn gatsby (mktemp -d)
Reflink aren't supported! Installs may be quite slower than necessary
Testing install-ready
Benchmark #1: yarn add dummy-pkg@link:./dummy-pkg
-  Time (mean ± σ):      2.771 s ±  0.076 s    [User: 2.577 s, System: 0.452 s]
+  Time (mean ± …
```

perf(core): handle Buffer allocation in `hashUtils.checksumFile`

---

.yarn/versions/76e603e2.yml
packages/plugin-essentials/sources/commands/set/version.ts
packages/plugin-git/sources/gitUtils.ts
packages/plugin-npm-cli/sources/commands/npm/info.ts
packages/plugin-pnp/sources/commands/unplug.ts
packages/plugin-typescript/sources/index.ts
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/LegacyMigrationResolver.ts
packages/yarnpkg-core/sources/Workspace.ts
packages/yarnpkg-core/sources/semverUtils.ts

There are still some locations in Yarn that uses uncached semver ranges slowing down installs.
Continues https://github.com/yarnpkg/berry/pull/1738
Cache `semverUtils.satisfiesWithPrereleases` and ensure all places in the codebase using semver uses `semverUtils.validRange` for ranges
**Result**
Installing the Storybook repo
```diff
➤ YN0000: ┌ Resolution step
- ➤ YN0000: └ Completed in 1s 46ms
+ ➤ YN0000: └ Completed in 0s 881ms
```
**Checklist**

perf: cache more semver ranges

---

.yarn/versions/3838bd93.yml
packages/yarnpkg-core/sources/formatUtils.ts

Hyperlinks were broken in Konsole because it doesn't support the non-standard `BEL` sequence in the case of hyperlinks.
Use the standard `ESC` sequence when Yarn is run from Konsole.
**Checklist**

fix(core): use correct sequence for hyperlinks in konsole

---

.yarn/versions/c5e90091.yml
packages/yarnpkg-core/sources/formatUtils.ts

CircleCI doesn't support hyperlinks so the CLI output looks horrible
```
➤ ]8;;https://yarnpkg.com/advanced/error-codes#yn0013---fetch_not_cachedYN0013]8;;: │ 5 packages were already cached, 1369 had to be fetched
➤ YN0000: └ Completed in 1m 38s
➤ YN0000: ┌ Link step
➤ ]8;;https://yarnpkg.com/advanced/error-codes#yn0062---incompatible_osYN0062]8;;: │ fsevents@patch:fsevents@npm%3A2.3.2#builtin<compat/fsevents>::version=2.3.2&hash=11e9ea The platform linux is incompatible with this module, link skipped.
➤ ]8;;https://yarnpkg.com/advanced/error-codes#yn0062---incompatible_osYN0062]8;;: │ fsevents@patch:fsevents@npm%3A1.2.13#builtin<compat/fsevents>::version=1.2.13&hash=11e9ea The platform linux is incompatible with this module, link …
```

fix(core): disable hyperlinks on circleci

---

.yarn/versions/570544e2.yml
packages/acceptance-tests/pkg-tests-specs/sources/basic.test.js
packages/yarnpkg-core/sources/Project.ts

Peer dependencies with a fallback doesn't work if the parent has an unmet peer dependency on the same dependency. In the following dependency tree `lib-2` should have access to `lodash` but doesn't
```
.
├── root
│   └── dependencies
│       └── lib-1
├── lib-1
│   ├── dependencies
│   │   └── lib-2
│   └── peerDependencies
│       └── lodash
└── lib-2
├── dependencies
│   └── lodash
└── peerDependencies
└── lodash
```
When the descriptor from the parent has a `missing:` range use the fallback instead
**Checklist**

fix(core): use dependencies if peer dependency wasn't provided

---

packages/gatsby/content/features/plugins.md

Adds "yarn semver up" plugin: https://github.com/tophat/yarn-plugin-semver-up to contrib page.
Note: the "preserve semver" functionality would actually be nice as an option in yarn's built-in "up" command. The group config that semver up supports doesn't make sense as a builtin though.
**Checklist**

docs: add semver up plugin to contrib plugins page

---

.yarn/versions/2b43493b.yml
packages/plugin-version/sources/commands/version.ts

Usage details for `--deferred` told the user to consult documentation for "Managing Releases", which when searched for, returned no results.
Found no open issues referring to this.
...
Direct the user directly to the intended place in the documentation via a link.
...
**Checklist**

docs(plugin-version): update the usage details to point to the correct docs

---

.yarn/versions/bd18fea1.yml
packages/yarnpkg-core/sources/Project.ts

`Project.tryWorkspaceByDescriptor` and `Project.tryWorkspaceByLocator` devirtualizes the descriptor/locator even if the ident doesn't match a workspace.
Check if the descriptor/locator matches a workspace before devirtualizing them
**Result**
Tested on the Storybook repo using PnP
```
$ YARN_IGNORE_PATH=1 hyperfine -w 5 'nodejs before.js' 'nodejs after.js'
Benchmark #1: nodejs before.js
Time (mean ± σ):      5.217 s ±  0.047 s    [User: 5.538 s, System: 1.219 s]
Range (min … max):    5.179 s …  5.339 s    10 runs
Benchmark #2: nodejs after.js
Time (mean ± σ):      5.156 s ±  0.013 s    [User: 5.535 s, System: 1.194 s]
Range (min … max):    5.137 s …  5.176 s    10 runs
Summary
'nodejs after.js' ran
1.01 ± 0.01 times faster …
```

perf(core): only devirtualize when ident matches a workspace

---

.yarn/versions/ca467354.yml
.yarn/versions/cd76e49c.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/unlink.test.js
packages/gatsby/content/getting-started/migration.md
packages/plugin-essentials/sources/commands/link.ts
packages/plugin-essentials/sources/commands/unlink.ts
packages/plugin-essentials/sources/index.ts
packages/yarnpkg-core/sources/miscUtils.ts
packages/yarnpkg-core/tests/miscUtils.test.ts

As a developer, I want to link local packages for local development, but revert the local links before committing other package.json and yarn.lock changes to the upstream VCS repository.
Currently the "reverting" process requires manual modification of the package.json. Manual modification means we rely on hacked together scripts to achieve automation (CI, commit hooks, dev experience tooling, etc).
This functionality to remove the effects of a `yarn link` should be present in yarn.
This closes #2459
Add a complimentary command `yarn unlink` which takes the same workspace path as `yarn link` (so it's the opposite), and removes resolutions from the top level manifest.
**Checklist**

feat(essentials): add unlink command

---

.github/workflows/e2e-preact-cli-workflow.yml
README.md
packages/gatsby/content/features/plugnplay.md

Preact CLI has PnP support now so we should have an e2e test to cover it
https://github.com/preactjs/preact-cli/pull/1418
Added a test
**Checklist**

ci: add preact cli e2e test

---

.yarn/versions/deebfe02.yml
packages/plugin-pnp/sources/PnpLinker.ts
packages/yarnpkg-core/sources/Project.ts

`@yarnpkg/core` is calling `Installer.installPackage` for workspaces without checking if the `Linker` supports it
Check `Linker.supportsPackage` before calling `Installer.installPackage` for workspaces
**Result**
Tested on the Storybook repo using PnP
```
$ YARN_IGNORE_PATH=1 hyperfine -w 5 './nodejs before.cjs' './nodejs after.cjs'
Benchmark #1: ./nodejs before.cjs
Time (mean ± σ):      4.279 s ±  0.036 s    [User: 5.421 s, System: 0.975 s]
Range (min … max):    4.253 s …  4.374 s    10 runs
Benchmark #2: ./nodejs after.cjs
Time (mean ± σ):      3.930 s ±  0.048 s    [User: 5.028 s, System: 0.863 s]
Range (min … max):    3.891 s …  4.054 s    10 runs
Summary
'./nodejs after.cjs' ran
1.09 ± 0.02 times faster than './nodejs …
```

fix(core): only call `installPackage` if the `Linker` supports it

---

.yarn/versions/10adb297.yml
packages/yarnpkg-core/sources/Configuration.ts

[`esbuild@0.8.43`](https://github.com/evanw/esbuild/releases/tag/v0.8.43) stopped emitting the `__esModule` flag for ESM to ESM imports (I think) causing all built-in plugins to be registered incorrectly.
Ignore the `__esModule` flag and just use `default` if it's defined
**Extra**
I didn't update to a newer esbuild version as it consistently panics on Windows when node is about to terminate
cc @evanw
```
panic: <object>
goroutine 7 [running]:
syscall.mapJSError(0x7ff8000100000f86, 0xb956e98, 0x17080008, 0x7ff8000100000f86)
/usr/local/go/src/syscall/fs_js.go:552 +0x1e
syscall.fsCall.func1(0x7ff8000100000005, 0xb956e88, 0x3f71480, 0x1, 0x1, 0xb956e90, 0x40000838f00)
/usr/local/go/src/syscall/fs_js.go:507 +0xb …
```

fix(core): ignore `__esModule` and always use `default` when defined

---

.yarn/versions/0d703eae.yml
packages/acceptance-tests/pkg-tests-specs/sources/auth.test.js
packages/plugin-npm/sources/npmHttpUtils.ts

npmAuthIdent needs to be base64 encoded as it's passed via HTTP Basic Auth.
If we detect a `:`, which is not a character in the base64 character set, we assume the value is not encoded and encode it for the user.
**Checklist**

fix: handle non-encoded npmAuthIdent

---

.yarn/versions/91427522.yml
packages/plugin-essentials/sources/index.ts

`@yarnpkg/plugin-essentials` is exporting `suggestUtils.ts` as both `dedupeUtils` and `suggestUtils`
Correct the path for the `dedupeUtils` import
**Checklist**

fix(essentials): export `dedupeUtils` from `./dedupeUtils`

---

README.md

The Preact badge I added in https://github.com/yarnpkg/berry/pull/2958 isn't showing up
Had GitHub generate a working one at https://github.com/yarnpkg/berry/actions/workflows/e2e-preact-cli-workflow.yml
**Checklist**

chore: fix preact e2e badge

---

.yarn/versions/04e0bcd3.yml
packages/yarnpkg-builder/sources/commands/build/plugin.ts

On Windows esbuild doesn't create the output directory recursively
Create the directory before running the build
**Checklist**

fix(builder): create output directory before building

---

.yarn/versions/7fbc3933.yml
packages/esbuild-plugin-pnp/sources/index.ts

`esbuild-plugin-pnp` didn't take into account the `external` field.
Fixes #2838.
The plugin will now support both simple module identifiers (`clipanion`) and wildcards (`cli*anion`). We don't need to implement support for absolute paths as, from my testing, they don't affect modules at all.
I implemented support for wildcards using a very similar implementation to the one in ESBuild (which we can't use because it's internal).
**Checklist**

fix(esbuild-plugin-pnp): respect `external` field

---

packages/gatsby/static/configuration/yarnrc.json

- `packageExtensions.<package>.peerDependenciesMeta` isn't documented on the website
- `packageExtensions.<package>.dependenciesMeta` is in the yaml manifest but isn't a valid setting
Fixes https://github.com/yarnpkg/berry/issues/1658
- Added some example keys so its visible
- Removed it
**Checklist**

docs: document `packageExtensions.<package>.peerDependenciesMeta`

---

packages/gatsby/static/configuration/yarnrc.json

I forgot to add example keys when I implemented `networkSettings.foo.enableNetwork` in https://github.com/yarnpkg/berry/pull/2030 and `networkSettings.foo.http(s)Proxy` in https://github.com/yarnpkg/berry/pull/2156 so they're not visible on the website
Added the missing `_exampleKeys` values
**Checklist**

docs: fully document `networkSettings`

---

packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
packages/acceptance-tests/pkg-tests-specs/sources/features/initFields.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/workspace.test.ts

Something that has been bothering me for a long time: the lack of editor completions when using the `run` function in tests.
By strongly typing it.
**Checklist**

refactor(pkg-tests-core): strongly typed run option bag

---

packages/gatsby/content/features/plugnplay.md

Gatsby's Yarn PnP version support information is misleading
I explicitly stated the fact that Gatsby v3 does not support Yarn PnP
**Checklist**
**References**
- https://www.gatsbyjs.com/docs/reference/release-notes/v3.7/#yarn-2-pnp-support

docs: PnP is supported with Gatsby 3.7.0+

---

.yarn/versions/31b9bbb3.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/link.test.js
packages/plugin-essentials/sources/commands/link.ts

Running `yarn link -Ap ~/foo` in PowerShell on Windows will link the current project to itself which most likely isn't what the user wanted to do.
Disallow linking a Project to itself
**Checklist**

fix(essentials): disallow linking a project to itself

---

.yarn/versions/37951b26.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/config/set.test.ts
packages/plugin-essentials/sources/commands/config/set.ts

Running `yarn config set --home` from a non-project folder throws an error.
I made it skip throwing the error when the `-H,--home` flag is used.
**Checklist**

fix: allow running `yarn config set --home` from arbitrary folders

---

.yarn/versions/ee01ac4d.yml
packages/plugin-npm/sources/npmHttpUtils.ts
packages/yarnpkg-core/sources/httpUtils.ts

Parsing URLs is expensive
- Reuse URL instances by making some methods accept a `string | URL` and passing the parsed URL to them
- Avoid parsing known invalid URLs
**Result**
Tested on the Gatsby benchmark with a cached registry to avoid external network latency and a hot cache to only measure the time spent on resolution
```
YARN_IGNORE_PATH=1 hyperfine -w 1 --prepare="rm -rf yarn.lock .yarn" "node before.cjs --skip-builds" "node after.cjs --skip-builds"
Benchmark #1: node before.cjs --skip-builds
Time (mean ± σ):     10.702 s ±  0.067 s    [User: 11.845 s, System: 1.473 s]
Range (min … max):   10.631 s … 10.856 s    10 runs
Benchmark #2: node after.cjs --skip-builds
Time (mean ± σ):     10.609 s ±  0.056 s    [User: …
```

perf: reduce the amount of URL parsing

---

.yarn/versions/816bc982.yml
packages/plugin-npm/sources/npmConfigUtils.ts

I am using npmHttpUtils.get in another open source project, and am passing a registry url with a trailing slash. Since Yarn normalizes the trailing slashes in the config, it doesn't match any credentials. I can normalize the url before passing it to yarn using the normalize function, however the nature of the normalization seems like an implementation detail, and we also normalize in some other functions in the config utils file.
Normalize the URL that we use to index into the npmRegistries map, so both the index and the Map keys have undergone the same transformation.
**Checklist**

fix: normalize registry when indexing into registry config

---

.pnp.cjs
.yarn/versions/2cb94862.yml
packages/plugin-version/package.json
packages/plugin-version/sources/index.ts
yarn.lock

Title is self-explanatory. I'm currently attempting to make a plugin that reuses parts of the release flow, but I can't import `versionUtils` at runtime.
...
I followed the same pattern as the other plugins for exporting utils under a namespace.
...
**Checklist**

export versionUtils from @yarnpkg/plugin-version

---

.yarn/versions/69f77a2e.yml
packages/yarnpkg-core/sources/Workspace.ts

When `globby` returns absolute paths from a UNC directory it returns the paths with forward slashes which isn't valid making Yarn unable to locate workspaces.
Use relative paths so they can be joined with the cwd correctly
**Checklist**

fix(core): handle UNC path on Windows when locating workspaces

---

.yarn/versions/062c5159.yml
packages/yarnpkg-builder/sources/commands/build/plugin.ts

Plugins can't bundle deep imports to dynamic libs where they could before. I have some Yarn 2 plugins that depend on some of `@yarnpkg/core`'s internals.
...
This appears to be a regression from the refactoring in #2717. Previously, `isDynamicLib` was passed the full request path, but now it only receives the package ident. I think the old behavior was more desirable as Yarn would bundle the internal code into the plugin bundle, now it just prints this at runtime:
```
This plugin cannot access the package referenced via @yarnpkg/core/... which is neither a builtin, nor an exposed entry
```
...
**Checklist**

fix(builder): pass full request path to isDynamicLib

---

.yarn/versions/375ad2da.yml
packages/yarnpkg-core/sources/StreamReport.ts

Running `yarn dlx --quiet` on CI still printed `yarn add`'s group markers.
Sherlock snippet from #3056:
```
Error: expect(received).toStrictEqual(expected) // deep equality
Expected: "2"
Received: "::group::Resolution step
::endgroup::
::group::Fetch step
::endgroup::
::group::Link step
::endgroup::
8"
```
Don't print group markers unless `includeInfos` is `true` (the same condition for printing the header and the footer of timers).
**Checklist**

fix(dlx): don't print ci group markers when --quiet is used

---

.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/sdks/typescript/package.json
.yarn/versions/230b05c5.yml
packages/yarnpkg-pnpify/sources/sdks/base.ts

The TypeScript SDK doesn't include a wrapper around the `tsserverlibrary.js` file and only returns the Session instead of the entire lib in `tsserver`
Fixes https://github.com/yarnpkg/berry/issues/2986
Generate a wrapper for it and return the entire tsserver
**Checklist**

fix(pnpify): include wrapper for `tsserverlibrary.js` and return the entire `tsserver`

---

.yarn/versions/a32be810.yml
packages/plugin-pnp/sources/PnpLinker.ts

The `PnpInstaller` fetches data about packages even if it isn't going to use it which slows down installs in monorepos
Depends on https://github.com/yarnpkg/berry/pull/2904
Only fetch the data if it will be used
**Result**
Tested on the Storybook repo using PnP
```
YARN_IGNORE_PATH=1 hyperfine -w 5 'node master.cjs' 'node PR-2904.cjs' 'node after.cjs'
Benchmark #1: node master.cjs
Time (mean ± σ):      4.394 s ±  0.069 s    [User: 5.542 s, System: 1.059 s]
Range (min … max):    4.284 s …  4.510 s    10 runs
Benchmark #2: node PR-2904.cjs
Time (mean ± σ):      3.986 s ±  0.025 s    [User: 5.049 s, System: 0.976 s]
Range (min … max):    3.955 s …  4.041 s    10 runs
Benchmark #3: node after.cjs
Time (mean ± σ):      3.758 s ± …
```

perf(plugin-pnp): only load package data when needed

---

.yarn/versions/0467df86.yml
packages/yarnpkg-parsers/sources/grammars/shell.d.ts
packages/yarnpkg-parsers/sources/grammars/shell.js
packages/yarnpkg-parsers/sources/grammars/shell.pegjs
packages/yarnpkg-parsers/tests/shell.test.ts
packages/yarnpkg-shell/sources/index.ts
packages/yarnpkg-shell/tests/shell.test.ts

The shell didn't support redirection from file descriptors (e.g. `ls 2>/dev/null`).
Fixes #2778.
By implementing fd support in both input (e.g. `cat 0< README.md`) and output (e.g. `ls 2>/dev/null`) redirections.
**Checklist**

feat(shell): implement redirection from file descriptors

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/versions/137f9f5f.yml
packages/yarnpkg-pnpify/sources/sdks/base.ts

The TypeScript SDK's `tsserver` crashes if the project uses the `node-modules` linker instead of PnP
Disable the `moduleWrapper` if PnP isn't enabled
**Checklist**

fix(pnpify): only wrap `tsserver` if PnP is enabled

---

.yarn/versions/c0a0f3db.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/config/unset.test.js
packages/plugin-essentials/sources/commands/config/unset.ts

Note: This is #3014 but for `yarn config unset` - I completely forgot this command existed when I opened that PR.
Running `yarn config unset --home` from a non-project folder throws an error.
I made it skip throwing the error when the `-H,--home` flag is used.
**Checklist**

fix: allow running `yarn config unset --home` from arbitrary folders

---

.yarn/versions/6601a028.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/commands/config/unset.test.js
packages/plugin-essentials/sources/commands/config/unset.ts

`yarn config unset` didn't unset non-nested properties correctly, as it was returning the result of `unsetPath` which was always a boolean.
Fixes #3072.
Return the clone mutated by `unsetPath` instead.
**Checklist**

fix(unset): correctly unset non-nested properties

---

.yarn/versions/2a5b0f44.yml
packages/plugin-essentials/sources/commands/set/version.ts
packages/plugin-init/sources/commands/init.ts
packages/yarnpkg-cli/sources/main.ts
packages/yarnpkg-core/sources/Manifest.ts
packages/yarnpkg-core/sources/miscUtils.ts
packages/yarnpkg-core/sources/scriptUtils.ts

This commit improves the workflows around `yarn init` and `yarn set version` in various ways:
- It's now possible to run `yarn init` on a folder that already exists. It'll simply add the missing baseline files and fields.
- Running `yarn init` will set the `packageManager` field from Corepack.
- Similarly, `yarn set version` will set the field, ~~and `yarn set version from sources` will remove it~~.
- If Yarn detects that `yarnPath` points to the same binary content as the current one, it'll ignore it.
- The URLs used for `yarn set version` now come from our own website (cached behind Cloudflare).
- If operating within Corepack, the shims we add to the environment will point to it (rather than the current binary).
**Checklist**

Improvements to `yarn init` / `yarn set version`

---

.yarn/versions/591061ea.yml
packages/yarnpkg-core/sources/WorkerPool.ts

When libuv's code that retrieves the cpus fails, [Node falls back to `[]` as the return value for `os.cpus()`](https://github.com/nodejs/node/blob/6dfdb0a37cf0bf2bf08f50727d698699c3b8d105/lib/os.js#L135).
This causes Yarn to try to create a pool with 0 concurrent workers (which causes `p-queue` to throw) on unsupported platforms such as Android.
Use `Math.max(1, cpus.length())`.
The `yarn workspaces foreach` command [doesn't suffer from this issue because it already uses `1` as a fallback](https://github.com/yarnpkg/berry/blob/fce9eb661522bb3989a5eb0c1b3f87027f8a3970/packages/plugin-workspace-tools/sources/commands/foreach.ts#L155).
**Checklist**

fix(core): handle case when os.cpus().length is 0

---

.github/workflows/e2e-nm-angular-workflow.yml
.github/workflows/e2e-nm-babel-workflow.yml
.github/workflows/e2e-nm-berry-workflow.yml
scripts/e2e-setup-ci.sh

The gatsby e2e test has been unintentionally using the node-modules linker ever since we've started migrating projects with v1 lockfiles to v2 with nm.
Force all pnp e2e tests to use the pnp linker.
**Checklist**

ci(e2e): force pnp e2e tests to run with pnp linker

---

packages/gatsby/src/components/util.js

example URL that now works: https://yarnpkg.com/package/instantsearch.js
The url prefixes in readme and Changelog doesn't work if the path starts with `.`, like `.github/...`
simplified the prefixURL code, and removed the part that removes `./` from the start, as it's allowed as a base url
**Checklist**

docs: allow dotfiles

---

.yarn/versions/ce61ee0a.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/__snapshots__/mergeConflictResolution.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/features/plugins.test.js
packages/yarnpkg-core/sources/Configuration.ts

Some use cases need to access the configuration in order to extract information necessary to setup the CLI (https://github.com/yarnpkg/berry/issues/3077). This isn't possible at the moment (at least not without reimplementing some of the configuration loading).
Plugins can now be loaded asynchronously. Note that it shouldn't affect much the boot time, because this only affects the plugins loaded from the environment or rc files - the builtin ones are always injected synchronously.
**Checklist**

feat(core): Asynchronous plugin loading

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/versions/ac97a50e.yml
packages/gatsby/content/getting-started/editor-sdks.md
packages/yarnpkg-pnpify/sources/sdks/base.ts

Linked to https://github.com/theia-ide/typescript-language-server/pull/220
Neovim's native LSP client uses [theia-ide/typescript-language-server](https://github.com/theia-ide/typescript-language-server) to wrap `tsserver`. For go-to-definition to work yarn needs to resolve virtual filepaths to on-disk paths for neovim to open.
Followed example of how the issues was fixed for other editor implementations
https://github.com/yarnpkg/berry/pull/2598
**Checklist**

Support PnP with Neovim native LSP

---

.yarn/versions/06f8d539.yml
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/yarnpkg-pnpify/sources/buildNodeModulesTree.ts

The portal compatiblity check currently thinks that portal having unresolved peer dependency conflicts with the parent that has resolved peer dependency with the same name. They are compatible indeed, because when the peer dep is unresolved all bets are off and install should not stop because of this.
Ignores unresolved peer dependencies during portal compatibility check
**Checklist**

fix(node-modules) Exclude unresolved peer deps from portal compatibility check

---

.yarn/versions/60c8888c.yml
packages/yarnpkg-pnpify/sources/cli.ts
packages/yarnpkg-pnpify/sources/commands/SdkCommand.ts

We've refactored `@yarnpkg/pnpify` into 3 packages and moved the `pnpify --sdk` command to `@yarnpkg/sdks`, but there's no user-friendly error stating this.
Added a better error message when somebody uses `pnpify --sdk`.
**Checklist**

feat: add better error message to pnpify --sdk

---

packages/gatsby/content/getting-started/editor-sdks.md

There was an outdated reference to `@yarnpkg/pnpify` that should refer to `@yarnpkg/sdks` instead.
Changed it.
**Checklist**

docs: change outdated pnpify reference

---

.yarn/versions/e704a693.yml
packages/plugin-essentials/sources/commands/set/version.ts
packages/yarnpkg-core/sources/miscUtils.ts

When running `yarn set version from sources`, `bundleVersion` is `sources` and Yarn tries to set corepack's `packageManager` field to `yarn@sources` which isn't valid.
Check if the `bundleVersion` is valid semver before setting the field.
**Checklist**

fix: don't set packageManager field when bundleVersion isn't semver

---

.yarn/versions/6003d3e1.yml
packages/yarnpkg-builder/sources/commands/build/plugin.ts

It wasn't possible to configure the entry point of the builder when building plugins.
Closes #3114.
Use `main` as the entry point.
**Checklist**

feat(builder): use `main` field as entry point when building plugins

---

.yarn/versions/cf905fb9.yml
packages/plugin-essentials/sources/commands/add.ts

`yarn add` didn't respect `preferInteractive` anymore.
I added support for it in #1568 but it was accidentally regressed in https://github.com/yarnpkg/berry/pull/2370/files#diff-25c3769b5d919544ba1e2f3dd148d8ce448cd2af68363a129aec641d641c1c6dR94.
Removed the default value so that the `??` fallback can kick in when the `--interactive` / `--no-interactive` flag isn't used. 
**Checklist**

fix: respect preferInteractive in yarn add

---

.yarn/versions/27b1a1ae.yml
packages/eslint-config/rules/best-practices.js
packages/gatsby/src/utils/schemaUtils.tsx
packages/yarnpkg-fslib/sources/ProxiedFS.test.ts

#1729 replaced all instances of `@ts-ignore` (at that time) with `@ts-expect-error`, but since then a few others were introduced in the codebase because ESLint didn't report them as linting errors.
Enabled `@typescript-eslint/prefer-ts-expect-error` and autofixed things.
**Checklist**

chore: enforce using `@ts-expect-error` instead of `@ts-ignore`

---

.yarn/versions/68a43f48.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/pnpLoose.test.ts
packages/plugin-nm/sources/PnpLooseLinker.ts

PnP loose mode always expected a junction point, but there's no junction point when the root workspace doesn't depend on anything.
Fixes #3126.
Early return if there's no junction point.
**Checklist**

fix: root workspace without dependencies in pnp loose mode

---

.pnp.cjs
.yarn/versions/1299405d.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/version.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/version/apply.test.ts
packages/plugin-version/package.json
packages/plugin-version/sources/commands/version.ts
packages/plugin-version/sources/versionUtils.ts
packages/yarnpkg-core/sources/miscUtils.ts
yarn.lock

- The version plugin didn't validate the versions from the release files / applied by `yarn version`.
- The version plugin didn't support applying releases using the `: decline` syntax
I also wanted to add tests testing manual modifications to the version files but I haven't managed to get them to work.
**Checklist**

fix: validate strategies in version plugin and support ": decline"

---

CHANGELOG.md

Small fix in Markdown.
[Before](https://github.com/yarnpkg/berry/blob/f8561e3f6c6a7442186c5233c621b28aeefe53ae/CHANGELOG.md#installs):
[After](https://github.com/yarnpkg/berry/blob/64260d74ea9a3b191ff28fcfeac4afa213b00df8/CHANGELOG.md):

Fix nested list indentation in CHANGELOG

---

.yarn/sdks/eslint/package.json
.yarn/sdks/typescript/package.json
.yarn/versions/d9194fbe.yml
packages/yarnpkg-sdks/sources/generateSdk.ts

We changed the sdk versions to be fixed to `0.0.0-sdk` in https://github.com/yarnpkg/berry/pull/3069 thinking it wouldn't affect VSCode's behavior, but apparently VSCode uses it for TS feature detection: https://github.com/yarnpkg/berry/pull/3069#issuecomment-886107112.
Made it use the real version again.
**Checklist**

fix: use real sdk versions again

---

.yarn/versions/6b06cd35.yml
packages/yarnpkg-core/sources/semverUtils.ts
packages/yarnpkg-core/tests/semverUtils.test.ts

Some of the extensions added in https://github.com/yarnpkg/berry/pull/3082 didn't get applied since `satisfiesWithPrereleases` didn't match them correctly
Let `semver` see if the version satisfies the range and if it doesn't run our loose check
**Checklist**

fix(core): let `semver` try to match first in `satisfiesWithPrereleases`

---

.yarn/versions/8e84815d.yml
packages/yarnpkg-shell/sources/index.ts
packages/yarnpkg-shell/tests/shell.test.ts

The shell was overriding the file descriptors when applying a file redirection to a builtin. I don't exactly remember why, but I think it has to do with having to setup the new file descriptors while still preserving the context (since things like `cd > foo` should still update the cwd; they don't operate in a separate context). As a result, something like `echo foo > x; echo bar` was causing the `echo bar` to be written into the redirection (but after it closed, so it wasn't actually written).
I made the shell restore the streams after the builtin finishes executing. Some note:
- I got the idea from [this SO answer](https://unix.stackexchange.com/a/266824/24106), which seems to point out it's what shells do
- It means that …

Restores the fds after builtins finish executing

---

.pnp.cjs
.yarn/versions/0326a790.yml
packages/yarnpkg-builder/package.json
packages/yarnpkg-builder/sources/commands/build/bundle.ts
packages/yarnpkg-builder/sources/commands/build/plugin.ts
yarn.lock

There is a missing peer dependency warning from `@yarnpkg/builder` since we're depending on `esbuild-wasm` instead of `esbuild`
Extracted from https://github.com/yarnpkg/berry/pull/2919
Fixes https://github.com/yarnpkg/berry/pull/2919#discussion_r638478601
Alias `esbuild-wasm` to `esbuild`
**Checklist**

fix(builder): alias `esbuild-wasm` to `esbuild`

---

.yarn/versions/9c706891.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/version.test.ts
packages/plugin-version/sources/commands/version.ts

What the title says, it's a small edge case I forgot to handle in #3158.
...
**Checklist**

fix: support `yarn version decline --immediate` on top of stored version

---

.yarn/versions/6d93bfff.yml
packages/gatsby/content/getting-started/questions-and-answers.md
packages/plugin-essentials/sources/commands/run.ts

The `-T` and `-B` flags for `yarn run` are currently hidden but are really useful so we should document them
**Checklist**

fix(essentials): document `yarn run`'s `-T` and `-B` flags

---

.yarn/versions/0d41aab4.yml
.yarn/versions/cf96796f.yml
CHANGELOG.md
packages/yarnpkg-pnpify/sources/commands/RunCommand.ts

Closes https://github.com/yarnpkg/berry/issues/3225
Added double quotation marks to path so that paths containing spaces will no longer throw an error when using pnpify.
This is now possible since Node version 10 is no longer supported (double quotation marks are supported in Node as of version 12).
**Checklist**
Not sure if it's considered a patch or not so put `undecided`.
I think so.

fix(pnpify): quote require path

---

.yarn/versions/c4d7aa18.yml
packages/esbuild-plugin-pnp/sources/index.ts

It changed esbuild-plugin-pnp's default loader function to not using `utf-8` charset, which leaves raw data to esbuild and takes care of binary files (like .woff, .png).
Related issue outside: evanw/esbuild#1501
Fixes #2590
Just remove the charset field on read file.
**Checklist**

fix(esbuild): read file without charset

---

.github/workflows/pr-smart-merge.yml
.yarn/versions/d6f917f2.yml
.yarn/versions/e959dc6e.yml
packages/plugin-essentials/sources/commands/config/set.ts
packages/yarnpkg-core/sources/Configuration.ts

It's a bit annoying when multiple PRs affect the PnP hook, because each one need to be merged against master.
This diff doesn't entirely solve that, but it makes it easier to run the merge conflict resolution without having to checkout the PRs locally.
**Checklist**

Adds a workflow to auto-merge master into PRs

---

packages/gatsby/content/features/protocols.md
packages/plugin-patch/README.md

This PR is a documentation fix and makes the usage of the `patch-commit` command a bit clearer.
This is now more in line with the official [protocols documentation](https://yarnpkg.com/features/protocols).
**Checklist**

docs: make usage of the patch protocol clearer

---

packages/gatsby/content/getting-started/install.md

I added 3" number in the "berry" term explain at `getting-startted/install.md`.  
Because v3 development and shipping still running on "berry".  
Thank you for making excellent tool!
**Checklist**

[Docs] add "3" number in the "berry" term explain.

---

.yarn/versions/e1764054.yml
packages/vscode-zipfs/package.json
packages/vscode-zipfs/sources/index.ts

The extension isn't activated automatically when using `enableGlobalCache: true` since the workspace doesn't contain any `.zip` files. This means the `TerminalLinkProvider` can't do its job until after the extension is activated by the user performing a `Go to Definition` or otherwise manually interacting with it.
Added `onStartupFinished` to `activationEvents`
**Checklist**

fix(vscode-zipfs): add `onStartupFinished` to `activationEvents`

---

.yarn/versions/ad4d146d.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
packages/plugin-pack/sources/packUtils.ts

Resolves #3145 - see issue for rationale.
This unconditionally reloads the active workspace's manifest during `prepareForPack` after the prepack lifecycle script exits.
**Checklist**

feat(plugin-pack): reload manifest after prepack script

---

packages/gatsby/content/getting-started/editor-sdks.md

Neovim's native LSP doesn't support go-to-definition like behaviour unless using the nightly builds. This adds a note to the docs to explain this. Bit of a continuation of #3192.
Updated the docs copying note format from other note.
**Checklist**

Explain limitation to neovim native LSP go-to-definition support

---

.yarn/versions/52de201d.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/constraints.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints.test.js
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/query.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/source.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/environments.js
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/fix.test.js
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/query.test.js
packages/plugin-constraints/sources/tauModule.ts

`workspace_field` uses `String(...)` instead of `JSON.stringify(...)`.
Fixes #3282.
Made it use `JSON.stringify`.
**Checklist**

fix(constraints): use JSON.stringify in workspace_field

---

.pnp.cjs
.yarn/versions/0be2150d.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/query.test.js.snap
packages/gatsby/content/advanced/error-codes.md
packages/plugin-constraints/sources/Constraints.ts
packages/plugin-constraints/sources/tauModule.ts
packages/plugin-constraints/sources/tauProlog.d.ts
packages/plugin-nm/package.json
packages/yarnpkg-core/sources/MessageName.ts
yarn.lock

The Prolog errors were kinda broken.
- Fixes our types to rename `throwError` into `throw_error`.
- Fixes instantiation error reporting.
- Adds documentation explaining the error.
**Checklist**

Fixes Prolog errors

---

.yarn/versions/033ce877.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/add.test.ts.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/add.test.ts
packages/plugin-essentials/sources/suggestUtils.ts

`yarn add` and `yarn up` didn't respect the modifier (either specified as `defaultSemverRangePrefix` or through `--caret`/`--tilde`/`--exact`) and always added workspaces with the `workspace:${relativeCwd}` range which isn't too useful as it gets replaced with the exact version at pack time.
Made `suggestUtils.getSuggestedDescriptors` take the modifier into account when attaching local workspaces. This means that, by default, workspaces will be attached with the `workspace:^` range.
**Checklist**

feat: make `{add,up}` respect modifiers when attaching local workspaces

---

.yarn/versions/9d048c9b.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/yarnpkg-nm/sources/buildNodeModulesTree.ts
packages/yarnpkg-nm/sources/hoist.ts

The problem - Yarn 1.x maximized chances to end up with only one node_modules in the case of workspaces by giving priority to direct workspace dependencies. The users expect now the same behaviour in 2+. The other consideration is that its a universally the best layout for node_modules when there is only one top-level node_modules folder - it has the best compatibility with the tools and packages, so it makes sense to do the same.
I gave hoisting priority to direct workspace dependencies above priority for other dependencies. Note, that direct portal dependencies have the highest priority. Fixes: #3266 
**Checklist**

fix(nm): Maximizes chances to end-up with only top-level node_modules

---

.yarn/versions/dd3c6000.yml
packages/plugin-version/sources/commands/version.ts

Running `yarn version --immediate` also runs `yarn version apply`, but the exit code doesn't get returned which causes it to exit with exit code `0` even when there are errors.
...
**Checklist**

fix: return exit code in `yarn version --immediate`

---

.yarn/versions/1aea82c9.yml
CHANGELOG.md
packages/yarnpkg-nm/sources/hoist.ts

The hoisting algorithm speed has slowed down compared to Yarn 2.x. This is mainly the result of making the hoisting algorithm better and producing the terminal result. Fixes: #3314 
I have changed the algorithm of finding used dependencies which was the culprit of speed degradation aside from the fact that we have to make multiple rounds of hoisting. We still need to make multiple rounds, but now the speed of each round is mostly the same, whereas previously the speed of the second round was many times slower than the first round.
Despite the intuition when we first precompute all the dependencies available on the higher levels and then search among them the ones that are used, it is better to do it the other way round. It …

fix(nm): Hoisting algorithm speedup for the next rounds after the first.

---

.yarn/versions/3f3739b9.yml
packages/yarnpkg-shell/sources/index.ts
packages/yarnpkg-shell/tests/shell.test.ts

Variables weren't properly split when interpolating them outside of double-quotes.
Now check whether the current segment is quoted or not, and split accordingly.
**Checklist**

Splits variables when interpolated outside of quotes

---

.github/workflows/e2e-gulp-workflow.yml
README.md
packages/gatsby/content/features/plugnplay.md

The Gulp package is still missing from the list of completed E2E tests required by #368.
I added an E2E test that installs gulp to a project as a dev dependency and tests with two short scripts.
One creates a simple default task that should run successfully when running "gulp", validating that the dependency installed and is able to run.
The next creates a public task that can be run with the "gulp <taskname>" CLI argument, and validates that we're able to import and use the gulp API by making use of the src() function to load the script file in.
I look forward to any suggestions for how to expand or improve E2E coverage for Gulp. Thanks for your time!
**Checklist**

ci: add gulp e2e test

---

.yarn/versions/60c95789.yml
packages/plugin-dlx/sources/commands/dlx.ts

Adds documentation to the `yarn dlx` command. I had to read through the source to understand how to install multiple packages.
By adding an example to the documentation.
...
**Checklist**

chore(dlx): add example of the `-p` flag

---

.yarn/versions/095aa322.yml
packages/acceptance-tests/pkg-tests-specs/sources/protocols/links.test.js
packages/acceptance-tests/pkg-tests-specs/sources/protocols/portals.test.js
packages/plugin-link/sources/LinkFetcher.ts
packages/plugin-link/sources/RawLinkFetcher.ts

Using nested portals fails with a manifest not found error since the `LinkFetcher` doesn't take the `localPath` into account when computing the `sourcePath`
Fixes https://github.com/yarnpkg/berry/issues/3091
Avoid making the `prefixPath` relative
**Checklist**

fix(link): handle nested portals

---

.yarn/versions/cfd3087f.yml
packages/yarnpkg-core/sources/Configuration.ts

The error message for invalid semver ranges in `packageExtensions` is using a old setting name.
Updated it
**Checklist**

fix(core): update outdated `packageExtensions` error message

---

.yarn/versions/9fef648d.yml
packages/yarnpkg-builder/sources/commands/build/bundle.ts
packages/yarnpkg-builder/sources/commands/build/plugin.ts

Fixes #3233
Prior to this change, the plugin builder would attempt to bundle all dependencies which would fail with node dependencies like util or path.
By setting `platform` to `node` it will not attempt to bundle Node dependencies.
See the [ESBuild platform docs](https://esbuild.github.io/api/#platform) for more details.
**Checklist**

Set platform to node to fix builder issues

---

packages/gatsby/content/getting-started/migration.md

Yarn no longer supports Node.js 10.x (https://github.com/yarnpkg/berry/pull/2373), which has reached End-of-Life on 2021-04-30.
Refs: https://github.com/nodejs/Release#end-of-life-releases
**Checklist**

docs: update migration guide to reflect the changes in Yarn 3

---

.yarn/versions/b8f1abb1.yml
CHANGELOG.md
packages/yarnpkg-builder/sources/commands/build/bundle.ts

Yarn CLI bundles built from sources output tree-hash as part of the version. I don't know if this was intended, it is very difficult to find sources that were used to build the bundle from tree hash. It is much more natural to use commit hash. You can see immediately everywhere over GitHub each commit hash.
I have changed `builder` to use commit hash instead of tree hash as part of the version of CLI.
**Checklist**

fix(builder): Outputs commit-hash instead of tree-hash as part of the CLI version.

---

.yarn/versions/37f592a2.yml
constraints.pro
packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
packages/plugin-compat/package.json
packages/plugin-constraints/package.json
packages/plugin-dlx/package.json
packages/plugin-essentials/package.json
packages/plugin-exec/package.json
packages/plugin-file/package.json
packages/plugin-git/package.json
packages/plugin-github/package.json
packages/plugin-http/package.json
packages/plugin-init/package.json
packages/plugin-interactive-tools/package.json
packages/plugin-link/package.json
packages/plugin-nm/package.json
packages/plugin-npm-cli/package.json
packages/plugin-npm/package.json
packages/plugin-pack/package.json
packages/plugin-patch/package.json
packages/plugin-pnp/package.json
packages/plugin-stage/package.json
packages/plugin-typescript/package.json
packages/plugin-version/package.json
packages/plugin-workspace-tools/package.json
packages/yarnpkg-cli/package.json
packages/yarnpkg-core/sources/Manifest.ts
packages/yarnpkg-core/sources/Project.ts
yarn.lock

It's currently impossible to use the pack-time workspace version management to let Yarn inject the right version number for inter-workspaces peer dependencies when publishing a package. As a result, merging release branches lead to painful merge conflicts.
The `peerDependencies` field now accepts the `workspace:` specifier (only with a semver range; relative workspace paths aren't supported unlike other dependency types). When found, Yarn will check that the inherited peer dependency is a workspace, and that it matches the specified range.
Additionally, the `workspace:^`, `workspace:~`, and `workspace:*` specifiers are now supported as well and will be replaced at publish time by respectively `^1.0.0`, `~1.0.0`, and `1.0.0` …

Adds support for `workspace:^` in peerDependencies

---

packages/gatsby/content/features/plugins.md

The `yarn outdated` plugin I wrote a while back wasn't featured on the third-party plugin list in the Yarn docs.  I recently was reading the docs and noticed the recommendation at the bottom of the page to open a PR for new third-party plugins to be feature here.
Adds yarn-plugin-outdated to the list of third party plugins.
**Checklist**

docs: add `yarn-plugin-outdated` to third-party plugin list

---

.yarn/versions/3af0c69c.yml
packages/plugin-npm/sources/NpmSemverResolver.ts

The same implicit node-gyp warnings were reported multiple times if the package was multiple times inside the dependency tree:
Changed it to only report the warnings once.
**Checklist**

fix: report implicit node-gyp warnings once

---

.github/ISSUE_TEMPLATE/bug-report.yml

The textarea for the environment information doesn't preserve the indentation from the output of `yarn dlx -q envinfo --preset jest` which is annoying me ever so slightly.
Render it in a codeblock to preserve the indentation
**Checklist**

chore: render `environment` in a codeblock for bug reports

---

.yarn/versions/2bc95c23.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/__snapshots__/foreach.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/foreach.test.js
packages/plugin-workspace-tools/sources/commands/foreach.ts

Scripts containing `:` become global but only if they exist in a single workspace, `workspaces foreach run` does not take this into account.
Fixes https://github.com/yarnpkg/berry/issues/3048
Loop over the workspaces and see if we encounter the script more than once
**Checklist**

fix(workspace-tools): handle global scripts correctly

---

.yarn/versions/e8976004.yml
packages/plugin-essentials/sources/commands/add.ts

Angular runs `yarn add --silent` and this does not execute succesfully on yarn modern.
`--silent` was a v1 flag
Added ignored `--silent` flag.
**Checklist**

add ignored --silent flag for `yarn add` for backwards compat

---

packages/gatsby/content/features/plugins.md

Yarn 2+ does not notify developers that they use an incompatible Node version. Which caused a colleague to spend half a day trying to figure out why scripts are not working correctly on their computer.
The corresponding feature request is https://github.com/yarnpkg/berry/issues/1177.
Added a plugin to the third-party plugins list which throws an error if a developer uses an incompatible Node version.
**Checklist**

docs: add yarn-plugin-engines to third-party plugin list

---

.yarn/versions/95fb1770.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/version.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/version/apply.test.ts
packages/plugin-version/sources/commands/version/check.tsx
packages/plugin-version/sources/versionUtils.ts
packages/yarnpkg-libui/sources/hooks/useListInput.ts

What the title says.
Example: Running `yarn version 3.4.5` didn't work if the current version was `1.0.0`.
Fixes #3322.
By allowing semver versions in release files again.
**Checklist**

fix: make release workflow work with versions that can't be described by strategies

---

packages/gatsby/static/configuration/manifest.json

The docs about `devDependencies` contains a note about Yarn not providing a "production" install but that has been outdated since https://github.com/yarnpkg/berry/pull/1087 
Removed the note
**Checklist**

docs: remove outdated note about `production` installs

---

.yarn/versions/597bb1d9.yml
packages/plugin-exec/sources/ExecFetcher.ts
packages/plugin-npm-cli/sources/commands/npm/info.ts
packages/plugin-npm-cli/sources/commands/npm/tag/list.ts
packages/plugin-pack/sources/commands/pack.ts
packages/plugin-version/sources/versionUtils.ts
packages/yarnpkg-core/sources/scriptUtils.ts

Some `PortablePath`s are printed without getting converted to `NativePath`s
Convert to `NativePath` before printing
**Checklist**

fix: convert `PortablePath`s to `NativePath`s before printing

---

packages/gatsby/content/getting-started/recipes.md

Small fix in the ["Hybrid PnP + node_modules mono-repo"](https://yarnpkg.com/getting-started/recipes/#hybrid-pnp--node_modules-mono-repo) recipe: `yarn` (install) has to be called in the monorepo root, not inside the nm subproject.

Fix "Hybrid PnP + node_modules mono-repo" recipe

---

packages/gatsby/static/configuration/yarnrc.json

Removes outdated information which is no longer the case about the `enableGlobalCache` option.
Deleted some docs.
**Checklist**

docs: remove outdated warnings about global cache

---

.yarn/versions/0cad2473.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/__snapshots__/foreach.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/foreach.test.js
packages/plugin-workspace-tools/sources/commands/foreach.ts

Permits users to specify `--jobs 1` and `--jobs unlimited` to `workspaces foreach` command.
`--jobs 1` takes precedence over `--parallel` and `--interlace`, disabling both. See the linked ticket below for justification.
`--jobs unlimited` kicks off every task simultaneously. It's intended to be used with watch tasks in combination with `--interlace`.
Resolves #3433.
- Change the argument validation to permit two new option values.
- Rearrange the way that concurrency/parallel/interlace arguments are initialized such that a calculated concurrency of 1 can override the parallel/interlace behavior to avoid extra work.
**Checklist**

feat(workspace-tools): support `--jobs 1` and `--jobs unlimited`

---

packages/gatsby/content/getting-started/editor-sdks.md

Resolves #2816 
In the issue @martinjlowm and @SirensOfTitan weren't sure if this was a great solution, but does work on emacs 27.2 while the one on the docs does not work. I think we should at least update the docs to have something that works out of the box so this isnt a roadblock for others, and then when someone with more elisp knowledge comes around they can make it better.
...
N/A
...
**Checklist**

docs: update SDKs guide to use working .dir-locals.el

---

.yarn/versions/59e996f0.yml
packages/gatsby/static/configuration/yarnrc.json
packages/yarnpkg-core/sources/Configuration.ts

The resolution step is a bit slow but at some point (the last benchmark) it gets unbearably slow where it's sitting at 0% CPU usage for a couple of minutes before some requests finish.
Limit the amount of concurrent requests to 50 since there wasn't much difference between 32 and 64
**Results**
1887 packages - tested on the Gatsby benchmark
```
YARN_IGNORE_PATH=1 hyperfine -w 1 --prepare="rm -rf yarn.lock" \
"YARN_NETWORK_CONCURRENCY=8 node ./master.cjs --mode update-lockfile" \
"YARN_NETWORK_CONCURRENCY=16 node ./master.cjs --mode update-lockfile" \
"YARN_NETWORK_CONCURRENCY=32 node ./master.cjs --mode update-lockfile" \
"YARN_NETWORK_CONCURRENCY=64 node ./master.cjs --mode update-lockfile" \
"node ./master.cjs --mode …
```

perf(core): limit concurrent network requests

---

packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/__snapshots__/foreach.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/foreach.test.js

I found this broken test while writing https://github.com/yarnpkg/berry/pull/3440 but pulled the change out to its own PR. It looks like this test wanted to run a bunch of commands, but instead it got `ENOENT` because there was no such workspace folder.
Made a guess about what fixtures the test was intending to use, then updated the snapshots to match.
**Checklist**

test(workspace-tools): fix a broken test

---

.yarn/versions/ebb1bd16.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/features/logFilter.test.js
packages/yarnpkg-core/sources/formatUtils.ts

`logFilters.pattern` treats the log entries as if they were filepaths which makes matching entries containing slashes really verbose.
Fixes https://github.com/yarnpkg/berry/pull/3032#issuecomment-922272497 (cc @olee)
Enable `contains` to match any part of the log entry
**Checklist**

fix(core): match `logFilters.pattern` against any part of the log entry

---

.yarn/versions/c6ca5622.yml
packages/plugin-workspace-tools/sources/commands/foreach.ts

When looking for an option to run all jobs on a parallel task using `yarn workspaces foreach --jobs`, one is not presented with the option for `unlimited` parallel runs, the only way to figure it out is looking in the code.
**How did I Fix it**
Added documentation to the `--jobs` option of `workspaces foreach` showing the usage of the new option `unlimited`.
Documents #3440
**Images of the documentation**
**Checklist**

docs(workspace-tools): add description for workspaces foreach --jobs unlimited

---

packages/gatsby/content/getting-started/editor-sdks.md

Added documentation that links to the official plugin for navigating the module cache in vscode.
Related to #806
...
N/A
...
**Checklist**

docs: update vscode docs to include zip nav plugin

---

.yarn/sdks/eslint/package.json
.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/sdks/typescript/package.json
.yarn/versions/045085fb.yml
packages/yarnpkg-sdks/sources/sdks/base.ts

I notice that auto imports are broken with yarn PNP for vim/neovim
...
Because `toEditorPath` is specialized for `vscode`, `coc-nvim`, and `neovim`, `fromEditorPath` should also have specialized handling for each host.
After this PR, I ran `yarn node scripts/run-sdks.js` and confirmed that auto import works for coc-nvim
...
**Checklist**

fix(yarnpkg-sdks): handle fromEditorPath for vim/neovim

---

.yarn/versions/99492e8d.yml
packages/yarnpkg-shell/sources/index.ts
packages/yarnpkg-shell/tests/shell.test.ts

- The shell's cd ENOENT error wasn't a recoverable error.
- We still used `stderr.write` & `return 1` in some places instead of using the `ShellError` abstraction
- Made the error recoverable
- Made it use `ShellError` everywhere
**Checklist**

fix(shell): make cd ENOENT error recoverable

---

.pnp.cjs
scripts/release/01-release-tags.sh

Depending on the order PRs are merged changes to `hook.js` and `.pnp.cjs` can end up getting reverted, the `hook.js` file is regenerated during release but `.pnp.cjs` isn't which causes the immutable install to fail when the release commit is tested.
Run an install after updating the release artifacts to make sure the `.pnp.cjs` file is up to date
**Checklist**

chore: install after updating release artifacts

---

.yarn/versions/6b81de03.yml
packages/esbuild-plugin-pnp/package.json

publishConfig.bin is pointing to a file that does not exist, which causes an error while installing the package as a dependency with pnpm.
```
ENOENT: no such file or directory, chmod '.../node_modules/.pnpm/@yarnpkg+esbuild-plugin-pnp@2.0.0-rc.1_esbuild@0.13.2/node_modules/@yarnpkg/esbuild-plugin-pnp/lib/cli.js'
```
Removed the publishConfig.bin field
**Checklist**

fix(esbuild): remove invalid `publishConfig.bin`

---

.yarn/versions/b934d2e4.yml
packages/plugin-version/sources/index.ts

- The default branch name for new repositories created on GitHub is now [`main`](https://github.com/github/renaming). plugin-version changesetBaseRefs default is set up only `master`. 
- add `main` to changesetBaseRefs default
**Checklist**

feat(plugin-version): add main to changesetBaseRefs default

---

.yarn/versions/301df8df.yml
packages/plugin-essentials/sources/commands/install.ts

Cloud services, like CI/CD etc. which supports Yarn v1 and call the install command with e.g. `yarn install --non-interactive --prefer-offline --network-timeout 600000` we still can have Yarn v3 inside git, and it would then do the job.
By having `--network-timeout` included in the legacy list of CLI flags, we would avoid aborting the install routine.
Add `--network-timeout` (networkTimeout) to the list of legacy flags inside the `/commands/install.ts` file.
Like the `--silent` flag, we do noting about it. But the question is, should we mention that this option can be set inside a config file (if it is equivalent)?
**Checklist**

fix(essentials): accept `--network-timeout` as a legacy flag

---

.yarn/versions/78cfe28d.yml
CHANGELOG.md
packages/yarnpkg-pnpify/sources/commands/RunCommand.ts

The require path added to `NODE_OPTIONS` by `@yarnpkg/pnpify` isn't escaped so it fails on Windows
Fixes https://github.com/yarnpkg/berry/issues/3680
Use `JSON.stringify` to escape and quote the path
**Checklist**

fix(pnpify): escape require path

---

.yarn/versions/e137d1fc.yml
packages/yarnpkg-nm/sources/buildNodeModulesTree.ts
packages/yarnpkg-nm/sources/hoist.ts

As discussed here:
https://github.com/yarnpkg/berry/issues/3648#issuecomment-952351470
the `localeCompare` might produce non-deterministic results, depending on the system locale, the input and the specifics of the usage. The chance there are practical problems with `localeCompre` code in nm linker is low to non-existent, because it affects only writing to `node_modules/.yarn-state.yml` and the order of entries in this file doesn't effect anything except its contents. But it is still better to be on the safe side and avoid usage of `localeCompare` to not introduce practical problems unintentionally.
Removed `localeCompare` usage in favor of direct string comparison.
**Checklist**

fix(nm): Avoids usage of localeCompare for the strings

---

.yarn/versions/51ba0ab8.yml
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/plugin-nm/sources/NodeModulesLinker.ts
packages/plugin-pnp/sources/jsInstallUtils.ts

There is a lot of log spam when installing packages like esbuild with the NM linker:
I feel like these logs are very useless and that it's not worth the user's time to read them.
Removed them.
For now I kept `checkAndReportManifestCompatibility` since it's still used in https://github.com/yarnpkg/berry/blob/e95a1df42f6b94fc7a308af1b038e43c7278ac5a/packages/plugin-pnp/sources/jsInstallUtils.ts#L49 to report skipped builds (I feel like those are a lot more important than skipped links).
**Checklist**

fix(plugin-nm): don't report "link skipped" warnings

---

.yarn/versions/3715e60b.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/foreach.test.js
packages/yarnpkg-parsers/sources/grammars/shell.js
packages/yarnpkg-parsers/sources/grammars/shell.pegjs
packages/yarnpkg-parsers/tests/shell.test.ts
packages/yarnpkg-shell/tests/shell.test.ts

The shell parser is still not compatible with bash in some cases.
Closes #1356
Closes #3657
Make the parser behave like bash by reducing escape characters of single-quote and double-quote that bash does not do.
**Checklist**

fix(shell): string syntax compatible

---

.yarn/versions/61c4a98a.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-fixtures/packages/self-require-dep-1.0.0/index.js
packages/acceptance-tests/pkg-tests-fixtures/packages/self-require-dep-1.0.0/package.json
packages/acceptance-tests/pkg-tests-fixtures/packages/self-require-dep-1.0.0/self.js
packages/acceptance-tests/pkg-tests-fixtures/packages/self-require-trap-1.0.0/bin.js
packages/acceptance-tests/pkg-tests-fixtures/packages/self-require-trap-1.0.0/package.json
packages/acceptance-tests/pkg-tests-specs/sources/basic.test.js
packages/acceptance-tests/pkg-tests-specs/sources/features/installArtifactCleanup.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
packages/acceptance-tests/pkg-tests-specs/sources/script.test.js
packages/plugin-pnpm/sources/PnpmLinker.ts

- The `PnpmLinker` didn't install transitive dependencies in such a way that they can require themselves
- The `PnpmLinker` didn't support running binaries of soft links
- The `PnpmLinker` didn't remove the scope folder (e.g. `node_modules/@yarnpkg`) after removing a scoped dependency
- The `PnpmLinker` didn't remove folders that looked like scopes
- ~~Made it copy the package sources to `node_modules/.store/<hash>/node_modules/<ident>` and use that as the symlink source so that self-references work. There is a special edge-case though: when a package depends on a different version of itself. Both pnp and nm get that right (though pnpm doesn't), so I made it skip generating self-references in that case (i.e. made it keep …

fix(plugin-pnpm): various improvements

---

.yarn/versions/bce99a86.yml
CHANGELOG.md
packages/yarnpkg-core/sources/scriptUtils.ts

The node version inside the `npm_config_user_agent` didn't include a leading `v` (which all other package managers include).
Made it use `process.version` instead of `process.versions.node`.
**Checklist**

fix(core): include a leading `v` in the node version of `npm_config_user_agent`

---

packages/gatsby/content/features/zero-installs.md

This PR adds a note to the docs that Zero-Installs depends on a project using Plug'n'Play. I ran into this following the [guide][migration-steps] to migrate from Yarn classic to Yarn 2. One step links out to a help item on [how to update the `.gitignore`][gitignore-faq], which mentions the Zero-Installs feature as an option. I followed the link to the feature page to understand more about it, but only when attempting to adopt the feature did it become clear that I would first have to use Plug'n'Play. I am blocked on adopting it as my project uses Flow.
The bullet points on the Zero-Installs page provides the sequence to enable the feature. I've added an extra step at the beginning to call out that projects using …

Note that Zero-Installs depends on Plug'n'Play

---

.yarn/versions/5e317228.yml
packages/plugin-essentials/sources/commands/set/version.ts

`yarn set version` sets the `packageManager` field of the top-level-manifest if the Yarn version is tagged (i.e. released on the registry), but it doesn't change it when the Yarn version isn't tagged (e.g. `yarn set version from sources` or `yarn set version <path-that-has-untagged-version>`). In these cases the version specified inside the `packageManager` field is the one used as the wrapper that calls the real Yarn binary that the project uses, and it's recommended to keep it up to date. Because of this I made `yarn set version` use the latest stable version as the wrapper.
Made it set it to the latest stable version.
**Checklist**

fix: use latest stable yarn version as the wrapper in the packageManager field if the yarn version isn't tagged

---

packages/gatsby/content/features/zero-installs.md

The plug n' play link in [zero installs](http://localhost:8000/features/zero-installs) is broken. The link toward plug n' play document seems to be changed before. 
I changed the broken link from `/features/plugnplay` to `/features/pnp`
**Checklist**

docs: fix the broken plugnplay link

---

.yarn/versions/203ecb3c.yml
packages/acceptance-tests/pkg-tests-fixtures/packages/@scoped__has-bin-entry-1.0.0/bin.js
packages/acceptance-tests/pkg-tests-fixtures/packages/@scoped__has-bin-entry-1.0.0/package.json
packages/acceptance-tests/pkg-tests-specs/sources/commands/run.test.js
packages/yarnpkg-core/sources/Manifest.ts

Some registries incorrectly normalize the `bin` field of scoped packages to be invalid.
E.g. from
```json
{
"name": "@yarnpkg/doctor",
"bin": "index.js"
}
```
to
```json
{
"name": "@yarnpkg/doctor",
"bin": {
"@yarnpkg/doctor": "index.js"
}
}
```
Fixes https://github.com/yarnpkg/berry/issues/3793
Since binaries are valid idents parse them as such and only use the name, ignoring the scope
**Checklist**

fix(core): normalize scoped bin entries

---

.yarn/versions/7f7ad3c0.yml
packages/acceptance-tests/pkg-tests-specs/sources/dragon.test.js
packages/yarnpkg-core/sources/Project.ts

I explained the issue in detail in the dragon test comment, feel free to take a look there.
I changed the heuristic so that instead of checking whether the virtual package got deleted, we now check whether the dependency got updated. It may be a very little bit slower, but better matches the intent of the code (to check whether the dependency needs to be deduped).
**Checklist**

fix(core): fix deduping of aliased virtual packages

---

.yarn/versions/92db221e.yml
packages/plugin-compat/sources/extensions.ts

See https://github.com/slorber/responsive-loader/pull/1
Added sharp and jimp as peer dependencies, which is the intended functionality
**Checklist**

chore(compat): add peer dependencies for `@docusaurus/responsive-loader`

---

.yarn/versions/e0e4e264.yml
CHANGELOG.md
packages/yarnpkg-core/sources/Project.ts
packages/yarnpkg-core/tests/Project.test.ts

If for whatever reason the install state is corrupted then Yarn is unable to recover and the user has to manually delete the install state to continue.
Catch the error and carry on as if the install state doesn't exist.
**Checklist**

fix(core): ignore corrupted install state

---

packages/gatsby/content/advanced/plugin-tutorial.md

The plugin tutorial used commands that extended `Command` instead of `BaseCommand`.
Changed it to use `BaseCommand`.
**Checklist**

docs: use BaseCommand in plugin tutorial

---

.yarn/versions/70f09833.yml
packages/vscode-zipfs/package.json
packages/vscode-zipfs/sources/index.ts

`vscode-zipfs` didn't offer a way to unmount a zip file from the context menu.
Fixes https://github.com/yarnpkg/berry/issues/3730.
Added an `unmountZipFile` command that is only shown when the zip file is mounted. It either removes the zip file from the current workspace if there are multiple remaining folders in that workspace or it gets rid of the workspace and returns back to "single-folder mode" otherwise.
**Checklist**

feat(vscode-zipfs): unmount

---

.github/workflows/e2e-svelte-kit-workflow.yml
scripts/e2e-setup-ci.sh

Due to a bug in `jest-worker` and/or Node.js adding a loader causes our e2e tests to time out
- https://github.com/nodejs/node/issues/39140
- https://github.com/nodejs/node/issues/37782
- https://github.com/facebook/jest/issues/12060
Disable the loader by default and require the tests that need it to explicitly enable it
**Checklist**

ci: fix e2e tests timing out

---

packages/gatsby/content/getting-started/install.md
packages/gatsby/content/getting-started/intro.md
packages/gatsby/content/getting-started/usage.md
packages/gatsby/src/templates/article.js

Supersede #3806
This PR introduces the ability to specifying the order of documentation article in the side navigation via `order` front matter.
...
**Checklist**

docs: allow specifying order via front matter

---

.yarn/versions/7d8190c0.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
packages/plugin-nm/sources/NodeModulesLinker.ts
packages/plugin-pnp/sources/PnpLinker.ts
packages/plugin-pnpm/sources/PnpmLinker.ts

The `findLocatorForLocation` method was attempting to get the locator from the linkers, then to query the package location (in order to get the root of the package). The problem was that it was doing this even on disabled linkers, causing crashes in the `findPackageLocation` calls since their install states were missing. As a result, the errors reported by running `yarn install` within a non-workspace directory were incorrect.
Closes #3777
Closes #3792 (Supersedes)
This diff ensures that the linkers never advertise anything as a package they own when they are disabled.
I think it should be a fairly safe change, but I'll keep an eye on the tests in case I forgot an edge case.
**Checklist**

fix(core): prevents findPackageLocation from being called from unactivated linkers

---

.yarn/versions/0d3ff95b.yml
packages/yarnpkg-core/sources/Project.ts

The recursion check was done before the deduplication pass. As a result, even if a locator got successfully deduped and thus won't be iterated again, it could lead to stack overflows.
Closes #3434
Closes #3561 
This diff moves the check until after the deduplication ran, right before we start the recursion.
**Checklist**

fix(core): moves the recursion check after deduplication

---

packages/gatsby/src/utils/useScroll.js

It's my first time contributing to this repository so I thought I'd give it a try to a `good first issue`.  Please tell me if anything is wrong with this
Resolves #3759
...
From what I've tested, the `sessionStorage` is existing when cookies are disabled but using it throws an error. Adding a try/catch prevents the site from crashing.
...
**Checklist**

docs: add try catch around the use of `sessionStorage` in `useScroll`

---

.yarn/versions/4a1a9b55.yml
packages/gatsby/static/configuration/yarnrc.json
packages/yarnpkg-core/sources/Configuration.ts

The documentation for `globalFolder` references the behaviour of `yarn link` from v1.
Removed it and synced the docs with the documentation in the source.
**Checklist**

docs: remove reference to `yarn link` in `globalFolder` docs

---

packages/gatsby/content/getting-started/editor-sdks.md

Following Neovim v0.6 the bug in the LSP URI handling has been fixed so I updated the docs accordingly.
v0.6 also introduced a change to how autocommands work so I've updated the vimrc snippet required for go-to-definition

docs: update editor docs following neovim v0.6 release

---

.yarn/versions/dc0140a5.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/npm/login.test.js
packages/acceptance-tests/pkg-tests-specs/sources/commands/publish.test.ts
packages/plugin-npm/sources/npmHttpUtils.ts

Sort of a followup to https://github.com/yarnpkg/berry/pull/3769

feat(plugin-npm): print error message specific to OTP being invalid

---

.yarn/versions/9c0db68d.yml
packages/gatsby/content/features/plugnplay.md
packages/gatsby/content/getting-started/editor-sdks.md
packages/yarnpkg-sdks/sources/generateSdk.ts
packages/yarnpkg-sdks/sources/sdks/base.ts
packages/yarnpkg-sdks/sources/sdks/vscode.ts

Resolves #3844
vscode-stylelint supports PnP natively since 1.1 so SDKs are no longer needed.
- SDK removed.
- Stylelint removed from SDK documentation.
- Added vscode-stylelint to the native support list in PnP docs.
**Checklist**

refactor!: Remove vscode-stylelint SDK

---

packages/gatsby/static/configuration/manifest.json

The [description  for the `resolutions` field](https://yarnpkg.com/configuration/manifest#resolutions) in the Yarn's documentation contains a typo and could be more understandable. Changes in this PR fix the aforementioned typo and improve the readability of the field's description.
...
- I have added the missing "s" letter in the "resolution**s**" word.
- I have added the missing line break (`\n`) that someone forgot to put there.
- I have unified the formatting for the document to be more coherent.
...
**Checklist**

docs: fix typo, improve readability, and unify formatting

---

packages/gatsby/content/features/plugins.md

This will add a [third-party plugin](https://github.com/AndyClausen/yarn-plugin-gcp-auth)  to the plugin list. The plugin will add a GCP access token to the NPM authentication header to any requests going to Google Artifact Registry repos - much like the existing [az-cli-auth](https://github.com/FishandRichardsonPC/yarn-plugin-az-cli-auth).
**Checklist**

docs: add `gcp-auth` to third-party plugin list

---

packages/gatsby/content/features/plugins.md

This PR adds additional plugins to the third-party plugin list:
* [licenses](https://github.com/mhassan1/yarn-plugin-licenses)
* [aws-codeartifact](https://github.com/mhassan1/yarn-plugin-aws-codeartifact)
* [after-install](https://github.com/mhassan1/yarn-plugin-after-install)
**Checklist**

docs: add `licenses`, `aws-codeartifact`, and `after-install` to third-party plugin list

---

tsconfig.json

Using `Go to Symbol in Workspace` in VSCode (`CTRL + T`) takes longer than necessary and shows irrelevant results because it indexes the built bundles too.
Excluded them in the `tsconfig.json`.
**Checklist**

chore: exclude `{bin,bundles}` from tsserver index

---

.yarn/versions/ed770662.yml
packages/gatsby/static/configuration/yarnrc.json
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/httpUtils.ts

Current .yarnrc.yml configuration does not support authorization in registry via certificate and private key.
...
Added the ability to specify values ​​for the certificate and private key. 
Added setting of certificate and key in configuration "got" package
...
**Checklist**

feat: add the ability to auth in using certificate and private key

---

.yarn/versions/a048c53b.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/yarnpkg-nm/sources/buildNodeModulesTree.ts
packages/yarnpkg-nm/sources/hoist.ts
packages/yarnpkg-nm/tests/hoist.test.ts

The nm hoister uses an eager approach to all the dependencies. Unfortunately, this doesn't play well for portals, since the portal dependencies might be hoistable to the direct parent, but if the portal symlink was hoisted to the root workspace or other indirect parent the dependencies might not be hoistable anymore. This situation leads to portal conflict diagnostic code to pass, but then assertion failure during an attempt to write non-hoisted portal dependencies to disk.
Fixes: #3873 
I have introduced knowledge about portals to the hoister algorithm, when it sees the portal it makes sure all the dependencies of the portal to be hoisted first and only after that the portal itself can be hoisted (provided portal …

fix(nm): Better portal hoisting by giving priority to portal dependencies first

---

packages/gatsby/content/features/plugins.md

The [`yaml-manifest` plugin](https://github.com/lyleunderwood/yarn-plugin-yaml-manifest) is not listed with the contrib plugins.
Add [`yaml-manifest` plugin](https://github.com/lyleunderwood/yarn-plugin-yaml-manifest) to the contrib plugin list.
**Checklist**

docs: add yaml-manifest contrib plugin

---

packages/gatsby/content/features/plugnplay.md

Using this package (3.5K stars), I was able to painlessly resolve the issues regarding having plugins as dependencies in a shareable config, while keeping PnP enabled. It could be worth mentioning that in the docs until eslint/eslint#3458 is merged.
N/A
N/A
**Checklist**

docs: link to `@rushstack/eslint-patch` in the PnP doc

---

.yarn/versions/3bda1f12.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
packages/plugin-essentials/sources/commands/install.ts

Resolves #3606
`--mode=update-lockfile` means that the user has explicitly expected "dependency update mode".
This should take precedence over immutable mode, which is automatically set in the CI environment.
This change disables all immutable flag behaviors in the update mode.
**Checklist**

fix(essentials): make `--mode=update-lockfile` disable immutable installs

---

packages/gatsby/content/advanced/plugin-tutorial.mdx

The `plugin-addition` example in [documentation](https://yarnpkg.com/advanced/plugin-tutorial#adding-commands) does not work without this change.

docs: fix example in plugin tutorial

---

packages/gatsby/src/components/layout.css

I can't see the target of anchor links, for example after searching and clicking the results. It's hidden below the topbar.
...
This sets `scroll-padding-top` to the height of the banner and topbar
...
**Checklist**

docs: add scroll-padding-top to avoid hiding anchor link targets

---

.yarn/versions/ce68f7d0.yml
packages/plugin-pnpm/sources/PnpmLinker.ts

There is potential for a race condition in the pnpm linker where it might try to remove the store while packages are about to be written to disk.
Check if the store is empty after the install is complete
**Checklist**

fix(pnpm): don't remove store before install finishes

---

packages/gatsby/src/components/hit/index.js

It's always annoyed me that the search page shows whether a package has TS types or not, but not whether they come from @definitelytyped or not (which is important, since it means they may have to be installed separately). You had to put your mouse over the widget to see the alt text.
Replaced the hint with a version that shows either DT or TS in the widget, depending on the status.
**Checklist**

Fixes search DT/TS disambiguation

---

.yarn/versions/ba257392.yml
CHANGELOG.md
packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx

- `upgrade-interactive` didn't display as many suggestions as can fit in the viewport.
- Available upgrades were only displayed after all of the suggestions had been fetched, which took forever on large monorepos.
Fixes https://github.com/yarnpkg/berry/issues/3918.
- Made it display as many suggestions as can fit in the viewport.
- Made it fetch suggestions that fit in the viewport in the foreground and load them one-by-one (but they still wait on the previous one because otherwise they'd be jumping up and down as more suggestions are resolved).
- Made it fetch suggestions that don't fit in the viewport in the background in batches of one viewport at a time so that they don't affect responsiveness (fetching them one-by-one …

feat: improve upgrade-interactive paging

---

.github/workflows/e2e-docusaurus-workflow.yml
README.md
packages/gatsby/content/features/plugnplay.md

We don't have an e2e test for Docusaurus
Depends on 
- https://github.com/facebook/docusaurus/pull/6047
- https://github.com/facebook/docusaurus/pull/6097
- https://github.com/yarnpkg/berry/pull/3862
**Checklist**

ci: add Docusaurus e2e test

---

.yarn/versions/d5a60103.yml
packages/plugin-pnp/sources/PnpLinker.ts
packages/plugin-pnpm/sources/PnpmLinker.ts
packages/yarnpkg-core/sources/miscUtils.ts

Packages are currently unplugged one by one. Now that we have a proper API to start processing such things in the background while we use the CPU for other things, we should use it.
Wrap unplugs into `api.holdFetchResult`.
**Checklist**

Parallelizes package unplugging

---

.yarn/versions/69964e29.yml
packages/yarnpkg-core/sources/Cache.ts

We're computing the checksum for conditional cache entries only to throw it away.
Skip computing the checksum for conditional cache entries unless we're doing a cache check.
**Benchmark results**
```sh
YARN_IGNORE_PATH=1 hyperfine -w 1\
"node ./master.cjs --mode skip-build"\
"node ./skip-checksum.cjs --mode skip-build"
Benchmark 1: node ./master.cjs --mode skip-build
Time (mean ± σ):     638.5 ms ±  13.2 ms    [User: 904.9 ms, System: 116.1 ms]
Range (min … max):   623.2 ms … 663.7 ms    10 runs
Benchmark 2: node ./skip-checksum.cjs --mode skip-build
Time (mean ± σ):     537.7 ms ±  10.8 ms    [User: 800.9 ms, System: 89.5 ms]
Range (min … max):   524.9 ms … 560.5 ms    10 runs
Summary
'node ./skip-checksum.cjs --mode …
```

perf(core): skip checksum for cache entries when it isn't required

---

.yarn/versions/c608964d.yml
packages/yarnpkg-core/sources/Manifest.ts
packages/yarnpkg-core/sources/Workspace.ts

When setting up `Workspace` and `Manifest` instances Yarn does an unnecessary "file exists" check.
Remove them.
**Benchmark results**
```sh
YARN_IGNORE_PATH=1 hyperfine -w 1\
"node ./master.cjs exec pwd"\
"node ./skip-exists-sync.cjs exec pwd"\
"node ./skip-exists-sync-and-promise.cjs exec pwd"
Benchmark 1: node ./master.cjs exec pwd
Time (mean ± σ):     945.1 ms ±  10.3 ms    [User: 786.6 ms, System: 112.4 ms]
Range (min … max):   932.9 ms … 968.9 ms    10 runs
Benchmark 2: node ./skip-exists-sync.cjs exec pwd
Time (mean ± σ):     897.0 ms ±   5.8 ms    [User: 781.2 ms, System: 106.7 ms]
Range (min … max):   888.0 ms … 906.4 ms    10 runs
Benchmark 3: node ./skip-exists-sync-and-promise.cjs exec pwd
Time (mean ± σ): …
```

perf(core): skip unnecessary exists checks

---

.yarn/versions/5f57d7bd.yml
packages/gatsby/gatsby-config.js
packages/gatsby/gatsby-plugin-clipanion-cli/gatsby-node.js
packages/gatsby/src/components/markdown.js
packages/yarnpkg-builder/README.md
packages/yarnpkg-builder/sources/commands/build/bundle.ts
packages/yarnpkg-builder/sources/commands/build/plugin.ts
packages/yarnpkg-builder/sources/commands/new/plugin.ts
packages/yarnpkg-pnpify/README.md
packages/yarnpkg-pnpify/sources/commands/RunCommand.ts
packages/yarnpkg-sdks/README.md
packages/yarnpkg-sdks/sources/commands/SdkCommand.ts

- `@yarnpkg/sdks` and `@yarnpkg/pnpify` didn't have READMEs.
- The command details of our external packages didn't have a `for more details` footer linking back to the main page in the docs.
- The pages of commands added by plugins didn't link to the README of the plugin.
- The pages of commands added by external packages didn't mention the fact that they need to be installed separately.
Fixes https://github.com/yarnpkg/berry/issues/3809.
- Added READMEs.
- Added one.
- Linked the name of the plugin to its README.
- Added a section about it, linked the external package name to its README, and mentioned how it can be installed.
**Checklist**

docs: add notes about external packages

---

packages/gatsby/content/features/plugins.md

This updates the description of yarn.build's plugin to cover a bunch of recent changes. Also includes an additional plugin from yarn.build.
I recently split the commands from yarn.build into individually installable plugins, so you can now just grab the ones you want if you don't want the full suite.
Added the `package.yaml` plugin, which I've been using for months in a polyglot repo. Particularly useful for building golang packages, as well as being able to add comments.
...
Updated the readme.
...
**Checklist**

Add package-yaml and update yarn.build description

---

.yarn/versions/ddc6b36f.yml
packages/plugin-nm/sources/NodeModulesLinker.ts

In https://github.com/yarnpkg/berry/pull/3575/files#diff-b6f2618cc58bd274cb6c2114799ab4f80cd5971a299ea847dd8c031c5c411134L370-L371 the custom data for the linkers changed but the custom data key wasn't updated.
Fixes https://github.com/yarnpkg/berry/issues/3877
Update the version in the data key.
I updated the key for the `PnpLinker` in https://github.com/yarnpkg/berry/pull/2161 and @paul-soporan updated the key for the `PnpmLinker` in https://github.com/yarnpkg/berry/pull/3681 so they're already fixed.
**Checklist**

fix(plugin-nm): update data key version

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/sdks/typescript/package.json
.yarn/versions/dd3df2e2.yml
packages/yarnpkg-sdks/sources/sdks/base.ts

[TypeScript 4.6](https://github.com/microsoft/TypeScript/issues/46858) and [VSCode 1.64](https://github.com/microsoft/vscode/issues/139607) will start using inter-process communication which the SDK doesn't handle and crashes.
- https://github.com/microsoft/vscode/pull/135341
- https://github.com/microsoft/TypeScript/pull/46418
Update the SDK to handle `object` messages
**Checklist**

fix(sdks): support `tsserver` inter-process communication

---

.yarn/versions/68aa817a.yml
CHANGELOG.md
packages/esbuild-plugin-pnp/sources/index.ts

`@yarnpkg/esbuild-plugin-pnp` incorrectly resolves Node.js builtins when the `platform` isn't set to `node`.
Fixes https://github.com/yarnpkg/berry/issues/3365
Only enable `considerBuiltins` if `platform` is set to `node`.
**Checklist**

fix(esbuild): disable Node.js builtins when `platform` isn't `node`

---

.github/workflows/e2e-cra-workflow.yml
.github/workflows/e2e-storybook-workflow.yml

The `create-react-app` e2e test has been failing for a while and https://github.com/facebook/create-react-app/pull/11751 hasn't been released yet.
I looked into the Storybook test as well but there are too many issues to deal with for now, I opened https://github.com/storybookjs/storybook/pull/17249 as a first step.
Add required workarounds to make it pass.
**Checklist**

ci: fix the `create-react-app` e2e test

---

.yarn/versions/2c6f436a.yml
packages/plugin-interactive-tools/sources/commands/search.tsx
packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
packages/plugin-version/sources/commands/version/check.tsx
packages/yarnpkg-libui/sources/misc/renderForm.tsx

`renderForm` was using the `process` streams instead of the context streams.
Made it use the context streams.
**Checklist**

fix: pass context streams to renderForm

---

.yarn/versions/9c1aea62.yml
packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/StreamReport.ts

- We used `process.stdout.{rows,columns}` in `yarn upgrade-interactive`
- We used `process.stdout.{rows,columns}` in `StreamReport`
- We computed `progressMaxScaledSize` even if progress bars weren't enabled
- We reported and refreshed progress even if progress bars weren't enabled
- Switched it to `this.context.stdout`.
- Switched it to `this.stdout`.
- Made it only be computed if they are enabled.
- Added an `return {...Promise.resolve(), stop: () => {}};` early return to `reportProgress`
Recurrent install benchmark on the next.js repo with all examples included:
```sh
➜  next.js git:(canary) ✗ CI=1 YARN_IGNORE_PATH=1 hyperfine -w 1 "node ./master.cjs --mode skip-build" "node ./skip-progress.cjs --mode skip-build" …
```

fix: use properties of actual stdout and skip progress calculations if progress bars are not enabled

---

.yarn/versions/8879720f.yml
packages/yarnpkg-core/sources/Project.ts
packages/yarnpkg-core/sources/nodeUtils.ts

Cf the comment; seems like WSL doesn't play nice with `getReport`.
Runs the report at startup, when the resources to log are still few.
**Checklist**

Generates report at startup

---

.yarn/versions/1e028524.yml
packages/yarnpkg-core/sources/Manifest.ts
packages/yarnpkg-core/tests/Manifest.test.ts

Yarn crashes if the `workspaces` field is set to `null`.
Fixes https://github.com/yarnpkg/berry/issues/3947
Check that `workspaces` isn't `null` before trying to access its properties
**Checklist**

fix(core): handle `workspaces` set to `null`

---

.github/workflows/e2e-docusaurus-workflow.yml

The Docusaurus e2e test started failing at [2022-01-26T20:01:17Z](https://github.com/yarnpkg/berry/actions/runs/1752768894) because it tries to import ESM but the ESM loader isn't enabled.
Enable the ESM loader
**Checklist**

ci: enable ESM loader for Docusaurus

---

.github/workflows/e2e-create-vue-workflow.yml
README.md

The new Vue documentation documents using `create-vue` to bootstrap projects[^1] so we should have an e2e test covering it
[^1]: https://github.com/vuejs/docs/blob/5947c91478c518cdeb34c41ef518b2d6e2323918/src/guide/quick-start.md#local
Depends on
- https://github.com/yarnpkg/berry/pull/4020
- https://github.com/johnsoncodehk/volar/pull/851
**Checklist**

ci: add `create-vue` e2e test

---

.yarn/versions/b8e463fe.yml
packages/plugin-init/sources/commands/init.ts

The current status of the docs and the generated result of `yarn init -2` missmatch:
After asking on the `Yarn Discord server` It was suggested to sync `yarn init` as the docs would the right version of it
* Asked before on discord
* was suggested to PR it here
* Remove the leading `/` on missmatch
* Add by default `!.yarn/versions` 
**Checklist**
edited through github portal/mobile, could not run it yet ^^

fix(init): sync `.gitignore` with docs

---

packages/gatsby/src/components/syntax.tsx

When keys and values on the configuration pages didn't fit on a single line, they overflowed out of the viewport.
Made them wrap to the next lines.
**Checklist**

fix(website): wrap keys and values on configuration pages

---

.yarn/versions/a1a4200d.yml
CHANGELOG.md
packages/yarnpkg-cli/sources/main.ts

`YARN_IGNORE_NODE` was compared to `1` instead of being parsed like all env variable configuration settings.
We now parse it using `miscUtils.parseOptionalBoolean` which correctly parses both `1`/`0` and `true`/`false`.
**Checklist**

fix: use parseOptionalBoolean on YARN_IGNORE_NODE

---

packages/gatsby/src/components/header.js

The header takes up too much space on mobile.
Before:
After:
**Checklist**

fix(website): make header take up less space on mobile

---

packages/gatsby/src/components/search/SearchResults.js

Apparently the sponsor carousel control dots have their `z-index` set to `1` by default so that they display on top of the selected item, but in our case we display the dots next to the selected item and the `z-index` messes things up when the sponsors section is hidden behind the searchbar after scrolling.
Set `z-index` to `auto`.
**Checklist**

fix(website): fix carousel control dots z-index

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/versions/8643ebe9.yml
packages/gatsby/content/getting-started/editor-sdks.md
packages/yarnpkg-sdks/sources/sdks/base.ts

It appears that as of zip.vim v32 the [URL format has changed](https://github.com/neovim/neovim/blob/c0efe49e78eca3a17a5934cc283199122d081467/runtime/doc/pi_zip.txt#L105-L107). This version is included in Vim as of [v8.2.3606](https://github.com/vim/vim/commit/519cc559b08b800edc429688aece7ad6a00d41eb) and Neovim as of [v0.6.0](https://github.com/neovim/neovim/commit/c0efe49e78eca3a17a5934cc283199122d081467), I believe.
I don't have a working setup from before this change, but believe the format was `/path/foo.zip:/path/foo.zip::bar.js`, while now, browsing a zipfile in Neovim opens paths like `zipfile:///path/foo.zip::bar.js`.
- In `toEditorPath`, I changed the Neovim case to create `zipfile:///path...` URLs.
- In …

fix(sdks): update neovim zipfile paths in TypeScript SDK

---

packages/gatsby/content/advanced/contributing.md

Notifies new contributors to not approve the PRs if they're not members.
Ref: https://github.com/yarnpkg/berry/pull/4060#issuecomment-1028287189
Added a note in CONTRIBUTING.md
**Checklist**

docs: add note about reviewing PRs in CONTRIBUTING

---

.yarn/versions/3b5fd138.yml
packages/yarnpkg-fslib/sources/xfs.ts

`@yarnpkg/fslib`s `xfs.mktemp*` performs unnecessary `realpath` calls on directories we know can't be symlinks.
Ref https://github.com/yarnpkg/berry/issues/4057
Call `realpath` on the tmpdir once and avoid calling it on the created folder.
**Benchmark results**
On the gatsby benchmark this removes 3839 statx calls when fetching packages
```sh
YARN_IGNORE_PATH=1 hyperfine -w 1 --prepare="rm -rf ./.yarn-global"\
"node ./master.cjs --mode skip-build"\
"node ./skip-realpath.cjs --mode skip-build"
Benchmark 1: node ./master.cjs --mode skip-build
Time (mean ± σ):      8.058 s ±  0.109 s    [User: 51.520 s, System: 3.590 s]
Range (min … max):    7.893 s …  8.234 s    10 runs
Benchmark 2: node ./skip-realpath.cjs --mode skip-build …
```

perf(fslib): skip unnecessary `realpath` calls in `xfs.mktemp*`

---

.yarn/versions/88da1151.yml
packages/yarnpkg-sdks/sources/sdks/base.ts

This PR fixes a bug where navigating to a dependency fails in the editor SDK when using portals and PnP.
Resolves #4090
I don't properly understand the code I'm changing here so please be kind! This is a local fix I applied which fixes the issue for me.
I've just changed the code path that is used for workspace linked packages to also work for portal packages.
**Checklist**

Editor SDK support for resolving portaled dependencies

---

.yarn/versions/5f099b36.yml
packages/yarnpkg-nm/sources/buildNodeModulesTree.ts

The variables `target` and `linkType` are declared as let and their values are populated in an if-else.
Change `target` and `linkType` to const, and use a conditional (ternary) operator instead.
**Checklist**

refactor(nm): return object with linkType and target

---

.github/workflows/pr-smart-merge-apply.yml
.github/workflows/pr-smart-merge-generate.yml
.github/workflows/pr-smart-merge-reset.yml

Smart merge currently requires to go into the `Actions` tab and pick the right action with the right parameters. Additionally it's not great in terms of security since the running code has access to the yarnbot token. Even with manual trigger, there's a decent chance someone could social-engineer us into running it on a malicious PR.
- The action is now triggered by adding the `infra: pending update` label to a PR
- Immediately, a privileged `pull_request_target` action will trigger and remove the label
- In parallel, an unprivileged `pull_request` trigger will generate a patchfile and store it as an artifact
- Once finished, a privileged `workflow_run` workflow will retrieve the patchfile and create the commit …

Implements smart merge v2

---

.pnp.cjs
.yarn/versions/9f750ca7.yml
packages/plugin-compat/sources/extensions.ts

`@cypress/snapshot` has a devDependency on `debug`, but uses `debug` during its `postinstall` step.
* I opened [an issue](https://github.com/cypress-io/snapshot/issues/158) and [a PR](https://github.com/cypress-io/snapshot/issues/159) on the https://github.com/cypress-io/snapshot/ repo.
* I added an extension for the `debug` dependency.
**Checklist**

add extension for '@cypress/snapshot' dependency on 'debug'

---

packages/gatsby/src/components/header.js
packages/gatsby/src/components/layout.css

There is a large-scale war happening in Ukraine with the 3rd largest army in the world with a non-zero risk to become a world war, we should show our stance somehow so that more people were aware and helped stop the Russian agression.
Adds a banner to Yarn website.
**Checklist**

docs: Add Ukraine support banner to Yarn website

---

.yarn/versions/d3f97928.yml
packages/plugin-git/sources/gitUtils.ts

The variables `protocol` and `request` can be converted into const, and get assigned under a conditional operator
use const for protocol/request
**Checklist**

refactor(git): use const for protocol/request

---

.yarn/versions/89ab2ac5.yml
packages/yarnpkg-nm/sources/buildNodeModulesTree.ts

The variable `segCount` is used inside while loop, although it's initialized and incremented like a for loop
Use for loop instead of while loop in buildTree fn
**Checklist**

chore(nm): use for loop in buildTree fn

---

.yarn/versions/5e49f6c7.yml
packages/esbuild-plugin-pnp/sources/index.ts

`esbuild` marks `rxjs/operators` as external if `rxjs` is external. Using the pnp esbuild plugin changes the behaviour and requires `rxjs/operators` to be explicitly marked as external.
Implement the check esbuild uses to make deep imports of externals also external.
**Checklist**

fix(esbuild): make `foo/bar` external if package `foo` is external

---

.yarn/versions/2eafeb47.yml
packages/esbuild-plugin-pnp/sources/index.ts

ESBuild uses package exports to load files based on whether import or require was used.
Configuring the PnP plugin breaks this behaviour, always resorting to CJS/require code.
Copy the logic ESBuild uses to decide on what conditions to pass in its resolution
**Checklist**

fix(esbuild): resolve to ESM when requested

---

.yarn/versions/dafa68fb.yml
CHANGELOG.md
packages/plugin-pnpm/sources/PnpmLinker.ts

The pnpm linker attempts to delete `node_modules` directory all the time, this causes install failure when Yarn has no permissions. This problem happens even when `node-modules` linker is active.
Fixes #4172
Fixes #4160
Based on the evaluation of pnpm linker finalizeInstall code, seems this behavior - to manipulate node_modules directory- was not intended. I have updated it so that this code was not run.
**Checklist**

fix(pnpm): pnpm linker no longer removes node_modules when nm linker is active

---

.yarn/versions/6983a0de.yml
CHANGELOG.md
packages/yarnpkg-nm/sources/hoist.ts
packages/yarnpkg-nm/tests/hoist.test.ts

The nm linker did not run a hoisting algorithm inside aliased packages.
Fixes: #4236
I have updated conditions inside nm hoister, so that it applied hoisting algorithm inside aliased packages.
In this PR I have also removed `hoisted form:` output in `NM_DEBUG_LEVEL=2` since it pollutes the output and it doesn't help in any way with hoisting troubleshooting.
**Checklist**

fix(nm): apply hoisting algorithm on aliased dependencies

---

packages/acceptance-tests/pkg-tests-specs/sources/features/installArtifactCleanup.test.ts

The artifact cleanup tests randomly fail on the CI and until we figure out why they're just noise.
Disable them.
**Checklist**

test: disable flaky tests

---

packages/gatsby/src/components/header.js
packages/gatsby/src/pages/index.js

I have added Ukrainian banner initially to all the pages of the website and into a fixed position. Unfortunately this disrupts docs UX, because the banner takes much of vertical space.
I have left the banner on the home page only and made it a part of the content. I'm open to other ideas how to make the banner visible and not disrupt the docs UX on the same time.
**Checklist**

fix(docs): move Ukrainain banner to the home page only to not disrupt docs UX

---

.yarn/versions/768814ed.yml
packages/yarnpkg-parsers/sources/syml.ts

The variables `data` and `sort` in parsers can be declared as const, and assigned values in a conditional operator using TypeScript tuples.
Use const for variables `data` and `sort`
**Checklist**

refactor(parsers): use const for vars `data` and `sort`

---

.yarn/versions/b2f24cb2.yml
packages/gatsby/content/advanced/lexicon.md
packages/plugin-npm/sources/NpmHttpFetcher.ts
packages/plugin-npm/sources/NpmSemverFetcher.ts
packages/plugin-npm/sources/NpmSemverResolver.ts
packages/plugin-npm/sources/npmHttpUtils.ts
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/httpUtils.ts

The local cache was enabled in Yarn 2 in large part because people weren't aware that it existed. However, it adds a significant friction around new project creation, and I suspect it might not be as necessary as before (our users have been confronted to it for a while now, so discovery should have improved).
Local cache is now disabled by default. Tests aren't updated yet.
**Checklist**

Make the local cache opt-in (rather than opt-out)

---

.yarn/versions/9aaf86c6.yml
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/plugin-nm/sources/NodeModulesLinker.ts

This is a follow-up PR to #3467. @merceyz noticed the performance regression, this was due to the #3467 didn't take into account scoped packages during syncing tree with disk and it resulted in the reinstallation of all the scoped packages each time.
Added handling scoped packages during syncing tree representation with disk contents and added an integration test.
**Checklist**

fix(nm): takes into account scoped packages during syncing tree with disk

---

packages/gatsby/static/configuration/yarnrc.json

The `libc` field is useful when using some dependencies but it's missing from the documentation.
Closes #4256
...
I added the field in the exampleKeys of the JSON.
...
**Checklist**

docs: add reference to `libc` key in `supportedArchitectures` documentation

---

.yarn/versions/95d4f806.yml
packages/plugin-git/sources/gitUtils.ts

There's a redundant variable `match` in `fetchRoot` function which can be removed.
Removed the redundant variable `match`
**Checklist**

chore(git): remove redundant variable match

---

packages/yarnpkg-nm/tests/hoist.test.ts

The second clause of this condition was not covered with unit, integration or E2E tests
https://github.com/yarnpkg/berry/blob/fde9dfafd515704abd8f066f9769d7fe3d9af5ab/packages/yarnpkg-nm/sources/hoist.ts#L686
I have found a unit test that recreates the conditions when this clause is needed - it is a graph with two similar circular branches.
**Checklist**

test(nm): Adds a unit test which checks that two-branch circular graphs handled properly

---

.yarn/versions/f6c9fb9e.yml
packages/plugin-file/sources/TarballFileResolver.ts

The variable `path` can be declared as const, and assigned values in a conditional operator
Use const for variable `path`
**Checklist**

chore(file): use const for path in getCandidates

---

.yarn/versions/d86fbacc.yml
packages/plugin-pnp/sources/PnpLinker.ts

There is a race condition in the PnP linker where it can end up trying to read the unplugged folder before it is created.
Fixes https://github.com/yarnpkg/berry/runs/5705475812?check_suite_focus=true#step:5:154
> Error: ENOENT: no such file or directory, scandir '/tmp/xfs-f4bc4a3d/.yarn/unplugged'
Wait for the unplugging to complete before calling `finalizeInstallWithPnp`
**Checklist**

fix(plugin-pnp): wait for unplugging to finish before finalizing

---

.yarn/versions/2847fa24.yml
packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/set/version.test.ts
packages/plugin-essentials/sources/commands/set/version.ts
packages/plugin-essentials/sources/commands/set/version/sources.ts
packages/yarnpkg-cli/sources/main.ts
packages/yarnpkg-core/sources/Configuration.ts

Node 14 will soon be the new Node LTS. Since it ships with Corepack, we don't need to store the version file unless users already expect really want it.
The new code detects whether there's a `yarnPath` setting. If there is, it assumes that the version file will be needed. Otherwise, it just updates the `packageManager` field.
**Checklist**

Prefer using exclusively Corepack when possible

---

.github/workflows/integration-workflow.yml

We currently run the full testsuite on all three systems, on all supported Node versions. Windows and OSX are very slow, making us wait significantly longer before being able to get all the results. The problem becomes worse when multiple PRs are merged quickly, as it swamps the runners which then become even more sluggish.
- Cancel runs when pushing multiple commits in PRs one after the other
- Only run Windows / OSX tests on the first LTS we support
It might make sense to later introduce scheduled tests that would run all the tests.

Soften CI coverage

---

.github/workflows/e2e-cra-workflow.yml
.github/workflows/e2e-create-vue-workflow.yml
.github/workflows/e2e-docusaurus-workflow.yml
.github/workflows/e2e-eslint-workflow.yml
.github/workflows/e2e-fsevents-workflow.yml
.github/workflows/e2e-next-workflow.yml
.github/workflows/e2e-preact-cli-workflow.yml
.github/workflows/e2e-snowpack-workflow.yml
.github/workflows/e2e-webpack-workflow.yml
.github/workflows/integration-workflow.yml

When cancelling a workflow it will continue running steps using `always()` which requires another cancelation and is quite annoying. This became more prominent with https://github.com/yarnpkg/berry/pull/4286.
Replaced `always()` with `success() || failure()` which matches what https://github.com/yarnpkg/berry/pull/3643 wanted.
**Checklist**

ci: don't continue running when cancelled

---

.yarn/versions/8f3f5219.yml
packages/yarnpkg-parsers/sources/grammars/shell.js
packages/yarnpkg-parsers/sources/grammars/shell.pegjs
packages/yarnpkg-parsers/tests/shell.test.ts

We didn't support passing `{}` into shell arguments.
Fixes https://github.com/yarnpkg/berry/issues/2670
Just a matter of removing `{` of the list of special characters (so we can write `echo {` or `echo {foo`), and adding a special case for `{}` (so we can write `echo {}` or `echo foo{}`). It seems that `echo }` isn't valid in zsh, so I didn't try to support it.
**Checklist**

Fixes {} parsing inside shell scripts

---

.yarn/versions/72a5ce52.yml
packages/plugin-compat/sources/extensions.ts

Updating this entry in response to https://github.com/apollographql/apollo-tooling/pull/2049
Up until and including `@apollographql/apollo-tools@0.5.2`, the package didn't specify its peer dependency on `graphql` which is the reason for this exception in the first place.
As of `v0.5.3` this package now includes its peer dependency correctly and shouldn't need any hardcoded exceptions made for it.
I specified the version range that this exception applies to (`*` is no longer correct)
...
**Checklist**

chore(compat): lock `@apollographql/apollo-tools` range

---

.yarn/versions/cfd4374c.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/add.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/up.test.ts
packages/plugin-essentials/sources/commands/add.ts
packages/plugin-essentials/sources/commands/up.ts
packages/plugin-essentials/sources/suggestUtils.ts

Calling `yarn add foo@beta` will add `"foo": "beta"` in the manifest. While consistent in practice, this behaviour is generally unexpected and shouldn't be the default.
Semver tags will now be resolved prior to being saved into the manifest. The `-F,--fixed` flag will restore the original behaviour.
**Checklist**

Resolves tags before storing them in the manifest

---

.yarn/versions/1f93b69c.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/checkResolutions.test.ts
packages/gatsby/content/advanced/error-codes.md
packages/plugin-essentials/sources/commands/install.ts
packages/plugin-essentials/sources/dedupeUtils.ts
packages/plugin-exec/sources/ExecResolver.ts
packages/plugin-file/sources/FileResolver.ts
packages/plugin-file/sources/TarballFileResolver.ts
packages/plugin-git/sources/GitResolver.ts
packages/plugin-http/sources/TarballHttpResolver.ts
packages/plugin-link/sources/LinkResolver.ts
packages/plugin-link/sources/RawLinkResolver.ts
packages/plugin-npm/sources/NpmRemapResolver.ts
packages/plugin-npm/sources/NpmSemverResolver.ts
packages/plugin-npm/sources/NpmTagResolver.ts
packages/plugin-npm/tests/NpmSemverResolver.test.ts
packages/plugin-patch/sources/PatchResolver.ts
packages/yarnpkg-core/sources/LegacyMigrationResolver.ts
packages/yarnpkg-core/sources/LockfileResolver.ts
packages/yarnpkg-core/sources/MessageName.ts
packages/yarnpkg-core/sources/MultiResolver.ts
packages/yarnpkg-core/sources/Project.ts
packages/yarnpkg-core/sources/Resolver.ts
packages/yarnpkg-core/sources/RunInstallPleaseResolver.ts
packages/yarnpkg-core/sources/VirtualResolver.ts
packages/yarnpkg-core/sources/WorkspaceResolver.ts
packages/yarnpkg-core/sources/miscUtils.ts
packages/yarnpkg-core/sources/structUtils.ts
packages/yarnpkg-core/tests/TestPlugin.ts

If an attacker changes the `resolutions` field in the lockfile, Yarn will take it relatively well and just assume the new resolution is the truth. As a result they can easily inject malicious code inside a large lockfile update, and they'll be very difficult to spot - even #4299 wouldn't protect against that, as Yarn would just refetch the compromised package resolution rather than the original one.
The `getSatisfying` function (previously only used for `yarn dedupe`) will now be used to check that the resolution locators are valid for a given descriptor (for example `bar@1.0.0` isn't a valid resolution for `foo@^1.0.0` since they have different idents, but it is a valid resolution for `bar@^1.0.0` or even …

Implements `--check-resolutions`

---

.github/workflows/integration-workflow.yml
.yarn/versions/bcc9db40.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
packages/plugin-essentials/sources/commands/install.ts

Lockfiles changes that are part of PRs submitted by third-parties may be compromised and contain metadata that don't match reality. This could lead to maintainers unknowingly starting to depend on packages they don't control / don't trust.
The current solution is to either review the whole lockfile (which is doable, but impractical for large changes, like when upgrading all `@babel` dependencies in a repository), regenerate the lockfile from scratch (high friction), or hope for third-party tools like Snyk to detect issues.
This diff adds a new flag, `--refresh-lockfile`, which will keep resolutions in place but will resolve the associated metadata anew (this is the same thing we do when we bump the lockfile version, to …

Implements `--refresh-lockfile`

---

.yarn/versions/2545ea9d.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.js
packages/plugin-essentials/sources/commands/install.ts
packages/yarnpkg-core/sources/Configuration.ts

The new hardening logic was triggered on all PRs from all repositories - but when a repository is private, the assumption is that people who can access it can also be trusted, so hardening isn't needed there. Additionally, it could lead to problems when the remote registry cannot be reached (for example because it requires a verdaccio instance, etc).
Whether to enable hardening or not is now abstracted behind a `enableHardenedMode` setting, which is automatically set when Yarn detects the current environment is both a PR, and a public repository.
It only supports GitHub Actions for now, but people using other providers can force-enable the mode by adding `YARN_ENABLE_HARDENED_MODE=1` in their environment (which wasn't …

Implements enableHardenedMode

---

.yarn/versions/06e43b84.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
packages/plugin-pack/sources/packUtils.ts

Using the `files` field in `package.json` to include a directory but exclude a files in said directory doesn't work.
Differentiate between "no match" and "negated match" in the `isIgnored` check.
**Checklist**

fix(pack): handle excluding from included parent directory

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/versions/4a257e90.yml
packages/yarnpkg-sdks/sources/sdks/base.ts

VSCode 1.66 changed the format for in-memory file paths (again) in https://github.com/microsoft/vscode/commit/e04c70a676898301b543bd59147e1bfb033d8fb9.
Fixes https://github.com/yarnpkg/berry/issues/4304
Closes https://github.com/yarnpkg/berry/pull/4322
Updated the pattern and fixed the VSCode version detection on Windows and Linux.
**Checklist**

fix(sdks): update for VSCode 1.66

---

.yarn/versions/4704a5d3.yml
packages/plugin-version/sources/commands/version/apply.ts
packages/plugin-version/sources/versionUtils.ts

We don't use `yarn version apply` much, and when trying to use it to bump the ZipFS extension I noticed it caused all release markers to be dropped (instead of just the ones relative to the package being bumped).
Fixed to only remove the entries relative to the packages being bumped.
A followup will be to write tests, but I want to make the release before that 🙂
**Checklist**

Fixes `yarn version apply`

---

.yarn/versions/10e66509.yml
packages/plugin-compat/sources/extensions.ts

`auto-relay` has a missing peerDependency on `reflect-metadata`.
- PR to fix `auto-relay`: https://github.com/wemaintain/auto-relay/pull/95
- I added an extension for the `reflect-metadata` peerDependency.
**Checklist**

chore(compat): add extension for 'auto-relay' peerDependency on 'reflect-metadata'

---

.yarn/versions/cb320125.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/plugin-nm/sources/NodeModulesLinker.ts

We forgot to update the `node-modules` linker in https://github.com/yarnpkg/berry/pull/3575 to support `supportedArchitectures`.
Fixes https://github.com/yarnpkg/berry/issues/4323
Updated the linker to use `this.opts.project.configuration.getSupportedArchitectures()` to get the supported architectures.
**Checklist**

fix(plugin-nm): handle `supportedArchitectures`

---

packages/gatsby/content/features/plugins.md

A typo in the docs.
Changing the words.
**Checklist**

docs: Fix plugin author name

---

.yarn/versions/2fb68a30.yml
packages/yarnpkg-core/sources/Cache.ts
packages/yarnpkg-core/sources/Project.ts

During the link step of an install the `Cache` will check if cache entries exists on disk even though it already checked that during the fetch step.
Ref https://github.com/yarnpkg/berry/issues/4057
Check if the cache entry is in `markedFiles` before checking the disk.
**Benchmark results**
On the gatsby benchmark this removes 1942 `access` syscalls
```
YARN_IGNORE_PATH=1 hyperfine -w 1 \
"node ./cache.cjs --mode skip-build" \
"node ./master.cjs --mode skip-build"
Benchmark 1: node ./cache.cjs --mode skip-build
Time (mean ± σ):      1.621 s ±  0.009 s    [User: 2.344 s, System: 0.352 s]
Range (min … max):    1.605 s …  1.637 s    10 runs
Benchmark 2: node ./master.cjs --mode skip-build
Time (mean ± σ):      1.707 s ±  0.012 …
```

perf(core): skip unnecessary `access` call in `fetchPackageFromCache`

---

.yarn/versions/47902e08.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/up.test.ts
packages/plugin-essentials/sources/commands/up.ts

The `yarn up` command was broken when run on dependency already up-to-date since #4305.
Normalizes the descriptor before passing it to `forgetResolution`.
**Checklist**

Fixes the "yarn up" command when the dependency doesnt need upgrades

---

.yarn/versions/27b23f7e.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/dlx.test.js
packages/plugin-dlx/sources/commands/dlx.ts

After https://github.com/yarnpkg/berry/pull/4291 `yarn dlx` stopped using the exact tag specified and instead resolved it to a SemVer range which breaks the SvelteKit e2e test.
Make `yarn dlx` use the exact version the tag points to.
**Checklist**

fix(dlx): preserve tags

---

.yarn/versions/778bfffd.yml
packages/plugin-compat/sources/extensions.ts

The `create-react-app` e2e test broke in https://github.com/yarnpkg/berry/pull/4253
As a temporary workaround until `create-react-app` fixes their ESLint setup make `eslint` a peer dependency /w fallback.
**Checklist**

fix(compat): `react-scripts`

---

.github/workflows/e2e-parcel-workflow.yml
.yarn/versions/3bf5a52e.yml
packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-backward-tags-1.0.0-rc.1/index.js
packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-backward-tags-1.0.0-rc.1/package.json
packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-backward-tags-1.1.0/index.js
packages/acceptance-tests/pkg-tests-fixtures/packages/no-deps-backward-tags-1.1.0/package.json
packages/acceptance-tests/pkg-tests-specs/sources/commands/add.test.ts
packages/plugin-compat/sources/extensions.ts
packages/plugin-essentials/sources/suggestUtils.ts

See https://github.com/parcel-bundler/parcel/issues/7999
Adding `@parcel/core` to the dependencies. This way users can add it to their dep and unblock the parcelrc issue. However perhaps this should be added to the Parcel documentation?
**Checklist**

Fixes the Parcel E2E test

---

.eslintrc.js
.yarn/versions/e2989261.yml
packages/plugin-essentials/sources/suggestUtils.ts
packages/yarnpkg-core/sources/semverUtils.ts

We shouldn't have to remember to use `semverUtils.validRange` instead of `semver.validRange` / `semver.Range`.
Ref https://github.com/yarnpkg/berry/pull/2890#issuecomment-840747821
Make ESLint remember it for us.
**Checklist**

chore: add lint rule for `semver.validRange` and `semver.Range`

---

README.md

Minor grammatical error in README file [here](https://github.com/yarnpkg/berry/blob/master/README.md?plain=1#L101) has been fixed. Grammatically, 'a historical' is the correct usage over 'an historical'.
Did not find any related issue open for the grammatical error.
...
Changed 'an' to 'a'. Now the sentence reads 'Cloudflare has also been a historical partner'.
**Checklist**

docs: fix incorrect grammar in README

---

scripts/dist-scripts/yarn

- Fixes https://github.com/yarnpkg/yarn/issues/5349
Also use `cygpath` for `MINGW`, similar to https://github.com/yarnpkg/yarn/blob/3119382885ea373d3c13d6a846de743eca8c914b/scripts/build-dist.sh#L8-L10.
**Checklist**

Use cygpath for MINGW (Git Bash)

---

scripts/bench-run.sh

The location of the pnpm store changed in v7 (https://github.com/pnpm/pnpm/releases/tag/v7.0.0) so the benchmark isn't testing a "full cold" install anymore.
Updated the store location.
**Checklist**

ci: update pnpm store location

---

.yarn/versions/fecc5928.yml
packages/yarnpkg-cli/sources/boot-cli-dev.js

[citgm](https://github.com/nodejs/citgm) will check the yarn version during installation step. And yarn cli's dev version is `x.x.x.dev` which can't be recognized by [semver](https://github.com/semver/semver)
So I would like to change it to `x.x.x-dev`
The related PR of [citgm](https://github.com/nodejs/citgm) is https://github.com/nodejs/citgm/pull/905
change the cli dev version format to `x.x.x-dev`
...
**Checklist**

fix(cli): correct the cli's dev version to match semver spec

---

.gitignore
packages/yarnpkg-fslib/tests/ZipFS.test.ts

ZipFS could do with some more tests.
Add some tests to cover `statSync` and `resolveFilename`.
**Checklist**

test(fslib): add more tests for `ZipFS`

---

.pnp.cjs
.yarn/versions/2e7530b2.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/npm/audit.test.ts
packages/gatsby/static/configuration/yarnrc.json
packages/plugin-npm-cli/package.json
packages/plugin-npm-cli/sources/commands/npm/audit.ts
packages/plugin-npm-cli/sources/index.ts
packages/plugin-npm-cli/sources/npmAuditTypes.ts
packages/plugin-npm-cli/sources/npmAuditUtils.ts
packages/plugin-npm-cli/tests/npmAuditUtils.test.js
yarn.lock

Closes #4355
...
This PR adds a `--exclude` flag to the `yarn npm audit` command in the
`nmp-cli` plugin. This flag can be passed multiple times, and any package
listed will be removed from the list of packages audited.
This PR also adds a `--ignore` flag to `yarn npm audit`, which is an array
of ID's to ignore from the audit report.
In addition, the ID is presented in the tree output (as well as the JSON).
...
**Checklist**

[plugin-npm-cli]: Add ability to exclude packages, or ignore specific advisories in `yarn npm audit`

---

.yarn/versions/adfd24fc.yml
packages/yarnpkg-extensions/sources/index.ts

focus-trap-react directly depends on tabbable, but relies on obtaining it transitively via its dependency on focus-trap. PR to resolve upstream here: https://github.com/focus-trap/focus-trap-react/pull/691
...
Added a new package extension for focus-trap-react.
~Note: I'm almost certain that I didn't apply the staged version changes correctly. I'm not sure exactly how the yarnpkg/extensions package is used, so I'm not totally sure how upgrading it should affect other packages! Happy to make any changes necessary to the version file.~ Thanks @merceyz!
...
**Checklist**

chore(extensions): add `tabbable` dependency to `focus-trap-react`

---

packages/gatsby/src/components/markdown.js
packages/gatsby/src/components/navigation.js

some styles are missing fallback font for PT Mono.
so it would be `serif` if web fonts aren't avilable...
I just add `monospace` as fallback font to some styles that missing fallback font.
**Checklist**

docs: use monospace for fallback font of PT Mono

---

.yarn/versions/fd50b4cb.yml
CHANGELOG.md
packages/plugin-nm/sources/NodeModulesLinker.ts
packages/plugin-pnp/sources/PnpLinker.ts
packages/plugin-pnpm/sources/PnpmLinker.ts
packages/yarnpkg-core/sources/Installer.ts
packages/yarnpkg-core/sources/Linker.ts
packages/yarnpkg-core/sources/Project.ts

Addresses one of the checklist items listed for Yarn 4 in #3591.
Moved the function from Installer to Linker in each of the linkers.
**Checklist**

feat!: move getCustomDataKey to Linker

---

packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js

One of the PnP tests fails when the path to the test folder contains whitespace.
Fixes one of the failing tests in https://github.com/nodejs/citgm/pull/905.
> Error: Cannot find module 'C:\Program'
https://ci.nodejs.org/job/citgm-smoker-nobuild/1242/nodes=win10-vs2019/testReport/junit/(root)/citgm/_yarnpkg_cli_v4_0_0_rc_6/
Use `JSON.stringify` to escape the path.
**Checklist**

test(pnp): escape path in `NODE_OPTIONS` env variable

---

.yarn/versions/c9075f14.yml
packages/plugin-constraints/sources/Constraints.ts
packages/yarnpkg-core/sources/MessageName.ts

The constraints plugin might silently ignore constraints due to an hardcoded Prolog interpreter limit.
Fixes https://github.com/yarnpkg/berry/issues/1260
* The Prolog limit is now proportional to the number of packages in the workspace
* If the limit is exceeded, an error will be thrown, to avoid silencing actual errors
**Checklist**

fix(plugin-constraints): use proportional prolog limit

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/versions/0d403b34.yml
packages/yarnpkg-sdks/sources/sdks/base.ts

VSCode 1.68 changed the format for in-memory file paths in https://github.com/microsoft/vscode/pull/148940 and https://github.com/microsoft/vscode/pull/149125.
~~VSCode 1.68 isn't released yet so this is only noticeable in VSCode Insiders and since the version detection doesn't work with the Remote Development extensions I'll leave this as a draft until it has been released.~~
Updated the paths to match the new format.
**Checklist**

fix(sdks): update for VSCode 1.68

---

.github/workflows/e2e-create-vue-workflow.yml

The `create-vue` e2e test [started failing again](https://github.com/yarnpkg/berry/actions/runs/2493717491).
Remove the temporary `yarn up vue-tsc` fix since it's no longer needed and is now what is causing the errors.
**Checklist**

ci: fix the `create-vue` e2e test

---

packages/gatsby/content/features/plugins.md

This PR adds a new plugin to the list of "contrib plugins". The plugin is [`yarn-plugin-pin-deps`](https://github.com/splitgraph/yarn-plugin-pin-deps), which adds a command `yarn pin-deps`. This command will find any dependencies referenced with a semver identifier, and will update `package.json` to replace that identifier with the exact version of the package currently resolved in the lockfile for that reference.
We've been using it "in production" for 1+ year and I recently migrated it to support Yarn 3, so I decided to also take the opportunity to package it as a plugin. It's worked well for our purposes, where the original goal was to migrate a mono-repo to use pinned dependencies. By it's nature it isn't something we use often, but we do …

docs: Append `yarn-plugin-pin-deps` to Contrib plugins

---

.yarn/versions/737b861b.yml
packages/plugin-patch/sources/patchUtils.ts
packages/plugin-patch/tests/__snapshots__/diffFolders.test.ts.snap

helps to avoid https://github.com/yarnpkg/berry/issues/3341 by generating diffs without renames
passed [`--no-renames`](https://git-scm.com/docs/git-diff#Documentation/git-diff.txt---no-renames) option when calling `git diff`
**Checklist**

fix(plugin-patch): avoid creating rename diffs

---

.yarn/versions/21659536.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/link.test.js
packages/plugin-essentials/sources/commands/link.ts

I find myself often linking specific packages from a remote monorepo. I don't want to link _all_ the workspaces so I don't use `--all`. Right now I have to run `yarn link <path-1> && yarn link <path-2>`. I'd like to be able to run `yarn link <path-1> <path-2>`. Similar to `yarn unlink`.
We now iterate over all destinations which I've changed to a rest arg in clipanion.
**Checklist**

feat(plugin-essentials): support specifying multiple paths in `yarn link`

---

.github/workflows/e2e-esbuild-workflow.yml
.yarn/versions/662b766b.yml
packages/esbuild-plugin-pnp/sources/index.ts

On-load callbacks can provide a custom `resolveDir` for virtual modules; if set, it should be used for resolving paths in that file. `importer` is only guaranteed to be a file system path if the namespace is `file`.
For context, see: https://esbuild.github.io/plugins/#on-resolve-arguments
If another esbuild plugin creates virtual modules with relative imports, esbuild-plugin-pnp will incorrectly resolve them, since it assumes `importer` (the virtual module) is a real file path, and there are no such guarantees. This bug was observed after [integrating esbuild-plugin-pnp into remix core](https://github.com/remix-run/remix/pull/1316) and attempting to [convert virtual modules to use relative …

fix(esbuild-plugin-pnp): respect resolveDir

---

packages/gatsby/content/getting-started/migration.md

Node.js 12.x had also reached its EOL on 30 April 2022
Node 12.x had also reached its official End Of Life on 30 April 2022 ([reference](https://nodejs.org/en/blog/release/v12.22.12/)) but the docs didn't mention it.
Updated the migration guide's *General Advices* section accordingly.
**Checklist**

docs: update Node.js versions in migration guide

---

.yarn/versions/24ae6364.yml
packages/yarnpkg-cli/sources/boot-cli-dev.js

Before #4458, the CLI dev version had `.dev` appended. #4458 changed it to have `-dev` appended.
Neither is correct 100% of the time.
I've changed it to use a dot as a delimiter if the version already has a prerelease component.
- Before: `4.0.0-rc.10-dev`
- After: `4.0.0-rc.10.dev`
**Checklist**

fix(cli): fix dev version

---

.yarn/versions/27f02004.yml
CHANGELOG.md
packages/yarnpkg-libui/sources/misc/renderForm.tsx

4.x TODO item: make `renderForm`'s streams required so that people don't forget to specify custom streams. This is consistent with what we do in other parts of the codebase that accept streams.
Made the `options` argument required.
**Checklist**

refactor(libui)!: require `renderForm` streams to be specified

---

packages/yarnpkg-core/tests/Configuration.test.ts

I accidentally removed tests in #4305:
https://github.com/yarnpkg/berry/pull/4305/files#diff-4d98124b51058e4b1b729f3792a00957ad367e76324658eb510d2eedc5e7a406
Add them back
**Checklist**

Adds tests accidentally removed in #4305

---

.yarn/versions/63ea7bc1.yml
CHANGELOG.md
packages/plugin-workspace-tools/sources/commands/foreach.ts

One of the 4.x items in #3591: automatically enabling the `-v,--verbose` flag of `yarn workspaces foreach` inside TTY environments.
The reasoning behind this is the fact that it's a lot more useful to see what output comes from which workspace, and it's consistent with what we do in `@yarnpkg/shell` with background jobs (only enabling verbose output and prefixes in TTYs).
Added an `isTTY` check.
I've also tried to add tests for it, but I can't trick `child_process` / `cross-spawn` / `execUtils` into making the process think it's running inside a TTY.
Because of this, the only alternative I see is using `node-pty` and processing the output, which is something I wouldn't wish on my worst enemy, so no tests for now. …

feat(foreach)!: automatically enable `--verbose` in tty environments

---

.yarn/versions/d54e2225.yml
packages/esbuild-plugin-pnp/sources/index.ts

A fix in the same area as #4569, for the `esbuild-plugin-pnp`, regarding the `resolveDir` property
Many plugins use the `resolveDir` argument in the `onResolve` callback (e.g. to find the absolute path of an imported relative module like in the [Remix compiler](https://github.com/remix-run/remix/blob/main/packages/remix-dev/compiler/plugins/emptyModulesPlugin.ts#L18)
Currently, plugins that rely on modules loaded with yarn pnp, get an empty `resolveDir` passed to the `onResolve` callback.
It would make sense to, when loading modules with pnp, default the `resolveDir` to the directory of the current module/file being loaded, as it also lives on disk. This brings us closer in behaviour to the default `file` namespaced modules too.
**How did you fix …

fix(esbuild-plugin-pnp): return `resolveDir` from `onLoad`

---

.yarn/versions/db7650d7.yml
packages/gatsby/static/configuration/yarnrc.json
packages/plugin-patch/sources/tools/apply.ts

Fixes #3660
- Documented it
- Also fixed 2 typos in the patch plugin's inline documentation (seemed small enough to keep here)
**Checklist**

docs(patch): document plugin options

---

.github/workflows/e2e-pnp-angular-workflow.yml

The bug has been fixed upstream in https://github.com/angular/angular-cli/pull/23487 and https://github.com/ng-packagr/ng-packagr/pull/2367 so we can remove the workaround.
Removed it.
**Checklist**

ci: remove workaround for Angular PnP e2e test

---

.pnp.cjs
.yarn/versions/0be235bd.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/commands/dlx.test.js
packages/plugin-dlx/sources/commands/dlx.ts
packages/plugin-init/package.json
packages/plugin-init/sources/commands/init.ts
packages/yarnpkg-core/package.json
packages/yarnpkg-core/sources/miscUtils.ts
packages/yarnpkg-core/tests/miscUtils.test.ts
packages/yarnpkg-sdks/sources/sdkUtils.ts
yarn.lock

`yarn dlx` reports `UNUSED_PACKAGE_EXTENSION` warnings when an extension is unused in the temporary project created by dlx, even if it is used in the actual project the command is run in.
Made `dlx` filter out all `UNUSED_PACKAGE_EXTENSION` warnings via `logFilters` since they should only be about the main project.
**Checklist**

fix(dlx): don't report `UNUSED_PACKAGE_EXTENSION` warnings

---

packages/gatsby/content/features/zero-installs.md

Clarifies zero-installs version requirement in the first step of the documentation; change proposed due to others' frustrations.
Some people, not naming Chris specifically, don't notice the mention of a version requirement in the opening sentence of the configuration instructions. This is quite common when people aren't familiar with a tool and can lead to excessive frustration, which should be minimised at all costs.
This commit makes the version requirement - and what to do if it isn't satisfied - very clear by adding it as the first step. Now one truly has to be blind to miss it.
**Checklist**

docs: clarify the zero-installs requirements

---

.pnp.cjs
.yarn/versions/c03bc2db.yml
packages/yarnpkg-extensions/sources/index.ts

Updates the extensions list to include
- https://github.com/bokuweb/react-rnd/pull/864
- https://github.com/vuetifyjs/vue-cli-plugins/pull/324
- https://github.com/jdesboeufs/connect-mongo/pull/458
- https://github.com/intlify/vue-i18n-next/commit/ed932b9e575807dc27c30573b280ad8ae48e98c9
- https://github.com/vuejs/router/commit/c2305083a8fcb42d1bb1f3f0d92f09930124b530
- https://github.com/unifiedjs/unified/pull/146
- https://github.com/ntkme/react-github-btn/pull/23
- https://github.com/facebook/create-react-app/pull/11716 / https://github.com/facebook/create-react-app/pull/11526
- https://github.com/asyncapi/asyncapi-react/pull/614
**Checklist**

chore(extensions): update list

---

.pnp.cjs
.yarn/versions/655b7b5f.yml
packages/plugin-pnp/sources/PnpLinker.ts

The package `open` doesn't work with PnP without users manually unplugging it.
Closes https://github.com/yarnpkg/berry/issues/856
Add `open` and `opn` to `FORCED_UNPLUG_PACKAGES`.
**Checklist**

fix(pnp): automatically unplug `open` and `opn`

---

.yarn/versions/fbc424b9.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/features/pnpm.test.ts
packages/plugin-pnpm/sources/PnpmLinker.ts

Fixes #4525 
Symlinks for dependencies are created higher in the directory structure. Instead of 
`<project_root>/node_modules/.store/webpack-cli-virtual-66f7aceb77/node_modules/webpack-cli/node_modules/commander`,
the symlink is created at:
`<project_root>/node_modules/.store/webpack-cli-virtual-66f7aceb77/node_modules/commander`
This is the same way as `pnpm` does. This avoids the symlink loop on the file system. It works, because Node.js fallbacks to `realpath` and parent directories look up when it fails to find a module without applying `realpath`.
**Checklist**

fix(plugin-pnpm) Pnpm linker avoids symlink loops on the file system

---

.yarn/versions/9bb15e03.yml
CHANGELOG.md
packages/plugin-npm-cli/sources/commands/npm/audit.ts
packages/plugin-npm/sources/npmConfigUtils.ts

4.x TODO item: removing the fallback to the publish registries inside `yarn npm audit`.
See https://github.com/yarnpkg/berry/pull/3583#discussion_r730413780 for the original discussion.
Removed the fallback and removed the `manifest` parameter of `npmConfigUtils.getAuditRegistry` since it isn't needed (consistent with `npmConfigUtils.getDefaultRegistry`).
**Checklist**

fix(audit)!: remove fallback to publish registries

---

.yarn/versions/2c936507.yml
CHANGELOG.md
packages/plugin-version/sources/versionUtils.ts

This PR removes the deprecated `versionUtils.{fetchBase,fetchRoot,fetchChangedFiles}` that have been moved to `gitUtils`.
Removed them.
**Checklist**

refactor!: remove deprecated versionUtils

---

.yarn/versions/dab3d358.yml
CHANGELOG.md
packages/plugin-init/sources/commands/init.ts

This PR removes the `--assume-fresh-project` flag of `yarn init`.
The flag has been a no-op since Yarn 3.x. Should be safe to remove now since AFAIK the only use case it breaks is initializing a Yarn 4 project using a `yarn@>=2.1.0 <3.0.0` binary, which should be very uncommon.
Removed it.
**Checklist**

refactor(init)!: remove `--assume-fresh-project`

---

.yarn/versions/17a3b8fe.yml
packages/yarnpkg-shell/sources/pipe.ts

`@yarnpkg/shell` uses the `exit` event to know when a process finishes executing but the `exit` event can be called before the `stdio` streams are flushed which causes a race condition where it sometimes wont get the `stdout` value.
Fixes https://github.com/yarnpkg/berry/issues/3220
Switch from the `exit` event to the `close` event which is called after the `stdio` streams are closed.
**Checklist**

fix(shell): wait for stdio streams of process to close

---

packages/gatsby/package.json
packages/gatsby/typedoc-plugin-yarn/package.json
yarn.lock

We're depending on `typedoc@next` but that tag doesn't exist anymore.
Use an explicit version.
**Checklist**

docs: use explicit version instead of `next` tag for `typedoc`

---

.yarn/versions/032af3c1.yml
packages/yarnpkg-core/sources/LegacyMigrationResolver.ts
packages/yarnpkg-core/tests/LegacyMigrationResolver.test.ts

It's common for companies to host their packages at an Artifactory deployment on their own domain, like `packages.mycompany.com`. This has the same URL pattern as any other JFrog repository, but on a non-JFrog domain.
Currently, migrating a Yarn v1 project that uses such packages fails due to the package URLs in the lockfile not being recognized, blocking easy migration at my company.
Example URL:
```
https://packages.example.com/artifactory/api/npm/npm/@convoy/code-style/-/@convoy/code-style-19.0.0.tgz#b89d83150ba80ec03dffb6c025ceeb00a2443697
```
We currently work around this with `sed -i 's|/-/@convoy/|/-/|' yarn.lock` to essentially fake the standard URL format right before migration.
...
Update the regex for the JFrog …

fix(core): support migrating resolutions from JFrog Artifactory registries regardless of the domain

---

packages/gatsby/src/components/json.tsx
packages/gatsby/src/components/syml.tsx
packages/gatsby/src/components/syntax.tsx

There are missing commas after array brackets and object braces on the manifest configuration page.
Got rid of the `dictionaries.suffix` and `array.suffix` distinction since they're always the same for the formats we care about, which allows us to always use `theme.delimiter` and stop worrying about passing the `suffix` prop.
Technically there are also trailing commas to worry about, but I don't think they're important enough to be worth the extra complexity. Even if we decided in the future to stop displaying them, it would still make a lot more sense to use a different boolean toggle prop for it instead of keeping `suffix` as a prop.
**Checklist**

docs: add missing commas on configuration pages

---

packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts

fix that test:integration cannot exit gracefully, for example, https://ci.nodejs.org/job/citgm-smoker-nobuild/1353/nodes=win10-vs2019/console
unref the timer
**Checklist**

test: clear timeout after test finishes

---

packages/gatsby/content/advanced/pnp-data.md
packages/gatsby/static/configuration/pnp.json
packages/yarnpkg-pnp/tests/testExpectations.json

A couple of errors have been raised in https://github.com/evanw/esbuild/pull/1985
**Checklist**

Fixes errors in the PnP spec

---

.yarn/versions/2be8c391.yml
packages/plugin-essentials/sources/commands/add.ts
packages/plugin-essentials/sources/commands/remove.ts
packages/plugin-essentials/sources/commands/set/version.ts
packages/plugin-essentials/sources/commands/up.ts
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/Project.ts

It doesn't make sense to have `FormatType` as a standalone export anymore, now that it can be used as `formatUtils.Type`.
Replaced all occurrences and deprecated it. I didn't completely remove it since I think it makes sense to keep it deprecated for a major so that plugin authors have time to migrate.
**Checklist**

refactor: deprecate `FormatType`

---

.yarn/versions/7a2baa8b.yml
packages/yarnpkg-fslib/sources/algorithms/copyPromise.ts

We were using `lockPromise` to write files into the cache; since there was a lot of files to write, and we did this for each one, it was very expensive.
Experimenting with instead "moving" the file from a temporary path to the final one once the write is finished.
**Checklist**

Faster copy through index

---

.yarn/versions/cd54fce4.yml
packages/yarnpkg-extensions/sources/index.ts

`xo` depends on `eslint-import-resolver-webpack`, but only calls into it conditionally.
So while `eslint-import-resolver-webpack` has a peer dependency on webpack, `xo` has an optional one.
Upstream PR: https://github.com/xojs/xo/pull/678
...
Added a new package extension for `xo`
...
**Checklist**

chore(extensions): Add `webpack` optional peerDependency to xo

---

.yarn/versions/11abead6.yml
.yarn/versions/39ddc77a.yml
.yarn/versions/434fcaba.yml
.yarn/versions/4ef8937b.yml
.yarn/versions/64fa7941.yml
.yarn/versions/7d95d0bf.yml
.yarn/versions/7e1696fd.yml
.yarn/versions/7f506ae4.yml
.yarn/versions/80053b5a.yml
.yarn/versions/80ae97a2.yml
.yarn/versions/bf825c43.yml
.yarn/versions/d7ae2216.yml
.yarn/versions/dc69403b.yml

https://github.com/yarnpkg/berry/pull/4707 removed `@yarnpkg/json-proxy` but didn't remove the references to it in the release files (probably because VSCode is set to ignore the `.yarn` folder when searching).
Fixes https://github.com/yarnpkg/berry/runs/7814553654?check_suite_focus=true#step:6:32
Removed the references.
**Checklist**

chore: remove release entries for `@yarnpkg/json-proxy`

---

packages/gatsby/content/features/plugnplay.md

Hi there!
ESBuild released a new [Version](https://github.com/evanw/esbuild/releases/tag/v0.15.0), supporting PnP. This PR updates the Docs.
**Checklist**

docs: update ESBuild PnP support status

---

packages/gatsby/content/advanced/pnp-spec.md

We don't highlight the fact that the PnP spec assumes all paths to be normalized to the unix format (https://github.com/evanw/esbuild/issues/2462#issuecomment-1214253036).
Tweaked the docs. I've also renamed the file from `pnp-data.md` to `pnp-spec.md` to match the URL and to make it easier to find.
**Checklist**

docs: highlight the fact that the spec assumes the unix path format

---

packages/gatsby/content/advanced/error-codes.md

Fixing typo in error code docs describing checksum mismatching caching workarounds.
Verbiage describes two commands, but in fact there are three.
...
...
**Checklist**

docs: update `error-codes`

---

.github/workflows/stale-workflow.yml

Stale issues are currently closed as `completed`, when they should be closed as `not_planned`, according to their respective descriptions:
Used the https://github.com/actions/stale#close-issue-reason parameter of the action.
**Checklist**

chore: use `not_planned` reason for stale issues

---

.yarn/versions/4aec9c76.yml
packages/plugin-git/sources/gitUtils.ts

https://github.com/yarnpkg/berry/pull/4729 forgot to make the network errors in `gitUtils` use the newly introduced `MessageName` too.
Made them use the new `MessageName` and extracted the logic to a new `validateRepoUrl` function to prevent duplication and so that we don't forget to do this again in the future.
**Checklist**

fix: use `MessageName.NETWORK_DISABLED` in `gitUtils` too

---

.yarn/versions/56df934e.yml
CHANGELOG.md
packages/plugin-pnpm/sources/PnpmLinker.ts

When using the `PnpmLinker` on this repo, it currently reports 69 identical `incompatible virtual` warnings.
I'd say one is enough.
**Checklist**

fix(pnpm-linker): warn only once about virtuals

---

.yarn/versions/db20fa43.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
packages/plugin-pnp/sources/PnpLinker.ts
packages/plugin-pnp/sources/index.ts

We still remove the old `.pnp.js` files when migrating, but our telemetry currently shows that only 5% of all modern users still use Yarn 2, so it doesn't make sense for us to still keep this migration feature one more major when they can just migrate one major at a time.
Removed the code.
**Checklist**

refactor!: stop removing old `.pnp.js` files when migrating

---

.yarn/versions/0d3b87f7.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/installArtifactCleanup.test.ts
packages/plugin-pnp/sources/PnpLinker.ts

The `PnpLinker` doesn't remove the unplugged folder when switching to a different linker.
Made it remove it and added tests.
**Checklist**

fix: remove unplugged folder when switching to a different linker

---

.github/workflows/integration-workflow.yml

Even if the check isn't run as part of PRs, it still takes almost 4 hours, and if we used shards we'd still use the same amount of CI minutes but everything would finish faster.
Made it use 4 shards. More than that would result in diminishing returns compared to the number of extra CI checks it creates.
If anybody considers these 4 checks too much we can also try 3, since it would be around 1 hour and 15 minutes each, which is still a lot better than 4 or 2.
**Checklist**

ci: use shards for big-endian

---

.yarn/versions/11cf053f.yml
packages/yarnpkg-core/sources/Resolver.ts

The JSDoc of `getSatisfying` still mentions passing an array of references as an argument, when it should now be an array of locators.
Updated the docs.
**Checklist**

docs: update `getSatisfying` JSDoc

---

.github/actions/prepare/action.yml
.github/workflows/benchmark-workflow.yml

The E2E tests use a minified bundle, which makes it a lot harder to read stack traces if something goes wrong with Yarn.
Build a bundle with `--no-minify` instead.
**Checklist**

ci(e2e): use non-minified bundle

---

packages/gatsby/static/configuration/yarnrc.json

The `enableScripts` setting currently [only applies to third-party packages](https://github.com/yarnpkg/berry/blob/f0e21079535302229314b08bb214ed9f9d157c6b/packages/yarnpkg-core/sources/Project.ts#L1080-L1106). I believe it's because we ideally would want installs to be made with `enableScripts` set to false by default (for security reasons), but there's no point into blocking the workspaces' `postinstall` scripts by default (since it doesn't improve security).
Closes https://github.com/yarnpkg/berry/issues/4780
Ref https://github.com/yarnpkg/berry/issues/4386
Ref https://github.com/yarnpkg/berry/issues/4547
Updated the documentation.
**Checklist**

Adds a note about workspaces in the `enableScripts` documentation

---

.pnp.cjs
.yarn/versions/67cdb4e6.yml
packages/yarnpkg-pnp/sources/generatePnpScript.ts

The `.pnp.cjs` file doesn't use strict mode because `Emscripten libraries aren't strict mode` but that isn't the case anymore.
Enabled strict mode.
**Benchmark result**
Doesn't do much for performance but either way:
```console
$ hyperfine "node -r ./.pnp-before.cjs -e 1" "node -r ./.pnp-after.cjs -e 1"
Benchmark 1: node -r ./.pnp-before.cjs -e 1
Time (mean ± σ):      91.7 ms ±   2.7 ms    [User: 1.9 ms, System: 3.9 ms]
Range (min … max):    89.6 ms …  99.7 ms    32 runs
Benchmark 2: node -r ./.pnp-after.cjs -e 1
Time (mean ± σ):      91.0 ms ±   1.1 ms    [User: 0.5 ms, System: 1.6 ms]
Range (min … max):    89.7 ms …  94.6 ms    31 runs
Summary
'node -r ./.pnp-after.cjs -e 1' ran
1.01 ± 0.03 times faster than 'node -r …
```

perf(pnp): enable strict mode in `.pnp.cjs`

---

packages/gatsby/content/getting-started/install.md

Installation requires a separate google search if you've never used `corepack`.
Added an "Activate Yarn" section to the documentation.
**Checklist**

docs: add yarn corepack activation

---

.yarn/versions/0d3ddb4d.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/add.test.ts
packages/plugin-essentials/sources/commands/add.ts

Yarn add `--peer` and `--dev` do not work when used together
Resolves #4691
...
Let the return value of the `suggestTarget` function of the `packages/plugin-essentials/sources/commands/add.ts` file change from `suggestUtils.Target` to `suggestUtils.Target[]`, It is possible to add different types of dependencies at once
...
**Checklist**

fix(essentials): yarn add `--peer` and `--dev` do not work when used together

---

scripts/actions/local-yarn-command/Dockerfile
scripts/actions/make-commit/Dockerfile

Some of our `Dockerfile`s use `alpine:latest`.
Closes https://github.com/yarnpkg/berry/issues/4753
Closes https://github.com/yarnpkg/berry/pull/4755
Lock the version.
**Checklist**

chore: lock Alpine version in `Dockerfile`s

---

.yarn/versions/35dc33e8.yml
packages/plugin-nm/sources/NodeModulesLinker.ts

The `NodeModulesLinker` computes the `extractHint` for no reason.
Removed it from its custom data.
**Checklist**

perf(NodeModulesLinker): remove `extractHint` from custom data

---

.yarn/versions/1a212dd8.yml
packages/plugin-essentials/sources/commands/set/version.ts

Nightly builds for Classic are broken (first because the CI is broken, second because the latest changes are in the cherry-pick branch, not in the master trunk).
Make `yarn set version classic` use the latest stable Classic build, not nightlies.
**Checklist**

Fixes the version used for set version classic

---

packages/gatsby/content/features/zero-installs.md

Some have concerns about repository size using zero-installs. This could be addressed in the feature page. It might also help some users who are unaware of this potential downside to make a better decision on whether this is good for them.
See #180
Mention it in the `concerns` section of the feature page.
**Checklist**

docs: mention zero-installs repo size

---

packages/gatsby/playground-sandbox/constants.js
packages/gatsby/playground-sandbox/cors.js
packages/gatsby/playground-sandbox/package.json
packages/gatsby/playground-sandbox/pages/api/check-repo.js
packages/gatsby/playground-sandbox/pages/api/clone-repo.js
packages/gatsby/playground-sandbox/pages/api/fetch-node-version.js
packages/gatsby/playground-sandbox/pages/api/sherlock.js
packages/gatsby/playground-sandbox/pages/index.js

The playground doesn't work anymore because of `cors` issues.
Fixes https://github.com/yarnpkg/berry/issues/4760.
Used `nextjs-cors` to properly setup `cors`. No idea why it previously worked though (before it broke a month ago). I assume the Next version used in the playground might have gotten updated when the playground reset itself for no reason a few months ago.
I've already synced the playground with this PR and I can confirm it works again.
**Checklist**

chore(playground): fix cors issue

---

packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
packages/acceptance-tests/pkg-tests-specs/sources/protocols/git.test.js

The `it should guarantee that all dependencies will be installed when using npm to setup npm repositories` test:
- manually specifies its timeout, bypassing the automatic timeout setting based on endianness, which sometimes makes the test timeout on BE (e.g. https://github.com/yarnpkg/berry/actions/runs/2883842363/jobs/4582779531#step:5:60).
- sometimes timeouts on windows (e.g. https://github.com/yarnpkg/berry/actions/runs/3074200372/jobs/4966840912#step:5:15)
- Removed the manually specified timeout.
- Increased the timeout by 5 seconds on LE. If it's not enough we can increase it even more in the future.
**Checklist**

test(integration): tweak timeout

---

.github/workflows/stale-workflow.yml

Fixes https://github.com/yarnpkg/berry/pull/4759#issuecomment-1226992424.
Quoting @merceyz from https://github.com/yarnpkg/berry/pull/4759#issuecomment-1226994964:
> We need to update actions/stale, close-issue-reason was added in [v5.1.0](https://github.com/actions/stale/releases/tag/v5.1.0) but we're using v3.
Updated to `actions/stale@v5`.
**Checklist**

chore: update `actions/stale` to v5

---

CODEOWNERS

We've had internal discussions about it and @arcanis agreed to stop codeowning `@yarnpkg/core` to make it easier for us to merge small PRs affecting the core.
Removed it.
@arcanis Feel free to tweak the file yourself in case I misinterpreted what you said or you've changed your mind. :smile:
**Checklist**

chore: remove @yarnpkg/core CODEOWNERS

---

scripts/bench-run.sh

Pnpm uses a request metadata cache so that it doesn't have to hit the network when rebuilding the lockfile unless the data is stale, but we don't clear it in the relevant benchmarks.
Removed [`~/.cache/pnpm`](https://pnpm.io/npmrc#cache-dir) in:
- full-cold, since this step needs to be fully cold
- ~~cache-only, since it's supposed to test how much it takes to resolve all packages (without caching)~~ Actually, we want `cache-only` to test real-life conditions so metadata caching is fair game.
**Checklist**

chore(bench): remove pnpm metadata cache in full-cold

---

.yarn/versions/038526b5.yml
CHANGELOG.md
packages/yarnpkg-parsers/sources/grammars/shell.js
packages/yarnpkg-parsers/sources/grammars/shell.pegjs
packages/yarnpkg-parsers/tests/shell.test.ts
packages/yarnpkg-shell/tests/shell.test.ts

The shell doesn't support whitespace-only commands.
Fixes #4164.
Implemented support for them, but only for whitespace-only *commands*, not *shell lines*, given the fact that the latter are only supported by zsh and fish (but they aren't consistent with each other) and they're quite useless.
**Checklist**

feat(shell): support whitespace-only commands

---

.pnp.cjs

My other PR In chore testing got an error, after I rebase it on master branch.
I tried to checkout to the master branch and found the same error, so I guess some PRs may have forgotten to update the pnp file.
...
Run the `yarn` command to update pnp file.
...
**Checklist**

fix: update pnp file to fix chore testing error

---

.pnp.cjs
package.json
scripts/test-typescript-patch.js
yarn.lock

Related https://github.com/yarnpkg/berry/pull/4853
I've noticed these days that master branch CI always has errors. ([github action log](https://github.com/yarnpkg/berry/actions/workflows/e2e-typescript-workflow.yml))
...
After checking, I found some small things that we have missed
1. Update the path to `libzip` in  `scripts/test-typescript-patch.js`
2. Add `@yarnpkg/libzip`  to `@yarnpkg/monorepo`  devDependencies
3. Run `yarn node ./scripts/test-typescript-patch.js` to confirm that it has been fixed
...
**Checklist**

ci: fix the typescript e2e test

---

.yarn/versions/187a6871.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/set/version.test.ts
packages/plugin-essentials/sources/commands/set/version.ts

`yarn set version` doesn't set the `yarnPath` in the project `.yarnrc.yml` if it's set in a parent directory of the project.
Fixes https://github.com/yarnpkg/berry/issues/4366 (Issue doesn't have a reproduction so I can only guess)
Fixes https://github.com/yarnpkg/berry/issues/4426
Update the `.yarnrc.yml` file in the project when required.
**Checklist**

fix(essentials): set `yarnPath` in project `.yarnrc.yml` regardless if it's set in a parent directory

---

.yarn/versions/656f837d.yml
packages/plugin-essentials/sources/commands/workspace.ts
packages/plugin-workspace-tools/sources/commands/foreach.ts
packages/yarnpkg-core/sources/structUtils.ts

There are 2 unnecessary `structUtils.convertToIdent` calls that don't have to exist since there's no problem if the ident has extra fields. 
Removed them.
**Checklist**

perf: avoid unnecessary `structUtils.convertToIdent`

---

.yarn/versions/5fa2fe14.yml
packages/plugin-essentials/sources/suggestUtils.ts

`findProjectDescriptors` returns a list of `workspace.locator`s, which is then compared against `workspace.anchoredLocator`, when they can never be equal.
Made it return a list of `workspace.anchoredLocator`s since in the future I'd prefer to just completely get rid of `workspace.locator` anyways and it also makes more sense to display the `anchoredLocator` in the interactive prompt since it matters more that the package is a workspace, not that it has a specific version.
**Checklist**

fix(suggestUtils): use `workspace.anchoredLocator`

---

.yarn/versions/99c1aeb7.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/fix.test.js
packages/acceptance-tests/pkg-tests-specs/sources/commands/version.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
packages/plugin-essentials/sources/dedupeUtils.ts
packages/yarnpkg-core/sources/Project.ts
packages/yarnpkg-fslib/tests/JailFS.test.ts
packages/yarnpkg-fslib/tests/NodeFS.test.ts
packages/yarnpkg-fslib/tests/xfs.test.ts
packages/yarnpkg-libzip/tests/ZipFS.test.ts

There are promises in the codebase (mostly in tests) that aren't awaited when they should be.
Hopefully solves the `Jest did not exit one second after the test run has completed.` from https://github.com/nodejs/citgm/pull/905#issuecomment-1272299869.
`await` the promise or change to the sync version if possible.
**Checklist**

fix: handle unintentional floating promises

---

.yarn/versions/95c5c99a.yml
packages/plugin-constraints/README.md
packages/plugin-exec/README.md
packages/plugin-interactive-tools/README.md
packages/plugin-stage/README.md
packages/plugin-typescript/README.md
packages/plugin-version/README.md
packages/plugin-workspace-tools/README.md

Since https://github.com/yarnpkg/berry/pull/4253, users no longer need to manually install the official plugins, so the readme installation section is outdated
...
Change the install section of all plugin's readme to `This plugin is included by default in Yarn 4.`
...
**Checklist**

docs: update the install section of all plugin's readme

---

.yarn/versions/1ac92dd7.yml
packages/yarnpkg-nm/package.json

Currently when using the nm package directly, there is compilation error because pnp is not in the deps:
...
**Checklist**

fix(nm): pnp should be a prod dep of nm

---

.yarn/versions/dfa11c68.yml
packages/yarnpkg-shell/sources/index.ts
packages/yarnpkg-shell/tests/shell.test.ts

close https://github.com/yarnpkg/berry/issues/4892
close https://github.com/yarnpkg/berry/issues/4893
after this PR is merged, https://github.com/yarnpkg/berry/pull/4900 all tests should pass
...
I modified the default case of `evaluateVariable`.
steps:
1. parse the argument and variable first
2. parse default value and alternative value according to the result of the previous step
3. If neither value is found, throw an error
...
**Checklist**

fix(shell): fix alternative value not working as expected

---

packages/gatsby/content/features/plugins.md

Add `scripts` capability to `.yarnrc.yml` file.
This is just to add more plugins to the Yarn 3 ecosystem. Specifically, a plugin that allows a `scripts` configuration within the `.yarnrc.yml` file that can be invoked under a `scripts` namespace (i.e `yarn scripts my-script`).
...
It is already built and linked in the README.md for others to use. Tests are run with `yarn test` and builds are run with `yarn build`. Idk if I am missing anything but everything is there to be tested and run.
...
**Checklist**

docs: add `yarn-plugin-scripts` to Contrib plugins

---

.yarn/versions/13f288ec.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/plugin/__snapshots__/check.test.ts.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/plugin/check.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/plugin/import.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/plugin/remove.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/features/plugins.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/features/plugins.utility.ts
packages/plugin-essentials/sources/commands/plugin/check.ts
packages/plugin-essentials/sources/commands/plugin/import.ts
packages/plugin-essentials/sources/index.ts
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/Plugin.ts

Closes https://github.com/yarnpkg/berry/issues/4464
When the user loses the `.yarn/plugins` directory, all yarn commands will fail. 
...
[reason](https://github.com/yarnpkg/berry/pull/4912#issuecomment-1262357332)
```    
before:
1. load RC file core fields
2. load core and third-party plugins
3. load RC file remaining fields
after:
1. load RC file core fields
2. load core plugins
3. load RC file remaining fields
4. load third-party plugins
```
...
**Additional attempts**
https://github.com/jj811208/berry/pull/4
...
**Checklist**

feat: when initializing the `Configuration`, auto fetch the missing plugins

---

packages/yarnpkg-shell/tests/shell.test.ts

We were running some test by calling missing binaries to check for the `||` and `&&` operators. While it worked, it seems that on Windows some extra cruft is printed on stderr, tainting the expectations.
Instead of calling a non-existent binary, we now just call the `false` builtin (which has the same effect but doesn't output anything).
**Checklist**

test(shell): fix failing tests

---

.github/actions/prepare/action.yml

GitHub has deprecated the use of `::set-output`.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
Update to write to the new `GITHUB_OUTPUT` environment file.
**Checklist**

ci: migrate from `::set-output` to `$GITHUB_OUTPUT` environment file

---

.yarn/versions/40c30377.yml
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/protocols/__snapshots__/git.test.js.snap
packages/gatsby/static/configuration/yarnrc.json
packages/plugin-nm/sources/NodeModulesLinker.ts
packages/plugin-nm/sources/index.ts

Closes yarnpkg/berry#4979
Currently on Windows `yarn` uses `junctions` to link workspaces into `node_modules` directories. On other platforms `yarn` uses symlinks.
As a result, workspace links in `node_modules` on Windows are _always_ absolute paths. On other platforms links may be relative paths, leading to _inconsistent behavior_ when using `nodeLinker: node-modules` and running `yarn install` from Windows vs. Linux.
A particularly bad side-effect of absolute paths on Windows is that it breaks Docker builds--when a monorepo is mounted into a container, the absolute paths are invalid.
The PR adds an additional configuration option for the `nm-linker` to use symbolic links on Windows as well, thereby supporting relative links, and fixing container …

feat(plugin-nm): support configuring link mode

---

packages/gatsby/content/getting-started/install.md

Corepack won't always have the latest Yarn release installed globally. It would be helpful to provide instructions on how to go about ensuring it does.
https://github.com/yarnpkg/berry/pull/4815 attempted to address that, but was reverted because it didn't specify which versions of Node.js have Corepack >=0.12 (and thus support using a `dist-tag` instead of a version number when running `corepack prepare`).
...
Added new section to docs (based on https://github.com/yarnpkg/berry/pull/4815) providing appropriate commands depending on the version of Node.js.
As I'm writing this, I'm wondering if I should edit it slightly to clarify that the underlying reason it matters which version of Node.js you're using is because of the …

docs: add Node.js versions for `corepack prepare yarn@stable`

---

.yarn/versions/6e4fa8ee.yml
packages/plugin-pack/sources/index.ts

The `browser` field is assigned twice while packing ([first assignment](https://github.com/yarnpkg/berry/blob/master/packages/plugin-pack/sources/index.ts#L33), [second assignment](https://github.com/yarnpkg/berry/blob/master/packages/plugin-pack/sources/index.ts#L39)). I removed the unnecessary second assignment.
...
...
**Checklist**

perf(pack): remove duplicated assignment of `browser` in `publishConfig`

---

packages/gatsby/static/configuration/yarnrc.json

In the documentation for `.yarnrc.yml` for the `cpu` value an incorrect value `x86` is shown as an example.
Fixes #4998
...
Updated the docs to:
- use the correct value `x64` as an example
- note that valid values for this option are the possible values from `node:process.arch`
...
**Checklist**
I did NOT update versions as this is a documentation change only. Wasn't sure what version to bump, if any.

docs: correct example value for `.yarnrc.yml` `cpu` field

---

.yarn/versions/96582795.yml
packages/plugin-npm/sources/npmHttpUtils.ts
packages/yarnpkg-core/sources/nodeUtils.ts

TOTP requests from the npm registry (#4308) aren't automatically opened on Windows.
We now make a call to `explorer.exe` to open them. Will double-check it works well on my Windows machine.
**Checklist**

Adds support for Windows when opening urls

---

.yarn/versions/dbec145e.yml
packages/plugin-exec/sources/ExecFetcher.ts

The `exec:` protocol logs aren't printed even when `enableInlineBuilds` is defined, which prevents seeing potential errors (especially on CI).
The fetcher will now respect `enableInlineBuilds`. I thought about adding a separate configuration setting, but it felt unnecessary as the reasons why one would want to see the output of the builds also require to show the output of the `exec:` package generation.
**Checklist**

feat(exec)!: Adds support for enableInlineBuilds to the exec: fetcher

---

.yarn/versions/a1d2b6c1.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/__snapshots__/mergeConflictResolution.test.js.snap
packages/plugin-essentials/sources/commands/install.ts
packages/yarnpkg-core/sources/MessageName.ts

The current merge conflict resolution algorithm is nice because it operates using only the conflict markers that Git puts into the files, but it has several drawbacks:
- Git sometimes generates bogus conflict markers, which lead to the resulting lockfile to have invalid checksums (#2583, https://github.com/yarnpkg/berry/issues/1771#issuecomment-734813568, ...)
- Git doesn't put conflict markers on the `__metadata.version` field (because it rarely change except when you upgrade Yarn, so there are no conflicts), which prevents us from knowing whether the merged lockfile has accurate metadata.
Closes #2583
Closes #5041
This diff reimplements the merge conflict auto-resolver to instead query the Git state. It retrieves the …

Reimplements the Git merge conflict resolution

---

.github/actions/prepare/action.yml
.github/workflows/e2e-preact-cli-workflow.yml
.github/workflows/integration-workflow.yml
.github/workflows/release-candidate.yml
.github/workflows/sherlock-workflow.yml

Node.js v18 is LTS now so we should run our e2e tests against it.
https://nodejs.org/en/blog/release/v18.12.0/
Also fixes:
> error Gatsby requires Node.js 18.0.0 or higher (you have v16.18.0).
https://github.com/yarnpkg/berry/actions/runs/3447208507/jobs/5752979253#step:4:72
Updated the CI to Node.js v18.
**Checklist**

ci: update to Node.js v18

---

packages/gatsby/content/advanced/lexicon.md

There are wrong link and line breaks in Lexicon document.
I saw no issue related.
...
I removed wrong link and added line breaks properly.
...
**Checklist**

docs(gatsby): wrong link & line breaks in Lexicon

---

scripts/release/01-release-tags.sh
scripts/release/03-release-npm.sh

- The fix in https://github.com/yarnpkg/berry/pull/3499 didn't work since the `yarn` binary it uses is created before the PnP hook is potentially updated
https://github.com/yarnpkg/berry/blob/86183c70a76a5556d290951b5c1385d304155023/.github/workflows/release-candidate.yml#L31-L41
- The CI creates `@yarnpkg/cli-dist` using the stable bundle instead of the RC since
https://github.com/yarnpkg/berry/blob/0926e2474e0d7431366988c4bbb1f2a407b1bcb8/scripts/release/01-release-tags.sh#L111-L116 runs before it does.
- Run the built bundle directly.
- Copy the correct bundle.
**Checklist**

chore: fix creation of `@yarnpkg/cli-dist` and artifact updating

---

.yarn/versions/768bd0b5.yml
packages/yarnpkg-builder/sources/commands/build/bundle.ts
packages/yarnpkg-builder/sources/commands/build/plugin.ts

https://github.com/yarnpkg/berry/pull/4732 stopped resolving `.mjs` files by default which probably wasn't on purpose.
Added `resolveExtensions` with the default extensions and `.mjs`.
**Results**
The performance doesn't change but the bundle size is slightly improved
```console
$ du -s yarn*
2736    yarn-after.js
2744    yarn-before.js
$ YARN_IGNORE_PATH=1 hyperfine -w 1 \
--prepare 'node ./before.cjs remove dummy-pkg || true' \
'node ./before.cjs add dummy-pkg@link:./dummy-pkg' \
--prepare 'node ./after.cjs remove dummy-pkg || true' \
'node ./after.cjs add dummy-pkg@link:./dummy-pkg'
Benchmark 1: node ./before.cjs add dummy-pkg@link:./dummy-pkg
Time (mean ± σ):      1.280 s ±  0.017 s    [User: 1.724 s, System: 0.306 s] …
```

fix(builder): restore resolution of `.mjs` files

---

.yarn/versions/cad178bf.yml
packages/plugin-workspace-tools/sources/commands/foreach.ts
packages/yarnpkg-core/sources/WorkerPool.ts
packages/yarnpkg-core/sources/nodeUtils.ts

Node.js v19.4.0 comes with a [`os.availableParallelism`](https://nodejs.org/dist/latest-v19.x/docs/api/os.html#osavailableparallelism) function and to quote the docs:
> os.cpus().length should not be used to calculate the amount of parallelism available to an application. Use [os.availableParallelism()](https://nodejs.org/dist/latest-v19.x/docs/api/os.html#osavailableparallelism) for this purpose.
https://nodejs.org/dist/latest-v19.x/docs/api/os.html#oscpus
Use `os.availableParallelism` when available.
**Checklist**

chore: use `os.availableParallelism` when available

---

.yarn/versions/c236874b.yml
packages/plugin-pnp/sources/PnpLinker.ts
scripts/e2e-setup-ci.sh

This PR removes some entries from `FORCED_UNPLUG_PACKAGES` that are no longer needed:
- `nan` - already unplugged because of `.h` files
- `node-gyp` - already unplugged because of `.cc` files
- `node-addon-api` - already unplugged because of `.h` and `.c` files
- `fsevents` - already unplugged because of `.node` files and conditions
- `node-pre-gyp` doesn't need to be unplugged because nobody remembers the reason it was originally unplugged anymore and it doesn't currently include any code that would require it to be. The package has also been deprecated and renamed to `@mapbox/node-pre-gyp` which isn't on our list (and therefore isn't unplugged) and nobody has complained about it not working anymore. I've also done a quick check and both seem to …

perf: remove obsolete forced unplug entries

---

.yarn/versions/54ba2009.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/constraints.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/features/constraintsChecks.test.ts
packages/plugin-constraints/sources/commands/constraints.ts
packages/plugin-constraints/sources/constraintUtils.ts
packages/plugin-constraints/sources/index.ts
packages/yarnpkg-core/sources/MessageName.ts
packages/yarnpkg-core/sources/Project.ts
packages/yarnpkg-core/sources/StreamReport.ts

Running constraints must currently be a conscious thing, or run on CI. I think some users have the expectation that Yarn should just report the errors during install, as it's the main interface they'll use.
This PR adds a new setting, `enableConstraintsChecks`. When enabled, constraints will be checked during each install, as part of the project validation.
*note:* Prolog constraints are slower than the (new) JS ones; it's suggested to upgrade to JS constraints when using this setting.
**Checklist**

Implements automated constraints checks

---

.yarn/versions/c6bf69b2.yml
packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
packages/acceptance-tests/pkg-tests-specs/sources/protocols/file.test.ts
packages/plugin-file/sources/FileResolver.ts
packages/plugin-file/sources/TarballFileFetcher.ts
packages/plugin-file/sources/TarballFileResolver.ts
packages/plugin-file/sources/fileUtils.ts

While `file:./folder` references are properly updated when their content changes, the same doesn't happen for `file:./file.tgz` references.
Fixes #5186
The resolver will now check the tgz file hash, so that changing its content should lead to the cache entry being refetched.
**Checklist**

Detects when file:./foo.tgz files have changed

---

packages/gatsby/content/getting-started/migration.md

https://yarnpkg.com/getting-started/migration suggests `yarn why` as a band-aid for `yarn list` "not being implemented yet", but `yarn info` is a better replacement, and I think fits better in the ["Renamed" table](https://yarnpkg.com/getting-started/migration#renamed) than in the ["Not implemented yet" table](https://yarnpkg.com/getting-started/migration#not-implemented-yet).
_References:_
_https://classic.yarnpkg.com/lang/en/docs/cli/list/_
_https://yarnpkg.com/cli/info_
**Checklist**

docs (migration): `yarn list` --> `yarn info --recursive`

---

packages/docusaurus/static/configuration/yarnrc.json
packages/gatsby/static/configuration/yarnrc.json

- Related https://github.com/yarnpkg/berry/pull/4436
- This pull request fixes plugin-compat database link in yarn documentation.
- Use correct url (correct package/directory name)
**Checklist**

docs: fix plugin-compat database link

---

.yarn/versions/2bf50a76.yml
packages/docusaurus/docs/getting-started/editor-sdks.md
packages/gatsby/content/getting-started/editor-sdks.md
packages/yarnpkg-sdks/sources/generateSdk.ts
packages/yarnpkg-sdks/sources/sdks/base.ts
packages/yarnpkg-sdks/sources/sdks/vscode.ts

`astro-vscode` has an `ls-path` setting that behaves the same as `svelte-vscode`'s. However, there is currently no SDK generation available in `@yarnpkg/sdks` to generate a compatible file.
Added generators for `@astrojs/language-server` to `@yarnpkg/sdks` in the same manner as `svelte-language-server` (https://github.com/yarnpkg/berry/pull/1465).
**Checklist**

feat(sdks): add `@astrojs/language-server` to vscode sdks

---

packages/gatsby/content/features/plugins.md

My plugin is missing on the list of contributed plugins
...
Added my plugin contribution to the list of plugins.
...
**Checklist**

docs: Add contributed plugin

---

.github/ISSUE_TEMPLATE/compatibility.md
packages/docusaurus/docs/getting-started/migration.md
packages/gatsby/content/getting-started/migration.md
packages/plugin-compat/README.md

I made some changes to keep the docs up-to-date with changes around `plugin-compat` database.
**Checklist**

Keep docs up-to-date with changes around `plugin-compat`

---

.yarn/versions/0af71d48.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
packages/plugin-pack/sources/index.ts

We don't currently copy `publishConfig.imports` to `imports` when packing the project, despite doing that for `exports`.
Adds the missing assignment.
**Checklist**

fix(pack): Adds support for "imports" in publishConfig

---

packages/acceptance-tests/pkg-tests-core/sources/utils/fs.ts
packages/acceptance-tests/pkg-tests-core/sources/utils/misc.ts

Some of our test code is referencing methods in the same file through `exports` which works due to how Babel transpiles the files, however when transpiled by esbuild it throws.
TypeScript doesn't complain because `@types/node` contains `declare var exports: any`.
Reference the functions directly.
**Checklist**

test: reference functions directly

---

packages/acceptance-tests/pkg-tests-core/sources/utils/fs.ts
packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts

Simplification of our use of Node.js streams.
Use [`stream.pipeline`](https://nodejs.org/dist/latest-v18.x/docs/api/stream.html#streampipelinesource-transforms-destination-callback) to pipe data between streams.
**Checklist**

test: use `stream.pipeline`

---

.yarn/versions/20b1eacd.yml
packages/plugin-constraints/sources/ModernEngine.ts
packages/plugin-constraints/sources/ModernEngineContext.d.ts

The `error` function is exposed to constraints for each dependency, but not on individual workspaces. It should, because someone may want to report an error in the workspace definition that isn't related to its dependencies.
Added the missing `error` function.
**Checklist**

Exposes the error function through the workspace

---

.pnp.cjs
.yarn/versions/92646a08.yml
packages/plugin-constraints/package.json
packages/plugin-constraints/sources/ModernEngine.ts
packages/yarnpkg-types/sources/constraints.ts
packages/yarnpkg-types/sources/index.ts
packages/yarnpkg-types/sources/yarn.ts
yarn.lock

The `@yarnpkg/types` package was using global declaration to work. It's not ideal since in case we need incompatible types we'll hit walls. It also wasn't working well due to missing imports.
I looked for a way to refactor the exported types so the following is possible (using JSDoc, since `yarn.config.js` can only be written in JS, so good compatibility with JSDoc is important):
```js
// @ts-check
const {Yarn} = require(`@yarnpkg/types`);
/** @type {Yarn.Config} */
module.exports = {
constraints({Yarn}) {
for (const w of Yarn.workspaces()) {
w.set(`license`, `MIT`);
}
},
};
```
**Checklist**

Fixes `@yarnpkg/types`

---

packages/acceptance-tests/pkg-tests-specs/sources/features/editorSdks.test.js

Due to the Windows CI often timing out I ignored the test failure in https://github.com/yarnpkg/berry/pull/5351 but the test was actually broken.
Updated the path to match.
**Checklist**

test: fix editor SDK test

---

.yarn/versions/a0820a77.yml
packages/plugin-constraints/sources/commands/constraints.ts
packages/plugin-constraints/sources/constraintUtils.ts
packages/plugin-constraints/sources/index.ts
packages/yarnpkg-core/sources/Configuration.ts

When a constraints fail, we currently print a message suggesting to run `yarn constraints` to get the full details. However, this doesn't make sense on CI, where the command can't be run.
On CI, we now print the error list.
I'm however kinda reconsidering this approach of "run `yarn constraints` for more details" - if this message is displayed, the user will have to run the command 100% of the time. By this point, why not display the output by default? 🤔
**Checklist**

Prints the constraints errors on CI

---

.yarn/versions/8ca5de64.yml
packages/plugin-git/sources/gitUtils.ts
packages/plugin-git/tests/__snapshots__/gitUtils.test.ts.snap

GitHub doesn't support `git://` anymore (and hasn't been for some time now):
https://github.blog/changelog/2022-03-15-removed-unencrypted-git-protocol-and-certain-ssh-keys/
A couple of old dependencies (including internal ones) still reference `git://` urls, which prevents them from being used.
Just autofix the `git://github.com` url into `https://github.com`. I don't think this has any negative impact.
**Checklist**

Autocorrects git:// into https:// for GitHub

---

.yarn/versions/6595326e.yml
packages/plugin-interactive-tools/sources/commands/upgrade-interactive.tsx

Folder aliases defined using `link:` were incorrectly listed as outdated dependencies
See https://github.com/yarnpkg/berry/issues/5393
Include a check that the dependency range must not start with `link:` to be listed by `yarn upgrade-interactive`
**Checklist**

fix(plugin-interactive-tools): don’t list folder aliases as outdated dependencies

---

packages/gatsby/src/components/seo.tsx

Hi, By adding `<meta name="theme-color " />` we can customise the colour of the app bar. For more info please [click here](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta/name/theme-color)
I have added `#25799f` as a theme-colour  :)
_Extremely sorry if I made any mistakes :(_

docs: add theme colour

---

.yarn/versions/35f2cce0.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/legacyPluginRemoval.test.ts
packages/plugin-essentials/sources/commands/config/set.ts
packages/plugin-essentials/sources/commands/config/unset.ts
packages/plugin-essentials/sources/commands/install.ts
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/index.ts
packages/yarnpkg-fslib/sources/FakeFS.ts

When using `yarn set version` with Yarn 4, the core plugins that were previously externals now conflict with the builtin ones, causing surprising errors.
Fixes #4952
Yarn will now ignore the specified list of plugins when booting. It'll then automatically remove them during the next install.
**Checklist**

Adds legacy plugin removal behavior

---

.yarn/versions/c594112e.yml
packages/acceptance-tests/pkg-tests-specs/sources/pnp-esm.test.ts
packages/yarnpkg-pnp/sources/esm-loader/loaderFlags.ts

The test added in https://github.com/yarnpkg/berry/pull/5362 doesn't run on Node.js v17.
Fixes https://github.com/yarnpkg/berry/actions/runs/5060283241/jobs/9083017466
Updated the range to match Node.js versions containing https://github.com/nodejs/node/pull/42881
**Checklist**

test: fix range for parent URL test

---

.github/workflows/release-branch.yml
scripts/release/01-release-tags.sh
scripts/release/02-release-builds.sh

- Release is stopped when `scripts/release/01-release-tags.sh` has no work to do.
- `scripts/release/02-release-builds.sh` assumes `HEAD` is the release commit but it might not be, for example after committing fixes to the release workflow and creating a new release.
- The release commit isn't getting pushed to `master`.
Follow-up to https://github.com/yarnpkg/berry/pull/5476 and https://github.com/yarnpkg/berry/pull/5478.
- Handle no new packages to release and change the exit code to 0.
- Find the last release commit and check that instead of `HEAD`.
- Reset the changes done to `.yarnrc.yml` and push the changes.
**Checklist**

ci(release): push release to master `master` and allow retrying releases

---

.github/workflows/release-branch.yml

[GitHub releases](https://github.com/yarnpkg/berry/releases) are created manually.
Automated it with the `gh release create` command.
**Checklist**

ci(release): create GitHub release

---

.yarn/versions/e6809da7.yml
packages/docusaurus/docs/getting-started/editor-sdks.md
packages/yarnpkg-sdks/sources/generateSdk.ts
packages/yarnpkg-sdks/sources/sdks/base.ts
packages/yarnpkg-sdks/sources/sdks/vscode.ts

`@yarnpkg/sdks` doesn't support [Relay GraphQL VSCode extension](https://marketplace.visualstudio.com/items?itemName=meta.relay).
Adds `relay-compiler` support to `@yarnpkg/sdks`.
**Checklist**

feat(sdks): add `relay-compiler` to vscode sdks

---

scripts/bench-run.sh

- https://github.com/yarnpkg/berry/pull/5491/commits/07b4ceb3c9c7b8a35037b9307980ffa2bcd1d9c8 changed the metadata cache structure but didn't update the benchmark script to match.
- We're not removing the `$globalFolder/index` folder so `install-full-cold` is skipping some work.
Follow-up to https://github.com/yarnpkg/berry/pull/5491
Clear the entire global folder.
**Checklist**

chore: delete global folder in benchmarks

---

.github/actions/prepare/action.yml

Now that https://github.com/yarnpkg/berry/pull/5491 has landed we can cache the metadata for our e2e tests to potentially speed them up.
Cache metadata.
**Checklist**

ci: cache metadata

---

.yarn/versions/5a966911.yml
packages/yarnpkg-sdks/sources/generateSdk.ts
packages/yarnpkg-sdks/sources/sdks/base.ts

Prettier v3 changes the path to the entry point so we need to update the path used.
Updated the SDK to require `prettier` and let Node.js find the entry point.
**Checklist**

fix(sdks): support Prettier v3

---

tsconfig.json

The exclude pattern `packages/*/{lib,bin,bundles}` in the `tsconfig.json` file doesn't work.
Split it out into separate entries.
**Checklist**

chore: fix tsconfig excludes

---

.yarn/versions/3da18857.yml
packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/npm/audit.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/stage.test.js
packages/plugin-npm-cli/sources/commands/npm/audit.ts
packages/plugin-npm/sources/npmHttpUtils.ts

The new `yarn npm audit` implementation checks the packages' metadata on the audit server rather than the server configured to serve their metadata.
Closes #5533 
Updated the code to use the new `getPackageMetadata` function, which should use the proper server while also leveraging the cache if possible.
**Checklist**

Fixes registry used to check for deprecation settings

---

.pnp.cjs
.yarn/versions/04b94c40.yml
package.json
packages/plugin-essentials/sources/commands/set/version/sources.ts
scripts/bench-folder.ts
yarn.lock

Making benchmarks required a little too much setup for me, so I made a script to make it seamless.
Running `yarn bench` in the repository will spawn a shell inside a temporary folder, with everything setup to run a benchmark when calling `bench-run`. It doesn't handle yet parametrized benchmarks, but should support comparing performances before/after.
Incidentally, the `yarn set version from sources` command now caches the result, to avoid rebuilding the same commits.
**Checklist**

Implements a benchmarking script

---

.yarn/versions/a1769d6c.yml
.yarnrc.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/dotEnvFiles.test.ts
packages/yarnpkg-core/sources/Configuration.ts

I forgot in #4718 to add a test making sure that the yarnrc settings could use the variable set in the dotenv files (the existing tests were mainly around the values set during script execution), and of course I forgot a change 🥲
We now pass the updated environment when interpolating values.
**Checklist**

Fixes settings interpolation with dotenv variables

---

.yarn/versions/523ca228.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/commands/config/set.test.ts
packages/acceptance-tests/pkg-tests-specs/sources/features/dotEnvFiles.test.ts
packages/plugin-essentials/sources/commands/install.ts
packages/plugin-essentials/sources/commands/plugin/remove.ts
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-parsers/sources/syml.ts

It was raised in https://github.com/yarnpkg/berry/pull/5544#issuecomment-1613691793 that automatically injecting the `.env` file in the environment could break compatibility with some software that already do this in their own way. It makes sense, and I prefer to avoid doing that if there's a reasonable compromise.
Also closes https://github.com/yarnpkg/berry/issues/5545.
Yarn will now default into loading the `.env.yarn` file, rather than `.env`.
**Checklist**

Tweaks the .env implementation

---

.github/workflows/release-branch.yml

The GitHub CLI requires setting the `GH_TOKEN` environment variable in order to use it.
Fixes https://github.com/yarnpkg/berry/actions/runs/5427185945/jobs/9870161176#step:6:414
```
gh: To use GitHub CLI in a GitHub Actions workflow, set the GH_TOKEN environment variable. Example:
env:
GH_TOKEN: ${{ github.token }}
```
Set the environment variable.
Verified this works with https://github.com/yarnpkg/berry/commit/87a0d818ce646284e3bda7234a014525f51fa164 to create https://github.com/yarnpkg/berry/releases/tag/%40yarnpkg%2Fcli%2F3.6.1.
**Checklist**

ci(release): set `GH_TOKEN` when creating GitHub release

---

.yarn/versions/620160d3.yml
packages/plugin-essentials/sources/commands/install.ts

I forgot to remove debug code from the upgrade CTA, causing Yarn to always think it should upgrade to 3.6.0.
Removes the hardcoded `3.0.0` version.
**Checklist**

Fixes hardcoded Yarn version

---

.pnp.cjs
.yarn/versions/d431919c.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/__snapshots__/constraints.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints.test.js
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/query.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/__snapshots__/source.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/environments.js
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/fix.test.js
packages/docusaurus/package.json
packages/eslint-config/package.json
packages/plugin-constraints/sources/ModernEngine.ts
packages/plugin-constraints/sources/commands/constraints.ts
packages/plugin-constraints/sources/constraintUtils.ts
packages/yarnpkg-types/sources/constraints.ts
yarn.config.js
yarn.lock

Constraints can only operate on the workspaces' listed dependencies, but have no idea about the shape of the global dependency tree. In general it's enough, but I wanted to write a constraint autofixing missing peer dependencies, and this wasn't possible without knowing the dependencies of our dependencies.
I added a concept of "package" to the constraint API. Some of their characteristics:
- They are based on the resolved dependency tree; as a result, there is no direct concept of devDependency / dependency (just like in the core `Package` type).
- They somewhat look like the `Package` type, but with fewer information (just the dependencies & peer dependencies, at the moment), and with a slightly different format (no need …

Exposes packages to constraints

---

.yarn/versions/20d2e33b.yml
packages/yarnpkg-core/sources/Report.ts

https://github.com/yarnpkg/berry/pull/5530 introduced a new `buffered` property to `Report` but it didn't end up being used.
Removed it, can always be introduced again if we ever need it.
**Checklist**

chore: remove unused `Report#buffered`

---

.yarn/versions/ccc34be1.yml
packages/plugin-essentials/sources/commands/install.ts

`install` checks `enableMotd` before showing a MOTD, but it's already checked inside `TelemetryManager` before setting `isMotd` to `true`: https://github.com/yarnpkg/berry/blob/634daaebb6c4e29f060698ec0241f8044cbe7fe2/packages/yarnpkg-core/sources/TelemetryManager.ts#L254-L255
Removed the duplicate check.
**Checklist**

refactor: remove duplicate `enableMotd` check

---

.yarn/versions/ff5cdcd5.yml
packages/gatsby/content/advanced/error-codes.md
packages/plugin-essentials/sources/commands/install.ts
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/MessageName.ts
packages/yarnpkg-core/sources/TelemetryManager.ts
packages/yarnpkg-core/tests/TelemetryManager.test.ts
tips.json

After some discussions, we've agreed on changing `motd` to `tips`, as the `motd` acronym (`message of the day`) might not be widespread enough.
This PR changes:
- `enableMotd` to `enableTips`
- the `MOTD_NOTICE` message name to `TIPS_NOTICE`
- `motd.json` to `tips.json` (CC @arcanis since you need to change the cloudflare worker)
- `TelemetryManager#isMotd` to `TelemetryManager#shouldShowTips` as it's more descriptive and also more consistent with the existing `shouldCommitTips`
**Checklist**

refactor: rename `motd` to `tips`

---

.github/workflows/integration-workflow.yml

Node.js v20.4 has been released which fixes https://github.com/yarnpkg/berry/pull/5445#issuecomment-1603377915
Use the latest Node.js v20 version.
**Checklist**

ci: use latest Node.js v20 version

---

.yarn/versions/4a8968a1.yml
packages/plugin-npm/sources/npmHttpUtils.ts
packages/plugin-npm/tests/npmHttpUtils.test.ts

While working on https://github.com/yarnpkg/berry/pull/5581 I noticed that we're not normalizing the registry passed to the `npmHttpUtils` methods.
There are tests that are supposed to catch this but the mock wasn't reset before each test so they didn't.
Normalize the registry and update the tests to use `wrapNetworkRequest`.
**Checklist**

fix(plugin-npm): normalize registry

---

packages/yarnpkg-core/tests/httpUtils.test.ts

One of our tests mocks `got` to validate that it is passed the correct URL which doesn't work when transpiled by esbuild.
We have a test that checks that the URL is correct using `wrapNetworkRequest` and various integration tests that should cover it.
Extracted from https://github.com/yarnpkg/berry/pull/5581
Removed the test that required mocking `got`.
**Checklist**

test(core): avoid mocking `got`

---

.yarn/versions/6459c603.yml
packages/yarnpkg-builder/sources/commands/build/bundle.ts
packages/yarnpkg-builder/sources/commands/build/plugin.ts

The builder doesn't make the bundle executable, which means that it can't be spawned directly without node.
I noticed this while testing the `yarn bench` script in our repo, which symlinks the bundle and then [tries to spawn it](https://github.com/yarnpkg/berry/blob/cb19bb3377b7564eced457c47db18109e1041cc1/scripts/bench-folder.ts#L111) without first `chmod`-ing it.
I decided that it makes sense for the builder to chmod it directly.
Made the builder `chmod` it.
**Checklist**

feat(builder): make bundle executable

---

packages/acceptance-tests/pkg-tests-core/sources/utils/fs.ts
packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts

Our tests still use `promisify(stream.pipeline)`.
Made them use `stream.promises.pipeline`, which has been available since Node `15.0.0`.
**Checklist**

test: use `stream.promises.pipeline`

---

packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts

In 90% of PRs, there's at least one check failing due to a few random tests exceeding timeout.
Unfortunately, that isn't helpful at all as it doesn't indicate anything useful. If something could be implemented more efficiently, we'll definitely get an issue about it at some point - timeouts only prevent us from merging PRs and can hide actual issues since it might make us skip checking why a check is failing and assume it's the timeout. 
Increased the timeout on LE systems from `50 seconds` to `75 seconds`.
**Checklist**

test: increase timeout

---

.pnp.cjs
.yarn/versions/7232adf9.yml
packages/plugin-pnp/package.json
packages/plugin-pnp/sources/index.ts
yarn.lock

https://github.com/yarnpkg/berry/pull/824 added a check that throws an error on Node < 12 if the `.pnp.cjs` path contains spaces, due to an old bug in Node.
Removed the check since the bug has been fixed since Node 12.
**Checklist**

perf(plugin-pnp): remove redundant node check

---

.pnp.cjs
packages/acceptance-tests/pkg-tests-specs/package.json
packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
packages/acceptance-tests/pkg-tests-specs/sources/require.test.js
yarn.lock

We have some tests that are disabled on old versions of Node.js but we've dropped support for those versions now so we can run the tests unconditionally.
Remove the Node.js version checks.
**Checklist**

test: remove unnecessary node version checks

---

.yarn/versions/8b252311.yml
packages/yarnpkg-shell/sources/index.ts
packages/yarnpkg-shell/tests/shell.test.ts

`timersPromises.setTimeout` has been available since Node `15.0.0`.
Replaced `promisify(setTimeout)` with `timersPromises.setTimeout`.
**Checklist**

refactor: use `timers/promises`

---

.yarn/versions/d3925be6.yml
packages/yarnpkg-parsers/sources/shell.ts
packages/yarnpkg-parsers/tests/shell.test.ts

Positional arguments were over-complexified during serialization. For example, `"foo bar"` was serialized as `$'foo bar'`. It works, but it's a surprising syntax for users.
Since I needed to use the serialization to generate part of the new website, I fixed it to make it look more natural, and added tests to avoid regressions.
**Checklist**

Improves string escaping during serialization

---

.yarn/versions/bfe31a8a.yml
packages/yarnpkg-cli/sources/cli.ts
packages/yarnpkg-cli/sources/index.ts
packages/yarnpkg-cli/sources/lib.ts

Passing the context to the CLI instance was impractical, as it required to know exactly what was the context that the commands expect. I think there's something to improve here in Clipanion itself (perhaps so that the context can be defined when instantiating the CLI, not running the first command), but that's for a separate time.
I made `getCliBase` add a `defaultContext` field to the CLI instance. I considered returning them as separate fields, but wasn't sure it'd be worth the hassle of conveying two different values. Might revisit in a follow-up PR.
**Checklist**

Refactors context passing

---

.yarn/versions/e5885c61.yml
CHANGELOG.md
packages/plugin-constraints/sources/Constraints.ts
packages/plugin-constraints/sources/index.ts
packages/plugin-essentials/sources/commands/link.ts
packages/plugin-essentials/sources/commands/unlink.ts
packages/plugin-essentials/sources/commands/workspace.ts
packages/plugin-nm/sources/NodeModulesLinker.ts
packages/plugin-version/sources/versionUtils.ts
packages/plugin-workspace-tools/sources/commands/foreach.ts
packages/yarnpkg-core/sources/Project.ts
packages/yarnpkg-core/sources/Workspace.ts
packages/yarnpkg-core/sources/structUtils.ts
packages/yarnpkg-doctor/sources/cli.ts

`workspace.locator` is quite useless and only creates confusion with `workspace.anchoredLocator`.
At the moment, it's only used in places that need an ident, which `workspace.anchoredLocator` can happily provide.
In the past, it was also used accidentally instead of `workspace.anchoredLocator` before I fixed it in https://github.com/yarnpkg/berry/pull/4937.
Removed it since it doesn't provide any benefits. Its only actual use is comparisons in `project.tryWorkspaceByLocator`, but nobody has ever passed it to `project.tryWorkspaceByLocator` anyways.
**Checklist**

refactor(core)!: remove `workspace.locator`

---

.github/workflows/e2e-nm-berry-workflow.yml
.yarn/versions/89a69c6d.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/installArtifactCleanup.test.ts
packages/plugin-pnp/sources/index.ts
scripts/setup-ts-execution.js

We [set `NODE_OPTIONS` for PnP](https://github.com/yarnpkg/berry/blob/f5f2f6ef97be320eb625adb69ad8cd6c54b75745/scripts/setup-ts-execution.js#L11) in `setup-ts-execution`, which causes `yarn config set nodeLinker && yarn install` to fail due to `NODE_OPTIONS` still referencing the removed PnP files during build scripts.
I consider this a Yarn issue and not a `setup-ts-execution` issue because Yarn, like any other package, is supposed to work under PnP, even if `NODE_OPTIONS` happens to be set.
Fixes https://github.com/yarnpkg/berry/actions/runs/5669921008/job/15363692897#step:4:229.
This PR makes `setupScriptEnvironment` from `@yarnpkg/plugin-pnp` remove the PnP flags from `NODE_OPTIONS` if the linker isn't `pnp`. …

fix(plugin-pnp): unset `NODE_OPTIONS` when preparing the environment after switching linkers

---

.yarn/versions/d9107e26.yml
packages/yarnpkg-cli/sources/lib.ts

`@yarnpkg/cli` currently does a `ppath.resolve(cwd ?? ppath.cwd())`, which is unnecessary for `ppath.cwd()` as it already returns an absolute path.
Made it skip resolving it.
**Checklist**

perf(cli): avoid resolving `ppath.cwd()`

---

.yarn/versions/3717145c.yml
packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
packages/acceptance-tests/pkg-tests-specs/sources/protocols/npm.test.js
packages/plugin-http/sources/constants.ts

fixes #5434
...
Add support for tar resolver URLs with fragments
...
**Checklist**

fix: support fragment in tar regex

---

packages/docusaurus/docusaurus.config.js
packages/docusaurus/src/components/HomepageFeatures/index.tsx
packages/docusaurus/src/components/HomepageFeatures/styles.module.css
packages/docusaurus/src/css/custom.css
packages/docusaurus/src/pages/index.module.css
packages/docusaurus/src/pages/index.tsx
packages/docusaurus/src/theme/Root.tsx
packages/docusaurus/static/js/custom.js

I'm working to deploy the new documentation to yarnpkg.com. Since it's been made for Yarn 4 (which is currently RC), we want to provide users a link to the old documentation for the time being.
**Checklist**

Adds a warning on the website about the document being intended for Yarn 4

---

.yarn/versions/12c46079.yml
packages/acceptance-tests/pkg-tests-specs/sources/pnp.test.js
packages/yarnpkg-pnp/sources/generatePnpScript.ts

Fix an infinite recursion in Yarn PnP that occurs when working tree is made of symlinks (e.g., inside bazel sandbox), and workspace's disabled the `pnpEnableInlining` option. In this type of scenario the `.pnp.cjs` ends up calling into itself when requiring the data file
```
/private/var/folders/s8/_fsw_h153fvdqr2vdzkwlm_00000gn/T/xfs-5ff6cf33/test-sandbox-out/.pnp.cjs:44
const fs__default = /*#__PURE__*/_interopDefaultLegacy(fs);
^·
RangeError: Maximum call stack size exceeded
at Object.<anonymous> (/private/var/folders/s8/_fsw_h153fvdqr2vdzkwlm_00000gn/T/xfs-5ff6cf33/test-sandbox-out/.pnp.cjs:44:34)
at Module._compile (node:internal/modules/cjs/loader:1254:14)
at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
at …
```

fix(pnp): fix infinite recursion when .pnp.cjs is a symlink and pnp inlining is disabled

---

.yarn/versions/e0fbb587.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/run.test.js
packages/yarnpkg-cli/sources/lib.ts

Fixes a scenario w/ Yarn CLI where a non-zero exit code is ignored (and `exitCode = 1` is used instead), when running a command using `yarn` binary specified by `yarnPath`.
Apparently [current implementation](https://github.com/yarnpkg/berry/blob/a66e528506168f7bfaa4fa9fc02b8edb226e47d4/packages/yarnpkg-cli/sources/main.ts#L107-L111) uses a `error.code` property, which does not exist on the `Error` that the underlying [`child_process.execFileSync()`](https://nodejs.org/api/child_process.html#child_processexecfilesyncfile-args-options) throws, when a child process exits w/ a non-zero exit status. The `error.status` should be used instead, as per Node.js API documentation:
> If the process times out or has a non-zero exit …

fix(cli): propagate proper exit status code when running yarnPath binary

---

.yarn/versions/0e2286cc.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/unplug.test.ts
packages/plugin-pnp/sources/commands/unplug.ts

I noticed that running `yarn unplug --all got` didn't work in our repository. After digging, I found out its traversal logic was mistakenly marking the workspaces as being visited as soon as they were seen as dependency - even if they weren't actually traversed due to the `--recursive` flag being missing.
Fixed the traversal logic.
**Checklist**

Fixes a bug in `yarn unplug --all`

---

.yarn/versions/03e1fe2a.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-core/sources/utils/makeTemporaryEnv.ts
packages/acceptance-tests/pkg-tests-specs/sources/features/enableOfflineMode.test.ts
packages/docusaurus/docs/advanced/01-general-reference/error-codes.md
packages/docusaurus/static/configuration/yarnrc.json
packages/plugin-essentials/sources/suggestUtils.ts
packages/plugin-npm/sources/NpmSemverResolver.ts
packages/plugin-npm/sources/NpmTagResolver.ts
packages/plugin-npm/sources/npmHttpUtils.ts
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/MessageName.ts
packages/yarnpkg-core/sources/Project.ts

We didn't have a good story for people performing local development on their projects while under network-constrained environments. I'm myself working from trains from time to time, and each time it always come a point where I want to do a quick repro with one package or another, but since I don't have network it's a pain.
A new `enableOfflineMode` setting tells Yarn to reuse the metadata stored in the cache, even if they may be stale (a good feature reuse of the logic @paul-soporan's originally made for perf reasons!).
**Checklist**

Implements enableOfflineMode

---

.github/workflows/integration-workflow.yml

It seems Ubuntu 22.04 has some issues with Node.js: a lot of ETXTBUSY errors are thrown.
Pins the version of Ubuntu to 20.04 for the integration tests. I didn't pin it for every single test since things seemed to work for other jobs and making it a variable seemed unnecessary.

Use ubuntu-20.04 to run the integration tests

---

packages/docusaurus/static/configuration/yarnrc.json

PR adds `arm64` to the list of example architectures for the CPU for the `.yarnrc` config file. I added this given that it's probably one of the most popular things people might add to this field given the existence of the Apple M1/M2 machines, and that I originally stumbled onto this field about just that, and the clickthrough to the node docs was unnecessary if the docs just listed this field. There is precedent in having the `arm64` field listed in the example per the `manifest.json` file:
https://github.com/yarnpkg/berry/blob/2634e6ca9c1c63a17b9c2f679ae77f9d852ff5d2/packages/docusaurus/static/configuration/manifest.json#L69-L77
By adding `arm64` to the list of supported CPU architectures.
**Checklist**

Add arm64 to example supported cpu values

---

packages/yarnpkg-shell/tests/shell.test.ts

Node.js 20.4 broke using emojis in file names: https://github.com/nodejs/node/issues/48673
Disabling the code that relies on it (it's just a sanity check anyway).
**Checklist**

Disables emoji in our Windows tests until Node is fixed

---

scripts/actions/local-yarn-command/Dockerfile

The Sherlock GitHub Action has been failing because the Alpine version specified for the Docker container only has packages for node 16.
Updated the Alpine version
**Checklist**

Update alpine version for sherlock workflow

---

packages/docusaurus/docs/features/plugnplay.md

The intended aside wasn't being rendered because of a typo.
Pls tag for hacktoberfest, if y'all participating.
**Before**
**After**
...
Corrected the typo
...
**Checklist**

docs: fix `:::warning` aside

---

.github/workflows/e2e-preact-cli-workflow.yml

Preact CLI not only now supports Node.js 18, but _requires_ it:
> Usage Error: This tool requires a Node version compatible with >=18.12.0 (got 16.20.2).
> `# Remove when Preact CLI supports Node.js 18`
So I did 🤷 
**Checklist**

ci: e2e - use Node.js 18 for Preact CLI tests

---

.github/workflows/e2e-cra-workflow.yml

CRA installs @testing-library/jest-dom@5.17.0, and @types/testing-library__jest-dom is already at v6. This caused incompatible definitions to be installed, eventually leading to tests crashing.
Recreated environment created by E2E tests, figured out what the error is, fixed type definitions version, made sure TypeScript no longer complains.
**Checklist**

ci: e2e - fix installing @types/testing-library__jest-dom v6 instead of v5 in CRA tests

---

README.md

Badge URLs were outdated (not in a format that "Create status badge" outputs function right now), causing them to be "stuck in the past". As a result, README shown both Angular E2E workflows as failing, where in fact they are running just fine!
Recreated all badges
**Checklist**

docs: fix broken "Current status" badges

---

packages/gatsby/content/features/zero-installs.md

`actions/checkout` now supports modifying the way `git clone` is performed so the link to the upstream PR should be removed.
Closes https://github.com/yarnpkg/berry/pull/5607
Closes https://github.com/yarnpkg/berry/pull/5598
Closes https://github.com/yarnpkg/berry/pull/5592
Removed the link from the v3 docs.
**Checklist**

docs: remove link to `actions/checkout` partial clone PR

---

packages/docusaurus/src/lib/packageChecks.tsx

The website reports incorrect results regarding `@types` package because it is reading the truthiness of the `react-query` return object instead of the result `data` boolean.
Read the correct data
Fixes #5761
**Checklist**

docs: Fix package "types available" check

---

packages/docusaurus/docs/advanced/04-technical/contributing.md

#5180 replaced `@babel/register` with `esbuild` but the docs were not updated
Update docs accordingly
**Checklist**

docs: replace `@babel/register` with `esbuild`

---

.yarn/versions/1dfc7586.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/npm/audit.test.ts
packages/plugin-npm-cli/sources/commands/npm/audit.ts
packages/yarnpkg-core/sources/treeUtils.ts

The rewrite of `yarn npm audit` broke a couple of things in the advisory reporting.
Fixes #5824 - The `--exclude` filter wasn't applied to deprecations
Fixes #5830 - The `--json` output was printing the raw registry output, not the filtered tree
Fixed the deprecation iterations (we were iterating the unfiltered data).
Fixed the json reporting to instead print the same tree as the one we would have displayed outside of `--json`. It's _technically_ a breaking change, but it was supposed to be like that so it's probably fine to treat it as a 7.0.1 bugfix.
Added tests to prevent regressions.
**Checklist**

Fixes bugs in yarn npm audit

---

.yarn/versions/17861fba.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/peerDependenciesMeta.test.ts
packages/plugin-essentials/sources/commands/explain/peerRequirements.ts
packages/yarnpkg-core/sources/Project.ts
packages/yarnpkg-core/sources/index.ts

I didn't update the `yarn explain peer-requirements` when I refactored the peer dependency warnings to report aggregates rather than independent entries. As a result, the reported hash doesn't work.
Fixes #5826
I reimplemented `yarn explain peer-requirements` to take those warnings into account. I also updated the output to use a more natural language which might help better understand the situation:
Note that I temporarily removed support for calling `yarn explain peer-requirements` on missing peer dependencies, as I'd like to take another look at those warnings in general (I noticed they aren't aggregated, but they probably should be too). Since they are fairly easy to understand by themselves, I don't feel like this is a …

Reimplements yarn explain peer-requirements

---

packages/docusaurus/static/configuration/yarnrc.json

Adds `injectEnvironmentFiles` to the documentation

---

packages/docusaurus/static/configuration/yarnrc.json

Refs: https://github.com/yarnpkg/berry/issues/5843
Moves compressionLevel `mixed` enum value to the end as:
* `mixed` is no longer the default in yarn@4.0.0
* `mixed` is a variant of 9. Visually keeping it closer to 9 is more intuitive.
**Checklist**

docs(yarnrc): move compressionLevel 'mixed' enum value to the end

---

packages/docusaurus/static/configuration/yarnrc.json

N/A
Adds a missing newline and creates list item for 'always' option.
<details>
<summary>Before</summary>
</details>
<details>
<summary>After</summary>
</details>
**Checklist**

docs(yarnrc): create list item for cacheMigrationMode 'always' option

---

packages/docusaurus/static/configuration/yarnrc.json

Fixes: https://github.com/yarnpkg/berry/issues/5856
Removes invalid 'auto' option for cacheMigrationMode yarn config
**Checklist**

docs(yarnrc): remove invalid 'auto' option for cacheMigrationMode

---

README.md

The link in the readme to the documentation for creating a new plugin is broken.
fixes https://github.com/yarnpkg/berry/issues/5861
...
Replace the link with a valid link to the documentation.
...
**Checklist**

fix: Update link to plugin tutorial

---

.yarn/versions/2f9e11d3.yml
packages/acceptance-tests/pkg-tests-core/sources/utils/makeTemporaryEnv.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/fix.test.js
packages/plugin-constraints/sources/commands/constraints.ts
scripts/detect-unsafe-writes.ts

I forgot to add a `Promise.all`, so the `package.json` files could end up corrupted when the constraints engine had to perform multiple iterations of the loop.
Fixes #5853
Adds `Promise.all` before running subsequent iterations.
**Checklist**

Waits for the manifests to be written before running the second loops

---

.yarn/versions/5452f3ea.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
packages/yarnpkg-core/sources/miscUtils.ts

#5872 made me notice that we have few tests covering how the `*` / `**` patterns are interpreted.
This diff fixes that by adding a couple of tests, along with comments on the few places where we seem to diverge from npm. It doesn't try to change the pack list generation, just to increase its coverage and make it easier to add more tests in the future.
**Checklist**

Adds tests for the pack list generation

---

.github/workflows/integration-workflow.yml
.yarn/versions/9d9fcf70.yml
packages/acceptance-tests/pkg-tests-specs/sources/pnp-esm.test.ts
packages/yarnpkg-core/sources/nodeUtils.ts
packages/yarnpkg-fslib/sources/NodeFS.ts

We don't run the unit tests on Node 20/21 on other OSes than Linux, so we didn't notice that one of them was [failing](https://github.com/nodejs/citgm/actions/runs/6652341543/job/18076121495#step:5:146).
This diff increases the coverage so we test both the oldest and newest supported releases across all platforms. It also adds Node.js 21, to track regressions before they land into an even release.
**Checklist**

Runs more tests

---

.github/workflows/e2e-vitest-workflow.yml
README.md

Vitest is increasingly important tool in JS ecosystem. While nowhere near "industry standard", it's [quickly gaining traction](https://npmtrends.com/vitest).
...
Copy Jest's E2E and "migrate" it to Vitest.
...
**Checklist**

ci: add `vitest` e2e tests

---

packages/docusaurus/src/lib/packageChecks.tsx

The existence of bundled TS types are not detected on some package page (e.g. [xterm-headless](https://yarnpkg.com/package?name=xterm-headless))
The check was resolving the main (JS) entrypoint of the package then checking for an adjacent `.ts`, `.tsx` or `.d.ts` file. It should instead prioritize type entrypoints (`types` and `typings` fields in `pacakge.json`, `types` condition) before falling back to the main entrypoint.
**Checklist**

docs: fix package bundled TS type check

---

.yarn/versions/3a508a64.yml
CHANGELOG.md
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/yarnpkg-nm/sources/buildNodeModulesTree.ts

Fixes: #5793 
The nm linker now creates circular symlinks that were explicitly requested by the user, in this case when inner workspace depends on outer workspace. The nm linker continues to avoid circular symlinks for self-references, for now this is not changed.
**Checklist**

fix(yarnpkg-nm): Fixes creation of symlinks when inner workspace depends on outer workspace

---

.github/actions/prepare/action.yml
.github/workflows/integration-workflow.yml
.github/workflows/release-branch.yml
.github/workflows/release-candidate.yml
.github/workflows/sherlock-workflow.yml

The primary reason for v4 update is that v4 uses Node 20 runtime, as opposed to Node 16 in v3.
...
...
**Checklist**

ci: use latest actions/setup-node version

---

.yarn/versions/3bcde5b8.yml
packages/plugin-essentials/sources/commands/set/resolution.ts

The option was never implemented in berry, but it's mentioned in the docs as well as in the CLI output.
I don't have the expertise to actually implement the flag, so the second best thing to do here is to remove it, so that people are no longer mislead.
Mitigates https://github.com/yarnpkg/berry/issues/2202 (actual resolution should be implementing the flag).
Removed unnecessary flag.
**Checklist**

fix: remove unused --save option for set resolution command

---

.yarn/versions/45fda3ad.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.ts
packages/plugin-essentials/sources/commands/install.ts

The refactoring in #5509 accidentally dropped the `includeLogs: true` from the `yarn install` implementation.
Fixes #5866 
I considered extending `installWithNewReport` to have a new `includeLogs` property, but it felt like this behaviour was unneeded for other use cases than `yarn install`, so I simply switched the `yarn install` implementation so that it manually creates the report stream rather than delegate to `installWithNewReport`.
**Checklist**

Fixes missing `--json` output on `yarn install`

---

.yarn/versions/68e485e1.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints.test.ts
packages/plugin-constraints/sources/constraintUtils.ts

The constraints engine is making a `===` check, so using the `set` method with a JS object will never match and will report an error (example [here](https://github.com/babel/babel/actions/runs/6711592648/job/18239331717?pr=16069#step:4:8)).
We now compare stringified values to check sameness. I considered using something like `_.equals`, but using stringify only returns `true` when the key are in the same order, which is important for fields like `exports`.
**Checklist**

Stops reporting identical objects as being different

---

.yarn/versions/70b508e3.yml
packages/plugin-http/sources/TarballHttpFetcher.ts
packages/plugin-http/sources/TarballHttpResolver.ts
packages/plugin-http/sources/constants.ts
packages/plugin-http/sources/urlUtils.ts
packages/plugin-http/tests/urlUtils.test.ts

The v2 never supported referencing packages exposed as extensionless tgz tarballs, despite other clients being fine with them. Us being stricter here doesn't provide any value, and just hurts compatibility.
Fixes #5929
Adds support for extensionless urls, which are now interpreted as regular tarballs.
**Checklist**

Adds extensionless url support

---

packages/docusaurus/docs/advanced/02-package-management/lifecycle-scripts.md

Grammar issue in documentation
...
Updated and fixed the line in the doc.
...
**Checklist**

Fix type for postinstall documentation

---

.yarn/versions/ddf3a56f.yml
packages/yarnpkg-sdks/sources/sdks/vscode.ts

My PR https://github.com/sveltejs/language-tools/issues/2196 introduces a small change alongside a new setting that allows sveltejs-language-tools to resolve PnP in ESM files, most importantly in a `svelte.config.js`. Please note that this PR shouldn't go in until that PR is ready as otherwise the Svelte language server itself will not have the setting available.
Also I'm no expert in Yarn PnP so if this is the wrong implementation avenue I would welcome advice!
The main portion of the solution is in the linked PR. The addition here is to set `svelte.language-server.runtime-args` to `["--loader", "./.pnp.loader.mjs"]`.
**Checklist**

Update Svelte Language Server PnP Configuration

---

.yarn/versions/89f35c90.yml
packages/plugin-npm-cli/sources/commands/npm/login.ts

This commit fixes `yarn npm login` when the remote registry is Verdaccio.
- Closes yarnpkg/berry#1044
- Closes #1848
- Closes verdaccio/verdaccio#1737
...
When a user already exists, the registry replies with `409 Conflict`. The official npm client then retrieves the latest user state and inserts a revision, using HTTP basic authentication. This step was missing, and this commits adds it.
The change was tested to work with a private Verdaccio registry. It should now be as reliable as the official npm client.
...
**Checklist**

fix(plugin-npm-cli): fix login with Verdaccio

---

packages/docusaurus/static/configuration/yarnrc.json

Currently, the documentation states that the default `globalFolder` location is `~/.yarn/berry/global`. However, based on my testing, this is not accurate.
```shell
 docker run -it --entrypoint bash node:20
root@29746f15333c:/# mkdir test-berry
root@29746f15333c:/# cd test-berry/
root@29746f15333c:/test-berry# yarn init -y
yarn init v1.22.19
warning The yes flag has been set. This will automatically answer yes to all questions, which may have security implications.
success Saved package.json
Done in 0.02s.
root@29746f15333c:/test-berry# cat package.json
{
"name": "test-berry",
"version": "1.0.0",
"main": "index.js",
"license": "MIT"
}
root@29746f15333c:/test-berry# yarn set version berry
➤ YN0000: Retrieving …
```

docs: correct default globalFolder in docs

---

.vscode/settings.json
.yarn/versions/0fefb43f.yml
packages/acceptance-tests/pkg-tests-specs/sources/pnp-esm.test.ts
packages/yarnpkg-pnp/sources/esm-loader/loaderFlags.ts

Node.js v18.19 has been released and contains https://github.com/nodejs/node/pull/49869 so we need to update tests.
Updated the version range.
**Checklist**

test: update Node.js range for extensionless files

---

.yarn/versions/07edaf86.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/__snapshots__/foreach.test.js.snap
packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/foreach.test.js
packages/plugin-workspace-tools/sources/commands/foreach.ts

Fixes #6033.
Changes the `-v,--verbose` flag in `workspaces foreach` to be a counter rather than a boolean. With one level it prints prefixes, with two levels it additionally prints start/finish/timing information (as was the behavior before).
The default TTY behavior has not changed (maximum verbosity). The behavior with a single `--verbose` _has_ changed, to be less verbose.
**Checklist**

Add second level of --verbose to `workspaces foreach` to permit specifying less logging.

---

packages/docusaurus/src/css/custom.css

Site navigation issues with bits of text overlapping each other and becoming unreadable, as well as awkward typography.
Screenshot before the fix:
- Allow horizontal scrolling of first top nav group
- Avoid awkward linebreaks
- Remove faux placeholder from search button that tries to act as a text input
Screenshot after the fix (note that the scrollbar is hidden unless scrolling is initiated or OS is set up to “always show” scrollbars):
**Checklist**

Fix site navigation being somewhat jumbled at certain viewport widths

---

.github/actions/prepare/action.yml

Our e2e tests and benchmarks use Node.js v18 which means by the time they catch regressions in the runtime itself a decent amount of time has passed.
Run them on the Node.js current release to catch regressions earlier.
**Checklist**

ci: use Node.js current release for e2e tests and benchmarks

---

.github/actions/prepare/action.yml
.github/workflows/e2e-pnp-angular-workflow.yml

The angular PnP test started failing with https://github.com/yarnpkg/berry/pull/5051.
Lock the Angular PnP test to Node.js v20 for now.
**Checklist**

ci(e2e): use Node.js v20 for angular pnp test

---

.github/workflows/e2e-gatsby-workflow.yml

The Gatsby development server test has been timing out in the CI for months now, though it passes locally.
Disable to so we notice when the build stops working.
**Checklist**

ci(e2e): remove gatsby development server test

---

.yarn/versions/4db9f07d.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/run.test.js
packages/plugin-essentials/sources/commands/runIndex.ts

Adds a `--json` option to the `yarn run` CLI command
Closes #5539 
Changed the command object defined in berry/packages/plugin-essentials/sources/commands/runindex.ts in order to add a `--json` option, and format the output.
**Checklist**

feat: yarn run --json

---

packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts

Adds an integration test for https://github.com/yarnpkg/berry/pull/6058 to assert that link: dependencies are not mistreated as inner workspaces.
It took a bit of trial and error to get the right dependency tree that causes the issue, but eventually figured it out. It's roughly the same as https://github.com/joshhunt/yarn-repro-uuid-install-location, but with the existing fixtures.
...
It's just a test :)
I wrote the test against main to make sure it fails, and then check out the PR with the test and it passed :)
<details>
<summary>Test output against main and branch</summary>
```shell
~/d/g/yarn-berry (master)> git status
On branch master
Your branch is up to date with 'origin/master'.
Changes not staged for commit:
(use …
```

Add test for #6058 nm mistreating link: deps as inner workspace

---

.yarn/versions/0fa4c1b4.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/resolutionCache.test.ts
packages/plugin-npm/sources/npmHttpUtils.ts

We now keep the package metadata in cache. To avoid missing new packages being released we have a check so that we only accept the cached metadata if 1/ the request asks for a semver version (not a range), and 2/ the requested version is found inside the cached metadata. In theory this means that whenever a dependency asks for a version we didn't cache, we assume something new got published, and we refetch it.
However, to prevent fetching the package metadata many times for many different versions or ranges, we also have an in-memory metadata cache where we store the cached metadata once we extracted them from either the disk or the network.
This may lead to memory cache corruption issues when two versions from the same package are resolved if one …

fix(npm): stale metadata cache issue

---

.pnp.cjs
.yarn/versions/ee91c169.yml
package.json
packages/docusaurus/package.json
packages/yarnpkg-builder/package.json
packages/yarnpkg-doctor/package.json
yarn.lock

For some reason we can't run `yarn prepack` in `@yarnpkg/libzip`. I'm not sure why, but upgrading to TS 5.3.3 fixes the issue. It's also a good opportunity to avoid relying on a RC release.
Upgrades TypeScript. It doesn't reveal any new issue in our types.
**Checklist**

Upgrades TypeScript

---

packages/docusaurus/src/pages/index.tsx
packages/docusaurus/src/pages/search.tsx
packages/plugin-interactive-tools/sources/commands/search.tsx

In the website search placeholder text (something like `Search packages (i.e. babel, webpack, react, ...)`), the word "i.e." is used incorrectly. ["i.e." means "that is,"](https://en.wiktionary.org/wiki/i.e.#Usage_notes) but the intended meaning here is ["e.g.," meaning "for example."](https://en.wiktionary.org/wiki/e.g.)
Changed the three instances I found of this placeholder text to use "e.g." instead.
**Checklist**
~👆 Not sure how to do that / if it's applicable to docs-only changes.~ never mind, see [comment](https://github.com/yarnpkg/berry/pull/6142#issuecomment-1963380206) below.

docs: change i.e. to e.g. in search placeholder

---

.vscode/settings.json

When searching in VS Code, the precompiled binaries often show up in the results, because whatever source code matched the search is included in the binary.
Added search exclusions for precompiled binaries in VS Code settings
**Checklist**

Exclude binaries when searching in VS Code

---

.yarn/versions/7ec9c2c1.yml
packages/yarnpkg-builder/sources/commands/build/bundle.ts
packages/yarnpkg-builder/sources/commands/build/plugin.ts

resolves #6211
...
- added a boolean CLI switch to `builder build {bundle,plugin}` called `--metafile`, defaults to `false` 
- if CLI switch 
- is `false`,  then the `esbuild` in instructed to NOT emit `metafile`
- is `true`, then ...
- the `esbuild` in instructed to emit `metafile`
- the `metafile` data is written to target file `bundles/${name}.meta.json`
- the target file is announced in the summary  
example ourput:   
```shellSession
$ builder build plugin --metafile 
➤ YN0000: ┌ Building @yarnpkg/plugin-cyclonedx
➤ YN0000: └ Completed in 8s 619ms
➤ YN0000: ✓ Done building @yarnpkg/plugin-cyclonedx!
➤ YN0000: ? Bundle path: /.../cyclonedx-node-yarn/bundles/@yarnpkg/plugin-cyclonedx.js
➤ YN0000: ? Bundle size: 771.52 …
```

feat(builder): add `--metafile` flag

---

.yarn/versions/dca3f277.yml
packages/acceptance-tests/pkg-tests-specs/sources/plugins/plugin-typescript.test.ts
packages/docusaurus/static/configuration/yarnrc.json
packages/plugin-typescript/README.md
packages/plugin-typescript/sources/index.ts

Given the following monorepo setup, `plugin-typescript` is currently not enabled by default in the `foo` workspace, as it only checks that a `tsconfig.json` exists at the root of the project:
```
package.json
workspace/foo/package.json
workspace/foo/tsconfig.json
```
I also found the [current `README` of `plugin-typescript`](https://github.com/yarnpkg/berry/blob/daa574791b3b2df01e76c1fdfd9c975050a0fb9d/packages/plugin-typescript/README.md) not to be helpful in diagnosing my issue
I've added a check to see if the current workspace had a `tsconfig.json`
I've also added a Configuration section to `plugin-typescript/README.md`, to help users find the `tsEnableAutoTypes` option.
**Checklist**
- I have only bumped …

feat(plugin-typescript): check workspace tsconfig.json

---

packages/plugin-compat/extra/typescript/gen-typescript-patch.js

Building the latest TypeScript patch requires fetching https://github.com/arcanis/typescript, https://github.com/microsoft/typescript, and https://github.com/merceyz/typescript which, according to git, requires fetching 1.87 GiB, 452 MiB, and 42 MiB of data and produces a 2.7GB `.git` folder.
Fork TypeScript to https://github.com/yarnpkg/TypeScript and push the branches required to build all the patches to it and change the script to use a treeless clone of it which only needs to fetch 55 MiB of data and produces a 74MB `.git` folder.
Depends on 
- https://github.com/yarnpkg/berry/pull/6186
**Checklist**

build(compat): use a treeless TypeScript clone

---

.yarn/versions/501b46bd.yml
packages/plugin-version/sources/commands/version/apply.ts

The documentation mentions `%d` but the code uses `%n`.
https://github.com/yarnpkg/berry/blob/c64644ae88ba42090ab9b87da0b09601d4218b0c/packages/plugin-version/sources/commands/version/apply.ts#L76-L78
Update the code
**Checklist**

fix(version) use correct counter placeholder in documentation

---

.github/ISSUE_TEMPLATE/feature-request.md
.github/PULL_REQUEST_TEMPLATE.md

In markdown, syntax have meaning. Those shouldn't be bold text, but titles:
- semantically it suggests something different
- `**text**` are easy to be removed as they could be interpreted as placeholders
- having titles allows deep linking

Use title for issue sesctions

---

.yarn/versions/d497ae00.yml
packages/yarnpkg-parsers/sources/shell.ts
packages/yarnpkg-parsers/tests/shell.test.ts

With `@yarnpkg/parsers`, stringifying a subshell (e.g. `echo $(echo a)`) uses the wrong brackets (e.g. `echo ${echo a}`)
Change to use the correct brackets.

Fix parser stringify subshell brackets

---

packages/docusaurus/docs/features/constraints.mdx

The current documentation overview for [Constraints](https://yarnpkg.com/features/constraints) reads somewhat like a sales pitch, rather than documentation. It's a bit wordy, and kind of grammatically incorrect/confusing. It might be more beneficial to mention "enforcement of workspace package rules" as the main point, rather than towards the end of the description. Additionally, constraints can be used for a large number of needs that are not necessarily "basic" ones.
I'd be fine with expanding the example list, but being sure to specify that these are just examples of how constraints are commonly used. They're not the limit of the capability.
Unclear documentation.
Made it a bit more clear and simple.

Simplify documentation of "constraints" overview

---

.yarn/sdks/typescript/lib/tsserver.js
.yarn/sdks/typescript/lib/tsserverlibrary.js
.yarn/versions/f094b4b7.yml
packages/yarnpkg-sdks/sources/sdks/base.ts

The SDK changes in https://github.com/yarnpkg/berry/pull/6248 broke support for older TypeScript versions.
I tested it on `5.4.1-rc` (master) and it was fine but it crashes on 5.2.0-beta (https://github.com/yarnpkg/berry/blob/4308dca8091438e8f88682e59ef5ba5bc72241ca/package.json#L26)
Check the TypeScript version and only apply the patch if needed.
**Checklist**

fix(sdks): only patch typescript entry point for >= 5.5

---

packages/acceptance-tests/pkg-tests-core/sources/utils/makeTemporaryEnv.ts

I want to run the tests on an alternate Yarn build.
Replaces the TEST_FROM_SOURCES environment variable by a more flexible TEST_BINARY which lets us select any binary on disk to run the tests.

Adds TEST_BINARY

---

.github/ISSUE_TEMPLATE/bug-report.yml

The linked documentation doesn't exist anymore.
The associated website for the tool [1] shows some useful information, but (IMHO) it's unclear to see how to apply it in a fresh repo.
Additionally, `arcanis` mentioned in a comment here [2] that perhaps it should be removed since it's not often used and the playground is broken.
Fixes #5837
Fixes #5950
[1] https://github.com/arcanis/sherlock
[2] https://github.com/yarnpkg/berry/pull/6139#issuecomment-1977286294

Remove "sherlock" from bug report template

---

.yarn/versions/a4f6973d.yml
packages/yarnpkg-doctor/sources/cli.ts

This swaps to use `isBuiltin` from Node rather than constructing a custom set of module names with `node:` prefix. For some modules that didn't have a "bare" module (e.g. `node:test`) this fixes false positive errors.
Closes #6343

Fix incorrect `node:…` module warnings in doctor

---

packages/gatsby/content/features/plugins.md

Plugin `yarn-plugin-cyclonedx` is missing on the list of contributed plugins
...
Added `yarn-plugin-cyclonedx` contribution to the list of plugins.
...

docs: add `yarn-plugin-cyclonedx` to contrib plugins list

---

.yarn/versions/39208ab7.yml
packages/plugin-essentials/sources/commands/explain.ts

This updates the URLs for the `yarn explain` command to make it work after the move from Gatsby to Docusaurus.
Resolves #6249.
- Change the version-tagged link (`repo.yarnpkg.com`) to what @arcanis says will be published after the next release
- Change the Github link for hint about how to help updating documentation

Update links for yarn explain to Docosaurus versions

---

packages/docusaurus/docs/advanced/04-technical/contributing.mdx

PR #6133 renamed the contributing file. This PR adjusts sources to changes.
...

fix: update contributing file reference

---

eslint.config.mjs
package.json

`.mjs` files (`eslint.config.mjs`) aren't linted and in my IDE it keeps breaking the JSON files.
Lint `.mjs` files and ignore JSON files.
**Checklist**

chore: lint mjs files and ignore json files

---

packages/docusaurus/src/components/StarrySky.tsx

When the starry sky crashes, we accidentally report an error on the homepage.
Fixes #6365
Adds a guard against errors occurring during the WebGL initialization.

Adds a guard against WebGL errors

---

.yarn/versions/3a4fece1.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/install.test.ts
packages/yarnpkg-cli/sources/lib.ts

If the event loop unexpectedly becomes empty `yarn` will terminate with exit code 0 even though the command didn't complete successfully.
Ref https://github.com/nodejs/node/issues/53902
Ref https://github.com/yarnpkg/berry/issues/6398 where that happens and the install is incomplete when `yarn` terminates with exit code 0. It's caught in the following `yarn build` step which can't find the install state.
Set `process.exitCode` to an error code before executing the CLI so an unexpected empty event loop counts as an error.
**Checklist**

fix(cli): ensure an empty event loop counts as an error

---

.yarn/versions/34e33c5b.yml
CHANGELOG.md
packages/plugin-essentials/sources/commands/add.ts
packages/plugin-essentials/sources/commands/up.ts
packages/yarnpkg-core/sources/Configuration.ts

When `preferInteractive` is set to `true`, `yarn {add,up}` are interactive even outside TTYs, which is unintended.
Can be checked by running `yarn add lodash > foo.txt` in our repository.
Made it disable interactivity when `stdout` isn't a TTY (and added a new `configuration.isInteractive` helper).

fix(cli): always disable interactive mode in non-TTYs

---

.github/workflows/e2e-docusaurus-workflow.yml

The Docusaurus JavaScript e2e test started failing at 2024-03-29T20:01:12.000Z / https://github.com/yarnpkg/berry/actions/runs/8485023278 due to it prompting for which template to use.
Update the command to specify the JavaScript template.
**Checklist**

ci(e2e): fix docusaurus javascript test

---

.github/workflows/integration-workflow.yml

Observed below error while pulling s390x/node image in CI jobs for Big Endian :
```
Unable to find image 's390x/node:latest' locally
latest: Pulling from s390x/node
docker: no matching manifest for linux/amd64 in the manifest list entries.
See 'docker run --help'.
```
Adds `--platform` flag to pull s390x node image in CI builds.
Recently node images were updated. This PR fixes this [issue](https://github.com/nodejs/docker-node/issues/2124)

Fixing CI jobs for Big Endian

---

packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts

The integration tests using custom certificates have been failing for quite a while on Windows with the error `RequestError: unsuitable certificate purpose`. 
This error was caused by the test CA certificate used; it was not configured to be used as a CA when it was generated. 
The test script that generates the CA certificate has been updated to generate it correctly. I used the same configuration options used by the test suite of the `pem` library that we are using for certificate generation: https://github.com/Dexus/pem/blob/3d71b87cec08a565ce5e73e26dd18f53b9e1fdea/test/pem.spec.js#L856
The problem does not seem to be specific to Windows; I was able to reproduce it locally on macOS as well. I don't yet know why it's passing on CI for Ubuntu and macOS, but not for Windows. Perhaps some …

test: fix custom certification tests on Windows

---

.yarn/versions/40a42318.yml
CHANGELOG.md
packages/yarnpkg-nm/sources/hoist.ts
packages/yarnpkg-nm/tests/hoist.test.ts

Fixes #6493
Fixes #6494
Issue: #6493. Sometimes hoisting algorithm was stopped too early, because it wasn't able to determine correctly stop condition. I made it safer but possibly one round slower by stopping only when nothing was hoisted during the last round.
Issue: #6494. Hoisting avoided hoisting to non-root workspace previously, I have removed this limitation, because it made inner workspaces meaningless.

fix(nm): Stop hoisting rounds only when nothing were hoisted

---

.github/workflows/e2e-parcel-workflow.yml

It seems like the issue (https://github.com/parcel-bundler/parcel/issues/9114) is stuck on Parcel's side with no interest of it being fixed. 
While this is not ideal, that leaves us with two choices: add a workaround and continue testing Parcel, or remove E2E tests for Parcel altogether. I chose the former.

fix(ci): add workaround for Parcel not working with Yarn PnP

---

packages/docusaurus/docs/advanced/03-pnp/pnpify.mdx
packages/docusaurus/docs/getting-started/extra/editor-sdks.mdx

The first two path items got switched in the URLs.

Fix CLI docs links

---

.yarn/versions/a6283714.yml
CHANGELOG.md
packages/yarnpkg-nm/sources/hoist.ts
packages/yarnpkg-nm/tests/hoist.test.ts

Fixes #6516
Simplified the sorting algorithm in `getHoistIndetMap`.

fix(nm): optimize hoisting by treating peer deps same as other deps

---

packages/docusaurus/netlify.toml

Some Netlify settings are unclear because they are set through Netlify UI
Created a `netlify.toml` to capture these settings

Website: add netlify.toml

---

packages/docusaurus/src/css/custom.css

When there isn't enough horizontal space, the scrollbar appears for the navbar.
Fixes #6070
Fixes #6537
Wraps the navbar instead if there isn't enough horizontal space. The [VSCode website](https://code.visualstudio.com/) does that too so it isn't like out of the way either
https://github.com/user-attachments/assets/a7ed8307-d9df-4539-af21-59856ffe6463

Website: Wrap navbar when there is not enough space

---

.github/actions/prepare/action.yml

There are a number of issues affecting Node 23, causing our E2E suite and performance benchmarks to fail since its release:
https://github.com/nodejs/node/pull/54224#issuecomment-2361850159
evanw/esbuild#3951
Drop down to Node 22 for those actions until the issues are cleared

Use Node 22 for GitHub actions for now

---

.yarn/versions/ce211f43.yml
packages/yarnpkg-nm/package.json

Bundling `@yarnpkg/nm` (due to subdeps) is large and not needed when one needs only a few exports from `./hoist` file: https://github.com/yarnpkg/berry/blob/b3dfa91abd591a3d572daadfdba54c671c7d882b/packages/yarnpkg-nm/sources/buildNodeModulesTree.ts#L1-L4
But `hoist.ts` is a zero-dep lib:
https://github.com/yarnpkg/berry/blob/b3dfa91abd591a3d572daadfdba54c671c7d882b/packages/yarnpkg-nm/sources/hoist.ts#L1-L3
It's already built/distrubuted separately (see https://www.npmjs.com/package/@yarnpkg/nm?activeTab=code), just an entry in package.json was missing
Both its exports (and types) are already re-exported:
https://github.com/yarnpkg/berry/blob/b3dfa91abd591a3d572daadfdba54c671c7d882b/packages/yarnpkg-nm/sources/index.ts#L23-L24
So this is not increasing public API surface, just adds a …

feat: add yarnpkg/nm/hoist export

---

.yarn/versions/ce18c01f.yml
packages/yarnpkg-core/package.json
packages/yarnpkg-shell/package.json
yarn.lock

cross-spawn has a vulnerability https://github.com/moxystudio/node-cross-spawn/issues/167.
This should allow the latest version of the cross-spawn package to work.
...
...

chore: unlock cross-spawn range

---

.yarn/versions/c6c3dd7a.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/cache/clean.test.js
packages/plugin-essentials/sources/commands/cache/clean.ts
packages/yarnpkg-core/sources/Configuration.ts

At [Datadog](https://github.com/datadog) we are using `yarn` inside a huge monorepository using the PnP linker and Zero-Installs with all the dependencies versioned through git.
The issue we have is that people frequently have the tendency to think that this kind of environment works like others, and that cleaning the cache is the way to go whenever they encounter an install issue (like deleting `node_modules`).
This is obviously not the case and we have to tell them to restore their packages from the git remote when that happens, which is a bit cumbersome.
_see also: https://github.com/yarnpkg/berry/discussions/6518_
This PR adds a non-breaking option inside the `.yarnrc` file to disallow running `yarn clean cache`.
cc @arcanis

add a config option to disallow the cache clean command

---

.yarn/versions/83473dbf.yml
packages/plugin-workspace-tools/sources/commands/foreach.ts

The log message when an `--exclude` is applied during `yarn workspaces foreach` seems inaccurate. It currently reports that we matched the _include_ but it should probably say that we matched the _exclude_.
Updated the log message!

Small typo in `yarn workspaces foreach`: include -> exclude

---

.github/workflows/e2e-eslint-workflow.yml

- supersedes https://github.com/yarnpkg/berry/pull/6690
The workflow [.github/workflows/e2e-eslint-workflow.yml](https://github.com/yarnpkg/berry/blob/master/.github/workflows/e2e-eslint-workflow.yml) fails with
```text
Oops! Something went wrong! :(
ESLint: 9.20.1
ESLint couldn't find an eslint.config.(js|mjs|cjs) file.
```
It was last successful 11 months ago on Apr 5, 2024 coinciding with the release of [ESLint 9.0.0](https://eslint.org/blog/2024/04/eslint-v9.0.0-released/) which changed the default config to flat.
The workflow installs `eslint` with no version specified, therefore `eslint@latest` is used (currently `eslint@9.20.1`).
In the workflow [.github/workflows/e2e-eslint-workflow.yml](https://github.com/yarnpkg/berry/blob/master/.github/workflows/e2e-eslint-workflow.yml)
each …

ci: migrate e2e to eslint v9 flat config

---

.github/workflows/integration-workflow.yml
packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts

Fixes the GA CI Integration jobs failing for Big endian.
1. Changed the Ubuntu image to Ubuntu 22.04 for Big Endian jobs as it fixes the test case failures. 
Also Ubuntu 20.04 is EOL in April 2025
2. Increased TEST_TIMEOUT for Big Endian to fix the following TC failing due to timeout issue:
`pkg-tests-specs/sources/commands/constraints/fix.test.js`

Fix Integration test failures for Big endian on GA CI

---

.yarn/versions/4c645b68.yml
packages/plugin-essentials/sources/commands/install.ts

Running `yarn --mode=update-lockfile` during git conflict resolution, performs `autofixMergeConflicts`. If the `yarn.lock` file has entries that lack a `checksum` value, that process introduces an `undefined` checksum value which is likely to be committed by accident. Subsequent full installs will remove them, but they're a cause of friction during their temporary existence.
In my case under Yarn `4.5.3` using `nodeLinker: node-modules` it was injecting `checksum: 10/undefined`, while in #6029 it was injecting `checksum: undefined`. I note the `__metadata.cacheKey` prefix (`10/` in my case) can vary from project to project.
...
Explicitly checking for `undefined` in the `autofixMergeConflicts` method.
I struggled to figure out a way to add test coverage for this. I tried to add an extra …

Fix #6029 Avoid undefined checksums after merge conflict resolution

---

.yarn/versions/c530da1b.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/pack.test.js
packages/plugin-pack/sources/commands/pack.ts

It creates missing sub-directories instead of crashing; closes #6706.
Added `await xfs.mkdirpPromise(ppath.dirname(target))` before packing

fix(6706): pack creates sub-directories

---

.yarn/versions/11405fb3.yml
packages/plugin-init/sources/commands/init-initializer.ts
packages/plugin-init/sources/commands/init.ts
packages/plugin-init/sources/index.ts

The `yarn init <package>` syntax works, but not `yarn init <package> [...options]`.
I split the `init` command in two, with the second one having a proxy option to consume whatever follows the first required positional argument.

Adds support for argument passing to "yarn init <initializer>"

---

.yarn/versions/81e42c15.yml
packages/acceptance-tests/pkg-tests-specs/sources/features/pnpmStoreLocation.test.ts
packages/docusaurus/static/configuration/yarnrc.json
packages/plugin-pnpm/sources/PnpmLinker.ts
packages/plugin-pnpm/sources/index.ts

This changes adds a configuration option to configure `node_modules/.store` folder when using `nodeLinker: pnpm`.
It adds an option `pnpmStoreFolder` to .yarnrc.yml which will be used when installing with pnpm Mode.
In our CI system we run a few copies of js repos for different architectures in parralel. We want to share the .store folder between the multiple runs, so we have to hoist it outside of the sourceroot.
This adds an option to configure this.
```
nodeLinker: pnpm
pnpmStoreFolder: ../cache/.store
```
Resolves #6623
...
* Added `configuration` field to `plugin-pnpm` that defines the new option `pnpmStoreFolder`
I'm open to naming suggestions. 
I just followed the pattern defined by `plugin-nm` of prefixing settings with the plugin name like `nmHoistingLimits`, `nmMode` & …

Add configuration option to configure .store folder in pnpm mode

---

.github/workflows/integration-workflow.yml
packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts

Fixes the GA CI Integration jobs failing for Big endian.
1. Changed multiarch image to `tonistiigi/binfmt:latest` for running Big Endian tests as the tests failed in `multiarch/qemu-user-static` image. 
**Note:** All tests passed on s390x host VM, issues were seen in `multiarch/qemu-user-static` image. 
Tested running Integration tests using `tonistiigi/binfmt:latest` and all Big Endian Integration tests have passed.
2. Increased `TEST_TIMEOUT` for Big Endian to fix TC's failing due to timeout issue:

Fix Integration tests for Big endian on GA CI

---

.yarn/versions/caca25a0.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/npm/logout.test.ts
packages/docusaurus/config/typedoc/plugin.ts
packages/docusaurus/src/lib/npmTools.ts
packages/docusaurus/src/theme/DocRoot/Layout/index.tsx
packages/eslint-config/rules/best-practices.js
packages/eslint-config/rules/errors.js
packages/eslint-config/rules/typescript.js
packages/plugin-constraints/sources/Constraints.ts
packages/plugin-npm-cli/sources/commands/npm/info.ts
packages/yarnpkg-core/sources/Configuration.ts
packages/yarnpkg-core/sources/structUtils.ts
packages/yarnpkg-doctor/sources/cli.ts
packages/yarnpkg-fslib/sources/MountFS.ts
packages/yarnpkg-fslib/sources/NodeFS.ts
packages/yarnpkg-fslib/sources/ProxiedFS.ts
packages/yarnpkg-fslib/sources/patchFs/patchFs.ts
packages/yarnpkg-fslib/tests/ProxiedFS.test.ts
packages/yarnpkg-libzip/sources/ZipFS.ts
packages/yarnpkg-pnp/sources/esm-loader/hooks/resolve.ts
packages/yarnpkg-pnp/sources/loader/makeApi.ts
packages/yarnpkg-pnp/sources/loader/makeManager.ts
packages/yarnpkg-pnpify/sources/NodeModulesFS.ts
packages/yarnpkg-shell/sources/pipe.ts

- closes https://github.com/yarnpkg/berry/issues/6713
`@yarnpkg/eslint-config` makes use of two ESLint rules that are now deprecated:
| Linter                                                                  | Deprecated Rule                                                                                         |
| ----------------------------------------------------------------------- | ------------------------------------------------------------------------------------------------------- |
| [ESLint](https://eslint.org/docs/latest/rules/)                         | [no-new-symbol](https://eslint.org/docs/latest/rules/no-new-symbol)                                     |
| [@typescript-eslint/eslint-plugin](https://typescript-eslint.io/rules/) | …

Replace deprecated ESLint rules

---

.yarn/versions/935843d5.yml
packages/plugin-workspace-tools/sources/commands/foreach.ts

Hey! Small PR to make the --no-private flag more visible
Updated examples

fix(workspaces-tools): promote --no-private in foreach usage

---

.yarn/versions/c0a2e918.yml
packages/plugin-essentials/sources/commands/set/resolution.ts

The example in the `set resolution` docs does not work for many packages. 
https://yarnpkg.com/cli/set/resolution#examples
Resolves #5979 
1. Clone and `cd` to the `yarnpkg/berry` repository
2. Run `yarn set resolution lodash@npm:^4.17.11 4.16.0`
3. Observe the following error
```
yarn set resolution lodash@npm:^4.17.11 4.16.0
➤ YN0000: · Yarn 4.7.0-dev
➤ YN0000: ┌ Resolution step
➤ YN0001: │ Error: lodash@4.16.0 isn't supported by any available resolver
at MultiResolver.getResolverByDescriptor (/Users/***/personal/berry/packages/yarnpkg-core/sources/MultiResolver.ts:73:13)
at MultiResolver.getResolutionDependencies (/Users/***/personal/berry/packages/yarnpkg-core/sources/MultiResolver.ts:37:27)
at startDescriptorResolution (/Users/***/personal/berry/packages/yarnpkg-core/sources/Project.t …
```

fix: correction to the set resolution docs

---

.github/workflows/integration-workflow.yml
.pnp.cjs
packages/acceptance-tests/pkg-tests-core/package.json
packages/acceptance-tests/pkg-tests-core/sources/utils/tests.ts
packages/acceptance-tests/pkg-tests-specs/sources/commands/publish.test.ts
yarn.lock

Follow-up #6750: add tests
New npm publish acceptance tests that verifies the provenance statement validity

test(acceptance-tests): add tests for provenance

---

.github/workflows/integration-workflow.yml

[Ubuntu 20 images have been deprecated by Github.](https://github.blog/changelog/2025-01-15-github-actions-ubuntu-20-runner-image-brownout-dates-and-other-breaking-changes/) [Workflows are failing because of it.](https://github.com/yarnpkg/berry/actions/runs/14700798041/job/41249908502?pr=6734)
Changed version `20.04` to `22.04`

chore: upgrade workflows to ubuntu 22 images

---

.yarn/versions/28abe8f1.yml
packages/plugin-dlx/sources/commands/dlx.ts

- closes https://github.com/yarnpkg/berry/issues/6695
The https://yarnpkg.com/cli/dlx#examples instructions fail:
> Use create-react-app to create a new React app :
```shell
corepack enable yarn
cd $(mktemp -d)
yarn dlx create-react-app ./my-app
```
```text
$ yarn dlx create-react-app ./my-app
! Corepack is about to download https://repo.yarnpkg.com/4.6.0/packages/yarnpkg-cli/bin/yarn.js
? Do you want to continue? [Y/n]
➤ YN0000: · Yarn 4.6.0
➤ YN0000: ┌ Resolution step
➤ YN0085: │ + create-react-app@npm:5.1.0, ansi-styles@npm:4.3.0, balanced-match@npm:1.0.2, block-stream@npm:0.0.9, and 60 more.
➤ YN0000: └ Completed in 0s 706ms
➤ YN0000: ┌ Fetch step
➤ YN0013: │ 64 packages were added to the project (+ 2.97 MiB).
➤ YN0000: └ Completed in 0s 815ms
➤ YN0000: ┌ Link step
➤ YN0000: └ …
```

docs: replace create-react-app with create-vite in dlx example

---

.yarn/versions/944c0a3d.yml
packages/acceptance-tests/pkg-tests-fixtures/packages/@scoped__has-bin-entry-2.0.0/bin.js
packages/acceptance-tests/pkg-tests-fixtures/packages/@scoped__has-bin-entry-2.0.0/package.json
packages/acceptance-tests/pkg-tests-specs/sources/node-modules.test.ts
packages/plugin-nm/sources/NodeModulesLinker.ts

Hi! :wave: 
Resolves #5344 #6551 
When using `nodeLinker: node-modules` there's an issue where bin files sometimes don't have the correct permissions (755) after installation. Some examples of scenarios where this can occur:
1. Deleting a package directory containing a bin file in `node_modules` and then running `yarn install`
2. Upgrading a package containing a bin file
3. Using a stale `node_modules` (e.g. when using a CI cache) and then running `yarn install`
I ran a bisect and at least scenario 1 above seems to have started in [3.2.1](https://github.com/yarnpkg/berry/blob/master/CHANGELOG.md#321), I suspect it's [this](https://github.com/yarnpkg/berry/pull/3467) change specifically although previous to this change the deleted directory was not reinstalled *at all*.
Digging into the …

fix(plugin-nm): set binary permissions for partial installs

---

scripts/release/03-release-npm.sh

#6750 started publishing our packages with provenance via config, but `@yarnpkg/cli-dist` is published separately where the config does not take effect.
...
Add the `--provenance` flag when publishing @yarnpkg/cli-dist`
...

feat: Add provenance to @yarnpkg/cli-dist

---

.yarn/versions/5ccd3d41.yml
packages/plugin-pnpm/sources/PnpmLinker.ts

EBUSY should be allowed, if `node_modules` is an active docker mountpoint where rmdir attempts to unmount it which fails because there are open files.
Closes #4373 #4974 #4259 #1184 #4172 
Allow EBUSY to not block "clearing" node_modules.

fix(pnpm): allow EBUSY when deleting node_modules

---

.yarn/versions/4c28a2b4.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/publish.test.ts
packages/plugin-npm-cli/sources/commands/npm/publish.ts

Addresses #6849 
Full disclosure, used Github Copilot Agent Mode to generate most of this PR here --> https://github.com/Saadnajmi/berry/pull/2
Since then, lots more manual edits on my side. I took some spirit from https://github.com/yarnpkg/berry/pull/3404/ and `pack.ts` to determine how to print paths and when to call `report.reportInfo` vs `report.reportJson`.
This adds a couple of flags to `yarn npm publish`, so that it matches other package managers like `pnpm` and `bun`, and is thus easier for tools like `nx release` to use (see https://github.com/nrwl/nx/issues/29242 ). We add
- `--dry-run` (Bails out right before the final publish to NPM)
- `--json` (This takes advantage of StreamReports JSON config)
Using both flags together looks something like this:
```shell
sanajmi@Mac foo % …
```

feat(publish): Add `--dry-run` and `--json` flag to `yarn npm publish`

---

.yarn/versions/d432d26e.yml
packages/plugin-essentials/sources/commands/explain/peerRequirements.ts

This fix of issue described here https://github.com/yarnpkg/berry/issues/6880
Fix validation of hash at `explain peer-requirements` command

fix(plugin-essentials): fix hash validation pattern of explain peer-requirements

---

.yarn/versions/68defaf8.yml
packages/acceptance-tests/pkg-tests-specs/sources/commands/stage.test.js
packages/plugin-npm/sources/npmHttpUtils.ts

Our cache key includes all fields from the package metadata ... but the time field isn't part of the package metadata, it's a separate field. As a result the time field is empty for people who already have a hot metadata cache.
Manually added the time key.

Bust the metadata cache

---

.yarn/versions/c1a29eeb.yml
packages/plugin-npm/sources/npmHttpUtils.ts

At #6898, I made a mistake, making it not work for scoped packages.

Fix OIDC publishing for scoped packages

---

packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/query.test.js
packages/acceptance-tests/pkg-tests-specs/sources/commands/constraints/source.test.js

The prolog constraints are deprecated and will be removed from the next majors. They should be migrated to the JS interface.
Prevent the tests from running on versions that don't support prolog constraints.

Disables Prolog tests from new releases

---

packages/acceptance-tests/pkg-tests-specs/sources/commands/workspaces/focus.test.js

Our tests were relying on the presence of `.gitignore`, which isn't relevant for the feature being tested.
Removed the dependency on `.gitignore`. Also added some extra checks to make sure that not only are the packages correctly installed, but they can also be properly required at runtime.

Improves 'yarn workspaces focus' tests
